### ISSUE TITLE
doorkeeper 4.0.0 & grape-doorkeeper 0.0.2 support (for runtime dependency)

### ISSUE THREAD

**Issue by tabish-saleem-nxb** [doorkeeper-gem/doorkeeper#1005]
Hi,
I am facing below issue while trying to upgrade doorkeeper version from 1.4.0 to 4.0.0 in gemspec file (i.e runtime dependency):
grape-doorkeeper (> 0.0.2) was resolved to 0.0.2, which depends on
doorkeeper (> 1.4.0)

Can anyone help me please how can I upgrade doorkeeper version with grape-doorkeeper?

**Comment by nbulaj** [comment]
Hi @tabish-saleem-nxb . I think you need to ask the maintainer of [grape-doorkeeper](https://github.com/sethherr/grape-doorkeeper) gem. Upgrading from `1.4.0` to `4.0.0` can be painful - to many major versions increased. As I can see, (this gem)[https://rubygems.org/gems/grape-doorkeeper] was updated in 2014, so it is not maintained anymore. All I can suggest you is to fork it and try to implement it yourself for a new version of Doorkeeper.
