### ISSUE TITLE
Improve documentation around foreign keys

### ISSUE THREAD

**Issue by fschwahn** [doorkeeper-gem/doorkeeper#1007]
In the readme there's the suggestion to add a foreign key on all tables with `resource_owner_id`-columns, however there's no note that this will make it impossible to destroy that record without adding an association with a dependent option (because a `ActiveRecord::InvalidForeignKey`-exception will be raised). This is easy to forget if it is mentioned nowhere. I think the README should be expanded to include that information, something along the lines:

```
Remember to add associations to your model so the related records are deleted:

has_many :oauth_access_grants, class_name: "Doorkeeper::AccessGrant", foreign_key: :resource_owner_id, dependent: :destroy
has_many :oauth_access_tokens, class_name: "Doorkeeper::AccessToken", foreign_key: :resource_owner_id, dependent: :destroy
```

**Comment by nbulaj** [comment]
Hi @fschwahn. Would you like to submit a PR ?

**Comment by nbulaj** [comment]
Impoved via #1025
