### ISSUE TITLE
Superapp (Whitelisted application): is a PR welcome?

### ISSUE THREAD

**Issue by aurelienshz** [doorkeeper-gem/doorkeeper#1008]
TL;DR: would you like a PR for an actual implementation of the whitelisted (aka trusted) application feature?

Hi there!

I feel like the superapp / whitelisted application, allowing to skip the authorization step when a user authorizes the application, is a very useful feature when dogfooding your own API with your own client. It is one of the things that make people (especially OAuth newcomers) comfortable with using an OAuth provider on their API layer for their own clients instead of developing their own (possibly vulnerable) authentication system.

It also seems like I'm not the first one to need this on Doorkeeper (for example #488, [this SO question](https://stackoverflow.com/questions/29249977/how-to-specify-the-list-of-superapps-for-doorkeepers-skip-authorization-block), or [this SO answer about using your own OAuth provider from a mobile app](https://stackoverflow.com/a/24353908/6607933)), and the example on how to skip the authorization step in the initializer file suggests this feature.

Those answer often rely on hardcoding the application's uid, which I feel is not very flexible.

I have successfully implemented a whitelist feature for OAuth applications, with the ability to check a box in the application form to whitelist the application and skip the authorization step.

![screenshot from 2017-12-22 11-10-30](https://user-images.githubusercontent.com/14823737/34310020-f1bf0a74-e709-11e7-937c-729614ff6133.png)

The question is: would you like me to extract those changes and put together a PR for Doorkeeper, or do you feel like this should stay in the hands of end users?

Happy holiday! :tada:

**Comment by nbulaj** [comment]
Hi @aurelienshz . What is the problem with some boolean field for `oauth_applications` and checking it in the `skip_authorization` hook ? Or you just want to have this feature (checkbox) in Doorkeeper "admin" panel?

First of all, it is not the prat of the OAuth2 framework. Btw, Doorkeeper is more than just OAuth2 framework :) But such functionality must be highly secured and can be activated only in the config (if user need's it), and by default it must be disabled. Moreover, boolean flag (for example) can be changed only in admin panel, and not with some API request.

**Comment by aurelienshz** [comment]
Hi @nbulaj !
There is no problem with a boolean field for `oauth_applications`, it's exactly how I implemented it. The trickiest part was about adding it to the admin panel, because you have to monkeypatch the [`application_params`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/applications_controller.rb#L50) method to allow the `:whitelisted` parameter (and add the field to the templates, which is pretty easy).

I get your point when you say that the application whitelist implementation is project-dependent, but I feel like the implementation using a boolean flag and a checkbox in the config covers the majority of use cases (who needs to whitelist an applications based on its name?). I feel like having this feature available would help people who are starting with oAuth 2 dogfood their API with their own clients (speaking from experience, when I started using oAuth 2 with other languages and I was puzzled by the fact that my users would have to see an Authorization screen when using my web client, until I stumbled upon the whitelisting feature on a different implementation). I completely agree with the fact that whitelisting an application must only be available in the admin panel and not through an API request.

My current implementation is always enabled, and cannot be disabled through the config. If I have the time, I'll try to put together a PR where this is opt-in and disabled by default, and try to make it in as few changes as possible in order not to add code all around the place for a feature that people don't necessarily need. I'm closing the issue in the meantime.
