### ISSUE TITLE
token/info can be accessed without applicationId/clientId/uid

### ISSUE THREAD

**Issue by beeplove** [doorkeeper-gem/doorkeeper#1011]
[doorkeeper-4.2.6]

It's possible to access /token/info without applicationId/clientId/uid. Should authentication server expose data (such as: resource_owner_id, scopes, uid) related to token without additional reference such as clientId and/or secret pair?

**Comment by nbulaj** [comment]
It is possible, but what is the purpose?

**Comment by nbulaj** [comment]
@beeplove take a look at the https://tools.ietf.org/html/rfc7662 ( OAuth 2.0 Token Introspection). Token info endpoint is something similar (but master now has a new endpoint for this). To get access token info you need to provide some authorization info as standard requires to.

**Comment by beeplove** [comment]
That's awesome @nbulaj, Thanks for taking this into consideration and adding endpoint for introspect. I'm sure this will be very useful!
