### ISSUE TITLE
Gem is not maintained anymore?

### ISSUE THREAD

**Issue by nbulaj** [doorkeeper-gem/doorkeeper#1021]
Hi @maclover7. I tried to connect you multiple times, but got no answer. What is the current gem status? Does you plan to support it or you need some help to work on issues / PRs ?

**Comment by jasl** [comment]
If has enough time we could fork the gem and give a little refinement, `request` and `response` handler of OAuth flows seems a bit complicated.

**Comment by jasl** [comment]
I was a committer, but since @tute set members require enable 2FA, I was removed by Github

**Comment by nbulaj** [comment]
@jasl I was trying to connect with current maintainer, even by @tute, but unfortunately no results :(

**Comment by jasl** [comment]
hmm... If long time no response, I think someone can fork one like cancancan does, I'm still using doorkeeper and this is the only out-of-box solution.

**Comment by jasl** [comment]
but I'm focusing on other works, don't have enough time to refine doorkeeper.

**Comment by tute** [comment]
> hmm... If long time no response, I think someone can fork one like cancancan does, I'm still using doorkeeper and this is the only out-of-box solution.

Better to find someone who can maintain it well here, and keep the community. @nbulaj sorry I wasn't very responsive. I'll try to be more present, albeit with delay, as I'm still on a trip and sometimes I have no internet connection for days.

@nbulaj what are the next issues/PRs you'd like to work on? Thank you.

**Comment by aurelienshz** [comment]
Hooking up to the train to ask for your opinion on #1008. Just tell me whether you want Doorkeeper to go this direction or if you feel like this falls out of scope of the project, and we'll have one less issue and maybe one more PR :)

**Comment by lefty313** [comment]
I'm waiting for simple response since 19.11.2017 so imo sadly it's not maintained anymore.

https://github.com/doorkeeper-gem/doorkeeper/issues/999

**Comment by nbulaj** [comment]
@tute as I said before, gem dependencies must be updated. Fixes for Rails >5 migrations must be merged (as you can see from the previous messages of the thread). Some small fixes also can be merged. Additional features like PKCE need some exploration. Token data improvements are also can be merged. And so on.

**Comment by tute** [comment]
Thanks for your patience, @nbulaj. Are you willing to step up as maintainer, so we start doing small fixes and a first patch release (update gem dependencies, Rails >5 migrations, other small fixes)? Then we shall discuss other features. If you'd like, make sure you have 2FA enabled in GitHub, and I will add you. Thanks!

**Comment by nbulaj** [comment]
@tute yep, I can help with some PRs and issues in my free time. Many great projects depends from this gem, so we can't abandon it :) If my help would be useful, then I'm ready

**Comment by tute** [comment]
Invite to collaborate on GitHub sent. 👍

**Comment by nbulaj** [comment]
@tute thanx! Closing due to resolving this issue :)

**Comment by nbulaj** [comment]
Hi @tute. Can you please give me an access to [doorkeeper-mongodb](https://github.com/doorkeeper-gem/doorkeeper-mongodb) repo? I think it also needs maintainer because I found many issues / PRs connected with this gem, so it also requires some work to do.

What about `doorkeeper` - some work already done, we have fixes for deps and other issues, also small new changes, but I'm waiting for a few PRs to be fixed and merged (Rails 5 migrations, etc), so we can publish a new release (I will ping you because I have no permissions for this).

**Comment by tute** [comment]
Granted to `doorkeeper-mongodb`. Ping me when publishing, I'll review the changes and publish the release when I see. :-)

**Comment by nbulaj** [comment]
Hi @tute. I totally refactored `doorkeeper-mongodb` in order to work with latest Doorkeeper versions and last Mongoid 6, but faced a small issue: I wanna to bump  `doorkeeper-mongodb` dependency version to Doorkeeper 4, but it's depends from Rails >= 4.2. Mongomapper is not maintained actively, and it depends from `active_model` >= 3.0.0 (https://rubygems.org/gems/mongo_mapper). So I need to drop the support of old mongoid (2 and 3, no problem there) and MongoMapper at all.

What do you think about this?

**Comment by tute** [comment]
You should only use my opinion as one opinion, as you are the user and
maintainer and will know better. It sounds fine to me to drop support for
older version, especially if there are older combinations that continue to
work securely for applications that depend on those versions.

**Comment by nbulaj** [comment]
Hi @tute. I updated `doorkeeper-mongodb` gem and now it supports Doorkeeper 4, have it's own mixins instead of buggy ActiveRecord, supports Mongoid 4-7 and MongoMapper (yep, I did it even for 5.1 Rails :) ), tested against Ruby 2.1 - 2.5 and Rails 4.2 - 5.2rc1 (see Travis), and so on. It closes many issues and PRs for this gem. Test are green for all the matrix with current Dorrkepeer specs.

I think we can publish new version on Rubygems (as [people request for it](https://github.com/doorkeeper-gem/doorkeeper-mongodb/issues/11)). But I have no permissions for that, so I need to ping you. What do you think?

**Comment by nbulaj** [comment]
Also @tute, I think we are ready to publish a new release of Doorkeeper (4.3.0), as many of the fixes and proposals was ,merged, the same as dependencies updated and so on. You can check NEWS.md to see more info.

**Comment by tute** [comment]
I don’t have access to https://rubygems.org/gems/doorkeeper-mongodb
<https://rubygems.org/gems/doorkeeper-mongodb/versions/3.0.0>, looks like
only @jasl has.

As of doorkeeper main, when I have access to my computer I’ll try! It may
take weeks though (it has sudden shutdowns during my long trip, can’t fix
it here and it works randomly). If it’s too long you may try other authors
listed in https://rubygems.org/gems/doorkeeper.

**Comment by tute** [comment]
Congrats on all the great work you list!

**Comment by jasl** [comment]
@tute @nbulaj strange, the owner of [doorkeeper-mongodb](https://rubygems.org/gems/doorkeeper-mongodb) is @dazzi, I don't remember I had transferred the ownership.

**Comment by Dev-Crea** [comment]
Hi, i pushed doorkeeper-mongodb gem to rubygems because isn't present (just with git).

I adding @jasl to owners

**Comment by nbulaj** [comment]
Hi @jasl. I think we can publish a new release to Rubygems. You or @Dev-Crea can give me permissions to do it myself if you has no time for it.

**Comment by Dev-Crea** [comment]
Hi @nbulaj 
send me to email accout to rubygem

**Comment by nbulaj** [comment]
@Dev-Crea sent to your dazzl.tv account, is it ok or I need to use another one?

**Comment by Dev-Crea** [comment]
@nbulaj  ok i update owners  list

**Comment by nbulaj** [comment]
Hi @tute. I think it would be great if you will give me permissions for doorkeeper-i18n repo - there are also many PRs to review & merge.

**Comment by tute** [comment]
Done 👌🏼

**Comment by nbulaj** [comment]
Hi @tute. I found [doorkeeper-provider-app](doorkeeper-provider-app), and it is very very outdated. There are already a PR to update and some other work to do, so I can help with it too.

And when you will have free time - we are ready to release Doorkeeper 4.3 with many bugfixes and usefull changes. Thanks!

**Comment by tute** [comment]
> Hi @tute. I found doorkeeper-provider-app, and it is very very outdated. There are already a PR to update and some other work to do, so I can help with it too.

Indeed it is. Added, thanks!

> And when you will have free time - we are ready to release Doorkeeper 4.3 with many bugfixes and usefull changes. Thanks!

Unfortunately I'm running on slow 3G, will try but can't promise for a while. Sorry, and thank you for your work!

**Comment by f3ndot** [comment]
Hi @tute, @nbulaj, I'm happy to contribute in maintaining Doorkeeper since I've used and customized it extensively in my own projects.

I have a wishlist to have it:

* Operate in Rails 5 API-only mode, for microservice apps like mine
* Support Authorization Code (PKCE)
* Add a "confidential" attribute on Application to properly model public vs non-public OAuth clients
* Relatedly, have Access Tokens set a "trusted_application" attribute that represents if the associated Application was confidential, and authenticated with `client_secret`, at that time of issuance
* Optionally require `client_secret` when `Application#confidential` is false
* Maybe expose, a la Auth0's strategy, an `offline_mode` special scope that will only issue refresh tokens if it's asked for and `use_refresh_tokens` is enabled

**Comment by nbulaj** [comment]
Hi @f3ndot . For the first two points we already have PRs, but I want to publish intermediate release with bugfixes and etc before we merge them (btw some of the PR's requires extra work).

What about other points in the list - all of them requires some investigation.
