### ISSUE TITLE
Request for access to doorkeeper-openid_connect repository

### ISSUE THREAD

**Issue by toupeira** [doorkeeper-gem/doorkeeper#1046]
I'd like to add @nashby to the [doorkeeper-openid_connect](https://github.com/orgs/doorkeeper-gem/teams/doorkeeper-openid_connect/members) team since he offered his help with maintaining the gem and [contributed a major new feature](https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/45).

Also, I have an example application running on Heroku that we use for [OIDC conformance testing](https://op.certification.openid.net:60000/) and it would be great to either set up a public repository for that, or integrate it into https://github.com/doorkeeper-gem/doorkeeper-provider-app. Let me know which option you prefer, if we go the first route I propose the name `doorkeeper-openid-connect-provider-app`.

**Comment by nbulaj** [comment]
Does @nashby has a 2FA on GitHub ? I can invite him as a collaborator to work on this gem.

What about the sample app, I prefer a standalone repo.

**Comment by toupeira** [comment]
@nbulaj sounds good, can you setup the repo and give the team Admin access?

@nashby please check if you have two-factor auth enabled, the org is set up to require it for all members.

**Comment by nashby** [comment]
@toupeira @nbulaj hey, I have 2FA enabled!

**Comment by nbulaj** [comment]
@toupeira ready - https://github.com/doorkeeper-gem/doorkeeper-openid-connect-provider-app

I've added a openid team as an owner of the repo, so you have a full control over it. Ping me if you need anything else from me.

@nashby I sent you an invitation to collaborate on the project.

**Comment by nbulaj** [comment]
Any news here? @nashby  @toupeira

**Comment by nashby** [comment]
@nbulaj hey, looks like you added me to the `doorkeeper-openid-connect-provider-app` repo but not to the `doorkeeper-openid_connect` itself. Could you please add me there as well? Anyway, I think you can close this issue now since repo for provider app is created.

**Comment by nbulaj** [comment]
Whoops, soory about that, I forgot to add you. Ready now :)
