### ISSUE TITLE
TokenResponse is missing `redirectable?` method

### ISSUE THREAD

**Issue by hasanen** [doorkeeper-gem/doorkeeper#1059]
I'm following this guide https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Resource-Owner-Password-Credentials-flow and I'm getting few errors.

1: Enabling password type
```
Doorkeeper.configuration.authorization_response_types << "password"
```
instead of 
```
Doorkeeper.configuration.token_grant_types << "password"
```
2: Block `resource_owner_from_credentials` (defined in doorkeeper config)is not called, instead the default `resource_owner_authenticator` is.

I guess these are just problems with the guide itself, as after these changes I'm getting error 
```
NoMethodError (undefined method `redirectable?' for #<Doorkeeper::OAuth::TokenResponse:0x00007f86e23c9838>):

doorkeeper (4.3.1) app/controllers/doorkeeper/authorizations_controller.rb:36:in `redirect_or_render'
doorkeeper (4.3.1) app/controllers/doorkeeper/authorizations_controller.rb:20:in `create'
actionpack (5.1.5) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.5) lib/abstract_controller/base.rb:186:in `process_action'
```

Using latest version (4.3.1) with rails 5.1.5.

Edit:

Setting
```
grant_flows %w(authorization_code client_credentials password)
```
makes `resource_owner_from_credentials` to be called, but the error stays.

Am I still missing something, or should `TokenResponse` extend `BaseResponse`?

**Comment by nbulaj** [comment]
Hi @hasanen . Why are you doing `Doorkeeper.configuration.authorization_response_types << "password"` instead of `Doorkeeper.configuration.token_grant_types << "password"` ?

[`authorization_response_types` method is only a reader, not a configuration option](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/config.rb#L325), so you are just modifying instance variable.

**Comment by hasanen** [comment]
Hi @nbulaj 

When I use that, I get `Doorkeeper::Errors::InvalidAuthorizationStrategy (Doorkeeper::Errors::InvalidAuthorizationStrategy):`

**Comment by hasanen** [comment]
Ah, found the issue, should have make the call to `/oauth/token` instead of `/oauth/authorize` :)
