### ISSUE TITLE
`redirect_uri` no longer valid since v4.3.0

### ISSUE THREAD

**Issue by jwoudenberg** [doorkeeper-gem/doorkeeper#1065]
### Steps to reproduce
I have an OAuth app. It redirects users to a `doorkeeper` endpoint to get authorized. It passes the following `redirect_uri` as a parameter:

```
http://localhost:8081/authorized?referrer=%2F
```

The `referrer` is the path on the app the user should be referred to after the authorization flow is done. It can be any path on the site, but in this example its the root.

The OAuth app has the following callback url configured: `http://localhost:8081/authorized`.

### Expected behavior
The user gets redirected back to the app. The app can then get an access token from `doorkeeper`.

### Actual behavior
In v4.2.6 this is working as expected.

From v4.3.0 things break. After the user logs in on the app running `doorkeeper`, they are correctly redirected back to the app. When the app than makes an API call to get a token however I get an error:

```
The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
```

I checked the authorization grant and I can find it in the database. Nothing seems wrong with it, so I assume the redirection URI is the problem.

### Analysis
I imagine this is probably related to  #974. Is there something I can do to fix this use case for v4.3.0 and above?

Thanks for reading!

**Comment by nbulaj** [comment]
Hi @jwoudenberg. Try to use `master` branch because we have some fixes for redirect_uri. If the problem shill exists - we will look into it

**Comment by jwoudenberg** [comment]
`master` works for me! Thanks @nbulaj, I'll just stay on `v4.2.6` until `v4.3.2` comes round!

**Comment by nbulaj** [comment]
You can try 4.3.2 release

**Comment by jwoudenberg** [comment]
Thank you, works perfectly!

**Comment by nbulaj** [comment]
> Thank you, works perfectly!

Thanks, good to know!
