### ISSUE TITLE
Support Silent Authentication

### ISSUE THREAD

**Issue by f3ndot** [doorkeeper-gem/doorkeeper#1073]
In order to support renewing expired tokens for Single Page Applications using the implicit flow, Doorkeeper will need to support the [Silent Authentication](https://auth0.com/docs/api-auth/tutorials/silent-authentication) strategy.

Essentially, it's supporting a `prompt` parameter where when you pass `none` it will always redirect with either success or failure:

* A successful authentication response if the user was already logged in
* An error response if the user is not logged in and therefore cannot be silently authenticated

**Comment by f3ndot** [comment]
An error will return either `login_required` or `consent_required` to indicate why it failed. Either no session exists or consent/prompt is required

**Comment by nbulaj** [comment]
Could we close this issue or there are something we need to do?

**Comment by f3ndot** [comment]
The correct course of action is to use the other gem
