### ISSUE TITLE
`invalid_ssl_uri` + `force_ssl_in_redirect_uri` incorrectly validates applications

### ISSUE THREAD

**Issue by shyshy** [doorkeeper-gem/doorkeeper#1091]
We're using the `force_ssl_in_redirect_uri` option, which we discovered through a comment here: https://github.com/doorkeeper-gem/doorkeeper/pull/1016#issuecomment-364916916.

That works great for its usecase, but, we think there's a bug related to how it's used in this method: https://github.com/doorkeeper-gem/doorkeeper/blob/644d2ceb41411b9b320a6c8ee769762b37deba01/app/validators/redirect_uri_validator.rb#L35

Any of our existing applications with an SSL `redirect_uri` can no longer be saved through the UI as it will fail validations.

We're on version 4.3.2.

This seems like it would fix it though:

```
    if forces_ssl.respond_to?(:call)
      forces_ssl.call(uri) && uri.try(:scheme) == 'http'
    else
      forces_ssl && uri.try(:scheme) == 'http'
    end
```

Does that seem like it would fix the issue?

### Steps to reproduce
1. Add to config `force_ssl_in_redirect_uri { |uri| uri.host != 'localhost' }` to allow for non ssl localhost redirects
2. Try to create an application with an SSL redirect_uri

### Expected behavior
We should be allowed to create SSL redirect_uris while also using the `force_ssl_in_redirect_uri` option.

### Actual behavior
The update fails the validation step.

**Comment by nbulaj** [comment]
@jonatanklosko check out 5.0.0.rc1 version from rubygems
