### ISSUE TITLE
response_type should be a required param

### ISSUE THREAD

**Issue by vemv** [doorkeeper-gem/doorkeeper#1092]
Say I visit `/oauth/authorize` in my browser, just like that.

Then I'm redirected to my app's login form, and then am redirected back to `/oauth/authorize`.

In that case I will find the following scenario:

![image](https://user-images.githubusercontent.com/1162994/39495704-b16c8656-4d9b-11e8-8680-77e791f9dffd.png)

That's a pretty uninformative message.

The source of the error is that `response_type` is bound to nil. I guess it should have been passed as a param?

* This param should be mandatory (`params.require`)?
* `The authorization server does not support this response type.` could say instead something like `Supported response types are x y z, found <value> instead`

WDYT?

Thanks - Victor

**Comment by nbulaj** [comment]
Take a look at 3.1.1.  Response Type of the OAuth RFC 6749:

>  If an authorization request **is missing the "response_type" parameter**, or if the response type is not understood, the authorization server **MUST return an error response as described in Section 4.1.2.1**.

From [4.1.2.1.  Error Response](https://tools.ietf.org/html/rfc6749#section-4.1.2.1) OAuth server need to return `error`, and optionally - `error_description` / `error_uri` / `state`.

Currently I don't think that it is an informative message. Actually, it shows that `response_type` parameter is wrong (blank, invalid value or something like this). You look at it and see that it is not defined - ooh, there it is! So current behavior corresponds with the specs.
