### ISSUE TITLE
Rails API-only mode and eager_load

### ISSUE THREAD

**Issue by milgner** [doorkeeper-gem/doorkeeper#1096]
### Steps to reproduce
- enable `api_only` in the Doorkeeper initializer
- set `config.eager_load = true` in your environment
- start the application

### Expected behavior
The application starts.

### Actual behavior
Eager loading tries to load `ApplicationsController` which invokes the non-existant `layout` method.

```
[bundle]/ruby/2.5.0/bundler/gems/doorkeeper-d98f6d0894d3/app/controllers/doorkeeper/applications_controller.rb:3:in `<class:ApplicationsController>': undefined method `layout' for Doorkeeper::ApplicationsController:Class (NoMethodError)
	from [bundle]/ruby/2.5.0/bundler/gems/doorkeeper-d98f6d0894d3/app/controllers/doorkeeper/applications_controller.rb:2:in `<module:Doorkeeper>'
	from [bundle]/ruby/2.5.0/bundler/gems/doorkeeper-d98f6d0894d3/app/controllers/doorkeeper/applications_controller.rb:1:in `<main>'
	from [bundle]/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
	from [bundle]/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
	from [bundle]/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:468:in `block in load_file'
```

### System configuration
Ruby 2.5.1, Doorkeeper from current `master`. `d98f6d0894d3`.

**Comment by nbulaj** [comment]
Take a look please at https://github.com/doorkeeper-gem/doorkeeper/pull/1098#issuecomment-393096095

**Comment by nbulaj** [comment]
Any news here? :)

**Comment by milgner** [comment]
Yes, the updated version works flawlessly! Many thanks! I'm going to close this then...
