### ISSUE TITLE
Error codes customization

### ISSUE THREAD

**Issue by NoMemoryError** [doorkeeper-gem/doorkeeper#1101]
When using Resource Owner Password Credentials Grant, is there a quick and clean way to customize response codes for the following cases. Right now they are all returning back `401`.

- Bad credentials (Invalid username or password) 
- Invalid access token
- Invalid refresh token

**Comment by nbulaj** [comment]
Hi @NoMemoryError . You could override `doorkeeper_status_for_error` helper method.

Also take a look at [other Rails controller helper methods](https://github.com/doorkeeper-gem/doorkeeper/blob/25028a8f2811dbc6b91bab731ed6e12ad07cbce2/lib/doorkeeper/rails/helpers.rb#L56)
