### ISSUE TITLE
Doorkeeper application controllers and Rails 5.2 protect_from_forgery default behavior

### ISSUE THREAD

**Issue by enrico** [doorkeeper-gem/doorkeeper#1110]
As of Rails 5.2 ```protect_from_forgery``` is set by default on ```ActionController::Base``` (rather than protecting from forgery in the generated ApplicationController) and a new method ```skip_forgery_protection``` is introduced to skip this default protection setting. 

See this PR: https://github.com/rails/rails/pull/29742

currently Doorkeeper ```ApplicationController``` invokes ```protect_from_forgery``` no matter what:

https://github.com/doorkeeper-gem/doorkeeper/blob/8bd96739d587cd6ecafe31b82a4a57cb925f0f5e/app/controllers/doorkeeper/application_controller.rb#L8

For rails 5.2, Doorkeeper should examine the the value of ```config.action_controller.default_protect_from_forgery``` and decide whether to request protection or not based on it.

**Comment by nbulaj** [comment]
Hi @enrico .Good point! Would you like to produce a PR to fix this?

**Comment by enrico** [comment]
@nbulaj , I'm leaving town for a week, so I won't have time to do this right away. 

When I started thinking about how to do this, I realized we would also have to consider  ```Doorkeeper.configuration.base_controller``` 's value when performing the check (i.e. if a user has overridden the value it's likely they wanted their own control/granularity with respect to enforcing or not the forgery check)

So now I'm starting to think Doorkeeper should not call ```protect_from_forgery``` at all and instead allow the containing app to enforce whichever policy they have chosen from the inheritance hierarchy.  

So if a developer leaves ```Doorkeeper.configuration.base_controller```'s value to its default, rails checks (or not depending on ```config.action_controller.default_protect_from_forgery```). and it they set it to a separate controller, the developer is free to enforce it there...

What do you think?

**Comment by nbulaj** [comment]
I think we need to be opionated enough, because it is a question of the security. If user would disable forgery protection - OAuth2 endpoints could be compromised. We can't allow this. So if developer disabled forgery protection for his controllers - we must validate requests ourselves..

**Comment by nbulaj** [comment]
Hi @enrico. Any thoughts on this issue?

**Comment by enrico** [comment]
Well, enabling ```protect_from_forgery``` based on the value of 
```Rails.application.config.action_controller.default_protect_from_forgery``` would not cover 100% of the cases since a developer can create his/her own base class to inherit from. 

That's where I'm doubtful on whether documentation is sufficient or we want to examine the action chain to check if verify_authenticity_token is present...

so either something like:

```ruby
if Doorkeeper.configuration.base_controller.constantize <= ActionController::Base 
    #subclass of ActionController::Base, check config's default_protect_from_forgery
    protect_from_forgery with: :exception unless Rails.application.config.action_controller.default_protect_from_forgery
else
    #developer has chosen a separate class... do not invoke protect_from_forgery 
    #since we're assuming he has protected that class accordingly?
end
```

If instead you want to ALWAYS invoke the filter, then all of this code could be simplified with simply performing the action chain check (independent of checking the controller class):

```ruby
# check if there is a before_action :verify_authenticity_token in the action chain
unless _process_action_callbacks.detect { |c| c.kind == :before && c.filter == :verify_authenticity_token }
   protect_from_forgery with: :exception 
end
```

**Comment by Erowlin** [comment]
> I think we need to be opionated enough, because it is a question of the security.

I do not agree. Not everyone needs the CSRF protection, for instance full API without any cookies. See below.

> Rails.application.config.action_controller.default_protect_from_forgery would not cover 100% of the cases since a developer can create his/her own base class to inherit from.

This. That's exactly our use case. Our application is a monolith, we have one part of the application running as non-API mode (regular MVC with HTML), and another part only for API (`controllers/api/`) folder.

All our API controllers inherits from an API controller, which himself inherit from the Doorkeeper::ApplicationController. We do not want CSRF security on the API folder, so we disabled it like that:  
```ruby
module Api::V1
  class ApiController < Doorkeeper::ApplicationController
    before_action :doorkeeper_authorize!

    protect_from_forgery with: :null_session
    [...]
  end
end
```

but from a performance standpoint, it would be better for us if we could pass a configuration variable that is read by the ApplicationController of Doorkeeper. 

BTW, if any of you have a better way to disable the CSRF protection that what we did, I will take any tips.

**Comment by nbulaj** [comment]
@enrico @Erowlin agree. Maybe it would be better to make it as a configurable option (like same-name `protect_from_forgery`) that by default inherits the value from configured controller? Anyone can change it for their requirements.

**Comment by enrico** [comment]
@nbulaj  yes, that sounds better, but @Erowlin' s use case brings up another point: what if a developer has a monolith app like he does, and intends to use Doorkeeper::ApplicationController mainly as an API, but also wants to allow some of his users (maybe admins) to manage Applications in the MVC HTML UI? 
In this case, since Doorkeeper::ApplicationsController (plural) inherits from Doorkeeper::ApplicationController, protect_from_forgery would be disabled...

**Comment by Erowlin** [comment]
IT should be a per-controller configuration to be really fine tune up. 
What if in my monolyth, I have 2 different APIs, 
- one that requires CSRF protection
- one that does not
?

**Comment by nbulaj** [comment]
@enrico @Erowlin would you like to submit a PR?

**Comment by Erowlin** [comment]
I would, but I'm OOC for 2 weeks starting tonight, I won't have time unfortunately.

**Comment by nbulaj** [comment]
Hi @Erowlin . Any update here?

**Comment by nbulaj** [comment]
Hi @Erowlin . What is the problem with the solution [mentioned by you above](https://github.com/doorkeeper-gem/doorkeeper/issues/1110#issuecomment-405858629)?

It's not fully clear to how configuration option can increase performance instead of just disabling it manually on controller level..

**Comment by nbulaj** [comment]
Hi @Erowlin @enrico . Any update on this issue?
