### ISSUE TITLE
Can use a refresh token to fetch a new access token without authenticating the client

### ISSUE THREAD

**Issue by skorks** [doorkeeper-gem/doorkeeper#1115]
### Steps to reproduce

You need an access token with a valid refresh token. After that you can instantiate an oauth2 client like this:

```
client = OAuth2::Client.new(
    "",
    "",
    site: "http://localhost:7000",
    redirect_uri: "http://hello_redirect_uri.com",
    authorize_url: "http://localhost:7000/api/v1/oauth/authorize",
    token_url: "http://localhost:7000/api/v1/oauth/token",
    token_method: :post,
    auth_scheme: :basic_auth,
    connection_opts: {
      headers: {
        "Accept" => "application/json",
      }
    }
)
```

Then we can try to fetch a new access token via the refresh_token grant type:

```
existing_token = Doorkeeper::AccessToken.first
new_token = client.get_token(grant_type: "refresh_token", refresh_token: existing_token.refresh_token)
```

For me this succeeds just fine, but I would expect it to fail as the client id and secret and empty strings.

What we need to do to see your problem or bug?

As per above.

### Expected behavior

It should return a 401.

### Actual behavior

It gives me back a shiny new access token.

My apologies if I am misunderstanding how things are supposed to work. But I had a dig around and the issue looks to be in `lib/doorkeeper/oauth/client/credentials.rb`, in this method:

```
def from_request(request, *credentials_methods)
  credentials_methods.inject(nil) do |_, method|
    method = self.method(method) if method.is_a?(Symbol)
    credentials = Credentials.new(*method.call(request))
    break credentials unless credentials.blank?
  end
end
```

Basically given the above scenario with empty string credentials, the instantiated credentials object will always be blank, and therefore the `inject` call will return `nil` and so the whole from_request method will return `nil`. If this happens when we hit this file `lib/doorkeeper/oauth/refresh_token_request.rb`, the `client` will end up being `nil` due to `credentials` being `nil` causing all client related validations to succeed. Which essentially allows you to make unauthenticated calls using the `refresh_token` grant type.

In my fork, I add an extra validation:

```
validate :credentials,  error: :invalid_client

def validate_credentials
  !!credentials
end
```

Which is one way to solve it, but that `from_request` method probably shouldn't assume that a `Credentials` instance will always be returned from the `inject` call. Maybe something like:

```
def from_request(request, *credentials_methods)
  credentials_instance = credentials_methods.inject(nil) do |_, method|
    method = self.method(method) if method.is_a?(Symbol)
    credentials = Credentials.new(*method.call(request))
    break credentials unless credentials.blank?
  end
  credentials_instance ? credentials_instance : Credentials.new(nil, nil)
end
```

Once again apologies if I am missing something obvious.

**Comment by nbulaj** [comment]
Hey @skorks . Strange behavior, because _Refresh Token_ strategy has validations for credentials (see `validate_client` and `validate_client_match` methods).

**Comment by nbulaj** [comment]
Also take a look at 1.5.  Refresh Token of the OAuth2 RFC

>    (G)  The client requests a new access token by authenticating with
        the authorization server and presenting the refresh token.  The
        client authentication requirements are based on the client type
        and on the authorization server policies.

Does your client application is public?

**Comment by nbulaj** [comment]
Any updates here?

**Comment by nbulaj** [comment]
Looks like  stale issue
