### ISSUE TITLE
Allow OAuth authentication request scope modification by a user

### ISSUE THREAD

**Issue by KOLANICH** [doorkeeper-gem/doorkeeper#1118]
### Steps to reproduce
I modify scopes requested by a third-party app (edit the URI)

GitLab uses this lib.

### Expected behavior
on GitHub this works.

### Actual behavior
on GitLab when I tamper with the `scopes` param anyhow I get 
>The requested scope is invalid, unknown, or malformed.

**Comment by nbulaj** [comment]
Hi @KOLANICH . Edited scopes exist on the server? Does application (client) you use has it's own scopes? What Doorkeeper configuration do you use?

**Comment by KOLANICH** [comment]
>Edited scopes exist on the server?

I guess they should since I don't add them, only remove.

>Does application (client) you use has it's own scopes? 

I guess no.

I use a web browser and try to use OAuth for signing in a webapp. But the webapp (it doesn't use this lib) requests access to personal data I don't wannt to give it access. For GitHub a well-known (some services check if it is used and refuse to operate without graning them the scope) way to do it is to remove scopes from URI. For gitlab any tampering with scopes caused an error on GitLab side. Searching for the error message lead to the yaml file with messages https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config/locales/doorkeeper.en.yml#L37 , and searching the key of that message `invalid_scope` has showed that it occurs only in that file. 



>What Doorkeeper configuration do you use?

I personally don't use. I'm not familiar with doorkeeper, rails and ruby, so I may be wrong, but I guess that you want me to give the links to these files: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config/initializers/doorkeeper.rb and https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/auth.rb

**Comment by nbulaj** [comment]
I don't know an actual info, but seems like client spp you are using requires this set of scopes or server configured this way (with required set of scopes). I don't sure could somehow help in this issue

**Comment by nbulaj** [comment]
Is there are anything we can do more on this @KOLANICH ?

**Comment by KOLANICH** [comment]
>Is there are anything we can do more on this @KOLANICH ?

I don't know. To figure out I need to investigate the issue more. For now I still haven't found the piece of GitLab code responsible for the throwing of the error. It seems I have to learn rails better for that. Close for now, but may be reopened.
