### ISSUE TITLE
(Potentially) confusing documentation in API endpoint descriptions wiki page

### ISSUE THREAD

**Issue by paris-plated** [doorkeeper-gem/doorkeeper#1128]
Hi All,

I am a bit confused about the documentation for the `DELETE /oauth/authorize` endpoint in the [API endpoint descriptions and examples](https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples#delete-oauthauthorize) wiki page. 

The docs say that this endpoint will "Revoke OAuth authorization, deletes the access token." After making requests to this delete endpoint, I would expect for the access token to be deleted. However the server just responds with
```
?error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request.
```
and my token seems to be untouched. It seems that the delete action of the authorizations controller just denies the authorization (whatever that means) and redirects to the redirect uri provided. [See here](https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/authorizations_controller.rb#L19)

I have since discovered the `POST /oauth/revoke` endpoint which is suiting my needs, but I just wanted to know if I was wildly misunderstanding the documentation and also get a better understanding as to what the aforementioned delete endpoint is for.

Thank you!

**Comment by nbulaj** [comment]
Hi @paris-plated . It is a good question BTW

Seems like previously this endpoint have worked like that, but currently it not (yep, it just returns Deny message). 

Also [first revision of the Wiki](https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples/d3b7f25fe34839f3316625c39136b0d80b488f4d) contains some misunderstanding of the DELETE request. The change about token revocation was added [here](https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples/_compare/d8a44d27a6d54c56c40197cf17d0a8ee443b7537).

So I think we need to:

1) review this route
2) review wiki

**Comment by nbulaj** [comment]
Ah, ok, I"ve get it. So it is a Deny button for Authorization request (just like Cancel), that will redirect back to the application with access denied message. 

Just like this Cancel button:

![GitHub app auth](https://cdn-docs-images.paw.cloud/github-api-3a-ece10444664f957c7a04dc7fe37465bd.png)

So we need just to fix the Wiki page.

**Comment by nbulaj** [comment]
Ready. Thanks @paris-plated !
