### ISSUE TITLE
Revoke all tokens related to user except new one after log in

### ISSUE THREAD

**Issue by ViTVetal** [doorkeeper-gem/doorkeeper#1135]
Hello!
I know that I should use stackoverflow for this kind of questions. [I asked question](https://stackoverflow.com/questions/51842118/revoke-all-tokens-except-one-after-log-in)

Is it possible revoke all tokens related to current user after log in? (except new one created after log in) User should be able use my app only from one device.

**Comment by nbulaj** [comment]
Hi @ViTVetal . How about something like this in `resource_owner_from_credentials` (or whatever authenticator you use):

```ruby
resource_owner_from_credentials do |_routes|
  owner = if params[:scope].present?
    case params[:scope]
      when "passenger"
        PassengerUser.authenticate(params[:email], params[:password])
      when "driver"
        DriverUser.authenticate(params[:email], params[:password])
    end
  else 
    PassengerUser.authenticate(params[:email], params[:password])
  end

  Doorkeeper::AccessToken.where(resource_owner_id: owner.id).delete_all # it will remove all the tokens for this user, and a new one will be created after this method finish

  owner
end
```

The only thing you need to know is in case you are using different models as resource owners you could face a problem when AccessToken was granted for Admin #1 and other token for Passanger #1 (both tokens will be removed).

**Comment by ViTVetal** [comment]
@nbulaj Thank you! Your proposal is good. I can remove tokens by user id and scope.
