### ISSUE TITLE
Authorizations stopped working after 4.4.2 upgrade

### ISSUE THREAD

**Issue by Gargron** [doorkeeper-gem/doorkeeper#1137]
Very strangely after performing the upgrade from Doorkeeper 4.2.6 to 4.4.2 pretty much all app authorizations stopped working, i.e. no app can get a new access token.

Here is an example of an error message: https://gulp.cafe/@Taris/100602053143287842

I hear more from end-users of a mobile app but it's impossible to get at a descriptive error there, I'll update the issue if I get more information though.

I have followed the instructions in the post-install message by generating a `confidential` column that defaults to true, here is the PR: https://github.com/tootsuite/mastodon/pull/8197

I have a suspicion that this problem might be related to this new column, because the other issue (native URIs) has already been fixed in 4.4.2 and the authorizations are still not happening.

### System configuration

**Doorkeeper initializer**:

https://github.com/tootsuite/mastodon/blob/master/config/initializers/doorkeeper.rb

**Ruby version**:

2.5.1

**Gemfile.lock**:

https://github.com/tootsuite/mastodon/blob/master/Gemfile.lock

**Comment by nbulaj** [comment]
Hi @Gargron . Could you please reproduce the problem with the 5.0.0rc2 ? I need to know if it is a problem of backporting features/fixes or it is a common bug. :bowing_man:

**Comment by Gargron** [comment]
Upgrading to 5.0.0.rc2 has indeed fixed the issue :thinking: I was hesitant to use an RC with possibly breaking changes but now that I'm looking at <https://github.com/doorkeeper-gem/doorkeeper/wiki/Migration-from-old-versions#from-4x-to-5x> it doesn't look like any of the breaking changes would affect how Mastodon uses Doorkeeper.

I did just yesterday push out a security patch release 2.4.4 with Doorkeeper 4.4.2 so now all of the fediverse has broken clients so I need to do something really quick.

**Comment by nbulaj** [comment]
Hi @Gargron . I released 5.0.0 version with all the new features and fixes, so you could use it. It is stable enough. Let me know if I can help you somehow.

**Comment by Gargron** [comment]
Thank you :tada:

**Comment by philkcw** [comment]
The problem in 4.4.2 might be related to the redirect_uri in auth requests which must match the redirect_uri of the client application.

**Comment by Gargron** [comment]
I guess not, since we upgraded to 5.0.0 and pushed out 2.4.5!
