### ISSUE TITLE
Different token scopes for login and refresh

### ISSUE THREAD

**Issue by harisp9631** [doorkeeper-gem/doorkeeper#1139]
I am currently working on implementing doorkeeper into our companies project and migrating from an old auth flow, our custom one. 

While doing it, I decided to use token scopes for reasons not important for this issue, but then saw something that might be considered as a bug. When using password flow to log in, the token created has `scopes` set to `nil`. 

```
lib/doorkeeper/oauth/password_access_token_request.rb
  
      def before_successful_response
        find_or_create_access_token(client, resource_owner.id, scopes, server)
        super
      end

```

```
lib/doorkeeper/oauth/base_request.rb

      def find_or_create_access_token(client, resource_owner_id, scopes, server)
         context = Authorization::Token.build_context(client, grant_type, scopes)
        @access_token = AccessToken.find_or_create_for(
          client,
          resource_owner_id,
          scopes,
          Authorization::Token.access_token_expires_in(server, context),
          Authorization::Token.refresh_token_enabled?(server, context)
        )
      end
```

Setting the token to nil is acceptable, since in the request our clients do not provide the key `scopes`.
The problem starts when clients use the token that they received to do the `refresh_flow`. As far as I understood, the method used for creating tokens for `refresh_flow`, is not the same as the one for `password_flow`. 

```
lib/doorkeeper/oauth/refresh_token_request.rb

      def create_access_token
        @access_token = AccessToken.create!(access_token_attributes)
      end

      def access_token_attributes
        {
          application_id: refresh_token.application_id,
          resource_owner_id: refresh_token.resource_owner_id,
          scopes: scopes.to_s,
          expires_in: access_token_expires_in,
          use_refresh_token: true
        }.tap do |attributes|
          if refresh_token_revoked_on_use?
            attributes[:previous_refresh_token] = refresh_token.refresh_token
          end
        end
      end
```

The problem is that `access_token_attributes` sets `scopes` to and empty string, since `nil.to_s' is an empty string. I was wondering, if someone could explain the logic behind this, since I believe that this is an inconsistency and should be fixed. 

Thank you

**Comment by harisp9631** [comment]
@nbulaj any info about this?

**Comment by nbulaj** [comment]
Hi @harisp9631. I have very little free time, sorry :( 

Could you please prepare a spec or small sample app where I can see a problem? I understand the second part of your thoughts, but not the first one //
