### ISSUE TITLE
Need more docs. 

### ISSUE THREAD

**Issue by AndreiMotinga** [doorkeeper-gem/doorkeeper#1141]
Guys, I've been banging my head against this thing for 10 straight days now.

Could please someone write up a wiki page on how to use pkce and/or auth for single page app
What exactly should I pass and when?

**Comment by nbulaj** [comment]
I think @bpieck could describe it in more details.

**Comment by bpieck** [comment]
I think I cannot add some entry to wiki?
I could write some details here and maybe someone will move it to the wiki.
PKCE is normally for mobile apps. But I assume you can protect your single page app from overregistering your redirect uri, too.

PKCE is not much different from standard authentication code grant. I hope you understood that one. Then following description should be enough:

First thing you do: Generate some random string as code_verifier. Second thing: generate the code_challenge. doorkeeper supports two code_challenge_method: plain and S256. First one is not recommended. If you choose plain, your code_challenge is just the same as your verifier.
If you choose S256, your code_challenge is an url safe base64 encoded SHA256 of the code_verifier.

Now you do standard authentication_code grant - with two small changes. In the oauth/authorize request you add two parameters: code_challenge and code_challenge_method.

After you got the authentication_code and do the token request - you add the code_verifier parameter.

---

Hope my description helps.

**Comment by nbulaj** [comment]
Hi @bpieck . You can add more info to [this page](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-PKCE-flow). Thanks you for your contribution :+1:

**Comment by bpieck** [comment]
Ok, thanks for pointing the direction, I can do so in the evening :)

**Comment by bpieck** [comment]
Sorry, yesterday I got some family matters in between. But now I added the wiki entry. Hope it is ok, as I wrote it.

**Comment by AndreiMotinga** [comment]
Hey @bpieck

Apologies for a bit late response. 

Thank you so much for the help. The wiki helped to clear out some misunderstandings. 
My [obviously wrong]  impression was that app and auth server should share some sort of `secret`, stored in something like `secret` on applications table, which "for some reason" wasn't there. 

I think this helps clear this out. 

Thank you, guys, for awesome work.  Feel free to close this. 

Since I'm already here and it seems relevant, I wonder how you would advice handling store receipts? 

There are ios and android apps that subscribe users via stores, 
  - during subscription apps send a receipt to auth server, 
  - which generates User with dummy data ( since there is no email and password for those users)

Those apps need to access api that is protected with auth server.  

So currently I'm `hijacking the process a bit`, manually creating acces_token with something like 

```
  def create
    config = Doorkeeper.configuration
    token = Doorkeeper::AccessToken.create!({
      resource_owner_id:   user.id,
      expires_in:          config.access_token_expires_in,
      use_refresh_token:   config.refresh_token_enabled?,
    })

    render json: { refresh_token: token.refresh_token }
  end
```

and those apps can go now to `/oauth/token` to get the access_token. 
There are no redirects, no code grant flow, no PKCE, nothing. 

I would greatly appreciate any advice or pointer to some useful resources, anything. 

I understand issue tracker is not a place for this kind of conversation, but I feel this is relevant enough and could benefit some future googlers.

**Comment by bpieck** [comment]
Hey, the secret is only needed for confidential apps. An app that needs PKCE is normally not confidential. So you do not need to share a secret - just to mark the app as public.

What is it you want to protect there? I have the feeling, your "authentication" is that much public, that you could just switch the API to a public mode - instead of beeing protected at all. There are no user information you need to secure (since the dummy user has no user information). And the client credentials are not really secured. So you are doing kind of a client credentials grant with some fake dummy user data - although your client credentials cannot be confidential (since anyone can decompile them from your app).

But maybe it's enough to just point you to client credentials grant ^^. I think you just use that to "secure" your api ...

**Comment by nbulaj** [comment]
Hi @AndreiMotinga . Can we close this issue now or you have any additional questions? Btw, discussions of such kind are preferably to ask on StackOverflow. This tracker is for issues / enhancements.
