### ISSUE TITLE
Consider defaulting Application.confidential to false

### ISSUE THREAD

**Issue by rhymes** [doorkeeper-gem/doorkeeper#1142]
Recently we had an app break because of the following reasons:

* version 4.4.0 was released with the following changelog message: `Backport security fix from 5.x for token revocation when using public clients`
* we applied the security fix knowing revocation wasn't an issue for our use case
* the security fix went to production without deep testing
* Android users started complaining, iOS users were fine
* after reverting and debugging we noticed a difference between the two: Android clients didn't send the client secret, iOS did
* the security fix set confidential to true which seems to disable clients without client secret

Setting it to false fixed the issue.

My question is: shouldn't a breaking change like this be clearer?

The changelog doesn't mention it, the upgrade guide says to add the migration but it doesn't clearly state: "hey, the default will break clients without client secret key"

### Expected behavior

Either the default should change or the documentation should be clearer about this change.

Thank you

**Comment by revskill10** [comment]
What do you mean by `clearer` ? Any example for it so that we could make the changelog better ?

**Comment by nbulaj** [comment]
Hi @rhymes . By default [all the clients have secret key](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/orm/active_record/application.rb#L18), so it doen't fully clear to me. Did you patch Doorkeeper models?

**Comment by rhymes** [comment]
@revskill10 I mean by explicitly saying in the changelog: "this change means that by default all clients logging without the secret will break" or something like that

@nbulaj the clients in this case are Android and iOS application, they don't use Ruby. The Android client didn't send back the secret.

**Comment by nbulaj** [comment]
Hi @rhymes . I took a look at original PR and backport . You are right - by default now all the apps are considered confidential. I'll work on more clearer changelog and upgrade guides, thanks for mentioning!

**Comment by rhymes** [comment]
@nbulaj thank you! :-)

**Comment by nbulaj** [comment]
[Upgrade guides updated](https://github.com/doorkeeper-gem/doorkeeper/wiki/Migration-from-old-versions) (feel free to add or fix something here, it's public)

[changelog also updated](https://github.com/doorkeeper-gem/doorkeeper/blob/master/NEWS.md#500rc1)

**Comment by arekt** [comment]
shouldn't be? 
"You need to manually change confidential column to `false` if you are using public clients"

The confidential column is true by default, isn't it?

**Comment by rhymes** [comment]
thank you! I think we can close the ticket :-)

**Comment by nbulaj** [comment]
Whooops, it's a typo in changelog. I'll fix it, thanks @xtagon

**Comment by xtagon** [comment]
Thanks, that was fast!
