### ISSUE TITLE
`URIChecker#valid_for_authorization?` false negative

### ISSUE THREAD

**Issue by krasnoukhov** [doorkeeper-gem/doorkeeper#1147]
### Steps to reproduce

Here's a comprehensive example when URIChecker returns false:

```
redirect_uri = "https://example.com/callback?"
Doorkeeper::OAuth::Helpers::URIChecker.valid_for_authorization?(redirect_uri, redirect_uri)
```

This seems to be a case only when query string is empty, so in case with `redirect_uri` like this: `https://example.com/callback?1` it works as expected.

### Expected behavior

Returns true when URI is a match, even with empty query string

### Actual behavior

Returns false in this specific case

### System configuration

Tested on `4.4.2`, but could be reproducible on `5.x` as well

**Comment by nbulaj** [comment]
Hi @krasnoukhov . Why do you use blank `?` in the callback URL ?

**Comment by krasnoukhov** [comment]
@nbulaj No particular reason. It just happened to be like that. Why do you ask?

**Comment by nbulaj** [comment]
Because I just don't see any valuable reason why do we need to fix this specific issue. Only if somebody by some reason will use such an url as callback_uri for his Application..

Btw, you can produce a PR if you want to fix this

**Comment by krasnoukhov** [comment]
Well, if you don't see any valuable reason to fix this specific issue, why do you want me to produce a PR?

I don't argue this is kind of an edge case, but AFAIK the URL in question is valid URL and it's weird to see that it's considered a no match.

**Comment by nbulaj** [comment]
I don't asking you to produce a PR, I just propose you. It's open source, don't forget about it.

Currently I have no time to work on it, and as it doesn't have a high priority I just leave this opportunity for someone else. Do not get me wrong

**Comment by krasnoukhov** [comment]
Ok, please don't get me wrong either, I was considering working on a change for this, but your attitude (specifically "I just don't see any valuable reason why do we need to fix this specific issue") kind of set me back. Why would I want to work on a PR if you as a maintainer don't see a reason for it?

Given all that, feel free to do whatever with this issue, I don't really mind. At least the problem is searchable now so potential users will know there's a bug in the comparison logic

**Comment by nbulaj** [comment]
Sorry I hurt your feelings. I'll work on this myself when I have free time. Thanks for mentioning of this bug!

**Comment by nbulaj** [comment]
Hi @krasnoukhov . Could you please take a look at #1149 ?

**Comment by krasnoukhov** [comment]
Looks good, thanks
