### ISSUE TITLE
Doorkeeper on multiple apps but shared Authorization

### ISSUE THREAD

**Issue by iamdriz** [doorkeeper-gem/doorkeeper#1156]
So we're building a set of Rails applications for a platform:

**http://www.domain.com/** - _Main website_
**http://account.domain.com/** - _Account management application_
**http://account.domain.com/oauth/** - _Doorkeeper is also installed here_
**http://api.domain.com/** -  _The API is a different application_

However we've encountered an issue... by having the API has a separate Rails application it means we can't use `before_action -> { doorkeeper_authorize! :read, :write }` for an endpoint because Doorkeeper is on our account application, and we don't want to have the oauth login, etc on the api application and want to keep it on the account one.

Is it possible to have doorkeeper on both applications? But have the oauth part on the account application and the protection and checking of valid tokens on the api one?

**Comment by nbulaj** [comment]
Hi @iamdriz . So why you don't just add Doorkeeper to both applications and use `before_action` in one of them and oauth routes in other?

**Comment by iamdriz** [comment]
@nbulaj Ah okies that makes sense... I also noticed you have an `api_only` mode as well now.
