### ISSUE TITLE
NoMethodError: undefined method `url_options' for #<Doorkeeper::TokensController:..>

### ISSUE THREAD

**Issue by nadnoslen** [doorkeeper-gem/doorkeeper#1169]
I fear that I am missing something or doing something really stupid.

My worry is that there's something I don't understand about Doorkeeper or the vast world of OAuth2.

Apologies if I waste some people's time with this issue.

### Steps to reproduce
What we need to do to see your problem or bug?

* ruby-2.5.1
* doorkeeper-5.0.2
  * configured to use `orm :active_record`  & `api_only`
  * `grant_flows %w[password]`
  * authored a simple `resource_owner_from_credentials` that returns a user
  * I've put the `before_action :doorkeeper_authorize!` on my controllers that are serving up my api
* rails-5.2.1
* jsonapi-resources-0.9.3
* using Rails default MiniTest

I created a basic controller test using `rails g test_unit:controller doorkeeper_password_flow`

Authored a test that confirms sign in is successful, token is returned 👍 

```ruby
test 'when authenticating with correct credentials' do
  some_guest = users(:some_guest)

  post oauth_token_url, params: { grant_type: 'password', password: 'secret', username: some_guest.email }

  assert_response :ok
  assert JSON.parse(response.body)['access_token'].present?
  # THIS WORKS PERFECTLY ... YAY
end
```

### Expected behavior

Based on the test above working, my expectation is that I can now write a new test that:
1. Signs user in
1. Receives token
1. Assemble a second request for a protected resource making sure to place the access token into the header
1. **BOOM** - just as the second request is queued up, the test fails.  I'm not given any meaningful line number, stacktrace, or any debugging information.  I'm lost!

Here's an example of the test:

```ruby
test 'when authenticated and accessing a protected resource' do
  some_guest = users(:some_guest)

  post oauth_token_url, params: { grant_type: 'password', password: 'secret', username: some_guest.email }

  access_token = JSON.parse(response.body)['access_token']
  
  Rails.logger.debug "Access Token: #{access_token}"

  # BOOM: test bombs right here at this call
  get api_v1_users_url, headers: { Authorization: "Bearer #{access_token}" }
  
  assert_response :ok
end
```

My expectation is that this test should at the very least fire the second request to receive some sort of non-500 response.

### Actual behavior

Instead I receive:
```bash
Minitest::UnexpectedError: NoMethodError: undefined method `url_options' for #<Doorkeeper::TokensController:0x00007f8d6b07ce20>
    test/controllers/doorkeeper_password_flow_controller_test.rb:##:in `block in <class:DoorkeeperPasswordFlowControllerTest>'
test/controllers/doorkeeper_password_flow_controller_test.rb:##:in `block in <class:DoorkeeperPasswordFlowControllerTest>'
Finished in 0.53299s
```

There is nothing meaningful in my logs or console.  

There is no sign of the second request even firing, the file basically ends where I logged the access token value.

Based on some heavy Googling, I am worried that I've hit some sort of threading issue related to Rails Engines.  Perhaps the way my test is structured is incorrect?  This technique of signing in with one request and then making subsequent request(s) has worked in so many other Rails applications that I've worked on (granted they did not use Doorkeeper).

### System configuration

**Doorkeeper initializer**:

```ruby
Doorkeeper.configure do
  orm :active_record

  api_only

  resource_owner_authenticator do
    raise "Please configure doorkeeper resource_owner_authenticator block located in #{__FILE__}"
    # Put your resource owner authentication logic here.
    # Example implementation:
    #   User.find_by_id(session[:user_id]) || redirect_to(new_user_session_url)
  end

  # Used for grant_type: 'password'
  # Throw DoorkeeperError should the authentication attempt fail, else return the User
  # --------------------------------------------------------------------------------------------------------------------
  resource_owner_from_credentials do
    user = User.find_by(email: params[:username]).try(:authenticate, params[:password])

    raise Doorkeeper::Errors::DoorkeeperError, I18n.t('doorkeeper.errors.messages.access_denied') if user.blank?

    user
  end

  grant_flows %w[password]
end

```

**Ruby version**: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]` 

**Gemfile.lock**: (if you want this I'll add it in a comment)

**Comment by crescentrose** [comment]
I was hit by this as well. Apparently Rails doesn't fully clear the state in between Minitest test cases and it causes something like this to happen? I don't really know but I'd appreciate it if someone smarter than me could look into this.

**Comment by nadnoslen** [comment]
Hey @crescentrose, that's very interesting and thank you for posting!

Just for clarity, I'm experiencing this problem in a single test case that sends two requests into my Rails API.  It consistently fails.

In my scenario, the clean up between each test case seems to be functioning as expected.

Cheers.

**Comment by nbulaj** [comment]
Hi all! This is a weird and strange error, I don't remember using of `url_options` method somewhere in Doorkeeper.. Also AFAIR `url_options` is a method from ActionView, but Doorkeeper controllers inherits from MetalController with a minimal set of modules included. So maybe MiniTest + Rails causes this issue? Maybe it's trying to render the view or refresh some ActionView cache, I don't know.

**Comment by nadnoslen** [comment]
Hey @nbulaj, to be honest, I can't see how Doorkeeper is responsible.  I too searched the Doorkeeper codebase for some sort of clue or usage of `url_options` and like you, I cannot find anything.

I did uncomment `require 'sprockets/railtie'` from my `config/application.rb` to use the `bootstrap-email` gem for sending emails from my Rails API app.  In my case, I believe this is the only thing that goes anywhere near the ActionView framework.  I'll play around with this configuration and see if that fixes my problem.  _For clarity sake, my failing test case described in this issue does not intend to use any of ActionMailer or ActionView._

Thanks again for the ideas and assistance.  I'll report back.

**Comment by nbulaj** [comment]
Hi @nadnoslen . Any news on this issue?

**Comment by nbulaj** [comment]
Maybe you can run specs with dome option like `--trace` or smth like that to show full stack-trace? It's hard to understand where is the root of the issue

**Comment by nadnoslen** [comment]
Hey @nbulaj,

I have to go back to my affected project and check this out.  I've been working on some other things recently.  I'll head back there and take another look today.

**Comment by nbulaj** [comment]
Well, any news @nadnoslen

**Comment by nadnoslen** [comment]
Hey @nbulaj,

It's taken me forever to get back to this, I do apologize.

I back-traced my simple unit test and didn't derive anything substantial:

```bash
Minitest::UnexpectedError: NoMethodError: undefined method `url_options' for #<Doorkeeper::TokensController:0x00007fb95cc71ab0>
    /Users/dnelson/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:125:in `block in url_options'
    /Users/dnelson/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:124:in `tap'
    /Users/dnelson/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:124:in `url_options'
    /Users/dnelson/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:265:in `call'
    /Users/dnelson/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:331:in `block (2 levels) in define_url_helper'
    /Users/dnelson/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:397:in `public_send'
    /Users/dnelson/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:397:in `method_missing'
    /Users/dnelson/Code/cybertooth.io/ermahgerd-rails-api-doorkeeper/test/controllers/doorkeeper_password_flow_controller_test.rb:69:in `block in <class:DoorkeeperPasswordFlowControllerTest>'
```

And once again, my `TokenControllerTest` (as seen above):

```ruby
test 'when authenticated and accessing a protected resource' do
  some_guest = users(:some_guest)

  post oauth_token_url, params: { grant_type: 'password', password: 'secret', username: some_guest.email }

  access_token = JSON.parse(response.body)['access_token']
  
  Rails.logger.debug "Access Token: #{access_token}"

  # ------------------------------------------------------------------------------------------------
  # BOOM: test bombs right here at this call
  # ------------------------------------------------------------------------------------------------
  get api_v1_users_url, headers: { Authorization: "Bearer #{access_token}" }
  
  assert_response :ok
end
```
This is all with Ruby-2.5.1.  I resumed googling this error where people have said it was fixed in Ruby-2.3.x.  I'm going to try a few other Ruby versions and then we can consider closing this issue.

**Comment by nadnoslen** [comment]
I've tried Ruby-2.6.1 to no avail:

```bash
Minitest::UnexpectedError: NoMethodError: undefined method `url_options' for #<Doorkeeper::TokensController:0x00007fa3e1443978>
    /Users/dnelson/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:125:in `block in url_options'
    /Users/dnelson/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:124:in `tap'
    /Users/dnelson/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:124:in `url_options'
    /Users/dnelson/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:265:in `call'
    /Users/dnelson/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:331:in `block (2 levels) in define_url_helper'
    /Users/dnelson/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:397:in `public_send'
    /Users/dnelson/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:397:in `method_missing'
    /Users/dnelson/Code/cybertooth.io/ermahgerd-rails-api-doorkeeper/test/controllers/doorkeeper_password_flow_controller_test.rb:69:in `block in <class:DoorkeeperPasswordFlowControllerTest>'
```

and also Ruby-2.4.5 just for $hits & giggles, and still receive the same error.

```bash
Minitest::UnexpectedError: NoMethodError: undefined method `url_options' for #<Doorkeeper::TokensController:0x00007f922a5374b0>
    /Users/dnelson/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:125:in `block in url_options'
    /Users/dnelson/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:124:in `tap'
    /Users/dnelson/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:124:in `url_options'
    /Users/dnelson/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:265:in `call'
    /Users/dnelson/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:331:in `block (2 levels) in define_url_helper'
    /Users/dnelson/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:397:in `public_send'
    /Users/dnelson/.rvm/gems/ruby-2.4.5/gems/actionpack-5.2.2/lib/action_dispatch/testing/integration.rb:397:in `method_missing'
    /Users/dnelson/Code/cybertooth.io/ermahgerd-rails-api-doorkeeper/test/controllers/doorkeeper_password_flow_controller_test.rb:69:in `block in <class:DoorkeeperPasswordFlowControllerTest>'
```

**Comment by nadnoslen** [comment]
Hey @nbulaj,

I think you can go ahead and close this issue if no one else is feeling this pain.  I've actually moved away from Doorkeeper for my Authentication needs because I'm using AWS Cognito.

If there's anything other information you'd like, please let me know.

**Comment by crescentrose** [comment]
Just a quick tip for anyone else with this issue: POSTing twice in the same request is not really "proper" testing anyway as you should be focusing just on the method you are testing. Just use a simple authorization helper to generate an access token to use with your requests:

```ruby
  module AuthorizationHelpers
    # Creates an access token for a user.
    # You can set scopes (default: all scopes) and expiration time (default: 1 
    # day) in the params.
    def create_token(user, params = {})
      access_token = Doorkeeper::AccessToken.create!(
        application_id: nil,
        resource_owner_id: user.id,
        scopes: params.fetch(:scopes, 'public private admin'),
        expires_in: params.fetch(:expires, 24.hours),
        use_refresh_token: Doorkeeper.configuration.refresh_token_enabled?
      )
      access_token.token
    end
  end
```

That's how I resolved this intermittent issue anyway.

**Comment by nadnoslen** [comment]
Hey @crescentrose, thanks so much for that anecdote and your example code!  I completely understand and somewhat agree with your don't `POST` multiple times per-test.

With that said, I've seen many projects over my career that use a `POST` request to authenticate.  This is usually authored in the `test_helper.rb` and then re-used within integration tests throughout the app.  This is the first time I've encountered this multiple POST issue.

Thank you very much for the helper code.

Feel free to close @nbulaj.

**Comment by nbulaj** [comment]
Ok, so ping me if somebody will face something similar
