### ISSUE TITLE
conformity to RFC8252

### ISSUE THREAD

**Issue by jobol** [doorkeeper-gem/doorkeeper#1170]
### Description

Paragraph 7.3 of RFC8252 tells:

    The authorization server MUST allow any port to be specified at the
    time of the request for loopback IP redirect URIs, to accommodate
    clients that obtain an available ephemeral port from the operating
    system at the time of the request.

but doorkeeper is not conforming to that.

### Steps to reproduce

- declare an application with URI  http://127.0.0.1:5555/auth/callback
- perform an authorization request with the URI http://127.0.0.1:48599/auth/callback
- observe that it is refused because the URI is wrong

### Expected behavior

Differences in ports must be ignored at least for 127.0.0.1 (or [::1]).

Relying on PKCE enforces the process.

### Actual behavior

The authorization is rejected

**Comment by nbulaj** [comment]
Hi @jobol . Seems like a bug, thanks!

So it seems like Doorkeeper need to implement IP loopback to get the actual  port, right?
Would you like to propose a PR ?

**Comment by jobol** [comment]
I'm not developping or using doorkeeper but I'm developing embedded clients and used gitlab for testing. gitlab use doorkeeper so I reported the issue here. I can make the PR but I prefer not because it is a lot of work for me when it can be more easy for someone with hands already in.

**Comment by nbulaj** [comment]
Hi @jobol . Thanks for posting this issue. The fix was introduced in 1e98b15 and will be released with a next version of the gem. Don't sure when GitLab will update it's Gemfile btw

**Comment by jobol** [comment]
nice news. thank you @nbulaj.
