### ISSUE TITLE
Limiting scopes for certain grant_types

### ISSUE THREAD

**Issue by rishabhsairawat** [doorkeeper-gem/doorkeeper#1177]
**Feature:** To limit certain scopes to certain grant type.

**Why?:** We may not want all the scopes available for all the grant types. We may want certain scopes to be available only for certain grant types. For example, read-only scopes over the implicit grant.

@nbulaj What do you think about this?

**Comment by nbulaj** [comment]
Hi @rishabhsairawat . I think it can be useful, but requires some changes that must not break compatibility with previous versions of Doorkeeper. Also I think it must be good-configurable. Would you like to try to produce a PR?
