### ISSUE TITLE
AccessGrant returns hashed token to authorization code page in native redirect

### ISSUE THREAD

**Issue by oliverguenther** [doorkeeper-gem/doorkeeper#1180]
### Steps to reproduce

- Enable `hash_token_secrets` in the initializer
- Set up application with native `urn:ietf:wg:oauth:2.0:oob`
- Access `http://localhost:3000/oauth/authorize?response_type=code&client_id=(code)&redirect_uri=urn:ietf:wg:oauth:2.0:oob` and authorize
- Check the token

### Expected behavior
The printed code should be the plaintext token.

### Actual behavior
The returned token is the hashed token. This is due to this line not returning `plaintext_token` https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/authorization/code.rb#L19 and a native redirect_uri spec was missed by me (sorry).

### System configuration

**Doorkeeper initializer**:

`hash_token_secrets`

**Ruby version**:

2.5.1

**Doorkeeper version**:

Doorkeeper at current master

**Comment by nbulaj** [comment]
Thanks @oliverguenther ! Merged
