### ISSUE TITLE
Revoking a token does not work

### ISSUE THREAD

**Issue by lethunder** [doorkeeper-gem/doorkeeper#1183]
**Expected behavior**
on version 5.0.2 we should be able to revoke token without having application_id

**Actual behavior**
when i generate a token on public default scope without application and i try to revoke the token it does not work

The reason is this is the code. The private method token in charge of returning the token in params

```ruby
def token
  @token ||= AccessToken.by_token(request.POST['token']) ||
    AccessToken.by_refresh_token(request.POST['token'])
end
```

`request.POST['token']` returns `nil` everytime on my app
i overrided it with `request.parameters['token']` to make it work

![image](https://user-images.githubusercontent.com/6217812/51030405-9f66ba00-1599-11e9-851a-982798785c43.png)

In the image without overriding it doen't work (in red)
in blue with override

**System configuration**

- windows 10
- ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
- Rails 5.2.1
- doorkeeper 5.0.2

**Comment by nbulaj** [comment]
Hi @lethunder . Does this token [was accesible on time of the first request](https://github.com/doorkeeper-gem/doorkeeper/blob/72425150a95c4c5874ac2926b0ede90e705bd736/app/controllers/doorkeeper/tokens_controller.rb#L74) and client [was authorized](https://github.com/doorkeeper-gem/doorkeeper/blob/72425150a95c4c5874ac2926b0ede90e705bd736/app/controllers/doorkeeper/tokens_controller.rb#L22)?

Also don't sure `request.POST['token']` or `request.parameters['token']` connected with `application_id` somehow :|

**Comment by lethunder** [comment]
@nbulaj you are right does not have nothing to do with application_id. i just created token by signing then i tried to revoke it immediatly after signing

**Comment by nbulaj** [comment]
Doesn't it the same as #1179 ?

Also we have [specs for Token revocation](https://github.com/doorkeeper-gem/doorkeeper/blob/master/spec/controllers/tokens_controller_spec.rb#L59-L116), don't sure how `request.parameters['token']` can fix described issue..

**Comment by lethunder** [comment]
not disame. If i don't override token method i keep having 200 response eventhough the token is not updated.
in my case request.POST['token'] does not return the token. request.parameters['token'] does

**Comment by nbulaj** [comment]
By RFC OAuth2 server must return 200 status in any case (token revoked or not revoked).

`request.POST['token']` must work the same as `request.parameters['token']`. Sorry, but I can't reproduce the bug. Maybe you could create a sample spec or a small application that reproduces the env to see the bug?

**Comment by lethunder** [comment]
In the zip file you have a izzi.sql to create DB (postgresql)

[test.zip](https://github.com/doorkeeper-gem/doorkeeper/files/2749678/test.zip)

SIGNIN => POST http://localhost:3000/oauth/token?password=lethunder1014&grant_type=password&phone=0033652861874

SIGNOUT => http://localhost:3000/oauth/revoke?token=TOKEN

**Comment by nbulaj** [comment]
@lethunder I created db with `rails db:create db:schema:load` and tried to load izzi.sql, but got multiple errors, most of them related to pgcrypto. Also I think you need to remove the file bacuse it has `.git` directory that has sensitive data.

It would be great if you could place a RSec sample..

**Comment by lethunder** [comment]
[doorkeeper_test.zip](https://github.com/doorkeeper-gem/doorkeeper/files/2750448/doorkeeper_test.zip)

sample project with sqlite db and existing user

POST http://localhost:3000/oauth/token?password=user123&grant_type=password&phone=0033652861874

**Comment by nbulaj** [comment]
Hi @lethunder . I've checked the latest ZIP and seems like we really have a weird bug. I introduced a fix, so it would be great if you can check the `master` branch and say me if everything is OK

**Comment by lethunder** [comment]
hi @nbulaj it works fine :)
