### ISSUE TITLE
option to set `token_reuse_limit`

### ISSUE THREAD

**Issue by rishabhsairawat** [doorkeeper-gem/doorkeeper#1189]
### Feature:
A configurable option to set `token_reuse_limit` 

### Why do we need this?
 Suppose the following situation: _(when requested `scopes` are same)_

Doorkeeper Configuration: 
`reuse_access_token` enabled & `access_token_expires_in` set to 2.hours

Now, if a client requests an `access_token` for the first time, it will be provided an `access_token` with expiry 2 hours (i.e. 7200 sec or 120 mins). Now if the client again requests an access_token after 1 hour, it will be provided the same access token with remaining expiry as 1 hour. 
But suppose if client requests `access_token` 2 minutes before the expiry of the previous token, then it will be provided the same access_token with remaining expiry 2 minutes. I don't think it is good. I think we can provide new `access_token` with full expiry(i.e. 7200 sec or 120 mins). 

### Solution:
We can provide an option to set `token_reuse_limit` to handle these cases which will be used only when `reuse_access_token` option is enabled. This option will be a percentage(i.e. 0-100). By default `token_reuse_limit` option will be 100 which means that same access_token will be returned for its full expiry time. But Suppose if it set 95, then the same token will be returned for 95% of `access_token_expires_in` time (i.e. 6840 sec or 114 mins). For the last 6 mins, New `access_token` with be provided.

@nbulaj  What do you think about this?

**Comment by nbulaj** [comment]
Hi @rishabhsairawat .

Yep, I've got an idea, thanks for clear clarification.
This sounds reasonable to me if it is not against the OAuth RFC. We can produce it like a standalone option or options for `reuse_access_token`
