### ISSUE TITLE
bcrypt gem is required explicitly in 5.1.0.rc version

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [doorkeeper-gem/doorkeeper#1190]
### Steps to reproduce

Install new version of doorkeeper - `gem "doorkeeper", "5.1.0.rc1"`

### Expected behavior

Application works and bcrypt is either not required or added as a dependency.

### Actual behavior

```
LoadError: cannot load such file -- bcrypt
```

**Comment by nbulaj** [comment]
Hi @ZilvinasKucinskas.

Yeap, bcrypt must be required if you activated option for secrets hashing. So we need to require it only in this case and not make as a strong dependency.

**Comment by oliverguenther** [comment]
That is a good point, I will have a look into it today.

Am 17. Januar 2019 22:48:16 schrieb Nikita Bulai <notifications@github.com>:
