### ISSUE TITLE
Client Credentials reuse token query is unbounded, entire result set loaded into memory

### ISSUE THREAD

**Issue by ryansch** [doorkeeper-gem/doorkeeper#1193]
### Steps to reproduce
1. Enable `client_credentials` flow.
2. Use client credentials flow with external clients that don't cache tokens but rather create a new token for every request.
3. Realize this is happening and enable `reuse_access_token`.
4. Observe ~3s response times and random OOM errors from the frontend rails containers.
5. Realize that each token request returns 96k results and loads them all into memory.

### Expected behavior
Doorkeeper should not match _all_ client credentials tokens for an application when querying the database.  It should use either `revoked_at` or date math on `expires_in`.

### Actual behavior
Doorkeeper matched all 96k tokens for one application.  Due to the use of `detect` in `matching_token_for`, doorkeeper loads the entire result set into memory.

### System configuration

**Doorkeeper initializer**:
```ruby
Doorkeeper.configure do
  # Change the ORM that doorkeeper will use (needs plugins)
  orm :active_record

  # This block will be called to check whether the resource owner is authenticated or not.
  resource_owner_authenticator do
    # Put your resource owner authentication logic here.
    # Example implementation:
    #   User.find_by_id(session[:user_id]) || redirect_to(new_user_session_url)
    current_user || authenticate_user!
  end

  admin_authenticator do
    current_admin_user || authenticate_admin_user!
  end

  # Use a custom class for generating the access token.
  # See https://github.com/doorkeeper-gem/doorkeeper#custom-access-token-generator
  #
  access_token_generator '::Doorkeeper::JWT'

  reuse_access_token
  use_refresh_token

  enforce_configured_scopes

  default_scopes :identity, :read, :write
  optional_scopes :provision_users

  access_token_methods :from_bearer_authorization, :from_access_token_param

  force_ssl_in_redirect_uri !Rails.env.development? && !Rails.env.test?

  grant_flows %w[authorization_code client_credentials]

  skip_authorization do |resource_owner, client|
    resource_owner.is_a?(User) &&
      resource_owner.white_label.oauth_application_id == client.id
  end
end
```

**Ruby version**:
2.4.5
**Gemfile.lock**:
```
    doorkeeper (5.0.2)
      railties (>= 4.2)
    doorkeeper-jwt (0.3.0)
      jwt (~> 2.1.0, >= 2.1.0)
```

**Comment by nbulaj** [comment]
Hi @ryansch . Thanks for notice! What do you think about to refactor it to use `find_each` / `find_in_batches`? It's ORM-tied, but would be memory-efficient I think. Also we can select custom DB fields in order to avoid type-casting and memory consumption

**Comment by nbulaj** [comment]
So not to return full token is not a good idea because almost all the columns are required on next steps of using Token, so we can return to bathing enumeration of found tokens. Smth like this:

```ruby
def find_matching_token(relation)
  catch(:matching_token) do
    # TODO: `find_in_batches` is ActiveRecord specific, we need to define enumerable interface for every ORM extension (Sequel, Mongo) with a fallback in case they don't support such functionality
    relation.find_in_batches do |group| 
      group.detect do |token|
        throw :matching_token, token if scopes_match?(token.scopes, scopes, application.try(:scopes))
      end
    end
  end
end
```

**Comment by nbulaj** [comment]
Any news @ryansch ?

**Comment by nbulaj** [comment]
Here we have a patch to fix the problem, https://github.com/doorkeeper-gem/doorkeeper/pull/1270, but need your attention and tests
