### ISSUE TITLE
Customize Token Introspection response

### ISSUE THREAD

**Issue by nhosoya** [doorkeeper-gem/doorkeeper#1194]
### Feature

A configurable option to customize Token Introspection Response

### Why?

There are members that are not implemented, but are defined as OPTIONAL by [rfc7662 section-2.2](https://tools.ietf.org/html/rfc7662#section-2.2). ( `sub`, `username`, and so on )  
We want to return these values to our clients.

https://github.com/doorkeeper-gem/doorkeeper/blob/614ec7d4b9db3bda309e118536e6f0533977ab69/lib/doorkeeper/oauth/token_introspection.rb#L61-L71

**Comment by nbulaj** [comment]
Hi @nhosoya . Introduced with https://github.com/doorkeeper-gem/doorkeeper/pull/1195 and will be released with next version of the gem

**Comment by nhosoya** [comment]
Thanks for your quick works! 😺 @nbulaj
