### ISSUE TITLE
custom TTL documentation

### ISSUE THREAD

**Issue by alexpil** [doorkeeper-gem/doorkeeper#1196]
Hello
In our project we decided to use a custom TTL. Based on the official documentation you can do the following:

 ```
 #Assign a custom TTL for implicit grants.
 custom_access_token_expires_in do |oauth_client|
     oauth_client.application.additional_settings.implicit_oauth_expiration
 end
```
Unfortunately that is not reflected in the api. There is a discrepancy between different grant types. 

- for grant types CLIENT_CREDENTIALS | PASSWORD 
    * `oauth_client.client.application` is a `Doorkeeper::Application` instance
- for grant type AUTHORIZATION_CODE | REFRESH_TOKEN
    * `oauth_client.client` is a `Doorkeeper::Application` instance

Something similar was already addressed here and part of it was fixed.
https://github.com/doorkeeper-gem/doorkeeper/issues/617
Shouldn't it be consistent for all the grant types?
Doorkeeper gem version 5.0

**Comment by nbulaj** [comment]
Hi @alexpil . Well, docs seems to be out of date.

Currently (from Dorrkeeper 5.0) `custom_access_token_expires_in` provides an instance of `Doorkeeper::OAuth::Authorization::Context` where you can handle required properties. You can see it in initializer:

```ruby
  # Assign custom TTL for access tokens. Will be used instead of access_token_expires_in
  # option if defined. `context` has the following properties available
  #
  # `client` - the OAuth client application (see Doorkeeper::OAuth::Client)
  # `grant_type` - the grant type of the request (see Doorkeeper::OAuth)
  # `scopes` - the requested scopes (see Doorkeeper::OAuth::Scopes)
  #
  custom_access_token_expires_in do |context|
    context.client.application.additional_settings.implicit_oauth_expiration
  end
```

Can you try it again?

**Comment by alexpil** [comment]
Hey @nbulaj
The example code I pasted was from the old reported bug. But the actual problem is that the 
`context.client` is not instance of `Doorkeeper::OAuth::Client` for all the grant types. Like i mentioned before for  `AUTHORIZATION_CODE | REFRESH_TOKEN`, `context.client`  is type of     `Doorkeeper::Application`

**Comment by nbulaj** [comment]
OK, I found the issue @alexpil . But don't sure we can easily fix it because some projects can depend on it and already checks for the application, so we will break their code. But we can add a changelog / upgrading entries for it.
