### ISSUE TITLE
Support reauthorization with a narrower set of scopes

### ISSUE THREAD

**Issue by toupeira** [doorkeeper-gem/doorkeeper#1197]
### Steps to reproduce

1. Perform an authorization to grant an access token for the scopes `one two`
2. Perform another authorization for the scopes `one`

(for some context, see https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/63#issuecomment-461866656)

### Expected behavior

I would expect the existing access token grant to be reused, and a fresh access token to be granted for the requested narrower scope, without again having to authorize the scopes as a user.

I can't find anything concrete in the specs except for [this section about *refresh tokens*](https://tools.ietf.org/html/rfc6749#section-1.5):

> Refresh tokens are issued to the client by the authorization server and are used to obtain a new access token when the current access token becomes invalid or expires, **or to obtain additional access tokens with identical or narrower scope**

Note that the existing access token must not be returned as-is, because it grants more than the requested scopes.

### Actual behavior

The existing token is ignored because it doesn't fully match the requested `param_scopes`:

https://github.com/doorkeeper-gem/doorkeeper/blob/9ae5f9fff7234123216ae56f37c73534a7373654/lib/doorkeeper/models/access_token_mixin.rb#L104-L113

Also see this spec which verifies this case:

https://github.com/doorkeeper-gem/doorkeeper/blob/9ae5f9fff7234123216ae56f37c73534a7373654/spec/models/doorkeeper/access_token_spec.rb#L511-L515

### System configuration

**Doorkeeper version**: 5.0.2

**Ruby version**: 2.6.1

**Comment by nbulaj** [comment]
Hi @toupeira . I think I saw something similar on issues or PR here, need to check.. It must be closed now. Need to go deeper into OAuth2 spec
