### ISSUE TITLE
Consider increasing complexity of default generated tokens

### ISSUE THREAD

**Issue by eliotsykes** [doorkeeper-gem/doorkeeper#1199]
Here are the character ranges for a few of the `SecureRandom` generator methods:

method|characters|total available characters
--------|-----------|------------------------------
`SecureRandom.hex` (Doorkeeper default)|`0-9`, `a-f`|`16`
`SecureRandom.alphanumeric `|`A-Z`, `a-z`, `0-9`|`62`
`SecureRandom.urlsafe_base64 `|`A-Z`, `a-z`, `0-9`, `-`,`_`|`64`

The [default configuration for doorkeeper uses `SecureRandom.hex`](https://github.com/doorkeeper-gem/doorkeeper/blob/72425150a95c4c5874ac2926b0ede90e705bd736/lib/doorkeeper/oauth/helpers/unique_token.rb#L8).

`.hex` generates a token with a limited character set. One of the alternatives with a larger character set would increase the complexity of the generated tokens.

Would it be worthwhile setting the default to `urlsafe_base64` or `alphanumeric` for fresh doorkeeper installs?

**Comment by nbulaj** [comment]
Hi @eliotsykes . Access token value must be as specified in OAuth2 spec Appendex A:

> VSCHAR     = %x20-7E

https://tools.ietf.org/html/rfc6749#appendix-A

So we can use the method that corresponds the spec. Would you like to produce a PR?

**Comment by eliotsykes** [comment]
`SecureRandom.urlsafe_base64` generates a subset of characters in the range `VSCHAR = %x20-7E`, so it may be good enough.

> Would you like to produce a PR?

I doubt I'll be able to get round to this. Fingers crossed there's another developer willing to take it on.

**Comment by nbulaj** [comment]
Thanks @eliotsykes , I'll work on it when I have time.

**Comment by nbulaj** [comment]
Hi @eliotsykes . Check #1200 please
