### ISSUE TITLE
Machine to machine Flow

### ISSUE THREAD

**Issue by suung** [doorkeeper-gem/doorkeeper#1203]
I am wondering how to poperly build this Flow in Doorkeeper

https://auth0.com/blog/using-m2m-authorization/

In my case it is an application that also has to implement the on-behalf-of-the-user - flow

Any hints how we could use or extend doorkeeper (hence opening a PR) appreciated

**Comment by nbulaj** [comment]
Hi @suung . Sorry, didn't use this flow and couldn't help you :(

Try to ask on StackOverflow, maybe somebody would give you more feedback

**Comment by nbulaj** [comment]
Hi @suung ! I read a little bit more about m2m and seems like you can just use Client Credentials flow. https://auth0.com/blog/using-m2m-authorization/

Or do you need this `audience`  functionality?

**Comment by nbulaj** [comment]
As I said, you can use Client Credentials flow for m2m flow. For some specific cases you could propose a PR.
