### ISSUE TITLE
Feature request: Customize grant types per application

### ISSUE THREAD

**Issue by alexpil** [doorkeeper-gem/doorkeeper#1207]
Hello,
We want to define different grant types for each oauth application we have. 
Some solutions for that could be having `config.custom_grant_flows` like in the case of  `config.custom_access_token_expires_in`
 or maybe allowing to accept proc in existing `config.grant_flows`.

Thank you.

**Comment by nbulaj** [comment]
I'm closing this in favor of #1245, @alexpil
