### ISSUE TITLE
custom_access_token_expires_in not accepting nil value

### ISSUE THREAD

**Issue by matteoredz** [doorkeeper-gem/doorkeeper#1222]
### Steps to reproduce
Inside doorkeeper.rb initializer set

```
custom_access_token_expires_in do |context|
  context.client.owner.access_token_expires_in
end
```

where `owner` is the user and `access_token_expires_in` is a custom attribute to set per-user access token expiration 

### Expected behavior
When `owner.access_token_expires_in` is set to `nil` I expect `nil` to be the access_token expiration, so that access_tokens generated by specific user are non-expiry 

### Actual behavior
Looking at the code, when `custom_access_token_expires_in` returns `nil`, the default `access_token_expires_in` is taken instead

**Comment by nbulaj** [comment]
Hi @matteoredz . Thanks for reporting this issue. Currently Doorkeeper fallbacks to `access_token_expires_in` in case `custom_access_token_expires_in` returned `nil`. It would be a breaking change if we "fix" this issue..

**Comment by matteoredz** [comment]
Hi @nbulaj thank you for your response.

How about allowing `custom_access_token_expires_in` to receive something like `-1` so that:

- If `custom_access_token_expires_in` returns `nil` fallback to `access_token_expires_in`
- If `custom_access_token_expires_in` returns valid time in seconds than use it
- If `custom_access_token_expires_in` returns `-1` set access_token expiration to `nil` (aka not-expiry access token)

**Comment by nbulaj** [comment]
I thought about to introduce `Float::INFINITY`, like:

```ruby
custom_access_token_expires_in do |context|
  if condition
    7200
  else
    Float::INFINITY
  end
end
```

that internally could be interpolated as `nil` for non-expiring tokens.. But it doesn't seems to be a human-friendly solution.
