### ISSUE TITLE
Error setting up doorkeeper for rails application

### ISSUE THREAD

**Issue by ajays1991** [doorkeeper-gem/doorkeeper#1240]
I am trying to add doorkeeper to my rails application. As getting started documentation mentions i will have to run 

`bundle add doorkeeper`

then 

`bundle exec rails generate doorkeeper:install`

```
This will introduce three changes:

New initializer in config/initializers/doorkeeper.rb
Add a doorkeeper's routes to your config/routes.rb
Locale files in config/locales/doorkeeper.en.yml
```

But i get the following error in console while running `bundle exec rails generate doorkeeper:install`

[Configuration for doorkeeper missing. Do you have doorkeeper initializer? (Doorkeeper::MissingConfiguration)](url)

Looks like something is broke.

**Comment by nbulaj** [comment]
Hi @ajays1991 . Take a look at old issue here, maybe you could find an answer https://github.com/doorkeeper-gem/doorkeeper/issues/973

**Comment by felipeelias** [comment]
@ajays1991 I hope that the link provided above solved your issue and I'm going to take the liberty to close this issue. Feel free to reopen the issue in case you still encounter problems.
