### ISSUE TITLE
No method for nil value exception in token introspection

### ISSUE THREAD

**Issue by linhdangduy** [doorkeeper-gem/doorkeeper#1242]
### Steps to reproduce
After update code with #1209 pull request (on master branch or tags v5.1.0rc2), send a request to token introspection endpoint with following format:
```
POST /oauth/introspect HTTP/1.1
Header: Authorization = Bearer bearer_access_token
Body: token=Wrong_token (just set a random token)
```

### Expected behavior
Because body's token was wrong, expected response is
```
{ "active": false }
```

### Actual behavior
Exception occurred: No method `.token` for nil value. At the following line https://github.com/doorkeeper-gem/doorkeeper/blob/9bb03f86583b4b71bd3632191abd93b1f7978021/lib/doorkeeper/oauth/token_introspection.rb#L166

### Reason
`@token` is gotten from request's param at these line https://github.com/doorkeeper-gem/doorkeeper/blob/9bb03f86583b4b71bd3632191abd93b1f7978021/app/controllers/doorkeeper/tokens_controller.rb#L77-L80
In case token is wrong, it will be nil. So the exception will occurred.

### System configuration
Using doorkeeper on master branch or tags v5.1.0rc2.

**Comment by nbulaj** [comment]
Fixed by #1243
