### ISSUE TITLE
Undefined method logout_uri

### ISSUE THREAD

**Issue by wallerjake** [doorkeeper-gem/doorkeeper#1244]
### Steps to reproduce

When I uncommented the after_successful_authorization successful block in the doorkeeper initializer I got an undefined method logout_uri.

### Expected behavior

I would expect this method to not throw an undefined method.

### Actual behavior

It throws an undefined method.

### System configuration

This is just using the standard doorkeeper initializer. 

**Doorkeeper initializer**:

**Ruby version**:

**Gemfile.lock**:

My guess is this is not a finished feature or not an actual feature but just an example of something you can do. If it's not a finished feature I am guessing all that would need to be done is a column added to the oauth_applications table and then populate that column when creating a new application? Also the method would then need to be completed to select from that column. Does that sound correct?

**Comment by felipeelias** [comment]
Hi, thanks for reporting this.

@nbulaj please confirm, but I believe this comment is just an example (introduced by ed95d94, #1062 and #1064)

**Comment by nbulaj** [comment]
Hi @wallerjake. @felipeelias is totally right about the `logout_uri` - it's just an example for the configuration option in the initializer. Doorkeeper itself [doesn't have any `logout_uri`](https://github.com/doorkeeper-gem/doorkeeper/search?q=logout_uri&unscoped_q=logout_uri), so you just need to redefine your configuration hooks and everything must be OK.
