### ISSUE TITLE
Upgrading Doorkeeper to 4.4.3 results NoMethodError: super: no superclass method `redirect_uri=' for Doorkeeper::Application

### ISSUE THREAD

**Issue by veluvijayv2** [doorkeeper-gem/doorkeeper#1250]
### Steps to reproduce
Upgrade the doorkeeper gem from 4.2.6 to greater versions, I was upgrading to 4.4.3

The more detailed the issue, the more likely that we will fix it ASAP.
I had upgraded the Doorkeeper gem to 4.4.3 to fix the below vulnerability that audit raised

> Title: Doorkeeper gem does not revoke token for public clients
> Solution: upgrade to >= 4.4.0, >= 5.0.0.rc2

After upgrading, my application test cases are failing in the Doorkeeper::Application.new(app_params) part with the below error,

NoMethodError: super: no superclass method `redirect_uri=' for #<Doorkeeper::Application >

I have checked the source code in the gem at application_mixin.rb file and found new code introduced for >4.2.6 versions

def redirect_uri=(uris)
    super(uris.is_a?(Array) ? uris.join("\n") : uris)
end

Note: In development environment it is working fine.

### Expected behavior
Test cases should pass

### Actual behavior
Test cases failing

**Comment by nbulaj** [comment]
Hi @veluvijayv2 . Which Rails version did you use? Maybe you have some patches to Doorkeeper models?

Seems like Doorkeeper application model can't resolve it's attribute methods. Try to update Rails first please

**Comment by veluvijayv2** [comment]
Thanks @nbulaj for the reply.
We are using 
    Rails version —> 5.1.6.1
    Ruby version —> 2.6.1
    Doorkeeper Version —> 4.4.3, tried with latest 5.1.0 too but getting the same error

In dev environment,
   Doorkeeper::Application(id: integer, name: string, uid: string, secret: string, redirect_uri: text, scopes: string, owner_id: integer, owner_type: string, created_at: datetime, updated_at: datetime)

In test environment,
 Doorkeeper::Application(Table doesn't exist)
But we have the tables in test env, Doorkeeper::Application model is not getting the attributes method as you said.

Tried some ways like,
* Rails.application.eager_load!
* ActiveRecord::Base.descendants
* Doorkeeper::Application.define_attribute_methods
* ActiveRecord::Base.send(:subclasses)
* ```
Doorkeeper.configure do
        orm :active_record
        active_record_options(
          establish_connection: Rails.configuration.database_configuration[Rails.env]
        )
      end

```

But still the attribute methods are not resolving.

**Comment by veluvijayv2** [comment]
Closing this as there is no issue after loading the model attributes in test suite
