### ISSUE TITLE
Rename news.md to changelog.md

### ISSUE THREAD

**Issue by ianbayne** [doorkeeper-gem/doorkeeper#1251]
From what I can tell, `changelog.md` is the standard and the one most readily identified as containing a log of changes between versions.

**Comment by nbulaj** [comment]
Agree about standards, but it can be harmful due to external services dependencies to this file (like services that posts change log entries for auto-updates, gemnasium and so on).

Maybe we can leave this document, but replace it with a link to a new changelog?
WDYT @felipeelias  ?

**Comment by ianbayne** [comment]
> Maybe we can leave this document, but replace it with a link to a new changelog?

That sounds like a good idea.

**Comment by nbulaj** [comment]
Done 🎉
