### ISSUE TITLE
Incorrect behaviour of context.client in custom_access_token_expires_in and use_refresh_token blocks

### ISSUE THREAD

**Issue by rishabhsairawat** [doorkeeper-gem/doorkeeper#1254]
### Steps to reproduce
Use `/oauth/token` API for `password` `grant_type` without `client_id` or `client_secret`

### Expected behavior
In `custom_access_token_expires_in` and `use_refresh_token` blocks, `context.client` should be `nil`

### Actual behavior
In `custom_access_token_expires_in` and `use_refresh_token` blocks, `context.client` is giving `false`

### System configuration
 `doorkeeper (= 5.0.2)`

**Comment by nbulaj** [comment]
Hi @rishabhsairawat . I think I know the source of this issue and why it worked this all the time, but think that to have `nil` for non-authorized client would be a better option. Would you like to propose a PR?

**Comment by rishabhsairawat** [comment]
@nbulaj This has been fixed (#1185) and released in [v5.1.0.rc1](https://github.com/doorkeeper-gem/doorkeeper/releases/tag/v5.1.0.rc1).
