### ISSUE TITLE
Doorkeeper inside mountable engines?

### ISSUE THREAD

**Issue by shittyhomework** [doorkeeper-gem/doorkeeper#1265]
###
May I know how to setup doorkeeper in rails engine?

I figured how to use doorkeeper views. but I have issues with the doorkeeper helper?

```
undefined local variable or method `oauth_applications_path'

def doorkeeper_submit_path(application)
    application.persisted? ? oauth_application_path(application) : oauth_applications_path     end
end end
```

**Comment by nbulaj** [comment]
Hi @shittyhomework . We have a page for multi-engine applications, https://github.com/doorkeeper-gem/doorkeeper/wiki/Integration-with-multi-engine-Rails-application , and also you could take a look at this issue: https://github.com/doorkeeper-gem/doorkeeper/issues/1083

**Comment by nbulaj** [comment]
Also check this https://edgeguides.rubyonrails.org/engines.html#routes and let us know if it helped please
