### ISSUE TITLE
Uncaught Null Exception When Creating Access Token

### ISSUE THREAD

**Issue by dylancopeland** [doorkeeper-gem/doorkeeper#1267]
When creating an access token using the Resource Owner Password Grant strategy, there is the possibility of a null exception being thrown due to a null `application_id` if a client isn't supplied. I understand that this can be suppressed by allowing nulls on the `application_id` column in the `oauth_access_tokens` table, but that will then allow tokens to be created without supplying a client ID (or a client secret, or both).

I have a use case that requires the Resource Owner Password Grant strategy while also requiring a client ID in the access token request. Everything works great, but I'd like to be able to catch exceptions if a bad client is trying to generate tokens.

Should a config option be added to the Doorkeeper initializer to allow for password grants to require a client?

**Comment by dylancopeland** [comment]
It looks like a recent pull request changed default behavior of Doorkeeper is to return an `invalid_client` if the `client_id` parameter is missing. This change was introduced in d873ef5cd09631b502a8e46ef4d6c8c105f0dfdd. However, the logic for checking for a `client_id` in  `validate_client` seems to be reversed. Is this intentional?

**Comment by nbulaj** [comment]
Hi @dylancopeland . Could you please provide some spec with the case you need ? It seems like you need something out of the RFC scope, so the only way I see it is to patch Doorkeepre controllers to find client by params. But let's see

**Comment by nbulaj** [comment]
Any update here?
