### ISSUE TITLE
Enforce Scope On Access Token Request

### ISSUE THREAD

**Issue by dylancopeland** [doorkeeper-gem/doorkeeper#1268]
Per [the spec](https://tools.ietf.org/html/rfc6749#section-3.3), the authorization server should have the option to reject authorization token requests that don't supply a scope:

>  If the client omits the scope parameter when requesting
   authorization, the authorization server MUST either process the
   request using a pre-defined default value or fail the request
   indicating an invalid scope.

It looks like Doorkeeper currently doesn't support rejecting requests that lack a scope out of the box. Is this something that should be added?

**Comment by nbulaj** [comment]
Hi @dylancopeland . So what is the current of Doorkeeper for the case when `scope` parameter is blank? I don't actually remember, but I think it's 400 Bad request response which is correct behavior. So you are suggesting to introduce an option to allow server to process the request with a default set of scope, right? Would you like to propose a PR ?

**Comment by dylancopeland** [comment]
Hi @nbulaj,

Currently, Doorkeeper will create the access token with a blank scope and return a 200. The current test config I'm using has `optional_scopes` defined but no `default_scope`. There doesn't seem to be a way to enforce the requirement of a scope. Ideally, I'd like Doorkeeper to only issue a token if the scopes defined in the request match what is defined in the `optional_scopes`.

I'm happy to make an attempt at implementing this in a PR if you think it's suitable and true to the spec.

**Comment by nbulaj** [comment]
It creates blank scopes and returns 200 because you have `default_scope []` or smth like this ? I think it must be fixed (use default scopes if they defined or return an error). Or be configurable (developer mush choose - use default scopes or throw an error)

**Comment by nbulaj** [comment]
Hi @dylancopeland . We merged fixes recently and it will be great if you could test new RC version of the gem and check if your issue is fixed
