### ISSUE TITLE
There is typo error in v5.2.0.rc1 release description

### ISSUE THREAD

**Issue by linhdangduy** [doorkeeper-gem/doorkeeper#1276]
### Expected behavior
At [release](https://github.com/doorkeeper-gem/doorkeeper/releases), two PRs of `Improve Token introspection...` is 1260 and 1262, not 1261
![image](https://user-images.githubusercontent.com/9018303/59752733-bda9b200-92bd-11e9-8f43-a0e67797cc37.png)

### Actual behavior
1260, #1262

**Comment by nbulaj** [comment]
Thanks @linhdangduy ! Fixed :tada:
