### ISSUE TITLE
401 always

### ISSUE THREAD

**Issue by stelasido** [doorkeeper-gem/doorkeeper#1278]
Hi, I have setup an app from 1. example app, from the tutorials - `https://scotch.io/@jiggs/rails-api-doorkeeper-devise` and right after that installing an app from example apps -`https://github.com/doorkeeper-gem/doorkeeper-provider-app`, but always for user that exists, I am getting 401 and I guess, I am missing something. What I send with Postman is this:

` {
  "user": "test@test.com",
  "password": "111111",
  "grant_type": "password"
}` (from docs)
I have that user and I can login with it with device sign_in views.
What I need to send and in which format ?

**Comment by stelasido** [comment]
???????????????????????????????????????????????????????????????????????????????????

**Comment by nbulaj** [comment]
Hi @stelasido . I think you've missed `client_id` and `client_secret` in your request payload. OAuth server needs to know which application (client) you are trying to authorize. Also not `user`, but `username`. 

Check password flow spec for more examples : https://github.com/doorkeeper-gem/doorkeeper/blob/master/spec/requests/flows/password_spec.rb
