### ISSUE TITLE
Wrong token scope for method results on empty 403

### ISSUE THREAD

**Issue by ArthurLuisLimaBender** [doorkeeper-gem/doorkeeper#1280]
I am using doorkeeper gem with devise on a Rails-API project. It was working really nice until I started creating scopes. I defined two scopes:

```
#initializers/doorkeeper.rb
    default_scopes  :user
    optional_scopes :admin
```

I also have a controller with two methods: post_main and get_main. get_main should be accessible by both :user and :admin, but post_main should be only accessible by admin. This is the code i have on my controller:
```
    before_action -> { doorkeeper_authorize! :user, :admin }, only: :get_main
    before_action only: :post_main do
        doorkeeper_authorize! :admin
    end
```
get_main is working fine, but when a token with scope :user tryies to reach post_main, the request returns empty with status 403, "forbidden". I want to customize this error, but i found nothing on Doorkeeper documentation. 

The console of the application also shows:

```
Filter chain halted as #<Proc:0x007f9470149ce8@/path/to/controller/characters_controller.rb:5> rendered or redirected
```
which is the `before_action only: :post_main do` line. Can someone help me?

**Comment by nbulaj** [comment]
Hi @ArthurLuisLimaBender . Actually I didn't get it: you face some issue or you just want to customize the error? 

For second one try configure the gem: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/generators/doorkeeper/templates/initializer.rb#L246

**Comment by ArthurLuisLimaBender** [comment]
I just want to customize the error. Return something, change the return status to 401: unauthorized...

**Comment by nbulaj** [comment]
Did you @ArthurLuisLimaBender checked the Wiki ? Like

[Customizing the response body when unauthorized](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-the-response-body-when-unauthorized) or [Customizing token error response](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-token-error-response), or try to check https://doorkeeper.gitbook.io

**Comment by ArthurLuisLimaBender** [comment]
Sorry for late answer. I checked this links and solved the problem. Thank you
