### ISSUE TITLE
Doorkeeper models not available in rake "environment"

### ISSUE THREAD

**Issue by thegcat** [doorkeeper-gem/doorkeeper#1281]
### Steps to reproduce

We use a rake task to create Doorkeeper Application objects, however it seems the availability of Doorkeeper models in rake tasks is broken for us.

The rake task https://stackoverflow.com/questions/tagged/doorkeeper
Relevant section in the README of our app: https://github.com/kif-ev/oskiosk-server#create-a-new-oauth-token

This used to work, I however haven't been able to find if the issue was with Doorkeeper or Rails by downgrading minor versions of each.

I have also tried adding `Doorkeeper::Rake.load_tasks` to the `Rakefile` and running the Doorkeeper rake tasks, it also fails to load the Doorkeeper models.

### Expected behavior

Doorkeeper models should be available in Rake tasks when the rake task depends on the `environment` task.

### Actual behavior

They aren't.

### System configuration

Mostly see https://github.com/kif-ev/oskiosk-server

**Comment by nbulaj** [comment]
Hi @thegcat . Looks like your rake task doesn't load ActiveRecord by some reason and Doorkeeper models isn't loaded too as they use `ActiveSupport#on_load` lazy loading hooks. Try to call `ActiveRecord::Base` somewhere in rake task before calling Doorkeeper models and if it started top work - that's the case. I don't sure why is such happening, there we need some debugging to check why Rails doesn't load ActiveRecord for you case

**Comment by thegcat** [comment]
Thank you for the suggestion, this works indeed!

As to why this doesn't happen automatically: I can't remember exactly but I might have created this project way back when as a RAILS API project, do you know if this might have an incidence in this case?

**Comment by nbulaj** [comment]
Also need to check it out, don't sure about it.

**Comment by nbulaj** [comment]
You can add `require 'active_record/base'` on top of your Rake task to call AR hooks that will invoke Doorkeeper model initialization. I just don't sure why it wasn't called if you use `task: :environment` :thinking: , maybe autoloading in development env or something like that.

**Comment by thegcat** [comment]
Thanks, that does the trick. As this is probably not directly related to doorkeeper and this fixes our problem I'll just close this here.
