### ISSUE TITLE
Cookies with token - OWASP fingerprinting

### ISSUE THREAD

**Issue by verenion** [doorkeeper-gem/doorkeeper#1284]
I am trying to implement the token sidejacking protection recommended by OWasp (https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/JSON_Web_Token_Cheat_Sheet_for_Java.md#token-sidejacking). This requres storing a cookie in token_payload. Is there a simple way of doing this?

**Comment by nbulaj** [comment]
Hi @verenion . Do you use doorkeeper-jwt gem? You could customize the payload of the token then. In other case you can't write additional data or check it somewhere ibside Doorkeeper.

**Comment by verenion** [comment]
I am yes. Sadly, `token_payload` is a callback method called deep within doorkeeper. Therefore, I cannot access the request or cookie object to actually store the cookie to be sent back as a header (Set-Cookie). I also cannot send the fingerprint back in the response, as that would then be accessible to javascript, making the entire purpose of the fingerprint pointless. I do however need to store a sha256 hash of the fingerprint inside the token - this can of course be done in `token_payload` - but there is then no way of storing the fingerprint in a cookie.

I have half-solved this already, by creating a deterministic fingerprint from the expiry time of the token, some element of the user (email, or ID) and some server-side secrets and salts. Being deterministic, this allows me to also generate the fingerprint in the tokenscontroller#create method and store the cookie there as a httpOnly, Secure cookie. I'm still researching how secure this actually is.

**Comment by nbulaj** [comment]
Ok, so seems like the answer to your first question is no, there is no simple way to to do it. You can try to patch doorkeeper internal controllers, here you have an access to cookies, headers and so on. However I don't sure we wanna to have such specific feature in the core gem, maybe only as some plugin.

**Comment by nbulaj** [comment]
There is nothing we can do with the issue (and it's actually not an issue), so I'm closing it. If you plan to propose a PR to add such functionality - you are very welcome :)

**Comment by zedtux** [comment]
@verenion have you done any kind of implementation, plugin or PR to solve this please ?

> However I don't sure we wanna to have such specific feature in the core gem

That's really surprised me, not wanting to have a good security level into the core gem, sounds wired to me.
