### ISSUE TITLE
Bug: client can request all server's scopes when it is registered without scopes 

### ISSUE THREAD

**Issue by linhdangduy** [doorkeeper-gem/doorkeeper#1301]
### Steps to reproduce
1. Register a client without specifying any scope: `scope=""`
2. Create an _authorization request_ to server by this client_id and with `scope` param that includes a subset of server's pre-defined scopes. 
3. __Client is granted to all scopes__ requested in authorization request.

Spec test:
```ruby
# spec/controllers/authorization_controller_spec.rb

describe "POST #create able to grant all server's scope to an empty scope client" do
  let(:client) { FactoryBot.create :application, scopes: "", name: "client_with_empty_registered_scopes" }

  before do
    default_scopes_exist :index, :create
    optional_scopes_exist :show, :destroy

    post :create, params: {
      client_id: client.uid,
      response_type: "token",
      redirect_uri: client.redirect_uri,
      scope: "index create show destroy",
    }
  end

  it "issues the token with requested scopes" do
    expect(Doorkeeper::AccessToken.first.scopes).to 
      eq(Doorkeeper::OAuth::Scopes.from_string("index show create destroy"))
  end
end
```
Although client is registered without any scopes, it could be granted to all scopes sent in authorization request.

### Expected behavior
At (3), instead of granting all requested scopes, client should be rejected with `invalid_scope` because it is registered without any scopes.

```ruby
it "includes error in fragment" do
  expect(response.query_params["error"]).to eq("invalid_scope")
end

it "does not issue any access token" do
  expect(Doorkeeper::AccessToken.all).to be_empty
end
```

### Cause
https://github.com/doorkeeper-gem/doorkeeper/blob/98a4036244fe92d2191486c1e6a47b44d6f01629/lib/doorkeeper/oauth/helpers/scope_checker.rb#L29-L35

If application's scope is not present, server's scopes will be used to validate against requested scopes.
because this code is used at many places to validate scopes, so it leads to this bug.

**Comment by acceptto-nhumble** [comment]
Given that the [documentation](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes) states:

> If the scopes field is not populated then the default_scopes from the Doorkeeper configuration will be used instead.

This is certainly unexpected behavior and leads to a potential security hole in implementations. I can confirm that this is present when `default_scopes` is set and the application has no scopes (`""`).
