### ISSUE TITLE
When setting api_only mode to true, ActionController::Base will cause CSRF issues

### ISSUE THREAD

**Issue by 0xtobit** [doorkeeper-gem/doorkeeper#1302]
I've spent several days trying to figure out why my api_only Rails 5 app and api_only Doorkeeper configuration would be throwing CSRF issues.

With some assistance I finally figured out that it was because Doorkeeper, by default, inherits from `ActionController::Base` which will re-add the check for CSRF protections (which are attempted to be disabled in `app/controller/doorkeeper/application_controller.rb`)

I believe it would be useful to either:
1. Change the `base_controller` to `ActionController::API` when `api_only` is set to `true
2. Add a note in the documentation/guide (perhaps adding on to the notes added in #1123 )
3. Add a note to the generated `config/initializers/doorkeeper.rb`, specifically the `api_only` block mentioning that adjustments to the `base_controller` need to be made.

or some combination of the above.

### Steps to reproduce
Create an API only rails application (I'm on 5.2.3). Add doorkeeper in and uncomment `api_only` in the initializer.

After creating an application, POST to /oauth/authorize as laid out in [the API docs](https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples#post---oauthauthorize)

### Expected behavior
POSTing to /oauth/authorize (with appropriate client_id, client_secret, etc.) should return a code and redirect

Setting api_only mode to true should either change the base_controller or tell me I have to in documetnation.

### Actual behavior
POSTing to /oauth/authorize `ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)` is raised

### System configuration

**Ruby version**: 2.6.3

**Doorkeeper version**: 5.1.0

I think this is somewhat related to the discussions happening in #1110

**Comment by 0xtobit** [comment]
I'm more than happy to make the proposed updates to the documentation, but would love to hear the maintainers thoughts and preferences <3

**Comment by nbulaj** [comment]
Hi @0xtobit . Thanks for reporting this issue, sorry for the delay - I was on vacation :beach_umbrella: 

I like this idea:

> Change the base_controller to ActionController::API when api_only is set to `true

But also I like next two points about documentation :) It would be great to have an opinionated config with mode-detecting logic for base application controller, and some notes about CSRF check that must be defined by developer itself in initializer and docs. Will be great if you propose a PR :handshake:
