### ISSUE TITLE
AccessToken.find_or_create_for passed incorrect argument types

### ISSUE THREAD

**Issue by KimBurgess** [doorkeeper-gem/doorkeeper#1316]
[Docs for `AccessToken.find_or_create_for`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/models/access_token_mixin.rb#L154-L155) point to this method expecting a `Doorkeep::Application` instance. Internal invocations appears to instead pass a `Doorkeeper::OAuth::Client`.

See:
- https://github.com/doorkeeper-gem/doorkeeper/blob/41ab5b20a1aeab237d349ea0aa64023dee3d0ded/lib/doorkeeper/oauth/client_credentials/creator.rb#L16-L19
- https://github.com/doorkeeper-gem/doorkeeper/blob/59a1227a963b1034bb9df61ad377bb745c34f297/lib/doorkeeper/oauth/authorization/token.rb#L57-L63
- https://github.com/doorkeeper-gem/doorkeeper/blob/6a9b09142b2e89ab87751322170ecf6f5dd4fe51/lib/doorkeeper/oauth/base_request.rb#L39-L45

[Delegations exist](https://github.com/doorkeeper-gem/doorkeeper/blob/59a1227a963b1034bb9df61ad377bb745c34f297/lib/doorkeeper/oauth/client.rb#L8) which masks this under most usage scenarios. However, issues arise downstream when attempting to access application attributes that are not included in these delegations. An example of this is [extracting `owner_id` in the couchbase orm](https://github.com/acaprojects/doorkeeper-couchbase/blob/468949de7e6582e922b072b6db02e5d372795a2c/lib/support/orm/couchbase/access_token.rb#L176).

Happy to submit a PR to fix this up, but before doing so - I don't have super deep knowledge of this lib - is this a bug, or is there a reason that client instances are passed instead of applications?

**Comment by nbulaj** [comment]
Hi @KimBurgess . Actually I think it's a bug, so I'll be happy to see a PR <3
