### ISSUE TITLE
ActiveRecord: Require redirect_uri_validator in the model so it does not blow up

### ISSUE THREAD

**Issue by grosser** [doorkeeper-gem/doorkeeper#1330]
I had to add `require 'doorkeeper/orm/active_record/redirect_uri_validator'` to my controller so using AccessToken does not crash with `Unknown validator: 'Doorkeeper::RedirectUriValidator'` ... please require that.
(I'm not eager-loading all of doorkeeper)

**Comment by arich** [comment]
Hi, can we get a new version released for this patch? Thank you!
