### ISSUE TITLE
Add a new permitted parameter on applications controller

### ISSUE THREAD

**Issue by thadeubrito** [doorkeeper-gem/doorkeeper#1333]
Hello guys, I would like to a new attribute to doorkeeper application but I faced to strong parameters in `applications_controller.rb`, where the attributes permitted are fixed. There is a easy way to add a new parameter?

`applications_controller.rb`:

```ruby
def application_params
    params.require(:doorkeeper_application)
        .permit(:name, :redirect_uri, :scopes, :confidential)
end
```

**Comment by thadeubrito** [comment]
RESOLVED
I don't know if it is the best way but it is good for now.
I added this in `config/initializers/doorkeeper.rb`:
```ruby
Doorkeeper::ApplicationsController.class_eval do
  private

  def application_params
    params.require(:doorkeeper_application)
          .permit(:name, :redirect_uri, :scopes, :confidential, service_providers: [], client_realms: [])
  end
end
```
the `[]` is because of parameters type is an array

**Comment by nbulaj** [comment]
Hi @thadeubrito . You can create custom `ApplicarionsController` which will inherit from `Doorkeeper::ApplicationsController`. And there you can just override the method for params
