### ISSUE TITLE
User cannot grant the client again after revoking AccessGrant

### ISSUE THREAD

**Issue by znz** [doorkeeper-gem/doorkeeper#1336]
### Steps to reproduce

- Call `Doorkeeper::AccessGrant#revoke`
- User tries to grant again
- get `OAuth2::Error (invalid_grant)` error when using oauth2 gem

### Expected behavior

- User can grant again after user revokes grant
- And create new AccessGrant

### Actual behavior

AccessGrant does not care revoked or not.
https://github.com/doorkeeper-gem/doorkeeper/blob/c075df53caf0c40f5accb276af256858c3aa79eb/lib/doorkeeper/request/authorization_code.rb#L22

AccessToken uses `where(..., revoked_at: nil)`.
https://github.com/doorkeeper-gem/doorkeeper/blob/c075df53caf0c40f5accb276af256858c3aa79eb/lib/doorkeeper/models/access_token_mixin.rb#L197

### System configuration

I confirmed with adding a rough scenario to spec of master.

```
% git rev-parse HEAD
c075df53caf0c40f5accb276af256858c3aa79eb
% git diff
diff --git a/spec/requests/flows/authorization_code_spec.rb b/spec/requests/flows/authorization_code_spec.rb
index 01eb0f0e..a273d11b 100644
--- a/spec/requests/flows/authorization_code_spec.rb
+++ b/spec/requests/flows/authorization_code_spec.rb
@@ -454,6 +454,21 @@ feature "Authorization Code Flow" do
       access_token_should_have_scopes :public, :write
     end

+    scenario "revoke!" do
+      visit authorization_endpoint_url(client: @client, scope: "public")
+      click_on "Authorize"
+      Doorkeeper::AccessGrant.first.revoke
+      #Doorkeeper::AccessGrant.delete_all # pass when delete
+      visit authorization_endpoint_url(client: @client, scope: "public write")
+      click_on "Authorize"
+
+      authorization_code = Doorkeeper::AccessGrant.first.token
+      create_access_token authorization_code, @client
+
+      access_token_should_exist_for(@client, @resource_owner)
+      access_token_should_have_scopes :public, :write
+    end
+
     scenario "returns new token if scopes have changed" do
       client_is_authorized(@client, @resource_owner, scopes: "public write")
       visit authorization_endpoint_url(client: @client, scope: "public")
```

**Comment by linhdangduy** [comment]
@znz 
```ruby
scenario "revoke!" do
     visit authorization_endpoint_url(client: @client, scope: "public")
     click_on "Authorize"
     Doorkeeper::AccessGrant.first.revoke
     #Doorkeeper::AccessGrant.delete_all # pass when delete
     visit authorization_endpoint_url(client: @client, scope: "public write")
     click_on "Authorize"
     authorization_code = Doorkeeper::AccessGrant.first.token
     create_access_token authorization_code, @client
     access_token_should_exist_for(@client, @resource_owner)
     access_token_should_have_scopes :public, :write
end
```
👆With this test case, we can see that you revoked first access grant 
> Doorkeeper::AccessGrant.**first**.revoke

Then you use exactly that access grant for exchange access token 
> authorization_code = Doorkeeper::AccessGrant.**first**.token

Just change to: `Doorkeeper::AccessGrant.last.token`, then it will run as you expected.

**Comment by nbulaj** [comment]
Hi @znz. Could you please check reply above? Does it solves your problem or it's an issue int the spec ?
