### ISSUE TITLE
Doorkeeper::Application#to_json doesn't respect ActiveRecord::Base.include_root_in_json

### ISSUE THREAD

**Issue by JoshNorthrup** [doorkeeper-gem/doorkeeper#1344]
Introduced by https://github.com/doorkeeper-gem/doorkeeper/commit/e59b25f6a26f01efd6339c8884dc06e7ab284b22
### Steps to reproduce

```
Doorkeeper::Application.include_root_in_json = true
JSON.parse(Doorkeeper::Application.take.to_json).keys # != ['application']

```

### Expected behavior
I would expect the root json key to be included in the json if `include_root_in_json == true`

**Comment by nbulaj** [comment]
Hi @JoshNorthrup ! First of all thanks for reporting the issue <3

Would you like to propose a PR to fix it?

**Comment by JoshNorthrup** [comment]
Thanks for the response @nbulaj, I can try to put something together over the weekend

**Comment by nbulaj** [comment]
Actually I've fixed it, so the fix would be released with 5.3.0 version

**Comment by JoshNorthrup** [comment]
Great, thanks! Do you have an ETA on 5.3.0?

**Comment by nbulaj** [comment]
@JoshNorthrup  actually I didn't have some, but I think we can prepare a release next week
