### ISSUE TITLE
Password Grant Type requires client_id and client_secret params to work..

### ISSUE THREAD

**Issue by errawn** [doorkeeper-gem/doorkeeper#1347]
> Hey people, I'm trying to implement the password grant flow, but it only works when I send the client_id and client_secret as params for /oauth/token endpoint. is there any way to implement password grant flow without sending those params (for security reasons) from the client app?.

same. when leaving the client_id and client_secret as params empty, error says:
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/18679035/72680652-6390f980-3af7-11ea-853f-fd4232fc300d.png">

but when I re-included it, it proceeds in OK:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/18679035/72680676-a357e100-3af7-11ea-888a-678bba60f2e9.png">

this is **confusing**. I may have misconfigured something. Thanks ^^

_Originally posted by @errawn in https://github.com/doorkeeper-gem/doorkeeper/issues/561#issuecomment-575998226_

This is my doorkeeper file:
https://github.com/errawn/oauth-rails/blob/master/config/initializers/doorkeeper.rb

**Comment by nbulaj** [comment]
Take a look at OAuth RFC, or more descriptive example here: https://www.oauth.com/oauth2-servers/access-tokens/password-grant/ , section "Request Parameters"

As Doorkeeper always creates application with secrets, to use Password Grant type server needs to perform Client Authentication. Also you could have more than one application (client) so you need to identify which ones used to authorize.
