### ISSUE TITLE
Doorkeeper UI does not show the application secret anymore

### ISSUE THREAD

**Issue by rhymes** [doorkeeper-gem/doorkeeper#1372]
### Steps to reproduce

Probably a regression from https://github.com/doorkeeper-gem/doorkeeper/issues/1246

1. enable `hash_applications_secret`
1. create an app
1. the application secret in the flash doesn't show anymore.

![flash](https://user-images.githubusercontent.com/146201/76200556-23462180-61f2-11ea-8d38-6a9446e0371f.gif)

### Expected behavior

1. the application secret should appear in the flash message so that the admin can note it down and communicate it to the integrator

Though the code has changed a bit since https://github.com/doorkeeper-gem/doorkeeper/issues/1246 it looks like the code to show the secret in the controller is still there:

https://github.com/doorkeeper-gem/doorkeeper/blob/1b2baed5b5e74c8f1d1f6fa939a61626fd84df06/app/controllers/doorkeeper/applications_controller.rb#L33-L35

but the show page doesn't show it the first time:

https://github.com/doorkeeper-gem/doorkeeper/blob/1b2baed5b5e74c8f1d1f6fa939a61626fd84df06/app/views/doorkeeper/applications/show.html.erb#L10-L11

🤷‍♂ 

### Actual behavior

1. the application secret in the flash doesn't show anymore.

### System configuration

**Doorkeeper initializer**:

```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  orm :active_record

  resource_owner_authenticator do
    current_user || warden.authenticate!(scope: :user)
  end

  admin_authenticator do
    if current_user
      head :forbidden unless current_user.admin?
    else
      warden.authenticate!(scope: :user)
    end
  end

  base_controller "ApplicationController"

  hash_token_secrets

  hash_application_secrets

  use_refresh_token

  default_scopes :public, :read_articles
end
```

see https://github.com/thepracticaldev/dev.to/blob/master/config/initializers/doorkeeper.rb (only uncommented `hash_application_secrets`)

**Ruby version**: Ruby 2.6.5

**Gemfile.lock**:

https://github.com/thepracticaldev/dev.to/blob/master/Gemfile.lock

**Comment by nbulaj** [comment]
Hi @rhymes . Thanks for reporting the issue. Actually as I remember we have specs for it (they check if secret renders when hashing enabled). But maybe we have some wrong tests setup. So need to check it.

BTW PRs are welcome :)

**Comment by nbulaj** [comment]
Hi @rhymes . I've tried to reproduce the erorr with a fresh Rails app and Doorkeeper from master branch, but when I create the application - I can see a secret:

![image](https://user-images.githubusercontent.com/1443426/78336618-55039b80-7598-11ea-97cd-cd4bd8584794.png)

On the page refresh it disappears and it's an expected behavior

**Comment by nbulaj** [comment]
Added some improvements for application secret data on #show page in #1393

But can't reproduced your error :(

**Comment by rhymes** [comment]
I tried with doorkeeper master as well, same configuration, but can't see it :( 
Tried both with Firefox and Chrome, did you try with the configuration we have?

**Comment by nbulaj** [comment]
I tried with default Doorkeeper configuration and a fresh new Rails app. 

Now I've tried with your initializer (except `admin_authenticator` - I used just `true` to make it faster)

And everything works

![image](https://user-images.githubusercontent.com/1443426/78555038-e67f4180-7814-11ea-9f62-4a5fd86c37f4.png)

**Comment by rhymes** [comment]
Weird :( I'll investigate further, thanks for the help!
