### ISSUE TITLE
Skip specific methods of controller routes

### ISSUE THREAD

**Issue by pjmartorell** [doorkeeper-gem/doorkeeper#1378]
### Steps to reproduce
```ruby
      use_doorkeeper do
        skip_controllers :applications, :authorized_applications, :authorizations, :token_info
      end
```
generates:
```ruby
                      Prefix Verb URI Pattern                             Controller#Action
                 oauth_token POST /oauth/token(.:format)                  doorkeeper/tokens#create {:format=>:json}
                oauth_revoke POST /oauth/revoke(.:format)                 doorkeeper/tokens#revoke {:format=>:json}
            oauth_introspect POST /oauth/introspect(.:format)             doorkeeper/tokens#introspect {:format=>:json}
```
but I would like to generate only:
```ruby
                 oauth_token POST /oauth/token(.:format)                  doorkeeper/tokens#create {:format=>:json}
```
skipping `revoke` and `introspect` since I don't want to expose these endpoints. Is it possible? I inspected the code but I didn't find any option. Sorry that this is more a question than an issue.

**Comment by nbulaj** [comment]
Hi @pjmartorell . Currently Doorkeeper doesn't support such option to skip some specific routes, but maybe Rails has something.

**Comment by pjmartorell** [comment]
@nbulaj I think it would be worth to add an option to skip some methods of specific controllers. Something like:
```ruby
skip_controllers: : authorizations, { applications: { only: :token }
```
It wouldn't break the current behavior and I can do a PR with these changes. What do you think?

**Comment by nbulaj** [comment]
Let's do it
