### ISSUE TITLE
Multiple Models

### ISSUE THREAD

**Issue by errawn** [doorkeeper-gem/doorkeeper#1379]
How does doorkeeper support multiple Models? something like this..

<img width="714" alt="image" src="https://user-images.githubusercontent.com/18679035/77232554-a5641c00-6bdc-11ea-86b2-efabe4bbfeaf.png">

**Comment by nbulaj** [comment]
Hi @errawn . Check this one and latest Doorkeeper version:" https://github.com/doorkeeper-gem/doorkeeper/pull/1355

Basically now you can enable polymorphic resource owner and just get it from the `doorkeeper_token` itself (type & id)

**Comment by errawn** [comment]
Thank you @nbulaj! Will try it out. Does it have a detailed docs or in wiki? Thank you very much

**Comment by nbulaj** [comment]
@errawn nope. still no docs or wiki page :(

**Comment by errawn** [comment]
@nbulaj  I am getting 
` undefined local variable or method `use_polymorphic_resource_owner' for #<Doorkeeper::Config::Builder:0x00007fb56eb9e328> (NameError)`

When I run `bundle exec rails g doorkeeper:enable_polymorphic_resource_owner`

**Comment by nbulaj** [comment]
Which version do you use? It's not released yet and available only [on master](https://github.com/doorkeeper-gem/doorkeeper/blob/master/CHANGELOG.md#master)

**Comment by nbulaj** [comment]
Added docs here: https://doorkeeper.gitbook.io/guides/ruby-on-rails/polymorphic-resource-owner

**Comment by nbulaj** [comment]
I think we can close this issue. If you wanna to use polymorphic resource owner feature - you need to use master version of the gem.

Also I saw somewhere on StackOverflow how people bypass the restrictions of Doorkeeper and uses additional http parameter or even scopes to indicate resource owner type. Try to find it

**Comment by errawn** [comment]
thanks @nbulaj  awesome work! <3
