### ISSUE TITLE
5.0.3 is missing from Ruby Gems 

### ISSUE THREAD

**Issue by pawurb** [doorkeeper-gem/doorkeeper#1403]
Hi. I want to fix https://github.com/doorkeeper-gem/doorkeeper/security/advisories/GHSA-j7vx-8mqj-cqp9 in my app but apparently 5.0.3 is not released to Ruby Gems https://rubygems.org/gems/doorkeeper/versions . 

I had to point gemfile to your repo as a workaround. Could you look into releasing this version?

**Comment by nbulaj** [comment]
Hi @pawurb . Yep, it's missed somehow :cry: Released, thanks for informing me!
