### ISSUE TITLE
Ignore code_verifier for non-PKCE grants

### ISSUE THREAD

**Issue by toupeira** [doorkeeper-gem/doorkeeper#1411]
### Summary

Doorkeeper rejects non-PKCE authorization requests if they include a `code_verifier` param:

```
invalid_request (The request is missing a required parameter, includes an unsupported parameter value, or is otherwise malformed.)
```

This does not conform with the spec, see the very last paragraph at https://tools.ietf.org/html/rfc6749#section-3.2 :

> The authorization server MUST ignore unrecognized request parameters.

### Background

This was originally reported at https://github.com/panva/node-openid-client/issues/247 and https://gitlab.com/gitlab-org/gitlab/-/issues/213643.

### Proposal

Only check the presence of `code_verifier` for PKCE grants:

```patch
diff --git i/lib/doorkeeper/oauth/authorization_code_request.rb w/lib/doorkeeper/oauth/authorization_code_request.rb
index 7511dee5..124f823f 100644
--- i/lib/doorkeeper/oauth/authorization_code_request.rb
+++ w/lib/doorkeeper/oauth/authorization_code_request.rb
@@ -56,7 +56,7 @@ module Doorkeeper
       end
 
       def validate_pkce_support
-        @invalid_request_reason = :not_support_pkce if grant &&
+        @invalid_request_reason = :not_support_pkce if grant&.uses_pkce? &&
                                                        !pkce_supported? &&
                                                        code_verifier.present?
 ```

I'm not sure if we still need the last condition (`code_verifier.present?`), it seems we should reject all PKCE grants if `pkce_supported?` is false?

Happy to submit a PR for this, but wanted to hear your thoughts first.

**Comment by nbulaj** [comment]
Hi @toupeira ! Thanks for reporting this!

Yep, makes sense to me . As well as your point about last condition. I remember @bpieck done a lot of work on PKCE so I'll ping him just in case

**Comment by bpieck** [comment]
Looks totally reasonable to me.

**Comment by toupeira** [comment]
@nbulaj @bpieck thanks for your input!

I wanted to implement this but then saw that `uses_pkce?` also checks `pkce_supported?`, so my suggested condition would actually never be true: https://github.com/doorkeeper-gem/doorkeeper/blob/4dd7c514e40eb8aea196f1bcf219ab234fc2e89e/lib/doorkeeper/models/access_grant_mixin.rb#L18

Looking at the [spec](https://tools.ietf.org/html/rfc7636#section-4.4.1) this error case isn't mentioned, so I *think* we can just remove `validate_pkce_support` altogether?

The opposite case where PKCE is enabled but the client isn't sending the required params should already be handled in `validate_params`.

**Comment by linhdangduy** [comment]
@toupeira 
> This does not conform with the spec, see the very last paragraph at https://tools.ietf.org/html/rfc6749#section-3.2 :
> 
> > The authorization server MUST ignore unrecognized request parameters.

We can see that the same sentence is written at here, too: 3.1.  Authorization Endpoint: https://tools.ietf.org/html/rfc6749#section-3.1

So I think we should ignore `code_challenge` and `code_challenge_method` parameters at [PreAuthorization](https://github.com/doorkeeper-gem/doorkeeper/blob/ca3b6441f039a8e4cdb5de5c2b3dd85822bc25bf/lib/doorkeeper/oauth/pre_authorization.rb#L119-L122)

May be we can change as following:
```ruby
# pre_authorization.rb
# if AS doesn't support PKCE, ignore code_challenge and code_challenge_method params.
def validate_code_challenge_method
  return true unless Doorkeeper.config.access_grant_model.pkce_supported?
        
  code_challenge.blank? ||
    (code_challenge_method.present? && code_challenge_method =~ /^plain$|^S256$/)
  end
end
```

**Comment by linhdangduy** [comment]
> Looking at the [spec](https://tools.ietf.org/html/rfc7636#section-4.4.1) this error case isn't mentioned, so I _think_ we can just remove `validate_pkce_support` altogether?

Agree!!! As RFC, that is unnecessary.

**Comment by toupeira** [comment]
@linhdangduy thanks! :+1: 

I submitted https://github.com/doorkeeper-gem/doorkeeper/pull/1415 now which addresses both of these changes.
