### ISSUE TITLE
Question for Doorkeeper provider app and devise client app.

### ISSUE THREAD

**Issue by sasha53727** [doorkeeper-gem/doorkeeper#1414]
### Question for doorkeeper-gem.
I installed **doorkeeper-gem/doorkeeper-provider-app** and **doorkeeper-gem/doorkeeper-devise-client** on my local.

**provider-app** is running with port 3000 and **devise-client** is running with port 3001.
and I registered **devise-client** on **provider-app**
And then I ran authorize on **provider-app** but authorize is not working.
Refer screenshots.
screenshot below is **devise-client** app environment variable from **provider-app**
![image](https://user-images.githubusercontent.com/54854604/82566464-f4312200-9b49-11ea-8d97-b3aa0152971c.png)
These below is action screen step by step.
![image](https://user-images.githubusercontent.com/54854604/82565814-08285400-9b49-11ea-9b52-a7c1690b2d33.png)
![image](https://user-images.githubusercontent.com/54854604/82565923-3017b780-9b49-11ea-96c3-fca136c902ee.png)
![image](https://user-images.githubusercontent.com/54854604/82565965-3f970080-9b49-11ea-888f-af3c90c90790.png)
![image](https://user-images.githubusercontent.com/54854604/82566055-5ccbcf00-9b49-11ea-8c5c-8821d320b7aa.png)
![image](https://user-images.githubusercontent.com/54854604/82566099-6ce3ae80-9b49-11ea-8050-913dedfca728.png)
![image](https://user-images.githubusercontent.com/54854604/82566141-7a993400-9b49-11ea-9317-75a14d8c8a2b.png)
What is incorrect?
so I decided to check live app to find my issue.

## Question for Doorkeeper provider live site.
https://doorkeeper-provider.herokuapp.com/
This website is not working.
and also http://doorkeeper-devise.herokuapp.com/ is not working with above provider app.

so I couldn't use this gem
Please  help me!!!!

Live site issue.
![image](https://user-images.githubusercontent.com/54854604/82566265-a5838800-9b49-11ea-8cb7-1365e297672f.png)
![image](https://user-images.githubusercontent.com/54854604/82566357-cba92800-9b49-11ea-91f5-150c2291a283.png)

**Comment by nbulaj** [comment]
Hi @sasha53727 . Sorry, I don't have enough time to check your question.

I fixed issues with the provider so it now works and you could check it again.
