### ISSUE TITLE
[Feature Request] No custom parameters could be sent to token generator from the client

### ISSUE THREAD

**Issue by FunkyloverOne** [doorkeeper-gem/doorkeeper#1417]
Maybe I am wrong, but I'm looking at this method here:
https://github.com/doorkeeper-gem/doorkeeper/blob/6e4c70f56460d9acdc4018615af102244ef58828/lib/doorkeeper/models/access_token_mixin.rb#L427

and it looks like I cannot pass any custom parameters there (for my custom token generator). But I need that :D 
Please let me know if I'm missing something, or if a PR for such feature would be welcome, thanks!

**Comment by nbulaj** [comment]
Hi @FunkyloverOne .

You could use a feature to define your custom access token model and override this method:

```ruby
class AccessToken < Doorkeeper::AccessToken
  def attributes_for_token_generator
    super.merge(hacker: "me")
  end
end

# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  access_token_class "::AccessToken"
end
```

More info here: https://doorkeeper.gitbook.io/guides/configuration/models

**Comment by FunkyloverOne** [comment]
Thank you @nbulaj! Closing this issue.
