### ISSUE TITLE
add X-Content-Type-Options to TokenResponse#headers

### ISSUE THREAD

**Issue by kinakobo** [doorkeeper-gem/doorkeeper#1419]
I thought it would be better to set `X-Content-Type-Options: nosniff` in the header of the TokenResponse.
https://github.com/doorkeeper-gem/doorkeeper/blob/ebe0fc12271c700edea5b4ceecc98ea256d55c37/lib/doorkeeper/oauth/token_response.rb#L27-L33

ref: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/gg622941(v=vs.85)

I create pull request if needed.

**Comment by nbulaj** [comment]
Hi @kinakobo . Isn't it something specific for Internet Explorer?
I also didn't find any recommendations on adding this one in OAuth specs

**Comment by kinakobo** [comment]
sorry I didn't check the OAuth specs. Certainly there is no such description.

> Isn't it something specific for Internet Explorer?

It is supported by Chrome / Firefox.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

Rails received X-Content-Type-Options by default, but it's not received by OAuth token endpoint, so I wondered and created issue.
https://guides.rubyonrails.org/v4.1/security.html#default-headers

**Comment by nbulaj** [comment]
So if Rails uses this headers by default, doesn't it means Doorkeeper use it too? I didn't check, but wanna to know

**Comment by kinakobo** [comment]
The cause was that my doorkeeper version is older than v5.1.0.

Prior to v5.1.0, `Doorkeeper::TokensController` inherits `ActionController::Metal`.
By default in v5.1.0 or later, `ActionController::API` is inherited.
https://github.com/doorkeeper-gem/doorkeeper/commit/cc37b86661fa2cf046bb87424516a2cd27883233#diff-19f61d7b331feabc5b91a716edc3c531R4

`ActionController::API` seems to include default_headers but not `ActionController::Metal`.

In case of Metal, `ActionDispatch::Response.new` is used.
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal.rb#L133
In case of API, `ActionDispatch::Response.create` is used.
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/api.rb#L124
https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/default_headers.rb#L11

`ActionDispatch::Response.new` does not include default_headers.
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/response.rb#L152
`ActionDispatch::Response.create` include default_headers.
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/response.rb#L166

So I found that raising the version would solve the problem.
Sorry for my lack of research. Thank you for your reply.

**Comment by nbulaj** [comment]
Could we now close this issue @kinakobo ? :)
Thanks for your proposal and investigation :bow:
