### ISSUE TITLE
PKCE should be generated in default migration

### ISSUE THREAD

**Issue by benaubin** [doorkeeper-gem/doorkeeper#1422]
I think that the PKCE grant should be generated in the migration generated by `rails g doorkeeper:migration`. 

By doing so, we'll encourage the use of the PKCE > implicit grant type.

Additionally, this means new applications only need to run a single migration to enable Doorkeeper, making it slightly easier to get started.

**Comment by nbulaj** [comment]
Hi @benaubin . This point is good, but I don't sure it makes sense. Many Doorkeeper users configure just `password` or `client_credentials` flows and they never need PKCE. And this two columns would be redundant.

On the other hand I don't think they make a lot of effort for the database. Moreover, even if you configured just `password` flow - you're still have access grant table. So two columns more or less - it doesn't matter.

So thinking about this once again - let's do it! Would you like to propose a PR? Don't remove an old one migration for now, let's keep it until next major release.
