### ISSUE TITLE
 form_post response_mode support?

### ISSUE THREAD

**Issue by pldavid2** [doorkeeper-gem/doorkeeper#1423]
I'm using openid through doorkeeper-openid_connect gem and seems form_post is not supported
https://github.com/doorkeeper-gem/doorkeeper-openid_connect/issues/92

Any chance this is added to doorkeeper so then the doorkeeper-openid_connect can use it too?

Thanks for this great gem :)

**Comment by nbulaj** [comment]
Hi @pldavid2 . It looks for me like it's a question to doorkeeper-openid_connect gem and not Doorkeeper (it has nothing about OpenID, and request is about openid stuff - https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html )

**Comment by pldavid2** [comment]
Hello @nbulaj. It's related to openid, but i think the problem is that doorkeeper doesn't support for the response_mode parameter available in the OAuth2 specification. Not sure if openid is the only one that use it or not.

**Comment by nbulaj** [comment]
I didn't find `response mode` / `response_mode` in the RFC6749 (https://tools.ietf.org/html/rfc6749) . It looks for me like it's not related to OAuth itself and something from OpenID world actually.

**Comment by pldavid2** [comment]
Hello @nbulaj. Well, it's mention on this OAuth 2 RFC8414 https://tools.ietf.org/html/rfc8414.
But i'm not an expert on this, I don't know if it's something specific to openid or not.

**Comment by nbulaj** [comment]
This is some brandly new (2018) extension to the base RFC that extends OpenID specification, yes. 

> This specification generalizes the metadata format defined by "OpenID Connect Discovery 1.0" [OpenID.Discovery] in a way that is compatible with OpenID Connect Discovery while being applicable to a wider set  of OAuth 2.0 use cases.

**Comment by nbulaj** [comment]
OK, this looks like something that requires a built-in support from Doorkeeper gem itself.

https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html

>  In this mode, Authorization Response parameters are encoded as HTML form values that are auto-submitted in the User Agent, and thus are transmitted via the HTTP POST method to the Client, with the result parameters being encoded in the body using the application/x-www-form-urlencoded format. The action attribute of the form MUST be the Client's Redirection URI. The method of the form attribute MUST be POST. Because the Authorization Response is intended to be used only once, the Authorization Server MUST instruct the User Agent (and any intermediaries) not to store or reuse the content of the response. 

> Any technique supported by the User Agent MAY be used to cause the submission of the form, and any form content necessary to support this MAY be included, such as submit controls and client-side scripting commands. However, the Client MUST be able to process the message without regard for the mechanism by which the form submission was initiated. 

If somebody wanna to propose a solution - you're welcome!
