### ISSUE TITLE
Callbacks no longer executed during token revocation

### ISSUE THREAD

**Issue by jsdalton** [doorkeeper-gem/doorkeeper#1424]
### Steps to reproduce

Revoke the token via controller, which eventually calls `#revoke` on an access token.

### Expected behavior

ActiveRecord callbacks should be executed.

### Actual behavior

ActiveRecord callbacks are not executed.

### System configuration

n/a

It looks like this PR (https://github.com/doorkeeper-gem/doorkeeper/pull/1384) introduced a change with how revocation is executed. See https://github.com/doorkeeper-gem/doorkeeper/pull/1384/files#diff-a4248d46038ea854feb27d7539b2032dR12

Formerly, doorkeeper used [#update_attribute](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attribute) to revoke the token. Now doorkeeper uses [#update_column](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_column). 

The major difference in behavior of the two methods:

* Callbacks are run for `#update_attribute` but skipped for `#update_column`
* updated_at/updated_on are updated for `#update_attribute` but skipped for `#update_column`

We had cache invalidation hooks tied to callbacks, so for us we discovered that this change caused cache invalidation to fail -- naturally not a desirable behavior for token revocation.

Of course, we can easily override this method in our local model to restore the previous behavior, but I wonder if this change was intended? I see nothing in the PR referenced above indicating the purpose of the change, nor any indication that the effect i described was in fact desired.

Feel free to close this issue if this new behavior is expected. It might be useful to be more explicit about the impact of such changes in the future (my apologies if i missed something in the changelog though.)

Cheers.

**Comment by nbulaj** [comment]
Hi @jsdalton . I didn't think about the fact that somebody could add a callbacks to oauth models.

This sounds reasonable to me. Do you want to perform a PR to return to `#update_attribute` behavior? I think the idea of the original change was some performance improvements by avoiding using callbacks, but for your case it seems like we need them

**Comment by jsdalton** [comment]
Thanks @nbulaj 👍 . I put together a quick PR: https://github.com/doorkeeper-gem/doorkeeper/pull/1426 . Hopefully this does the trick.

**Comment by nbulaj** [comment]
Fixed, thanks @jsdalton !
