### ISSUE TITLE
Removing /oauth/token/info route

### ISSUE THREAD

**Issue by kristianpd** [doorkeeper-gem/doorkeeper#1428]
Doorkeeper exposes a `GET /token/info` route that can be used to query the status of a token without any credentials. 

This concern was raised here https://github.com/doorkeeper-gem/doorkeeper/issues/1011 but the issue was resolved by simply pointing them to the newer `POST /token/introspect` endpoint which validates credentials before providing a response.

I feel like this doesn't quite solve the original concern of having the `/token/info` endpoint open to the wild. 

I am using doorkeeper as a way of authenticating my API with the `client_credentials` grant flow. While nothing is stopping a malicious entity from spamming one of my API endpoints with arbitrary `Authorization: Bearer` or `access_token` parameters, I do believe it's more likely that developers will be rate-limiting,  monitoring, and possibly blacklisting their controller endpoints with more scrutiny than routes provided by the doorkeeper gem.

I think this is a risk that people can accept/mitigate in other ways, so in my case I was mostly interested in just removing access to that endpoint, but I could not find a way to ignore this particular route (https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/rails/routes.rb#L44)?

I ended up not using the `use_doorkeeper` route helper and just rolled my own: 

```ruby
  scope :oauth do
    post :token, to: 'doorkeeper/tokens#create', as: :oauth_token
    post :revoke, to: 'doorkeeper/tokens#revoke', as: :oauth_revoke
    post :introspect, to: 'doorkeeper/tokens#introspect', as: :oauth_introspect
  end
```

Am I missing something obvious here? If not, I think it would be useful to expose a `skip_token_info` type option to `use_doorkeeper`.

**Comment by dcangulo** [comment]
@kristianpd 

I use the following:

```
use_doorkeeper do
    skip_controllers(
      :authorizations, :token_info, :applications, :authorized_applications
    )
  end
```

And it just produces the following routes:

```
# == Route Map
#
#           Prefix Verb   URI Pattern                 Controller#Action
#      oauth_token POST   /oauth/token(.:format)      doorkeeper/tokens#create
#     oauth_revoke POST   /oauth/revoke(.:format)     doorkeeper/tokens#revoke
# oauth_introspect POST   /oauth/introspect(.:format) doorkeeper/tokens#introspect
```

It doesn't include `/oauth/token/info`.

**Comment by kristianpd** [comment]
Thanks @dcangulo i didn't realize `skip_controllers` could also skip actions.
