### ISSUE TITLE
Skip scope authorization

### ISSUE THREAD

**Issue by Gambitboy** [doorkeeper-gem/doorkeeper#1431]
Hi,

Is there any way to skip the requirement for scope authorization even I login?

Currently whenever I login, afterwards I get a request to authorize public scope.
I'd like to skip that screen entirely and just assume the user has authorized.

I've found no resources or other issues where someone has asked this question and gotten a working response.

**Comment by linhdangduy** [comment]
You could use `skip_authorization` at Doorkeeper config as describing at here:
https://github.com/doorkeeper-gem/doorkeeper/blob/f387b101e8144f407969424393b975879dbd841f/lib/generators/doorkeeper/templates/initializer.rb#L426-L432

Just add attribute to client_app or resource_owner to allow them skip authorization.

**Comment by Gambitboy** [comment]
Awesome, I somehow missed that. Thanks.

My solution was: 

```
skip_authorization do
    true
end
```
inside the `config/initializers/doorkeeper.rb` file
from https://doorkeeper.gitbook.io/guides/configuration/skip-authorization
