### ISSUE TITLE
Using token_type_hint logic

### ISSUE THREAD

**Issue by benaubin** [doorkeeper-gem/doorkeeper#1433]
I noticed that Doorkeeper does not use the token_type_hint logic in the RFC:

https://github.com/doorkeeper-gem/doorkeeper/blob/f387b101e8144f407969424393b975879dbd841f/app/controllers/doorkeeper/tokens_controller.rb#L113:L120

However, I believe it would be possible to use `token_type_hint` to choose which lookup to perform first, which should provide a slight performance improvement.

I think this would be a pretty simple & straightforward change, and I'd be happy to implement it.

**Comment by nbulaj** [comment]
Hi @benaubin . If it will not break existing ORMs - I'm fully for it :+1:
