### ISSUE TITLE
Hooks around authentication

### ISSUE THREAD

**Issue by craftyphotons** [doorkeeper-gem/doorkeeper#1437]
It would be useful to be able hook into the [`Doorkeeper::OAuth::Token.authenticate`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/token.rb#L15-L23) method, similar to how hooks for authorization work in [`Doorkeeper::AuthorizationsController`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/authorizations_controller.rb#L99-L125).

If not in `Doorkeeper::OAuth::Token.authenticate`, maybe it would make sense to fire the hooks from [`Doorkeeper::Rails::Helpers#doorkeeper_authorize!`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/rails/helpers.rb#L6-L10) instead.

Perhaps there could be a `Doorkeeper.config.before_successful_authentication` hook that gets passed the `request`, and a `Doorkeeper.config.after_successful_authentication` hook that gets passed both the `request` and the `access_token`.

The main use case that comes to mind for this is to enable tracking usage of a token, similar to what Devise's [`trackable`](https://github.com/heartcombo/devise/wiki/How-To:-Add-:trackable-to-Users) module provides. This would enable things like the `Last used within the last nine months` type of presentation one often sees in an Authorized Applications view.

This is something I'd be interested in contributing if it's the right direction to go.

**Comment by szechyjs** [comment]
@tbhb Did you ever figure out a way to do this? I'd love to have Devise's trackable trigger when refresh tokens are used exchanged.
