### ISSUE TITLE
Upgrade from 5.1.0 to 5.4.0 memory usage doubles and high CPU

### ISSUE THREAD

**Issue by ahsandar** [doorkeeper-gem/doorkeeper#1441]
The memory usage doubles on upgrading from 5.1.0 to 5.4.0. is this a known consequence or  issue ?  upgrading to resolve this issue reported earlier https://github.com/doorkeeper-gem/doorkeeper/issues/1310
![Screenshot 2020-09-08 at 1 44 16 PM](https://user-images.githubusercontent.com/2472371/92437447-83397700-f1d9-11ea-8e60-7f907438156e.png)
 also has high erratic CPU usage
![Screenshot 2020-09-08 at 2 40 09 PM](https://user-images.githubusercontent.com/2472371/92441757-5d17d500-f1e1-11ea-839f-85d2fa3ddc57.png)

**Comment by nbulaj** [comment]
It's hard to say using this graph if it's actually doorkeeper or whatever issue. Also will be better to utilize which method produces such memory consumption.

You can also find more info here ( https://github.com/doorkeeper-gem/doorkeeper/issues/1310#issuecomment-630795240 ) and here ( https://github.com/doorkeeper-gem/doorkeeper/issues/1310#issuecomment-681748360 ). If it still hurts, we need to think on how to make database lookup more lightweight
