### ISSUE TITLE
Doorkeeper 5.1.2 is missing from rubygems.org

### ISSUE THREAD

**Issue by kymmt90** [doorkeeper-gem/doorkeeper#1446]
### Steps to reproduce

Installing [Doorkeeper 5.1.2](https://github.com/doorkeeper-gem/doorkeeper/releases/tag/v5.1.2) fails:

```
$ bundle update doorkeeper
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'doorkeeper (= 5.1.2)' in any of the gem sources listed in your Gemfile.
```

Doorkeepr 5.1.2 is missing from [rubygem.org](https://rubygems.org/gems/doorkeeper/versions).

<img width="200" alt="The list of doorkeeeper gems on rubygem.org" src="https://user-images.githubusercontent.com/9291031/95281127-6a33ec80-0891-11eb-8fff-c9a2272da698.png">

### Expected behavior

Installing Doorkeeper 5.1.2 succeeds.

### Actual behavior

Installing Doorkeeper 5.1.2 fails.

### System configuration

**Gemfile**:

```ruby
source 'https://rubygems.org'

gem 'doorkeeper', '5.1.2'
```

**Comment by nbulaj** [comment]
Thanks @kymmt90 . Published

**Comment by kymmt90** [comment]
Thanks!
