### ISSUE TITLE
Why are applications and authorized_applications routes skipped in api_only mode?

### ISSUE THREAD

**Issue by pjmartorell** [doorkeeper-gem/doorkeeper#1448]
### Steps to reproduce

1. Enable `api_only` in Doorkeeper initializer
2. Run `rails routes`
3. See that `applications` and `authorized_applications` routes are not generated

Just check https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/rails/routes.rb#L33. It skips `applications` and `authorized_applications` routes if `api_only` mode is set. The code that skips these routes was done in a moment  (https://github.com/doorkeeper-gem/doorkeeper/pull/992) where the corresponding controllers were not providing a JSON response, but now they are.

### Expected behavior
Since [this commit](https://github.com/doorkeeper-gem/doorkeeper/commit/4acc923dc77fa00928268136f54136d5a6a865dc) added JSON responses to both `AuthorizedApplicationsController` and `ApplicationsController` I would expect these routes not to be skipped anymore.

### Actual behavior
`applications` and `authorized_applications` routes are not generated when `api_mode` is enabled.

### System configuration
N/A

**Doorkeeper initializer**:

```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  # If you are planning to use Doorkeeper in Rails 5 API-only application, then you might
  # want to use API mode that will skip all the views management and change the way how
  # Doorkeeper responds to a requests.
  #
  api_only
end
```

**Ruby version**: N/A

**Gemfile.lock**: N/A

**Comment by nbulaj** [comment]
Hi @pjmartorell . Yep, seems like it was disabled because this controller haven't been supported JSON mode.

You're welcome with the PR to fix this issue :+1:
