### ISSUE TITLE
owner_id should be an int8 column

### ISSUE THREAD

**Issue by connorshea** [doorkeeper-gem/doorkeeper#1456]
In the `add_owner_to_application_migration.rb` migration template, the `owner_id` is just an `integer`: https://github.com/doorkeeper-gem/doorkeeper/blob/b8abbe6bb8646232b9d5065c27de9e1e78e974b9/lib/generators/doorkeeper/templates/add_owner_to_application_migration.rb.erb#L5

In Postgres (and presumably MySQL/sqlite), this creates an int4, which means it maxes out at around 2.1 billion records (`2,147,483,647` specifically).

Since Rails 5.1, the primary key on all tables has been a bigint (int8): https://www.mccartie.com/tech/2016/12/05/rails-5.1.html

While it's unlikely anyone will ever actually hit anything this large, I figure it's worth updating the generated migration to use int8 just in case.

**Comment by nbulaj** [comment]
Hi @connorshea . Good point, do you want to propose a PR?

**Comment by connorshea** [comment]
Sure, I can open one later today after work :) I'll set a reminder for myself.
