### ISSUE TITLE
Refresh tokens are not being revoked when new access token is created

### ISSUE THREAD

**Issue by verenion** [doorkeeper-gem/doorkeeper#1462]
### Steps to reproduce

1. Create a new access token using the Authorisation Code grant type.
2. Client saves refresh token and uses access token to access resources.
3. Token expiry is set to 10 seconds (for testing), so after expiry, client uses refresh token to acquire new access token
4. This generates a new access token with a new refresh token, but previous refresh/access token is still active, valid and never gets revoked.

### Expected behavior
When an access token is generated from a refresh token, the previous access token should be revoked, according to the OAuth spec.

### Actual behavior
Access tokens are never revoked, every refresh just causes a new access token to be created.

This is becoming a very large issue for us, we have fairly short-lived tokens on a very busy application. We are currently racking up 100m+ rows in `oauth_access_tokens`, and cleaning them out is pointless if it keeps creating more.

### System configuration

**Doorkeeper initializer**:

```ruby
Doorkeeper.configure do
  orm :active_record

  resource_owner_authenticator do
    if current_user
      current_user
    else
      # Refer the HERE document at the bottom on why this session variable
      # is being set.
      session[:user_return_to] = request.fullpath
      redirect_to(new_user_session_url)
    end
  end

  resource_owner_from_credentials do |_routes|
    User.authenticate(params[:email], params[:password])
  end

  access_token_expires_in 10.seconds

  access_token_generator '::Doorkeeper::JWT'

  use_refresh_token

  default_scopes  :public

  grant_flows %w(authorization_code)

  skip_authorization do |resource_owner, client|
    true
  end
end

Doorkeeper::JWT.configure do
  token_payload do |opts|

    exp = Time.now + 10.seconds
    user = User.find(opts[:resource_owner_id])
    iat         = Time.current.utc.to_i

    {
        iss: 'user-service',
        iat: iat,
        exp: exp.to_i,
        jti: SecureRandom.uuid,
        application_id: opts[:application].id,
        user: {
            id: user.member_id,
            username: user.name,
            email: user.email,
        }
    }
  end

  use_application_secret false

  secret_key "testsecret"

  secret_key_path File.join('/', 'app', 'secret.pem')

  encryption_method :rs256
end
```

**Comment by verenion** [comment]
Forgot to add, we have the `previous_refresh_token` in the database, and from what I've read, this should be working correctly already.

**Comment by linhdangduy** [comment]
> Forgot to add, we have the previous_refresh_token in the database, and from what I've read, this should be working correctly already.

I have also check the code again.

If you don't migrate the previous_refresh_token column. The refresh_token will be revoke immediately when you use it to get new access token.

The `previous_refresh_token` is added from [this pull](https://github.com/doorkeeper-gem/doorkeeper/pull/769). As it's description:
> Also allows for **refresh tokens to not be revoked until an access token created with that refresh token is successfully used once**

Memo for the code related to `previous_refresh_token`:
- If the `previous_refresh_token` column exists:
  - refresh_token will not be revoked
https://github.com/doorkeeper-gem/doorkeeper/blob/c54e73115738edb5eb819147516592253198beeb/lib/doorkeeper/oauth/refresh_token_request.rb#L37
  - then it is saved to new access token record as previous_refresh_token:
https://github.com/doorkeeper-gem/doorkeeper/blob/c54e73115738edb5eb819147516592253198beeb/lib/doorkeeper/oauth/refresh_token_request.rb#L61-L63

- On the first time the new access token is used, the `previous_refresh_token` will be revoked:
https://github.com/doorkeeper-gem/doorkeeper/blob/c54e73115738edb5eb819147516592253198beeb/lib/doorkeeper/oauth/token.rb#L19 

@verenion So I think we can close this issue.
