### ISSUE TITLE
Secret Encryption for versions earlier than 5.1

### ISSUE THREAD

**Issue by TimoMoss** [doorkeeper-gem/doorkeeper#1463]
Hello Doorkeeper team. 
Please help us to solve the following issue:
We have Doorkeeper 5.0.3 
ruby 2.5.7
rails 5.2.4
At the moment we don't have any possibility of an update Doorkeeper to versions that support secret encryption.
I tried to look for how we can properly patch the library so we can hash secrets but I haven't managed to find any. 
Could anybody please give a quick solution to patching?
Thank you in advance

**Comment by nbulaj** [comment]
Hi @TimoMoss . There is no known quick way to port this functionality to older versions. What is stopping you from the upgrade? Any issues we could help you?
