### ISSUE TITLE
ActiveRecord Multi-DB Support

### ISSUE THREAD

**Issue by chadwilken** [doorkeeper-gem/doorkeeper#1464]
### Steps to reproduce
What we need to do to see your problem or bug?
Create a Rails app that uses Rails multi-db support and then attempt to:
- Perform a GET request using a refresh token with the `previous_refresh_token` option enabled
  - This calls `revoke_previous_refresh_token!` and if you're on a `GET` request it uses the `reading` role by default and throws an error
- While performing an authorization grant there are times where a grant may be automatically created in the `new` action and thus it throws an error since it's a GET request.

I am currently overcoming this by `include`ing a custom `Overrides` class that patches the `revoke_previous_refresh_token!` method:
```ruby
module Doorkeeper
  module AccessTokenMixin
    module Overrides
      extend ActiveSupport::Concern

      def revoke_previous_refresh_token!
        ActiveRecord::Base.connected_to(role: :writing) do
          super
        end
      end
    end
  end
end

Doorkeeper::AccessToken.include(Doorkeeper::AccessTokenMixin::Overrides)
```

There are cases that I probably do not have covered and will have to patch eventually. It would be cool if there was a callback or something that allowed hooking into actions that write to the database similar to the before and after hooks for auth.

### Expected behavior
Tell us what should happen
The gem should either allow hooking into database actions OR in the AR classes check to see if they have a `writing_role` and if so call `connected_to` passing in that role.

### Actual behavior
Tell us what happens instead
It tries to write to a read-only connection which AR prevents.

### System configuration
You can help us to understand your problem if you will share some very
useful information about your project environment (don't forget to
remove any confidential data if it exists).

**Doorkeeper initializer**:

```ruby
# config/initializers/doorkeeper.rb
# frozen_string_literal: true

# NOTE: We `include` method overrides into Doorkeeper::AccessToken
# at the bottom of this file.

Doorkeeper.configure do
  orm :active_record

  # This block will be called to check whether the resource owner is authenticated or not.
  resource_owner_authenticator do
    current_user || warden.authenticate!(scope: :user)
  end

  resource_owner_from_credentials do
    user = User.find_for_authentication(username: params[:username])
    user ||= User.find_for_authentication(email_address: params[:username])

    if user && user.valid_for_authentication? { user.valid_password?(params[:password]) }
      user
    end
  end

  admin_authenticator do |routes|
    Admin.find_by(id: session[:admin_id]) || redirect_to(routes.new_session_path)
  end

  # Access token expiration time (default 2 hours).
  # If you want to disable expiration, set this to nil.
  #
  access_token_expires_in 24.hours

  base_controller 'ApplicationController'

  reuse_access_token

  use_refresh_token

  enforce_configured_scopes

  default_scopes  :read
  optional_scopes :write, :destroy

  force_ssl_in_redirect_uri { |uri| uri.host != 'localhost' }

  grant_flows %w[authorization_code password]
end

Doorkeeper::AccessToken.include(Doorkeeper::AccessTokenMixin::Overrides)
```

**Ruby version**: `2.5.7`

**Gemfile.lock**: 
- Doorkeeper 5.4.0
- Rails 6.0.3.2

**Comment by nbulaj** [comment]
Hi @chadwilken . Starting from 5.3 Doorkeeper allows to configure your custom classes for OAuth models. How about to define your own `AccessToken` class inherited from Doorkeeper one and override required behavior?

```ruby
class OAuthToken < Doorkeeper::AccessToken
  def revoke_previous_refresh_token!
    ActiveRecord::Base.connected_to(role: :writing) do
      super
    end
  end
end

# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  access_token_class "OAuthToken"
end
```

**Comment by GuillaumeGillet** [comment]
Same problem. I have a configuration with a read, and a write database as define [her](https://guides.rubyonrails.org/active_record_multiple_databases.html)
Do I need to overload every model?

**Comment by nbulaj** [comment]
Doorkeeper doesn't have any configuration for multi-db, it's your own how will you use models/database. So yes, you have to configure any model you need

**Comment by GuillaumeGillet** [comment]
Thanks @nbulaj, I have implemented the custom class as you suggested and it fix the problem. I am a bit concerned with some future error, do you know if there is any other methods that write in db and is called during a GET request?
