### ISSUE TITLE
Always Show Authorization

### ISSUE THREAD

**Issue by scottrobertson** [doorkeeper-gem/doorkeeper#1468]
Essentially the opposite of https://doorkeeper.gitbook.io/guides/configuration/skip-authorization

It would be nice to have an option to always show the authorization screen. This is particularly useful for services that users often have multiple logins for, as it gets confusing which account you are logging in with.

Is this something that would be relatively easy to support, and would others find it useful. May be able to find some time to PR it if they would.

**Comment by nbulaj** [comment]
Hi @scottrobertson . I think this could be useful

> May be able to find some time to PR it if they would.

You're welcome :bow: Thanks!

**Comment by rishabhsairawat** [comment]
@scottrobertson Can't this be achieved by using the same skip-authorization part:
### **Instead of this:**
```
skip_authorization do
  true
end
```
### **Do this:**
```
skip_authorization do
  false
end
```

**Comment by scottrobertson** [comment]
> @scottrobertson Can't this be achieved by using the same skip-authorization part:
> 
> ### **Instead of this:**
> ```
> skip_authorization do
>   true
> end
> ```
> 
> ### **Do this:**
> ```
> skip_authorization do
>   false
> end
> ```

Sadly not. The default is `false`. It's not designed to work in that way.

**Comment by jeffsawatzky** [comment]
You can try adding the doorkeeper-openid_connect gem, which adds support for "prompt" param
https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

Then you would pass `prompt=login` or `prompt=select_account`

**Comment by linhdangduy** [comment]
> You can try adding the doorkeeper-openid_connect gem, which adds support for "prompt" param
> https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
> 
> Then you would pass `prompt=login` or `prompt=select_account`

@nbulaj 
I agree with @jeffsawatzky.
The "Show Authorization" screen should be use just only for "Authorization", not for multiple accounts purpose.

The right use is `prompt` parameter. It is already implemented at doorkeeper_openid-connect (I'm also using it in production right now)
References:
- Config: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/6e500d9bb7d0f3cb3435f102f1afc08f2031017e/spec/dummy/config/initializers/doorkeeper_openid_connect.rb#L50-L52

- Where config is called: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/2dd6865d011ffacbb07a993e1317395fcb711d4f/lib/doorkeeper/openid_connect/helpers/controller.rb#L79-L80

**Comment by scottrobertson** [comment]
To be clear, this is not about offering "multi-account" support. These accounts are totally separate and are not connected in any way, other than the person knows the login details to both of them.

This is purely just about forcing them to see the authorization step on every login request. Adding the whole openid gem just for that feels heavy-handed, especially when we will not be using any of the features from OpenID.

**Comment by delphaber** [comment]
@scottrobertson have you find a way to do it? :)

**Comment by antonlitvinenko** [comment]
It seems that I was able to achieve this by generating my own controller which subclasses the `Doorkeeper::AuthorizationsController` and overrides the `matching_token?` method to always return `nil`.

**Comment by vanboom** [comment]
:+1: suggest reopening this as it was closed as stale.  I am also trying to figure out how to have this behavior, i.e. to force a prompt for authorization even if the user is signed in to the serving application.  This would help to increase security in scenarios where the computer is shared and another user may already have a session open (e.g. forgot to log out).

**Comment by vanboom** [comment]
This work around works in config/initializers/doorkeeper.rb with Devise...

1. The resource_owner_authenticator block is called twice, but the user is authenticated prior to the second call, so we can detect the initial attempt by looking at the `current_sign_in_at` timestamp.  
2. If the current user sign in timestamp is stale, sign out the user, effectively forcing the sign in screen. 
3. If we have a new timestamp, the user has just been signed in by Doorkeeper. 

```ruby
  resource_owner_authenticator do
    if current_user.present? and current_user.current_sign_in_at.present?
      if current_user.current_sign_in_at < (Time.now - 5.seconds)
        sign_out :user
      end
    end
    current_user || warden.authenticate!(scope: :user)
  end
```

This is a bit of hacking imho, it would be more proper to force the sign in screen for the initial authorization attempt.  We would appreciate the maintainers advice and consideration on reopening this issue for potential development.  Thanks!
