### ISSUE TITLE
authorisation request with scope ignores scope

### ISSUE THREAD

**Issue by jason9364** [doorkeeper-gem/doorkeeper#1470]
### Steps to reproduce
Add a 'scopes' parameter to the authorisation request
http://localhost:3000/oauth/authorize?client_id=ca417906d8411cf6c4969d5a72ad0ea9c988896e97f7ed12f5b92ad0d9305984&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Fauth%2Ftodo%2Fcallback&response_type=code&**scopes=admin**

### Expected behavior
The authorisation screen should display 'admin' as the scope being granted and the resultant activegrant record should contain scopes = 'admin'

### Actual behavior
The scopes parameter is ignored.  The specification (I think) specifies a parameter of 'scope' rather than 'scopes'.  Most of the code assumes 'scope' but ApplicationController/application_params specifies 'scopes'.  PreAuthorization/initialisation however is looking for ':scope' which will always be blank and so :scopes gets ignored.  I changed ApplicationController/application_params to accept :scope rather than :scopes and everything works as expected

### System configuration
You can help us to understand your problem if you will share some very
useful information about your project environment (don't forget to
remove any confidential data if it exists).

**Doorkeeper initializer**:

```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  enforce_configured_scopes
  default_scopes  :public
  optional_scopes :admin, :resident
end
```

**Ruby version**: ``

**Gemfile.lock**:

<details>
  <summary>Gemfile.lock content</summary>
  
```
Place your Gemfile.lock content here
```
</details>

**Comment by yolk** [comment]
Use singular `scope` not `scopes` as parameter and it should work. See https://tools.ietf.org/html/rfc6749#section-3.3

**Comment by nbulaj** [comment]
As stated in the RFC (section 4.1.1.  Authorization Request ) you must include parameter named `scope` and not `scopes`.

https://tools.ietf.org/html/rfc6749#section-4.1.1
