### ISSUE TITLE
[Feature Request] Allow Refresh Tokens for some apps only

### ISSUE THREAD

**Issue by jeffsawatzky** [doorkeeper-gem/doorkeeper#1479]
I would like to enable refresh tokens for only some applications, and not across the board. Is this possible?

**Comment by nbulaj** [comment]
Hi @jeffreyc . Actually it's only possible with patching gem internals, there is no such ability inside the gem config itself.

**Comment by PhilipSkinner** [comment]
This should be enforced through the offline_access scope being available on an application.

**Comment by jeffsawatzky** [comment]
I now see that this feature already exists:
https://github.com/doorkeeper-gem/doorkeeper/pull/1103/files#diff-fdd559c8fa2cd93526914d72d4e1902aaaac12de5b4d0ace9e09c9191014b52fR69
