### ISSUE TITLE
I18n path for missing scopes

### ISSUE THREAD

**Issue by mbajur** [doorkeeper-gem/doorkeeper#1493]
### Steps to reproduce

Define a default scope (`:public`) and try to request a resource that needs that scope.

### Expected behavior
API should return an error like `{"full_error_messages":"missing scope public"}`

### Actual behavior
API returns `{"full_error_messages":"translation missing: en.doorkeeper.scopes.public"}`. It's not an issue on it's own but one thing bothers me - the i18n error path - it kinda suggests it holds a general scope description which (according to, for example, this page: https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes#translating-scopes) would be "Access your public data".

Given all that, if i define the scope translation as suggested on the documentation page, running the above request would result in a following error: `{"full_error_messages":"Access your public data"}` which doesn't make much sense. I think errors like this should have their own i18n path

**Comment by nbulaj** [comment]
Hi @mbajur . I don't sure I undertstood the issue. Have you placed a translation for your scope and it didn't find it? Or what exact is the issue?

**Comment by mbajur** [comment]
Hey @nbulaj - the issue in here is that the same i18n path is used both for scope name translation and missing scope error translation. So you can't separately translate the name and the missing error message. They both use `<lang>.doorkeeper.scopes.<scope>` path.

**Comment by mbajur** [comment]
Oh, i just realized it's not fault of Doorkeeper itself but the gem that wraps it (Winebouncer in my case). I will open the same issue in there. Sorry for confusion.
