### ISSUE TITLE
Random token is revoked when `previous_refresh_token` column present

### ISSUE THREAD

**Issue by arekk** [doorkeeper-gem/doorkeeper#1497]
### Steps to reproduce

Issue any token with `password` grant_type to get a token with `refresh_token` - in database `previous_refresh_token` is NULL for issued token.

Next try to make request with token.

`OAuth::Token.authenticate` is performing `access_token.revoke_previous_refresh_token!`, and there `old_refresh_token&.revoke` is performed where `old_refresh_token` is detected by value in `previous_refresh_token`, Value is NULL, so first (or random) token without refresh token is revoked.

### Expected behavior
Probably `previous_refresh_token` should be populated somehow. If there is no possibility to populate (first access token ever) and `previous_refresh_token` is NULL, no revoking action should be taken.

### Actual behavior
Random token is revoked

### System configuration
gem 'doorkeeper', '~> 5.5' (5.5.0)
Latest migration applied (including new `previous_refresh_token`) column

Config:
```
api_only
use_refresh_token
access_token_class 'OauthAccessToken'
application_class 'OauthApplication'
```

**Comment by nbulaj** [comment]
Hi @arekk , please check https://github.com/doorkeeper-gem/doorkeeper/pull/1496 - looks like it should fix the issue too

**Comment by arekk** [comment]
> Hi @arekk , please check #1496 - looks like it should fix the issue too

Indeed, looks like a solution for reported issue. Closing issue, thanks.
