### ISSUE TITLE
invalid_grant when client redirect_uri contains a query parameters

### ISSUE THREAD

**Issue by DMoN-dt** [doorkeeper-gem/doorkeeper#1507]
https://github.com/doorkeeper-gem/doorkeeper/blob/2418589bb3074a6bbcde4369dd18d0de93afcffc/lib/doorkeeper/oauth/authorization_code_request.rb#L78

https://github.com/doorkeeper-gem/doorkeeper/blob/2418589bb3074a6bbcde4369dd18d0de93afcffc/lib/doorkeeper/oauth/helpers/uri_checker.rb#L48

https://github.com/doorkeeper-gem/doorkeeper/blob/88aea0f7080eb6699cf80f9de57938b44eb28235/lib/doorkeeper/oauth/helpers/uri_checker.rb#L78

(`client_query.split("&").sort == query.split("&").sort`)

Callback `query` contains at least a **code** & **state**, but `client_query` unable to contain them.

**Comment by pacoguzman** [comment]
You can start on this issue to know more about this - https://github.com/omniauth/omniauth-oauth2/issues/28

So after reading those I think our error is not related with doorkeeper
