### ISSUE TITLE
Add columns to Doorkeeper models?

### ISSUE THREAD

**Issue by ghost** [doorkeeper-gem/doorkeeper#153]
Hello, I recently started exploring Doorkeeper. How do I build on the Doorkeeper models i.e. 

1) Add say a logo and description columns to Applications
2) I want each application to define some more configuration e.g. 1 application has many process_maps. I want to add has_many :process_maps to Application model. 

Is all this possible?

**Comment by gabrielgarza** [comment]
For anyone still lost on this, this is how I got a logo column working on the OAuthApplication model:

1. Add a column to oauth_applications table, for example `rails g migration AddImageUrlToOauthApplications image_url:string` and run `rake db:migrate`

2. Generate the doorkeeper views so you can customize them, run in terminal `rails generate doorkeeper:views` this will copy the default Doorkeeper templates into your views folder so you can change them (see: https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-views)

3. Go to your `doorkeeper/authorizations/new.html.erb` template

4. Now you can access your column with `<%= @pre_auth.client.application.image_url %>`

5. Add the image tag `<img class="client-logo" src="<%= @pre_auth.client.application.image_url %>" alt="" />`

Of course you have to add an image url to the record in the database, I just added it directly to the DB column using Postico, I think if you want to include this new field in the new/edit templates of the application you'd have to add it as a permitted parameter, see: https://github.com/doorkeeper-gem/doorkeeper/issues/391

**Comment by NaixSpirit** [comment]
my solution

```ruby
# config/initializers/doorkeeper_extend.rb
doorkeeper_extend_dir = File.join(Rails.root, "app", "models", "doorkeeper")
Dir.glob("#{doorkeeper_extend_dir}/*.rb").each { |f| require(f) }

# app/models/doorkeeper/application.rb
module Doorkeeper
  class Application < ActiveRecord::Base
    has_many :roles
  end
end
```
