### ISSUE TITLE
Doorkeeper support for CIBA Flow

### ISSUE THREAD

**Issue by carlosgorges** [doorkeeper-gem/doorkeeper#1538]
Due to a requirement of the project I am working on, a way to request authorization for an action from a third person involved in the flow, we understand that the best way is to follow the CIBA open standard (https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0-03.html) on top of the doorkeeper, which we already use as oauth2/open id provider.

We are starting development with the guidelines defined at https://github.com/autoseg/doorkeeper-ciba.

Any help will be welcome.

**Comment by carlosgorges** [comment]
Hi guys, the module is almost at version 1.0, let's put it below https://github.com/doorkeeper-gem/ ?

**Comment by nbulaj** [comment]
Hi @carlosgorges . Thanks for such a great work! :+1: 
We can add a link to this extension to the guides and into (Extensions)[https://github.com/doorkeeper-gem/doorkeeper#extensions] section of the readme, WDYT?

**Comment by carlosgorges** [comment]
@nbulaj , as I'm the only dev working on this code at this time, NP just link in doc. Thank you ;-)
