### ISSUE TITLE
Why does `previous_refresh_token` column require `default: ""`?

### ISSUE THREAD

**Issue by senny** [doorkeeper-gem/doorkeeper#1544]
I am looking to enable `refresh_token_revoked_on_use?` for a deployment that has many millions of access tokens. The generated migration adds a `NOT NULL` column with a default value:

```ruby
    add_column(
      :oauth_access_tokens,
      :previous_refresh_token,
      :string,
      default: "",
      null: false
    )
```

We won't be able to deploy this change with zero downtime. The migration will run for a long time with an exclusive lock on the access tokens table. Is there a reason that all past access token rows need to be rewritten with this default and can not stay `NULL`? Is a value of `""` required for or would `NULL` work as well?

Scanning the code, I only found: `previous_refresh_token.blank?` in `access_token_mixin.rb`, which would work on both (`nil` and `""`).

Is there another way to enable this feature without requiring application downtime to migrate the database?

**Comment by nbulaj** [comment]
Hi @senny . It was long time before me started to work on this project so maybe it's something legacy. I think you can safely remove the constraint, I hove we have blank protection eveywhere we use previous refresh token or at least convert the value to string to avoid nil errors

**Comment by senny** [comment]
From my investigations it looked safe. I did remove it from the migration on my end to prevent production issues (we have been running this for a while and have not observed any problems). 

Might be worth to remove it from the generated migration as well, just in case to prevent anyone from running a large-scale blocking migration in production by accident.
