### ISSUE TITLE
Sorry a question - The oauth application is necessary to use 3rd auth like google-oauth and etec?

### ISSUE THREAD

**Issue by dcalixto** [doorkeeper-gem/doorkeeper#1547]
As nobody on stackoverflow answered the question unfortunately this is the only place left to please: The oauth application is necessary to use 3rd auth like google-oauth and etec?

**Comment by nbulaj** [comment]
Hi @dcalixto . I don't sure I understood you question correctly.

Doorkeeper is a gem which provides you an ability _to be an OAuth provider_ (just like Google and other).
You don't need google or anything else to deploy your own oauth provider and your Oauth clients (applications) don't need google or some other service.
