### ISSUE TITLE
request and response in lower camel 

### ISSUE THREAD

**Issue by danieldocki** [doorkeeper-gem/doorkeeper#1553]
is there a way to receive a request and response in lower camel? 

Request
```
 {
  "grantType": "client_credentials",
  "clientId": "",
  "clientSecret": ""
}
```

Response
```
{
    "accessToken": "",
    "tokenType": "Bearer",
    "expiresIn": 86400,
    "scope": "od.all",
    "createdAt": 1643834020
}
```

**Comment by nbulaj** [comment]
OAuth2 has [strong specs](https://datatracker.ietf.org/doc/html/rfc6749) around request & response format so nope, there is no ability to change it.

What you can do is only to patch Doorkeeper internals, but it's for your own :no_good_man:
