### ISSUE TITLE
Propshaft support

### ISSUE THREAD

**Issue by miharekar** [doorkeeper-gem/doorkeeper#1555]
Now that [Rails is switching away from sprockets](https://world.hey.com/dhh/introducing-propshaft-ee60f4f6) to [propshaft](https://github.com/rails/propshaft) I think it would make sense to add support for it or maybe move away from sprockets and instead inline css.

Alternatively you could expand guides to explain what to do. For me it was as simple as generating doorkeeper views, and adding bootstrap to both admin and application layout like so:

```diff
- <%= stylesheet_link_tag "doorkeeper/admin/application" %>
+ <%= stylesheet_link_tag "doorkeeper/bootstrap.min", "doorkeeper/admin/application" %>
```

What are your thoughts on this?

**Comment by nbulaj** [comment]
I'm totally fine with with it. Just don't have any experience with it so any PRs are welcome
