### ISSUE TITLE
Able to obtain a token with default scopes even if they are not present in the application scopes using client credentials request

### ISSUE THREAD

**Issue by enrico** [doorkeeper-gem/doorkeeper#1557]
When grant type is "client credentials" and application scopes are present:

If the the scope parameter is NOT present in the `/oauth/token` request then this api is returning a token with default scopes (for exp. 'public' scope) even if 'public' scope is not present in the application scopes.

This is similar to issue #1002

**Comment by nbulaj** [comment]
I think we can close this #1558 being merged
