### ISSUE TITLE
Request to add skip_client_authentication_for_password_grant to the doorkeeper initializer

### ISSUE THREAD

**Issue by esnrRahman** [doorkeeper-gem/doorkeeper#1565]
I recently installed doorkeeper and while I was trying to configure for the "Resource Owner Password Credentials flow" (ROPC) and I noticed after looking into the source code that I have to set the option `skip_client_authentication_for_password_grant` to true.

I had to do some digging to figure this out and I noticed while there is some documentation in the migrations table to handle the ROPC flow, there is nothing that is set in the initializer to indicate the setting of this option. 

So can this be added please and it can be commented out by default? I don't mind creating a PR once I get an approval from the core team

Thank you beforehand for all your work on this amazing gem!

**Comment by mateuscelio** [comment]
[Seems](https://github.com/doorkeeper-gem/doorkeeper/wiki/Migration-from-old-versions#api-changes) that this option is for migration purpose only. The recommended subsituition for [public clients](https://datatracker.ietf.org/doc/html/rfc6749#section-2.1) is creating an application setting `confidential` column value to `false` and send only `client_id`?

**Comment by esnrRahman** [comment]
As I need to set this option in the initializer, I believe this is not for migration purpose but its for setup. So my suggestion was putting something in the generated doorkeeper.rb in the initializer where you have something along the lines as follows -

```
Doorkeeper.configure do
  ...
  ...
  # Not a recommended approach. Set this to true if you want to setup the password flow without a client
  # skip_client_authentication_for_password_grant :true
end
```

**Comment by nbulaj** [comment]
@mateuscelio is right. This option was added just for the developers who used Password grant flow for years without any client authentication. But OAuth RFC and security considerations against of such solution. 

The only thing which stops me from removing this configuration option is that **a lot** of clients are using such flow and don't want to create any Doorkeeper Application instances. So... I have to think about it a little bit more
