### ISSUE TITLE
`base_controller` config option has no effect

### ISSUE THREAD

**Issue by mroach** [doorkeeper-gem/doorkeeper#1569]
### Steps to reproduce

In the initialiser, set `base_controller` to any value. Fire up a Rails console:

```
Doorkeeper::ApplicationMetalController.superclass
=> ActionController::API
```

### Expected behavior

Setting `base_controller` should set the base controller for the Doorkeeper controllers as advertised in the documentation.

### Actual behavior

The setting is ignored and the Rails' API controller is used.

I grep'd the code and `base_controller` only appears in 3 files: template initializer, config.rb, and config_spec.rb. Not anywhere in the actual code itself.

### System configuration
You can help us to understand your problem if you will share some very
useful information about your project environment (don't forget to
remove any confidential data if it exists).

**Doorkeeper initializer**:

```ruby

Doorkeeper.configure do
  orm :active_record
  api_only

  resource_owner_authenticator do
    current_user || warden.authenticate!(scope: :user, store: false)
  end

  base_controller "OAuthBaseController"

  use_refresh_token

  grant_flows ["authorization_code", "client_credentials", "password", "mfa"]
end

Rails.application.reloader.to_prepare do
  Doorkeeper::TokensController.rescue_from(Security::AuthenticationError) do |err|
    render(json: { reason: err.user_reason }.merge(err.user_data), status: :unauthorized)
  end

  Doorkeeper::GrantFlow.register(
    :mfa,
    grant_type_matches: "mfa",
    grant_type_strategy: Security::MfaGrantStrategy
  )
end
```

**Ruby version**: `3.1.1`

**Gemfile.lock**: `5.5.4`

**Comment by nbulaj** [comment]
It's here @mroach - https://github.com/doorkeeper-gem/doorkeeper/blob/main/app/controllers/doorkeeper/application_controller.rb#L5

But could be the issue in `constantize` - https://github.com/doorkeeper-gem/doorkeeper/blob/main/app/controllers/doorkeeper/application_controller.rb#L5

**Comment by moiristo** [comment]
`Doorkeeper::ApplicationMetalController` is dependent on the `base_metal_controller` setting, not `base_controller`.

https://github.com/doorkeeper-gem/doorkeeper/blob/main/app/controllers/doorkeeper/application_metal_controller.rb#L5
