### ISSUE TITLE
`Doorkeeper::Application.matching_token_for` returns hashed token values

### ISSUE THREAD

**Issue by dblessing** [doorkeeper-gem/doorkeeper#1585]
### Steps to reproduce
What we need to do to see your problem or bug?

Enable `hash_token_secrets` and disable `reuse_access_token`. 

Once hashing is enabled, make sure a new token is saved in the database in hashed format. Now, use `Doorkeeper::AccessToken.matching_token_for(application, user, scopes)` with the relevant application, user and scopes and note that the hashed value is returned. 

### Expected behavior

When `hash_token_secrets` (or even just when `reuse_access_token` is disabled??) `Doorkeeper::AccessToken.matching_tokens_for` should not return a value. 

Of note, [`Doorkeeper::Application.find_or_create_for`](https://github.com/doorkeeper-gem/doorkeeper/blob/bfc132f58455052db7b0c7f936fb72ffd033130d/lib/doorkeeper/models/access_token_mixin.rb#L183) already handles this and it will not call `matching_token_for` if `reuse_access_token` is not enabled. 

### Actual behavior

`Doorkeeper::AccessToken.matching_token_for` happily returns a hashed token value.

**Comment by nbulaj** [comment]
hey @dblessing 

If I remember correctly `matching_tokens_for` should return access token instance, not the token value. So should have correct value at the end. Fix me please if I;m wrong
