### ISSUE TITLE
Expired tokens require new authorization on different devices

### ISSUE THREAD

**Issue by j-seixas** [doorkeeper-gem/doorkeeper#1595]
### Steps to reproduce
- Have an authorized application with expired token
- Try to access application
  - If on the same device / browser / session it opens the application
  - If on different device / or private/ anonymous window it requests a new authorization

### Expected behavior
On 5.5.4 it wasn't needed the new authorization, but on 5.6.0 it does. 
Found this #1542 which is where the behaviour started to happen. Why is a new authorization required if the token is expired for a different device/ session?

### System configuration

**Doorkeeper initializer**:
```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  orm :active_record
  resource_owner_authenticator do
    ...
  end
  use_polymorphic_resource_owner
  use_refresh_token
  optional_scopes :scope1, :scope2 ...
  # no default scopes
end
```

**Ruby version**: `3.1.0`
**Doorkeeper version**: `5.6.0`

**Comment by nbulaj** [comment]
Hi @j-seixas . Doorkeeper doesn't have 5.4.4 version. Maybe you meant 5.5.4 ? 

https://github.com/doorkeeper-gem/doorkeeper/compare/v5.5.4...v5.6.0

**Comment by j-seixas** [comment]
> Hi @j-seixas . Doorkeeper doesn't have 5.4.4 version. Maybe you meant 5.5.4 ?
> 
> [v5.5.4...v5.6.0](https://github.com/doorkeeper-gem/doorkeeper/compare/v5.5.4...v5.6.0)

Yep, you're correct, I meant 5.5.4 (edited it) - it was probably a typo on my part

**Comment by j-seixas** [comment]
@nbulaj I tested around and updated the issue. I believe the problem comes from #1542 , which was where it started appearing this behaviour.

Why is a new authorization required if the token is expired in a different device/ session?

**Comment by j-seixas** [comment]
Closing as it has bad information. Debugged and created a clean one #1616
