### ISSUE TITLE
Inconsistent parameter naming between client_credentials and password grant flows

### ISSUE THREAD

**Issue by aaronmallen** [doorkeeper-gem/doorkeeper#1596]
The [documentation](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Resource-Owner-Password-Credentials-flow#testing) for the `client_credentials` flow calls for json parameters:

```json
{
  "grant_type": "client_credentials",
  "client_id":  "the_client_id",
  "client_secret": "the_client_secret"
}
```

However the [documentation](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Resource-Owner-Password-Credentials-flow#testing) for the `password` flows calls for json parameters:

```json
{
  "clientid"      : "the_client_id",
  "secret"        : "the_client_secret",
  "grant_type"    : "password",
  "username"      : "user@example.com",
  "password"      : "sekret"
}
```

it would be nice to see some consistency in the keys for each grant flow.

**Comment by nbulaj** [comment]
Project wiki community driven, so any fixes are very welcome :smiley: 
Fixed now, thanks :bow:

**Comment by nbulaj** [comment]
Can we close this issue now?
