### ISSUE TITLE
5.6.1 broken with custom application_class defined in devise.rb

### ISSUE THREAD

**Issue by sealabcore** [doorkeeper-gem/doorkeeper#1603]
### Steps to reproduce
What we need to do to see your problem or bug?

1. Use custom application_class
2. Mix in functionality to custom application class

Detailed here:
https://github.com/doorkeeper-gem/doorkeeper/pull/1599/files#r1034131675

### Expected behavior
The app should not error with

```ruby
NoMethodError: undefined method `application' for #<MyCustomApplicationClass:0x0000000111c48e40>
```

### Actual behavior
The app is crashing with the above error because the gem explicitly checking for the class `Doorkeeper::Application`

```ruby
application = client.is_a?(Doorkeeper::Application) ? client : client.application if client
```

We have a custom class, so this is eval'ing to false and application is not defined on `client` thus raising.

### System configuration
You can help us to understand your problem if you will share some very
useful information about your project environment (don't forget to
remove any confidential data if it exists).

**Doorkeeper initializer**:

https://github.com/doorkeeper-gem/doorkeeper/pull/1599/files#r1034131675

**Ruby version**: `2.7.4`

**Gemfile.lock**:

<details>
  <summary>Gemfile.lock content</summary>
  
GEM
  remote: https://rubygems.org/
  remote: https://enterprise.contribsys.com/
  remote: https://gems.graphql.pro/
  specs:
    MailchimpMarketing (3.0.80)
      excon (>= 0.76.0, < 1)
      json (~> 2.1, >= 2.1.0)
    MailchimpTransactional (1.0.50)
      excon (>= 0.76.0, < 1)
      json (~> 2.1, >= 2.1.0)
    actioncable (6.1.7)
      actionpack (= 6.1.7)
      activesupport (= 6.1.7)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.7)
      actionpack (= 6.1.7)
      activejob (= 6.1.7)
      activerecord (= 6.1.7)
      activestorage (= 6.1.7)
      activesupport (= 6.1.7)
      mail (>= 2.7.1)
    actionmailer (6.1.7)
      actionpack (= 6.1.7)
      actionview (= 6.1.7)
      activejob (= 6.1.7)
      activesupport (= 6.1.7)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.7)
      actionview (= 6.1.7)
      activesupport (= 6.1.7)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.7)
      actionpack (= 6.1.7)
      activerecord (= 6.1.7)
      activestorage (= 6.1.7)
      activesupport (= 6.1.7)
      nokogiri (>= 1.8.5)
    actionview (6.1.7)
      activesupport (= 6.1.7)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.7)
      activesupport (= 6.1.7)
      globalid (>= 0.3.6)
    activemodel (6.1.7)
      activesupport (= 6.1.7)
    activerecord (6.1.7)
      activemodel (= 6.1.7)
      activesupport (= 6.1.7)
    activerecord-session_store (2.0.0)
      actionpack (>= 5.2.4.1)
      activerecord (>= 5.2.4.1)
      multi_json (~> 1.11, >= 1.11.2)
      rack (>= 2.0.8, < 3)
      railties (>= 5.2.4.1)
    activestorage (6.1.7)
      actionpack (= 6.1.7)
      activejob (= 6.1.7)
      activerecord (= 6.1.7)
      activesupport (= 6.1.7)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.7)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    algolia (2.3.0)
      faraday (>= 0.15, < 3)
      faraday-net_http_persistent (>= 0.15, < 3)
      multi_json (~> 1.0)
      net-http-persistent
    algoliasearch-rails (2.2.1)
      algolia (< 3.0.0)
      json (>= 1.5.1)
    ast (2.4.2)
    aws-eventstream (1.2.0)
    aws-partitions (1.656.0)
    aws-sdk-core (3.166.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.5)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.59.0)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.117.1)
      aws-sdk-core (~> 3, >= 3.165.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sigv4 (1.5.2)
      aws-eventstream (~> 1, >= 1.0.2)
    backport (1.2.0)
    barnes (0.0.9)
      multi_json (~> 1)
      statsd-ruby (~> 1.1)
    bcrypt (3.1.18)
    benchmark (0.2.0)
    bindex (0.8.1)
    bootsnap (1.15.0)
      msgpack (~> 1.2)
    browser (5.3.1)
    bugsnag (6.24.2)
      concurrent-ruby (~> 1.0)
    builder (3.2.4)
    byebug (11.1.3)
    capybara (3.38.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.10)
    connection_pool (2.3.0)
    crack (0.4.5)
      rexml
    crass (1.0.6)
    crawler_detect (1.2.1)
      qonfig (~> 0.24)
    declarative (0.0.20)
    devise (4.8.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-async (1.0.0)
      activejob (>= 5.0)
      devise (>= 4.0)
    diff-lcs (1.5.0)
    doorkeeper (5.6.1)
      railties (>= 5)
    e2mmap (0.1.0)
    einhorn (1.0.0)
    erubi (1.11.0)
    ethon (0.15.0)
      ffi (>= 1.15.0)
    excon (0.93.1)
    expo-push (1.0.3)
      typhoeus (~> 1.4)
    factory_bot (6.2.0)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    faker (3.0.0)
      i18n (>= 1.8.11, < 2)
    faraday (2.3.0)
      faraday-net_http (~> 2.0)
      ruby2_keywords (>= 0.0.4)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (2.1.0)
    faraday-net_http_persistent (2.0.1)
      faraday-net_http
      net-http-persistent (~> 4.0)
    ffi (1.15.5)
    globalid (1.0.0)
      activesupport (>= 5.0)
    google-apis-calendar_v3 (0.24.0)
      google-apis-core (>= 0.9.1, < 2.a)
    google-apis-core (0.9.1)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.16.2, < 2.a)
      httpclient (>= 2.8.1, < 3.a)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.a)
      rexml
      webrick
    googleauth (1.3.0)
      faraday (>= 0.17.3, < 3.a)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (>= 0.16, < 2.a)
    graphiql-rails (1.8.0)
      railties
      sprockets-rails
    graphql (2.0.15)
    graphql-pro (1.23.2)
      graphql (>= 1.7.5)
    hashdiff (1.0.1)
    hashie (5.0.0)
    httpclient (2.8.3)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    imgix (4.0.3)
    jaro_winkler (1.5.4)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jmespath (1.6.1)
    json (2.6.2)
    jwt (2.5.0)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.19.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    memoist (0.16.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    mini_portile2 (2.8.0)
    minitest (5.16.3)
    mocha (2.0.2)
      ruby2_keywords (>= 0.0.5)
    msgpack (1.6.0)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.2.3)
    net-http-persistent (4.0.1)
      connection_pool (~> 2.2)
    newrelic_rpm (8.13.1)
    nio4r (2.5.8)
    nokogiri (1.13.9)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    oauth2 (2.0.9)
      faraday (>= 0.17.3, < 3.0)
      jwt (>= 1.0, < 3.0)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 4)
      snaky_hash (~> 2.0)
      version_gem (~> 1.1)
    omniauth (2.1.0)
      hashie (>= 3.4.6)
      rack (>= 2.2.3)
      rack-protection
    omniauth-google-oauth2 (1.1.1)
      jwt (>= 2.0)
      oauth2 (~> 2.0.6)
      omniauth (~> 2.0)
      omniauth-oauth2 (~> 1.8.0)
    omniauth-oauth2 (1.8.0)
      oauth2 (>= 1.4, < 3)
      omniauth (~> 2.0)
    omniauth-rails_csrf_protection (1.0.1)
      actionpack (>= 4.2)
      omniauth (~> 2.0)
    orm_adapter (0.5.0)
    os (1.1.4)
    parallel (1.22.1)
    parser (3.1.3.0)
      ast (~> 2.4.1)
    pg (1.4.5)
    phonelib (0.7.5)
    public_suffix (5.0.0)
    puma (6.0.0)
      nio4r (~> 2.0)
    pusher (2.0.3)
      httpclient (~> 2.8)
      multi_json (~> 1.15)
      pusher-signature (~> 0.1.8)
    pusher-signature (0.1.8)
    qonfig (0.28.0)
    racc (1.6.0)
    rack (2.2.4)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-protection (2.2.2)
      rack
    rack-proxy (0.7.2)
      rack
    rack-test (2.0.2)
      rack (>= 1.3)
    rack-timeout (0.6.3)
    rails (6.1.7)
      actioncable (= 6.1.7)
      actionmailbox (= 6.1.7)
      actionmailer (= 6.1.7)
      actionpack (= 6.1.7)
      actiontext (= 6.1.7)
      actionview (= 6.1.7)
      activejob (= 6.1.7)
      activemodel (= 6.1.7)
      activerecord (= 6.1.7)
      activestorage (= 6.1.7)
      activesupport (= 6.1.7)
      bundler (>= 1.15.0)
      railties (= 6.1.7)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.3)
      loofah (~> 2.3)
    railties (6.1.7)
      actionpack (= 6.1.7)
      activesupport (= 6.1.7)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
    rainbow (3.1.1)
    rake (13.0.6)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    redis (4.8.0)
    regexp_parser (2.6.1)
    representable (3.2.0)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    retriable (3.1.2)
    retryable (3.0.5)
    reverse_markdown (2.1.1)
      nokogiri
    rexml (3.2.5)
    rrule (0.5.0)
      activesupport (>= 2.3)
    rubocop (1.39.0)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.1.2.1)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.23.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.23.0)
      parser (>= 3.1.1.0)
    rubocop-performance (1.15.1)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rails (2.17.3)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.33.0, < 2.0)
    ruby-progressbar (1.11.0)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (4.6.1)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    semantic_range (3.0.0)
    shoulda (4.0.0)
      shoulda-context (~> 2.0)
      shoulda-matchers (~> 4.0)
    shoulda-context (2.0.0)
    shoulda-matchers (4.5.1)
      activesupport (>= 4.2.0)
    sidekiq (6.5.8)
      connection_pool (>= 2.2.5, < 3)
      rack (~> 2.0)
      redis (>= 4.5.0, < 5)
    sidekiq-ent (2.5.3)
      einhorn (>= 0.7.4)
      sidekiq (>= 6.5.0, < 7)
      sidekiq-pro (>= 5.5.0, < 6)
    sidekiq-pro (5.5.5)
      sidekiq (~> 6.0, >= 6.5.6)
    signet (0.17.0)
      addressable (~> 2.8)
      faraday (>= 0.17.5, < 3.a)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    snaky_hash (2.0.0)
      hashie
      version_gem (~> 1.1)
    snitcher (0.4.2)
    solargraph (0.47.2)
      backport (~> 1.2)
      benchmark
      bundler (>= 1.17.2)
      diff-lcs (~> 1.4)
      e2mmap
      jaro_winkler (~> 1.5)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.1)
      parser (~> 3.0)
      reverse_markdown (>= 1.0.5, < 3)
      rubocop (>= 0.52)
      thor (~> 1.0)
      tilt (~> 2.0)
      yard (~> 0.9, >= 0.9.24)
    sorbet-runtime (0.5.10148)
    spring (4.1.0)
    spring-watcher-listen (2.1.0)
      listen (>= 2.7, < 4.0)
      spring (>= 4)
    sprockets (4.1.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    statsd-ruby (1.5.0)
    stream-chat-ruby (3.0.0)
      faraday
      faraday-multipart
      faraday-net_http_persistent
      jwt
      net-http-persistent
      sorbet-runtime
    thor (1.2.1)
    tilt (2.0.11)
    trailblazer-option (0.1.2)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    twilio-ruby (5.73.3)
      faraday (>= 0.9, < 3.0)
      jwt (>= 1.5, <= 2.5)
      nokogiri (>= 1.6, < 2.0)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2022.6)
      tzinfo (>= 1.0.0)
    uber (0.1.0)
    unicode-display_width (2.3.0)
    vcr (6.1.0)
    version_gem (1.1.1)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.2.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    webmock (3.18.1)
      addressable (>= 2.8.0)
      crack (>= 0.3.2)
      hashdiff (>= 0.4.0, < 2.0.0)
    webpacker (5.4.3)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    webrick (1.7.0)
    websocket (1.2.9)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    will_paginate (3.3.1)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    yard (0.9.28)
      webrick (~> 1.7.0)
    zeitwerk (2.6.6)

PLATFORMS
  ruby

DEPENDENCIES
  MailchimpMarketing
  MailchimpTransactional
  activerecord-session_store
  algoliasearch-rails
  aws-sdk-s3
  barnes
  bcrypt (~> 3.1.16)
  bootsnap (>= 1.4.2)
  browser
  bugsnag
  byebug
  capybara (>= 2.15)
  crawler_detect
  devise
  devise-async
  doorkeeper
  expo-push
  factory_bot_rails
  faker
  faraday (= 2.3.0)
  google-apis-calendar_v3
  graphiql-rails
  graphql
  graphql-pro!
  hashie
  imgix
  jbuilder (~> 2.11)
  listen (~> 3.7)
  mocha
  newrelic_rpm
  nokogiri
  omniauth-google-oauth2
  omniauth-rails_csrf_protection
  pg (>= 0.18, < 2.0)
  phonelib
  puma
  pusher
  rack-cors
  rack-timeout
  rails (= 6.1.7)
  redis
  retryable
  rrule
  rubocop
  rubocop-performance
  rubocop-rails
  sass-rails (>= 6)
  selenium-webdriver
  shoulda
  sidekiq (< 7)
  sidekiq-ent (< 7)!
  sidekiq-pro (< 7)!
  snitcher
  solargraph
  spring
  spring-watcher-listen (~> 2.1.0)
  stream-chat-ruby
  turbolinks (~> 5)
  twilio-ruby
  tzinfo-data (>= 1.2016.7)
  vcr
  web-console (>= 3.3.0)
  webdrivers
  webmock
  webpacker (~> 5.4.3)
  will_paginate

RUBY VERSION
   ruby 2.7.4p191

BUNDLED WITH
   2.1.4

</details>

**Comment by nbulaj** [comment]
Oh, I still live in times when Doorkeeper didn't allow to customize these classes :see_no_evil: 
Thanks for reporting, will fix and release

**Comment by nbulaj** [comment]
Whoops, GitHub closes the ticket
@sealabcore could you please check with a fresh release? It has a fix to check the custom model
