### ISSUE TITLE
`rails generate doorkeeper:install` fails with `Doorkeeper::MissingConfiguration` error

### ISSUE THREAD

**Issue by leemeichin** [doorkeeper-gem/doorkeeper#1617]
### Steps to reproduce

1. Add doorkeeper to a Rails app
2. Run `rails generate doorkeeper:install` as suggested by docs

### Expected behavior

It creates the doorkeeper initializer, updates routes, adds i18n, etc.

### Actual behavior

```
bundle exec rails generate doorkeeper:install

[..]/doorkeeper-5.6.2/lib/doorkeeper/config.rb:33:in `configuration': Configuration for doorkeeper missing. Do you have doorkeeper initializer? (Doorkeeper::MissingConfiguration)
```

No files are generated.

### System configuration

**Rails version**: 7.0.4

**Ruby version**: `3.2.0`

**Gemfile.lock**:

<details>
  <summary>Gemfile.lock content</summary>
  
```
...
    doorkeeper (5.6.2)
      railties (>= 5)
...
```
</details>

**Comment by leemeichin** [comment]
never mind, looks like I've duplicated https://github.com/doorkeeper-gem/doorkeeper/issues/1577#issue-1284626166 :)

**Comment by nbulaj** [comment]
Hey @leemeichin 

could you please try with 

```ruby
# Gemfile

gem "doorkeeper", github: "doorkeeper-gem/doorkeeper", branch: "fixes/lazy-load-associations"
```

and report any issues you found? (and backtrace please if present, I have to see which Doorkeeper lined caused an error)
