### ISSUE TITLE
Authentication status pending in Salesforce

### ISSUE THREAD

**Issue by spennerCC** [doorkeeper-gem/doorkeeper#1645]
### Steps to reproduce
What we need to do to see your problem or bug?

The more detailed the issue, the more likely that we will fix it ASAP.

Doorkeeper will not authorize the connection between Salesforce and another software and is stuck as "pending." The error that is shown says "Problem Logging In" we can't log you in because of an authentication error.

Don't use GitHub issues for questions like "How can I do that?" —
use [StackOverflow](https://stackoverflow.com/questions/tagged/doorkeeper)
instead with the corresponding tag.

### Expected behavior
Tell us what should happen

Edit and save the named credentials, directs you to an authorization screen where you hit "authorize" button and the connection is made.

### Actual behavior
Tell us what happens instead

Problem Logging In, we can't log you i because of an authentication error.

### System configuration
You can help us to understand your problem if you will share some very
useful information about your project environment (don't forget to
remove any confidential data if it exists).

**Doorkeeper initializer**:

```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  # ...
end
```

**Ruby version**: ``

**Gemfile.lock**:

<details>
  <summary>Gemfile.lock content</summary>
  
```
Place your Gemfile.lock content here
```
</details>

**Comment by nbulaj** [comment]
Hi @spennerCC .

Sorry but I'm not quite sure I understood the issue. How this gem is related to Salesforce? How we can debug the logs?

**Comment by nbulaj** [comment]
Any more details @spennerCC ? I have to close this issue as I have no idea what exactly is the problem and how it relates to Doorkeeper

**Comment by nbulaj** [comment]
I think we can close this one as no further details were added. Issue couldn't be escalated properly

**Comment by ransombriggs** [comment]
If it helps, I followed [these instructions](https://help.salesforce.com/s/articleView?id=sf.sso_provider_plugin_custom.htm) and was able to get my idp set up successfully in salesforce.
