### ISSUE TITLE
Documentation: empty pages

### ISSUE THREAD

**Issue by mtancoigne** [doorkeeper-gem/doorkeeper#1650]
Hello !

I'm integrating Doorkeeper in an existing application with _polymorphic owners_ and PKCE grant flow.

There are a few pages with no content on the documentation and I wanted to know what was expected in term of content, to see if I can help to fill the gaps:

- https://doorkeeper.gitbook.io/guides/concepts/application
- https://doorkeeper.gitbook.io/guides/concepts/resource-owner
- https://doorkeeper.gitbook.io/guides/concepts/access-grant
- https://doorkeeper.gitbook.io/guides/concepts/access-token

**Comment by nbulaj** [comment]
Hey @mtancoigne . You can contribute here https://github.com/doorkeeper-gem/guides/ for the Guides or check Wiki section for the gem itself, but it could be outdated. Thanks

**Comment by nbulaj** [comment]
Removed blank pages. If anyone is interested in porting current repo Wiki into guides - will be very thankful :bow:
