### ISSUE TITLE
NoMethodError: undefined method `name_for_response' since v5.6.8

### ISSUE THREAD

**Issue by nov** [doorkeeper-gem/doorkeeper#1681]
this line start causing an error 

https://github.com/doorkeeper-gem/doorkeeper/blob/c48fd2d989e761ab3ebe21698fcfa70261df7f57/lib/doorkeeper/oauth/error_response.rb#L13

```ruby
NoMethodError: undefined method `name_for_response' for :invalid_request:Symbol
```

**Comment by nbulaj** [comment]
Thanks for reporting! @camero2734 I think we have one more issue here :disappointed:

**Comment by camero2734** [comment]
Hmmm, I don't immediately see where this happens, could you provide an example request that causes this error?

**Comment by nov** [comment]
ah, I had an custom error handling code like below.

```ruby
module Doorkeeper::OAuth::PkceRequirement
  extend ActiveSupport::Concern

  included do
    validate :pkce_requirement, error: :invalid_request
  end

  :
```
