### ISSUE TITLE
How do I know if an application has been authorized by a resource owner?

### ISSUE THREAD

**Issue by danieldocki** [doorkeeper-gem/doorkeeper#1684]
I'm listing applications for a specific resource_owner, is there any method to find out if the application was authorized by the resource_owner?

I thought this https://github.com/doorkeeper-gem/doorkeeper/blob/c48fd2d989e761ab3ebe21698fcfa70261df7f57/lib/doorkeeper/orm/active_record/mixins/application.rb#L88 method could return this, but it always returns true

**Comment by piyush5050** [comment]
@danieldocki If you just want to list applications, you can try customising the view for the `/oauth/authorized_applications` page. It is created by default and lists the authorized applications for an authenticated resource_owner.
