### ISSUE TITLE
`Doorkeeper::AccessToken.find_or_create_for` with empty scopes raises NoMethodError

### ISSUE THREAD

**Issue by pdany1116** [doorkeeper-gem/doorkeeper#1699]
### Steps to reproduce
`Doorkeeper::AccessToken.find_or_create_for` raises NoMethodError when searching with empty scopes.

```ruby
application = Doorkeeper::Application.create(name: "test_application") # => Doorkeeper::Application
Doorkeeper::AccessToken.create_for(application: application, resource_owner: 42, scopes: 'public') # => Doorkeeper::AccessToken
Doorkeeper::AccessToken.find_or_create_for(application: application, resource_owner: 42, scopes: '') # => NoMethodError
```

### Expected behavior
A new Doorkeeper::AccessToken should be created with empty scopes.

### Actual behavior
```
NoMethodError: undefined method `sort' for "":String
from /usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper/models/access_token_mixin.rb:155:in `scopes_match?'
```

### System configuration

Ruby version 3.0.6
Doorkeeper version 5.6.6

**Comment by nbulaj** [comment]
Hey @pdany1116 . Try to use `Doorkeeper::OAuth::Scopes.new("")` instead.

Also even plain one works without issues for me:

![image](https://github.com/doorkeeper-gem/doorkeeper/assets/1443426/ce075ae2-edd4-47f1-946c-af6070645f92)

**Comment by pdany1116** [comment]
Indeed, I have the `reuse_access_token` config option enabled.

**Comment by nbulaj** [comment]
Can we close this issue? Or do you think it makes sense to add some extra protection into `#find_or_create_for` method?

```ruby
def find_or_create_for(application:, resource_owner:, scopes:, **token_attributes)
  scopes = Doorkeeper::OAuth::Scopes.from_string(scopes) if scopes.is_a?(String)
  # ...
end
```

**Comment by pdany1116** [comment]
I think it makes sense to add extra protection, I was not expecting this to be the problem, maybe other devs will encounter the same issue and be confused.

I would like to contribute if possible 😄

**Comment by nbulaj** [comment]
Yeah sure, will be great @pdany1116 , thanks a lot! Please refer CONTRIBUTING guide when open a PR :pray:
