### ISSUE TITLE
Token revocation error when token contains null byte. 

### ISSUE THREAD

**Issue by rczern** [doorkeeper-gem/doorkeeper#1700]
An error is thrown when token passed to revoke method contains null byte. The the vulnerability was found during a scan with [ZAP - API Scan](https://www.zaproxy.org/docs/docker/api-scan/) .

### Steps to reproduce

Send a token containing null byte to /oauth/revoke

```
curl -X POST https://example.com/oauth/revoke \
     -H "Content-Type: application/json" \
     -d '{"token": "\u0000"}'

```

### Expected behavior
Successful response similar to sending empty token.

```
curl -X POST https://example.com/oauth/revoke \
     -H "Content-Type: application/json" \
     -d '{"token": ""}'

```

### Actual behavior
An error is thrown.

ArgumentError (string contains null byte)

### System configuration

**Doorkeeper initializer**:

```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  orm :active_record
end
```

**Ruby version**: `3.2.2`

**Gemfile.lock**:

<details>
 doorkeeper (5.6.9)
</details>

**Comment by nbulaj** [comment]
Hey @rczern . It actually looks like a Rails/Rack bug processing the request params: https://discuss.rubyonrails.org/t/argumenterror-string-contains-null-byte/84271/3  or https://joshfrankel.me/blog/don-t-let-the-null-bytes-bite/

**Comment by rczern** [comment]
Thanks for the reply. I’m closing the issue.
