### ISSUE TITLE
Dependabot ruby experience 

### ISSUE THREAD

**Issue by Myahr208** [doorkeeper-gem/doorkeeper#1740]
### Steps to reproduce
What we need to do to see your problem or bug?

The more detailed the issue, the more likely that we will fix it ASAP.

Don't use GitHub issues for questions like "How can I do that?" —
use [StackOverflow](https://stackoverflow.com/questions/tagged/doorkeeper)
instead with the corresponding tag.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
You can help us to understand your problem if you will share some very
useful information about your project environment (don't forget to
remove any confidential data if it exists).

**Doorkeeper initializer**:

```ruby
# config/initializers/doorkeeper.rb
Doorkeeper.configure do
  # ...
end
```

<Ruby/version>``

<Gemfile/unlock>

<details>
  <summary>Gemfile.lock content</summary>
  
```
Place your Gemfile.lock content here
```
</details>

**Comment by nbulaj** [comment]
Hey @Myahr208 . Not sure what does issue means? :thinking:

**Comment by nbulaj** [comment]
OK I'll close this one as there is no clear description of the problem
