### ISSUE TITLE
Refresh tokens that are paired with expired access tokens cannot be revoked

### ISSUE THREAD

**Issue by ransombriggs** [doorkeeper-gem/doorkeeper#1743]
### Steps to reproduce

> What we need to do to see your problem or bug?

The token revocation endpoint accepts either access or refresh tokens, but will not revoke refresh tokens if the access token it is paired with has expired.  This is not the right behavior because the refresh tokens have no expiration and we should be able to revoke them at anytime.

I am pushing up a PR soon with specs for the behavior I would expect as well as an initial awkward fix.

### Expected behavior

> Tell us what should happen

I should be able to revoke a refresh token after the `expired?` method returns true.

### Actual behavior

> Tell us what happens instead

It silently fails to revoke.

**Comment by nbulaj** [comment]
And this one can be closed as well? https://github.com/doorkeeper-gem/doorkeeper/pull/1744

**Comment by ransombriggs** [comment]
yup, closing
