### ISSUE TITLE
The error message for invalid pkce method is not affected by pkce_code_challenge_methods configuration

### ISSUE THREAD

**Issue by ransombriggs** [doorkeeper-gem/doorkeeper#1746]
### Steps to reproduce

I am upgrading to get the functionality in https://github.com/doorkeeper-gem/doorkeeper/pull/1735 because we do not accept the `plain` method but noticed that the error message still says that plain is an acceptable method.
 
> What we need to do to see your problem or bug?

```
  Doorkeeper.configure
    pkce_code_challenge_methods ["S256"]
  end
```

```
        # from a request spec that we have for our hack that I am trying to remove
        get oauth_authorization_path,
            params: {
              client_id: application.uid,
              redirect_uri: application.redirect_uri,
              response_type: "code",
              scope: scope,
              code_challenge: code_challenge,
              code_challenge_method: "plain",
            },
            headers: {
              "cookie" => session_cookie,
            }
```

### Expected behavior

 The code challenge method must be S256.

### Actual behavior

 The code challenge method must be plain or S256.

**Comment by nbulaj** [comment]
I believe we can close this one via https://github.com/doorkeeper-gem/doorkeeper/pull/1747 , right?

**Comment by ransombriggs** [comment]
yup, closing
