### ISSUE TITLE
Separate resource server from the authentication server

### ISSUE THREAD

**Issue by apellizzn** [doorkeeper-gem/doorkeeper#266]
When i make a request to the resource server like url/resource?access_token=XXX with the access token provided by the authentication server the doorkeeper_for :all in resources_controller search for the access token inside resource server app's oauth table: oauth_access_tokens but i want it to search in the authentication server app's db. How to solve this?

**Comment by cickes** [comment]
@apellizzn Can you help with a few more details?  Did you connect to the Auth Database or the Auth Server?  My understanding is you connected to the Auth Database directly from the Resource Server.  
  
If you connected directly to the Auth server, can you provide your `database.yml` or `mongoid.yml` example?  Trying to connect to the Auth Server and only allow the Auth Server to access the Auth database.  Thanks.
