### ISSUE TITLE
Getting the "invalid client" error when using the oauth2 gem

### ISSUE THREAD

**Issue by ekampp** [doorkeeper-gem/doorkeeper#282]
Hi there. 

I have this cURL command, which works fine, to retrieve a valid token from the doorkeeper engine.

``` bash
curl -i http://movis.dev/oauth/token \
-F grant_type=client_credentials \
-F client_id=92645627ec318278c2d7f94271e858f5c02d313226a0764ffbf7ade196e86b84 \
-F client_secret=d21c63732ee2a2ea7bada0192a2387d571dc713de587f3094b2b890067b9bafc \
-F username=emil \ 
-F password=hej
```

I'm trying to replicate this in my rails client, using the [oauth2 gem](https://github.com/intridea/oauth2) with this following script:

``` ruby
client_id = params[:client][:id]
client_secret = params[:client][:secret]
client = OAuth2::Client.new(client_id, client_secret,
  site: "http://movis.dev")

username = params[:user][:username]
password = params[:user][:password]
user = User.where(username: username).first
raise "Invalid password" unless Authentication.new(user, password).valid?

access_token = client.password.get_token(username, password)
```

The last of those lines, where I retrieve the access token with `client.password.get_token` raises this error:

``` bash
#<OAuth2::Error: invalid_client: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
{
  "error":"invalid_client",
  "error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."
}
```

So somehow, Doorkeeper has decided that the client is invalid. How do i rectify this? 

I have also [raises this issue with the oauth2 project](https://github.com/intridea/oauth2/issues/150)

**Comment by volund** [comment]
If anyone ends up here looking for answers, I got this same error when `hash_application_secrets` was enabled and I was creating a Doorkeeper::Application in `seed.rb` for testing, then (without thinking too much) passing the _hashed_ secret in the curl request. When the secret is compared against the value in the database it is of course hashed again, making it not match, causing client validation to fail.
