### ISSUE TITLE
Adding logo to doorkeeper applications

### ISSUE THREAD

**Issue by apellizzn** [doorkeeper-gem/doorkeeper#304]
Hi, i want to know the best way to add a logo to doorkeeper applications, uploading it in /oauth/applications/new.
I have to copy the entire model in my project and adding the logo field or there is another way to do this without copying the model?

**Comment by gabrielgarza** [comment]
For anyone still lost on this, this is how I got a logo column working on the OAuthApplication model:

1. Add a column to oauth_applications table, for example `rails g migration AddImageUrlToOauthApplications image_url:string` and run `rake db:migrate`

2. Generate the doorkeeper views so you can customize them, run in terminal `rails generate doorkeeper:views` this will copy the default Doorkeeper templates into your views folder so you can change them (see: https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-views)

3. Go to your `doorkeeper/authorizations/new.html.erb` template

4. Now you can access your column with `<%= @pre_auth.client.application.image_url %>`

5. Add the image tag `<img class="client-logo" src="<%= @pre_auth.client.application.image_url %>" alt="" />`

Of course you have to add an image url to the record in the database, I just added it directly to the DB column using Postico, I think if you want to include this new field in the new/edit templates of the application you'd have to add it as a permitted parameter, see: https://github.com/doorkeeper-gem/doorkeeper/issues/391
