### ISSUE TITLE
Cleartext Storage of refresh tokens

### ISSUE THREAD

**Issue by mbulat** [doorkeeper-gem/doorkeeper#320]
It seems to me that clear text storage of refresh tokens (and other credentials in general) isn't the greatest idea. Refresh tokens specifically seem to provide any attacker who compromises the database with long lived credentials, which would be akin to leaving the resource owners password in cleartext.

In other words, if I have resource owner passwords hashed with something like bcrypt, and then implement refresh_tokens, i've basically negated much of the security of bcrypting the resource owners passwords. 

RFC 6819, "OAuth 2.0 Threat Model and Security Considerations" does specify in section 5.1.4.1.3 that there should be no cleartext storage of credentials.

http://tools.ietf.org/html/rfc6819#section-5.1.4.1.3

Thoughts?

**Comment by tute** [comment]
Related: https://neosmart.net/blog/2015/using-hmac-signatures-to-avoid-database-writes

**Comment by donpinkster** [comment]
Are there any updates on this? I see access tokens as passwords, and in that case it is just wrong to store them in cleartext.

**Comment by tute** [comment]
> Are there any updates on this? I see access tokens as passwords, and in that case it is just wrong to store them in cleartext.

Agreed. This conversation is related: https://github.com/doorkeeper-gem/doorkeeper/issues/675

Encrypt them is an alternative, what I'm really interested in doing is not storing them altogether.

I won't have time for a few weeks to work on this though.

**Comment by nbulaj** [comment]
Now we have optional hashing for token & client credentials and secrets :fire:  #1168

It will be released with the next version of Doorkeeper
