### ISSUE TITLE
Cannot use models with UUIDs as their id field

### ISSUE THREAD

**Issue by evoL** [doorkeeper-gem/doorkeeper#330]
Rails 4 adds the possibility to use UUIDs as the `id` field for Postgres users. Unfortunately, Doorkeeper expects the `resource_owner`'s `id` to be an integer, which breaks when trying to use a UUID-based model as the resource owner.

For my purposes I have simply replaced the type of `resource_owner_id` in `oauth_access_tokens` and `oauth_access_grants` with `uuid` through a migration. Obviously it's not a universal solution, but it works for me.

**Comment by tute** [comment]
This will be an application config soon in Rails, so we can observe for that to decide what migration to generate: https://github.com/rails/rails/pull/21762

Thanks for [the tip](https://twitter.com/lleger/status/660523298682343424), @lleger!

**Comment by lleger** [comment]
Sounds like a good plan to me 👍🏻 I imagine they will be targeting this for a 5.0 release.

**Comment by tute** [comment]
For people who find this issue, here is a doc to enable it: https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-PostgreSQL-UUIDs-as-primary-keys-with-Doorkeeper

Kudos to @lleger for it.
