### ISSUE TITLE
Interfacing with Doorkeeper from other gems is tricky

### ISSUE THREAD

**Issue by Dantemss** [doorkeeper-gem/doorkeeper#371]
When developing rails engines (gems) that interface with doorkeeper, you can't always rely on autoload and might need to `require 'doorkeeper'`. However, if app/validators/redirect_uri_validator is not autoloaded, trying to load Doorkeeper::Application will throw an `ArgumentError: Unknown validator: 'RedirectUriValidator'` because it is not required and assumed to autoload before the lib/doorkeeper/models/active_record/application.rb is actually used.

A require_relative could correct this situation (but really, why would a lib depend on something under app?)

Not a huge issue in the end, as I only encountered it while testing my gem with the dummy app and putting doorkeeper in the gem's actual Gemfile (as opposed to the gemspec) solves this case.

**Comment by dusterio** [comment]
@Dantemss what was your solution in the end? your link is not valid anymore - I suppose you removed the repo :)

**Comment by Dantemss** [comment]
@dusterio basically Doorkeeper models can only be used after the application runs its Doorkeeper initializer and picks the ORM. So if you need to run some initialization code or similar that uses Doorkeeper, the best place to put it is probably in an after_initialize block:

```
Rails.application.configure do
  config.after_initialize do
    # Code that uses doorkeeper models here
  end
end
```

For gems, you would use the gem `Engine` instead of `Rails.application`.
