### ISSUE TITLE
Adding more fields to application model

### ISSUE THREAD

**Issue by apellizzn** [doorkeeper-gem/doorkeeper#391]
I want to add more fields to the Doorkeeper::Application model by using a concern like this: 

``` ruby
module MoreFields
  extend ActiveSupport::Concern

  included do
    field  :first
  end
end
```

and update it by adding  <%= f.text_field :first  %>  in the edit/new view, but i noticed this

``` ruby
def create
 @application = Application.new(application_params)
  ...
end
def application_params
    if params.respond_to?(:permit)
      params.require(:application).permit(:name, :redirect_uri)
    else
      params[:application].slice(:name, :redirect_uri) rescue nil
    end
end
```

in your applications_controller.rb, this means that you (by default) dont allow  the update or creation of other fields in the application model? It is right to override this method if i want to do that?
INFO :
Rails version: 3.2.13
Doorkeepr version: 1.1.0

**Comment by j-miyake** [comment]
https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-routes#changing-controllers
Following a wiki page, I added a custom controller that overrides `application_params` and modified the routing so that `/applications` directs to the custom controller.
