### ISSUE TITLE
Disable refresh token rotation? Longer lived refresh tokens?

### ISSUE THREAD

**Issue by dagumak** [doorkeeper-gem/doorkeeper#449]
I've been looking into a solution for dealing with lost refresh tokens. In iOS, this seems to be an issue when the user locks his phone disallowing the an app from writing to the new refresh token to the keychain. Another scenario would be when the the network is unavailable. Either way, losing the refresh token mandates the user to re-login to acquire a new AT and RT. It seems Box.com and Google have extended RTs, and they re-use this to obtain a new AT. I looked around the wiki and issues, but I couldn't find what I needed. I want to disable issuing a new refresh token on every refresh.

**Comment by grk** [comment]
@moneytree-doug any plans to make a pull request from your work on this? I checked your repo and it looks pretty solid.

**Comment by moneytree-doug** [comment]
@grk @tute, @rsharrott just made a PR #575.
