### ISSUE TITLE
Sinatra Provider

### ISSUE THREAD

**Issue by cj** [doorkeeper-gem/doorkeeper#45]
How hard would this be to implement do you think?  Maybe a [Padrino](http://www.padrinorb.com/) Provider would be easier, It's built on top of sinatra but lays things out similar to rails and also has quick support for activereocrd etc.... 

Maybe we could work on one together, as I know a lot of people would find this useful when building a lightweight api.

**Comment by pjmartorell** [comment]
@felipeelias any update on how to integrate Doorkeeper with Sinatra + ActiveRecord? I'm trying it but I have to do a lot of hacks and requiring a lot of individual files. Any hint?
