### ISSUE TITLE
Shouldn't doorkeeper return the token_type it expects?

### ISSUE THREAD

**Issue by andreasklinger** [doorkeeper-gem/doorkeeper#453]
This might be a minor thing but i got a client who ran into this.
#### Issue

Currently `/token` sends `{ access_token: 'xxxx', token_type: 'bearer' }` 
Notice the small 'b'  [[link]](https://github.com/doorkeeper-gem/doorkeeper/blob/685a5f3ed52c87c8bc951297dbe2d664b3d63ec8/lib/doorkeeper/models/access_token.rb#L70)

But the `from_bearer_authorization` method expects "Bearer" 
Case-sensitive check for capital "B" [[link]](https://github.com/doorkeeper-gem/doorkeeper/blob/685a5f3ed52c87c8bc951297dbe2d664b3d63ec8/lib/doorkeeper/oauth/token.rb#L13)
#### Suggestion

The `token_type` i receive together with my `access_token` should be the `token_type` i provide (and not close to it). So token_type should provide `Bearer`

I know that most client libs don't depend on that token_type because oauth is kinda implict about being either basic or bearer. But still would be good to be consistent here.

If it's faster i can provide a PR for this (i guess it might take some time to get the doorkeeper dev env set up)

PS: this is a followup to this discussion: https://twitter.com/tutec/status/497373956626972673
PPS: 0 open issues. I am highly impressed.

**Comment by MarvinNazari** [comment]
this is still a issue, it should be fixed somehow

**Comment by tute** [comment]
> Following the specification seems more important that having to update clients when doing a major upgrade of a library.

Theoretically, yes. :) That said, version 3 is coming soon, I would accept a PR changing this then, with a note in the `NEWS.md` file (but I don't think there's enough interest enough to change it myself).
