### ISSUE TITLE
path helper

### ISSUE THREAD

**Issue by aymericbouzy** [doorkeeper-gem/doorkeeper#466]
oauth_authorized_application_path(application) fails systematically for me, with : 

No route matches {:action=>"destroy", :controller=>"doorkeeper/authorized_applications", :format=>nil, :id=>nil, :locale=>#<Doorkeeper::Application _id: 53e8f2696c0e32545e000001, created_at: 2014-08-11 16:42:17 UTC, updated_at: 2014-08-11 16:42:17 UTC, name: "Foobar", uid: "d938832444fe519704ec9c6536d8cc40017443f2db66a0bcc1c250bfaf6a4552", secret: "1b1772c69fcd5c55fcb75efbe531992891fdddcd88fe4e158880087d2197671e", redirect_uri: "urn:ietf:wg:oauth:2.0:oob">} missing required keys: [:id]

Am I doing something wrong ?

**Comment by joerixaop** [comment]
Do you remember what the problem was?

**Comment by aymericbouzy** [comment]
Not at all ! I don't even work on this anymore sorry ...

**Comment by joerixaop** [comment]
Ah well, I figured out my problem (it wasn't quite the same): for some reason `url_for [:oauth, application]` used to work with doorkeeper 1.4, but not with doorkeeper 2.x, replacing it with an explicit url works of course, but I didn't notice the views were the error occurred didn't come from this gem but from my application, so I was wondering why noone else had this problem
