### ISSUE TITLE
Add hooks for /oauth/token /oauth/revoke

### ISSUE THREAD

**Issue by tilo** [doorkeeper-gem/doorkeeper#472]
it would be good to have some hooks in /oauth/token /oauth/revoke 
to enable logging, or other actions which need to be triggered upon creating or revoking a token

**Comment by tilo** [comment]
re-opening ...

**Comment by tute** [comment]
What hooks would you exactly add?

**Comment by tilo** [comment]
before and after hooks for /oauth/token /oauth/revoke and refresh_token

**Comment by tute** [comment]
Would it be a template method pattern? I'm not opposed to a PR on this.

**Comment by tilo** [comment]
I'm not familiar enough with the internals

**Comment by jpaas** [comment]
+1

use case: If you're building an admin app with a requirement for an audit log, you need to be able to insert a record into the audit log when a user signs in/out.

**Comment by northoutvarun** [comment]
+1 need this feature
