### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by chrise86** [doorkeeper-gem/doorkeeper#473]
Not sure if I've over looked it in the docs, but how are you supposed to handle user registration via an API with Doorkeeper?

Using `doorkeeper_for` expects the access_token, which won't exist at that point. So I assume there is some method of registering the user, then looking up the correct application via the app id and secret, and generating the token based on the supplied scope?

**Comment by himangshubitcanny** [comment]
Thank You

**Comment by huttneab** [comment]
@chrise86 how did you generate the clientID and secret in the first place?

**Comment by dagumak** [comment]
@tute I've re-read this and still have a few questions to clarify. Are you suggesting that there is one Rails app for using with OmniAuth for Twitter, Facebook, Google authentication who talks to our provider? How does this work if we were to have a frontend app?
