### ISSUE TITLE
Rails 4.2 beta 2 undefined method `persisted?' for #<Array:>

### ISSUE THREAD

**Issue by wannabefro** [doorkeeper-gem/doorkeeper#494]
When creating a new application the redirect to the show page fails because record is an array as opposed to an object when persisted? is called. 
The record looks like this

```
[[:oauth, #<Doorkeeper::Application id: 1, name: "test", uid: "908447d16ce1d9b9cbd66d9314d7b4c1cdfb2798a7c0eb8a27...", secret: "987cc169f8697a35b94384e8cf501e8c47223d0acb2358e155...", redirect_uri: "http://test.com", created_at: "2014-10-12 10:32:50", updated_at: "2014-10-12 10:32:50">]]
```

I'm using Rails 4.2.0 beta 2 and my gemfile only has devise and better_errors as extras. I tested with the same gems in Rails 4.1.6 and didn't run into an issue.

I've also run the test suite against 4.2.0 beta 2 and all the specs are passing.

Thanks!!

**Comment by linjunzhu** [comment]
Maybe U should be updated the wiki about  `owner`

`https://github.com/doorkeeper-gem/doorkeeper/wiki/Associate-users-to-OAuth-applications-%28ownership%29`

```ruby
  # only needed if each application must have some owner
  def create
    @application = Doorkeeper::Application.new(application_params)
    @application.owner = current_user if Doorkeeper.configuration.confirm_application_owner?
    if @application.save
      # Here should be flash.now[:notice]
      flash[:notice] = I18n.t(:notice, :scope => [:doorkeeper, :flash, :applications, :create])
       # Here should be render :show
       respond_with( :oauth, @application, location: oauth_application_url( @application ) )
    else
      render :new
    end
  end
```
