### ISSUE TITLE
documentation with Minitest

### ISSUE THREAD

**Issue by andrericardo** [doorkeeper-gem/doorkeeper#503]
Is it possible to document the [Testing of Protected Controllers](https://github.com/doorkeeper-gem/doorkeeper/wiki/Testing-protected-controllers) using Minitest?
    what is the equivalent of stubbing doorkeeper_token in Minitest?

``` ruby
    let(:token) { double :acceptable? => true }

    before do
      controller.stub(:doorkeeper_token) { token }
      # allow(controller).to receive(:doorkeeper_token) {token} # => RSpec 3
    end
```

**Comment by hugueslamy** [comment]
I post a possible solution to use only minitest to handle doorkeeper authentification.
http://stackoverflow.com/questions/22387975/minitest-with-rails-doorkeeper/28950425#28950425

**Comment by tute** [comment]
I find my previous comment quite short, sorry about that. Thanks @hugueslamy for your answer, and every piece of knowledge you people gather also has a place in the wiki.

Thank you both for your input!
