### ISSUE TITLE
Improve error message for expired refresh token

### ISSUE THREAD

**Issue by thomasballinger** [doorkeeper-gem/doorkeeper#510]
When an expired access token is used in a request, the `:expired` message "The access token expired" is pretty helpful, however when an expired refresh token is used to request a new access token only the generic `:invalid_request` message "The request is missing a required parameter, includes an unsupported parameter value, or is otherwise malformed." message is used.

It would be nice to provide a more specific message for this case, particularly since using single-use refresh tokens is optional in the spec. Would there be interest in such a PR?

**Comment by tute** [comment]
Fixed in https://github.com/doorkeeper-gem/doorkeeper/commit/722113f with the help of @whatasunnyday and @euraldius. Thanks also to @thomasballinger for noting it too!
