### ISSUE TITLE
Selectively enable urn:ietf:wg:oauth:2.0:oob. Security of Implicit Flow.

### ISSUE THREAD

**Issue by ArTiSTiX** [doorkeeper-gem/doorkeeper#514]
Hello !

I'm having some troubles to make my API secure.
In OAuth2 RFC, there is no mention of urn:ietf:wg:oauth:2.0:oob, and implicit flow is a redirection flow... It supposes that the access_token is redirected to an URI with # fragment... handled by a trusted app (browser does not permit to access this fragment outside of the intended document).

Thus, urn:ietf:wg:oauth:2.0:oob is very useful for authorization_code flows (because we provide a non-redirection way to get this code, token is obtain with secret) but for implicit flow, i think it generates a big breach, because we can't suppose that the http client (document) is secure. Indeed, the redirection points to /oauth/token (and displays the token, + query params could be logged).

For example, my webapp is trusted by default (skip authorization), so when i authorize to get the token, with urn:ietf:wg:oauth:2.0:oob, any other application can do the same... And get an access_token which is supposed to be handled only by webapp. This is not supposed to happen !

Now, I changed my flows to forbid urn:ietf:wg:oauth:2.0:oob for implicit flow. But i would like to enable it only for authorization codes, or for untrusted apps (forcing a non-dangerous scope).

**Could you please implement a way to selectively enable/disable this native redirect_uri, depending on client_id/application ?**
I tried with lambdas without success.

I am currently searching for any additional information about securing implicit flows. My main issue is because it's too easy for any application to act like my web application, and get an access token.
In fact, i think it's strange to use 'urn:ietf:wg:oauth:2.0:oob' with an implicit flow redirecting to /oauth/token. It might be a breach in doorkeeper.

Here are my strategies:
[if client is trusted] -> disable 'urn:ietf:wg:oauth:2.0:oob' -> force redirect_uri (with # fragement containing access_token) => hacker application cannot get a token, since it can't access to hash fragment
[if client is untrusted] -> force authorization (no skip is possible) -> enable 'urn:ietf:wg:oauth:2.0:oob' if a native application need to get an access token or authorization code => then, it's user responsibility if he accepts a hacker's application

Anybody have relevant answer ? I don't know if i'm wrong...

**Comment by tute** [comment]
Implicit flow has been disabled by default in https://github.com/doorkeeper-gem/doorkeeper/commit/2115a5243b4663090b49c872a1837f6dda6b0b91.

Regarding the potential PR you quote, I an interested.

Thank you for your input!
