### ISSUE TITLE
`check_for_missing_columns` failing Heroku buildpack asset compilation

### ISSUE THREAD

**Issue by agrobbin** [doorkeeper-gem/doorkeeper#530]
Unfortunately #526 nor #527 fixed issues with deploying Doorkeeper 2.0 when using Heroku's [Ruby buildpack](https://github.com/heroku/heroku-buildpack-ruby). Part of their build process includes running asset compilation, which when using Postgres will raise a `PG::ConnectionBad` exception as soon as it hits [this line](https://github.com/doorkeeper-gem/doorkeeper/blob/3444e56739816cdf414079aae2c2136fa869269c/lib/doorkeeper/config.rb#L21). Because the error message from the `pg` gem doesn't include "does not exist" (which [Rails looks](https://github.com/rails/rails/blob/v4.1.8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L896-L901) for when determining whether to raise `ActiveRecord::NoDatabaseError`), the exception is not caught.

I'm not sure what the best solution is to fix this, but I am hoping I'm not the only one who is experiencing this issue.

**Comment by twk3** [comment]
Also having this same issue, but on our chef omnibus build. We are running precompile during our deb/rpm creation, but without a valid db connection.

**Comment by tute** [comment]
Should this be a PR in Rails? cc @sgrif.

**Comment by tute** [comment]
@agrobbin could you workaround this problem already?

**Comment by tute** [comment]
Proposed PR in doorkeeper: https://github.com/doorkeeper-gem/doorkeeper/pull/545.

**Comment by sgrif** [comment]
Yes, this should be a PR in Rails.

**Comment by tute** [comment]
Closing this issue in favor of #545. Thank you Sean!
