### ISSUE TITLE
Using Resource Owner Password Credentials flow with client credentials

### ISSUE THREAD

**Issue by chumakoff** [doorkeeper-gem/doorkeeper#537]
How to make doorkeeper to require and validate client credentials (client_id, client_secret as well as resource owner's username and password) when using Resource Owner Password Credentials flow ?

**Comment by smnplk** [comment]
@tute  What do you mean it's not described in the spec, resource owner credentials flow is described in Oauth 2 spec. @chumakoff I have a demo rails 4 app demonstrating your requirements https://github.com/smnplk/oauth_provider_example
