### ISSUE TITLE
Undefined method `attr_accessible

### ISSUE THREAD

**Issue by rjrferreira** [doorkeeper-gem/doorkeeper#541]
Hi,

I have this error:
NoMethodError: undefined method `attr_accessible' for Doorkeeper::AccessGrant:Class
                        AccessGrantMixin at C:/jruby-1.7.16/lib/ruby/gems/shared/gems/doorkeeper-2.0.1/lib/doorkeeper/models/access_grant_mixin.rb:1

Gemfile.lock:

(...)
doorkeeper (2.0.1)
      railties (>= 3.1)
protected_attributes (1.0.8)
rails (4.0.8)
(...)

Any idea?

**Comment by jmguedes** [comment]
I have the same problem! 
Any idea to fix this?

**Comment by tute** [comment]
`protected_attributes (1.0.8)` should provide `attr_accessible`. The failure comes form: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/models/access_grant_mixin.rb#L14-L16. Do you see anything wrong with that condition? Can you provide a failing test case or a failing app in GitHub?

Thanks for reporting.

**Comment by rjrferreira** [comment]
The condition works fine.
"::Rails.version.to_i" returns 4 and "defined?(::ProtectedAttributes)" returns ProtectedAttributes defined!

Unfortunately i can't provide my failing app.

**Comment by tute** [comment]
I'll need an app where to reproduce the problem in order to try solutions. Thanks for reporting.

**Comment by rjrferreira** [comment]
Hi Tute,

Please follow this link:
https://github.com/rjrferreira/MyProject/tree/master/doorkeeper_test

**Comment by tute** [comment]
Thanks, can reproduce it there. Will leave open until it is fixed.

**Comment by tute** [comment]
For some reason in mongoid `protected_attributes` gem is not extending the models. If we add `include ActiveModel::MassAssignmentSecurity` in doorkeeper models/mixins, then it works (https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/models/access_grant_mixin.rb#L14-L16).

I'd like to know, though, when exactly do we need to add it, and if we need to add it here in some cases or it's rather a PR for protected_attributes. cc @sgrif @rafaelfranca

**Comment by rjrferreira** [comment]
Thanks Tute!

**Comment by andremfaria** [comment]
I was with the same problem @tute, and your answer solved my problem! thanks

**Comment by rafaelfranca** [comment]
@tute I believe it is because mongoid users have to include `ActiveModel::MassAssignmentSecurity` manually. The gem only hooks automatically on Active Record, so just detecting if the gem is present is not a good way to detect.

Maybe doorkeeper should check if the class respond to `:attr_accessible`?

**Comment by tute** [comment]
Thank you Rafael. Mongoid could include that module, and I don't remember why didn't we use `respond_to?(:attr_accessible)`. If that works that would be the welcomed PR to doorkeeper. :)

Thank you all!
