### ISSUE TITLE
Applications should not be able to create tokens with a scope they don't have

### ISSUE THREAD

**Issue by williamhc** [doorkeeper-gem/doorkeeper#542]
An application can, as of now, generate tokens with arbitrary scopes even if the application has not been granted that scope. Simply change the query params of the oauth/authorize url and it will be created with whatever scopes are selected.

**Comment by tute** [comment]
Started work on https://github.com/doorkeeper-gem/doorkeeper/tree/tc-scopes. Thanks for reporting.
