### ISSUE TITLE
Doorkeeper potentially ignoring config client_credentials

### ISSUE THREAD

**Issue by whatasunnyday** [doorkeeper-gem/doorkeeper#543]
Hi! Firstly, incredible work on Doorkeeper. It's really made my life a lot better. 

I think that doorkeeper may be ignoring configuration options for `client_credentials`.

My config looks like this:

```ruby
Doorkeeper.configure do
  orm :active_record

  resource_owner_authenticator do
    current_user || warden.authenticate!(:scope => :user)
  end
  
  resource_owner_from_credentials do |routes|
    u = User.find_for_database_authentication(:email => params[:username])
    u if u && u.valid_password?(params[:password])
  end

  access_token_expires_in 2.hours

  use_refresh_token

  client_credentials :from_basic

  access_token_methods :from_bearer_authorization

  grant_flows %w(password)
end
```

I have a test that I expected to fail after setting `client_credentials :from_basic` (from the default values).

```ruby
require 'test_helper'

class OAuthAuthorizationTest < Capybara::Rails::TestCase
  def setup
    @app = Doorkeeper::Application.create!(name: 'App', redirect_uri: 'urn:ietf:wg:oauth:2.0:oob')
    @user = users(:valid)
    @client = OAuth2::Client.new(@app.uid, @app.secret) do |c|
      c.request :url_encoded
      c.adapter :rack, Rails.application
    end
  end

  test 'auth ok' do
    token = @client.password.get_token(@user.email, 'password')
    assert_not token.expired?
  end

  test 'auth nok' do
    assert_raises(OAuth2::Error) { @client.password.get_token(@user.email, 'wrong') }
  end
end
```

By default, [OAuth2](https://github.com/intridea/oauth2) uses parameters so I thought it was possible that it was actually doing it from basic auth but I checked the tests logs and found this:

```
------------------------------------
OAuthAuthorizationTest: test_auth_ok
------------------------------------
   (0.1ms)  SAVEPOINT active_record_1
  Doorkeeper::Application Exists (0.2ms)  SELECT  1 AS one FROM "oauth_applications" WHERE "oauth_applications"."uid" = '7fc2f7c10cf2f5928fcb75be5a8be3078897d2
6a241761bd9c05d454438aba6b' LIMIT 1
  SQL (0.2ms)  INSERT INTO "oauth_applications" ("name", "redirect_uri", "uid", "secret", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING
 "id"  [["name", "App"], ["redirect_uri", "urn:ietf:wg:oauth:2.0:oob"], ["uid", "7fc2f7c10cf2f5928fcb75be5a8be3078897d26a241761bd9c05d454438aba6b"], ["secret",
 "0a9d1a3a511f073a6c4fb8e2d47a6a6cea989242346101a4d2ea22286c871edf"], ["created_at", "2015-01-07 01:49:10.212656"], ["updated_at", "2015-01-07 01:49:10.212656"
]]
   (0.1ms)  RELEASE SAVEPOINT active_record_1
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 201799169]]
Started POST "/oauth/token" for 127.0.0.1 at 2015-01-06 17:49:10 -0800
Processing by Doorkeeper::TokensController#create as HTML
  Parameters: {"client_id"=>"7fc2f7c10cf2f5928fcb75be5a8be3078897d26a241761bd9c05d454438aba6b", "client_secret"=>"0a9d1a3a511f073a6c4fb8e2d47a6a6cea9892423461$1a4d2ea22286c871edf", "grant_type"=>"password", "password"=>"[FILTERED]", "username"=>"jrsunny@gmail.com"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["email", "jrsunny@gmail.com"]]
   (0.1ms)  SAVEPOINT active_record_1
  Doorkeeper::AccessToken Exists (0.5ms)  SELECT  1 AS one FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = '98b6efaedd104360877a8dcab90337ac3$b39045dde84c631ea4d602adedeeff' LIMIT 1
  Doorkeeper::AccessToken Exists (0.3ms)  SELECT  1 AS one FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."refresh_token" = '4a7a5c31accb52ff76cf5ff6f$b19b6ea1e57d2af7735794a39b138134ebfb2a' LIMIT 1
  SQL (0.4ms)  INSERT INTO "oauth_access_tokens" ("resource_owner_id", "scopes", "expires_in", "token", "refresh_token", "created_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["resource_owner_id", 201799169], ["scopes", ""], ["expires_in", 7200], ["token", "98b6efaedd104360877a8dcab90337ac32b39045dde84c631e$4d602adedeeff"], ["refresh_token", "4a7a5c31accb52ff76cf5ff6feb19b6ea1e57d2af7735794a39b138134ebfb2a"], ["created_at", "2015-01-07 01:49:10.228289"]]
   (0.1ms)  RELEASE SAVEPOINT active_record_1
Completed 200 OK in 14ms
   (0.1ms)  ROLLBACK
```

I'm not sure if I'm misunderstanding something but it seems that Doorkeeper is authenticating users from params even if its set only to authenticate users from basic auth.

**Comment by tute** [comment]
I see https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/client/credentials.rb#L8 choosing only from the methods you allow. If you can provide a failing test, or at least an app where I can replicate this behavior, I'll be able to triage this potential issue. Thanks!

**Comment by whatasunnyday** [comment]
He @tute,

I created this repo to reproduce the problem:
https://github.com/whatasunnyday/doorkeeper-client-credentials

Hopefully, I'm not misunderstanding what's happening and wasting both of our time.

**Comment by apellizzn** [comment]
It also seems to me that when you are requesting a token with client_credentials or password_credentials flows, when requiring an optional scope that is not included inside client scopes it doesn't throw an error, instead it returns a token with that scope.
The content of server.scopes that you are using to check if a scope is allowed is always returning the full list of scopes (default and optional), so it seems that configuration are not working well here, also i see this case in not covered by tests.

**Comment by whatasunnyday** [comment]
Hey @tute, I know  you must be obviously very busy. I was wondering if you looked at this. If you can confirm this an issue, I would be happy to give a hand fixing it.

**Comment by tute** [comment]
Indeed I've been too busy, thanks for understanding. If I don't get to it tonight hopefully it'll be the weekend.

**Comment by whatasunnyday** [comment]
@tute Don't sweat it. Let me know if there's anything I can do to help. Thanks again for your amazing work on doorkeeper. It's a lifesaver :).

**Comment by tute** [comment]
In your app the token gets created without any application being assigned to it, which is expected:

```
# from_basic (no client application)
  INSERT INTO "oauth_access_tokens" ("resource_owner_id", "scopes", "expires_in", "token", "refresh_token", "created_at") VALUES (?, ?, ?, ?, ?, ?) [["resource_owner_id", 1], ["scopes", ""], ["expires_in", 7200], ["token", "959c45719b23304dee713e8a116c72493f452cd062f87ee8cb3621f61eb739ad"], ["refresh_token", "a8fbf347cfb0fab1a62a791898f22b24bff44feda73a7067efb343ff40aed810"], ["created_at", "2015-01-27 22:53:32.397285"]]

# from_params (no client application)
  INSERT INTO "oauth_access_tokens" ("application_id", "resource_owner_id", "scopes", "expires_in", "token", "refresh_token", "created_at") VALUES (?, ?, ?, ?, ?, ?, ?) [["application_id", 19], ["resource_owner_id", 1], ["scopes", ""], ["expires_in", 7200], ["token", "989adf2718e58835f4fdbda003505502471c06467da80693965ba591cb7e864d"], ["refresh_token", "cc48883cd146e151924eb78c2483c3548ec630009757519245353f32e2d99898"], ["created_at", "2015-01-27 22:52:58.273938"]]
```

This is because you are using the Resource Owner Password Credentials Grant Flow, which, if doesn't have client credentials (as it's not seen by doorkeeper because in your configuration it expects HTTP Basic params), it doesn't need to authenticate it. See related: https://github.com/doorkeeper-gem/doorkeeper/issues/561.

If you used the Client Credentials Grant Flow it should reject the client authorization step.

Thank you for reporting and for your help trying to replicate. Closing this issue for now, happy to continue further discussion.

**Comment by whatasunnyday** [comment]
Thanks for your quick response @tute. To confirm, because I'm using the resource owner password credentials grant flow, it is **not possible** to restrict the client credentials from being sent in the params?

**Comment by tute** [comment]
I don't understand your question @whatasunnyday. The access token gets sent in the request body, as in http://tools.ietf.org/html/rfc6749#section-5.1. And it gets sent because the email and password match in the application. Does this help?
