### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by maclover7** [doorkeeper-gem/doorkeeper#546]
Hi!

I just upgraded from 1.4.1 to 2.0.1, and ran

```
rails generate doorkeeper:application_scopes && rake db:migrate
```

However, doorkeeper keeps adding a little error message saying that I haven't done this yet:

```
[doorkeeper] Missing column: `applications.scopes`. If you are using ActiveRecord run `rails generate doorkeeper:application_scopes && rake db:migrate` to add it.
```

**Comment by tute** [comment]
mmh, the condition for that necessary error message seems to be too brittle. I'm not sure how to solve in a better way though.

Meanwhile, please run a migration with `add_column :oauth_applications, :scopes, :string, null: false, default: ''`, which is what would be generated with the command you quote. See https://github.com/doorkeeper-gem/doorkeeper/blob/master/CHANGELOG.md#200.

Thank you for reporting.

**Comment by maclover7** [comment]
Already generated the migration and rake db:migrate, that's why I'm not sure what is causing the error.

**Comment by tute** [comment]
It complains on this condition: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/config.rb#L22.

Are you sure your `oauth_applications` table has a `scopes` column?

**Comment by maclover7** [comment]
https://github.com/hackcentral/hackcentral/blob/master/db/schema.rb#L117

**Comment by tute** [comment]
The call in https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/config.rb#L22 should have the `Doorkeeper::` prefix, as you also have an `Application` model defined and name collides. Want to send a PR?

**Comment by maclover7** [comment]
So the line would be:

```
!Doorkeeper::Application.new.attributes.include?("scopes")
``

**Comment by tute** [comment]
Indeedy.

**Comment by tute** [comment]
Please explain in the commit message why the change, and add an entry in the CHANGELOG as part of the PR.

**Comment by maclover7** [comment]
PR has been sent over, is PR #547

**Comment by tute** [comment]
Closing this issue in favor of the PR.

**Comment by tute** [comment]
For now you can point your `Gemfile` to this repository's `master`, I expect to release 2.0.2 this week. Thanks!

**Comment by maclover7** [comment]
Ok, thanks agin for your help on this!
