### ISSUE TITLE
Include 'spec' directory into s.files

### ISSUE THREAD

**Issue by miyagawa** [doorkeeper-gem/doorkeeper#55]
I wonder if it is intentional that the 'spec' directory is excluded from the s.files in the gemspec. Probably these spec files were meant to be used only for testing on your development end, but I've found that some of the helpers and factories in the doorkeeper git repository are useful on my own app testing. 

For example, i can use the `Factory(:application)` to create a new application, then use `client_is_authorized` to quickly create a new access token, then use `with_access_token_header` to send a new authorized request.

If they are installed in the `gem install`, we can load them using our own spec_helper by looking at `Gem.loaded_specs` and load from `spec/support/helpers` etc. What do you think?

**Comment by jormon** [comment]
https://github.com/doorkeeper-gem/doorkeeper/commit/09cb679186a3197fcc29c7e315e3bcd13ae02de1 breaks this (in 2.1.4+)

**Comment by jormon** [comment]
fixed in v4.2.0 which includes work done in #871
