### ISSUE TITLE
Minor: Error response HTTP status differs from OAuth Spec

### ISSUE THREAD

**Issue by ahegyi** [doorkeeper-gem/doorkeeper#550]
I just noticed that in the OAuth spec, when there is an error response upon issuing an access token, a `400 Bad Request` should be returned (in most cases): http://tools.ietf.org/html/rfc6749#section-5.2

However, it looks like the error code sent back from Doorkeeper is always a `401 Unauthorized`: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/error_response.rb#L29

Does Doorkeeper intentionally always use a `401` or am I misunderstanding something? Thanks!

**Comment by tute** [comment]
We should conform to spec, PR with tests welcome this inconsistency! Thanks for reporting.

**Comment by ahegyi** [comment]
Cool, thanks for confirming! If I get a chance, I'll submit a PR.

**Comment by tute** [comment]
ping @ahegyi

**Comment by tute** [comment]
Quoting the HTTP spec:

> 400 Bad Request
> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).[14]

These errors seem not fit into a 400. Anyhow, which flavor of 40x we return might be practically irrelevant because if clients follow the HTTP spec they will treat any 4XX as a 400 (3rd paragraph of http://tools.ietf.org/html/rfc7231#section-6).

Closing for now, thanks for reporting!

**Comment by slross16** [comment]
Vanilla HTTP spec doesn't include the Oauth context. Oauth spec which was linked above does place these errors in a 400:  http://tools.ietf.org/html/rfc6749#section-5.2

401 vs 400 does matter in reality - iOS 8 safari for example will pop up a basic authentication dialog (and doesn't allow client JS to handle the response) on receiving a 401 - which may be an error on their part but this is a specific example of an advantage to having doorkeeper follow oauth spec.

**Comment by tute** [comment]
@slross16, indeed we can do better and clients can be smarter if we provide more specific responses. I'll be glad to review and merge a PR that improves this. Thanks for your input.

**Comment by toupeira** [comment]
@nbulaj can we reopen this issue?

If I understand https://tools.ietf.org/html/rfc6749#section-5.2 correctly:
- a 400 status should be returned for most error conditions
- a 401 MAY be be returned for an `invalid_client` error, and MUST be returned if the `Authorization` request header is used.

https://tools.ietf.org/html/rfc6750#section-3.1 defines some additional errors:
- a 401 SHOULD be returned for an `invalid_token` error
- a 403 SHOULD be returned for an `insufficient_scope` error

**Comment by nbulaj** [comment]
Hi @toupeira . Looks like you are right:

> If the  client attempted to authenticate via the "Authorization"
> request header field, the authorization server MUST
> respond with an HTTP 401 (Unauthorized) status code and
>  include the "WWW-Authenticate" response header field
> matching the authentication scheme used by the client.

So 400 for cases except this one above. Also we can review `invalid_token` and `insufficient_scope` codes, Would you like to produce a PR ?

**Comment by toupeira** [comment]
@nbulaj sure! I submitted https://github.com/doorkeeper-gem/doorkeeper/pull/1202 which should address this.
