### ISSUE TITLE
Support for native URL schemes

### ISSUE THREAD

**Issue by stuartgibson** [doorkeeper-gem/doorkeeper#552]
I can't seem to find away to let the callback URL to allow native callbacks for iOS apps etc without also enabling non-ssl web URLs.

eg `myappscheme://oauth.authorize/` will be rejected because it is not an SSL URL.

I have temporarily added `force_ssl_in_redirect_uri false` in my config, but ideally would rather have this enforced while still allowing URL schemes.

**Comment by tute** [comment]
The validation is for the admin web interface. If you careful and not seed in an HTTP only url, disabling that enforcement will be fine.

I don't mind it being misnamed for this case, so the user turning it off is aware of the risks and need for SSL URLs.

If you can think of a code solution that would take into account your use case (checking for non-HTTP URLs for example), I'll gladly discuss/merge a PR.

Thanks for reporting!

**Comment by stefanvermaas** [comment]
:+1: for native redirect URI's.

**Comment by antek-drzewiecki** [comment]
@tute, @stefanvermaas  We let users specify their own applications and we would like to allow users to edit their redirect uri's themself. This validation is ran on the users input when updating the application callback URI. 

Just to be one step ahead of a security issue, are you aware of other non secure protocols other then http that a user could specify?  

Or should I implement an valid URI's validator instead that only allows 'https' and 'some_other_secure_protocol' instead?

**Comment by tute** [comment]
> Just to be one step ahead of a security issue, are you aware of other non secure protocols other then http that a user could specify?

I don't know of other common unsecure by default protocols, and if there are we should add them here.

If programmers use their custom protocols, I expect them to be aware of their custom security implications.
