### ISSUE TITLE
OpenID Connect (OAuth 2.0 for Login)

### ISSUE THREAD

**Issue by ryanjones** [doorkeeper-gem/doorkeeper#553]
Hi @tute,

I recently noticed that google is leaning towards OpenIDConnect. Are there any plans to start shaping the doorkeeper around the requirement (DK 3.0?)? From what I can tell OpenID Connect has set some standards around the calls and flows, and some session management.

https://developers.google.com/accounts/docs/OpenIDConnect

Thanks,
Ryan

**Comment by tute** [comment]
I'm interested in discussing if enough people request it, and there's intersection with current implementations.

If it doesn't change current OAuth 2 flows it doesn't need to be in a new major release.

**Comment by christopherhein** [comment]
Looks like someone has started this? https://github.com/playon/doorkeeper-openid_connect

**Comment by tute** [comment]
It hasn't been updated for a while, but probably it's stable. And it has no tests. Have you tried it? I'd like it if possible to have this functionality in another repo.

**Comment by tute** [comment]
As https://github.com/doorkeeper-gem/doorkeeper/issues/598, I'd like this to be an extension. Will close this issue, please let me know if I can help you in any way.
