### ISSUE TITLE
Scope checker allow application with scopes=nil to require any scope

### ISSUE THREAD

**Issue by apellizzn** [doorkeeper-gem/doorkeeper#559]
It seems to me that when you are requesting a token with client_credentials or password_credentials flows, when requesting an optional scope with an app with scopes = nil it doesn't throw an error, instead it returns a token with that scope.

The flow starts from [client_credentials.rb] (https://github.com/doorkeeper-gem/doorkeeper/blob/ad5b17e4d21b6bc1f596d20f47cbbf2b3f257aa6/lib/doorkeeper/request/client_credentials.rb) in the request method an ```OAuth::ClientCredentialsRequest``` is being initialized with the ```Doorkeeper.configuration``` object that has the ```default_scopes``` and the ```scopes``` keys then in ```ClientCredentialsRequest::Validation#validate_scopes``` you call ```OAuth::Helpers::ScopeChecker``` with ```@server.scopes // all the scopes (default + optional)``` and if the application has ```scopes = nil``` the validation is **performed against all the scopes**. 
This ends is **allowing each application without scopes to obtain any scope**.
Is this a wanted behavior or am i missing something? At least it shouldn't be good to save an applicaition with ```scope = il```

**Comment by tute** [comment]
That is right, and that's expected behavior as it was designed. Read discussion in the PR: https://github.com/doorkeeper-gem/doorkeeper/pull/469#issuecomment-63911022.

This is so that people upgrading don't need to seed in default values on every application. If you need to invalidate all scopes for an application, you would seed in an invalid scope, or delete the application altogether.

Thanks!

**Comment by mmzoo** [comment]
> This is so that people upgrading don't need to seed in default values on every application.

Thank you @tute for the clarification. I kept wondering for a day or two whether I would have to seed the new scopes column when upgrading. There was no hint anywhere that I'd have to do that, but I was not sure whether that omission was to be interpreted as "it's going to work" :) I'm glad I found this issue to get some reassurance.
