### ISSUE TITLE
Override doorkeeper application layout

### ISSUE THREAD

**Issue by davidfrey** [doorkeeper-gem/doorkeeper#56]
The default layout provided by doorkeeper is nice, but if I want to use my own layout and simply disregard app/views/layouts/doorkeeper/application.html.erb, where would be the best place to start? I'm not all that familiar with engines and simply adding the custom view to my app breaks devise helpers used in my layout.

**Comment by flynfish** [comment]
In case someone else comes looking for an answer...

http://stackoverflow.com/questions/10879150/isolated-engine-doorkeeper-use-helper-methods-from-the-main-app

```
class YourApp::Application < Rails::Application
  config.to_prepare do
    # include only the ApplicationHelper module
    Doorkeeper::ApplicationController.helper ApplicationHelper

    # include all helpers from your application
    Doorkeeper::ApplicationController.helper YourApp::Application.helpers
  end
end
```

**Comment by flynfish** [comment]
I also updated the wiki with [this info] (https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-views)
