### ISSUE TITLE
before_action :doorkeeper_authorize! not working

### ISSUE THREAD

**Issue by tejans24** [doorkeeper-gem/doorkeeper#562]
Similar previous Issues

https://github.com/doorkeeper-gem/doorkeeper/issues/470
https://github.com/doorkeeper-gem/doorkeeper/issues/474

My Issue:

Gemfile: 

```
gem 'doorkeeper'
```

UserController: 

```
class Api::V1::UsersController < Api::ApiController

  before_action :doorkeeper_authorize!, except: :index
  before_filter :set_user, only: [:index]

  def index
    users = User.all
    render json: users
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end
```

Result: 

```
NoMethodError at /api/v1/users/1
undefined method `doorkeeper_authorize!'
```

I followed all the instructions in the readme file. 

I tried the following in the UserController and it works

```
doorkeeper_for :all, except: :index
```

Is the documentation not up to date or am I doing something wrong?

**Comment by tute** [comment]
You must be using a pre v2 version. See previous README versions adjusting the tag in the URL: https://github.com/doorkeeper-gem/doorkeeper/tree/v1.4.1.

Thanks!
