### ISSUE TITLE
Mongoid 4 application owner index

### ISSUE THREAD

**Issue by sandelius** [doorkeeper-gem/doorkeeper#564]
Hi. If I enable application ownerships the application model does not get the appropriate indexes like ActiveRecord models does (in migrations). Is this intentional?

**Comment by tute** [comment]
I practically don't maintain other ORMs, I can't do it reliably as I don't use them, and it is my end goal to move those outside of doorkeeper's codebase. If indexes should be there please add them in your application (I don't know if they should), and PRs are welcome to fix this if doorkeeper should do that automatically. Thanks!
