### ISSUE TITLE
Remove assets from precompile

### ISSUE THREAD

**Issue by sandelius** [doorkeeper-gem/doorkeeper#565]
It should be an option to remove the doorkeeper css and js from the precompile array.

**Comment by tute** [comment]
What is your use case for this option @sandelius? How would you implement it?
Thanks!

**Comment by tute** [comment]
Is this still an issue for you, @sandelius?

**Comment by tute** [comment]
I believe this is not an issue with doorkeeper, happy to reopen if you disagree @sandelius. Thanks!

**Comment by matthew-levan** [comment]
If I want to use my own stylesheets instead of the ones Doorkeeper provides (Bootstrap, etc.) how could I do this?
