### ISSUE TITLE
Cant get access token on response

### ISSUE THREAD

**Issue by EricMcRay** [doorkeeper-gem/doorkeeper#566]
why I cant get access token as json on my facebook login callback?

My code:

token = Doorkeeper::AccessToken.find_by_resource_owner_id(user.id)
render json: token

**Comment by tute** [comment]
@EricMcRay I need more information to debug your issue. Please see http://yourbugreportneedsmore.info/.

For general questions, please post in [StackOverflow](http://stackoverflow.com/questions/tagged/doorkeeper).
