### ISSUE TITLE
Require client credentials on password grant flow.

### ISSUE THREAD

**Issue by akianderson** [doorkeeper-gem/doorkeeper#569]
Client credentials validation was removed in this commit: 10bec40fadb86d86bbc807969f248f4d4e7f226b 

...but I am not sure why?  From my understanding Oauth2 specification still requires client credentials even on password grant flow: http://oauthlib.readthedocs.org/en/latest/oauth2/grants/password.html

**Comment by tute** [comment]
This issue might belong to https://github.com/idan/oauthlib. Client credentials presence validation was removed in https://github.com/doorkeeper-gem/doorkeeper/issues/569 because the OAuth spec doesn't require it:

> The authorization server MUST: authenticate the client if client authentication is included
>
> http://tools.ietf.org/html/rfc6749#section-4.3.2

Thanks for your input.

**Comment by akianderson** [comment]
@tute it looks like you guys did add back the client validation but the problem is here:
```
      def validate_client
        !credentials || !!client
      end
```
