### ISSUE TITLE
Error in Clearance Example documentation 

### ISSUE THREAD

**Issue by ianwalter** [doorkeeper-gem/doorkeeper#573]
Missing do after resource_owner_authenticator:
```ruby
resource_owner_authenticator
  @user = env[:clearance].current_user

  unless @user
    session[:return_to] = request.fullpath
    redirect_to(routes.sign_in_url)
  end

  @user
end
```

https://github.com/doorkeeper-gem/doorkeeper/wiki/Authenticating-using-Clearance-or-DIY

**Comment by tute** [comment]
Thanks Ian! Mind updating the wiki yourself?

**Comment by ianwalter** [comment]
Ok done (didn't realize I could edit it!)

**Comment by tute** [comment]
Thank you! :)
