### ISSUE TITLE
Add client_secret to list of Rails filterered_paramters

### ISSUE THREAD

**Issue by wireframe** [doorkeeper-gem/doorkeeper#576]
sensitive information should be excluded from production logs.

see http://guides.rubyonrails.org/configuring.html

**Comment by tute** [comment]
`config.filter_parameters += [:client_secret]` very much needed indeed. We also need to filter out refresh and access tokens. Thanks for reporting.

**Comment by wireframe** [comment]
@tute you may want to also scrub the `access_token` and `bearer_token` parameters as well.  Those params are used by the `OAuth::Token::Methods` module for fetching tokens from request parameters.

I can open a new issue if you'd prefer?

**Comment by tute** [comment]
Both would match `token`, so they should be handled. If they are not, a PR would be the cherry on top!

**Comment by apsoto** [comment]
Any chance this can be backported to create 1.4.2?  I'm using bundle-audit and doorkeeper 1.4.1 is now failing the bundle-audit check.

**Comment by tute** [comment]
For two weeks I'll be quite busy, but I'd gladly merge the PR and release 1.4.2 with this adjustment. Make sure to update the CHANGELOG too! :) Thanks for your comment and sorry for my absence.

**Comment by apsoto** [comment]
PR created.  Let me know if you need any tweaks.

**Comment by apsoto** [comment]
PR updated and build is passing
