### ISSUE TITLE
Authorization server does not support this response type

### ISSUE THREAD

**Issue by pepibumur** [doorkeeper-gem/doorkeeper#579]
Hello
I'm trying to setup Doorkeeper in my project but I get the following message when I'm trying to authenticate with a given app:

![image](http://cl.ly/image/042B1h2s1R0t/Image%202015-02-12%20at%2011.13.04%20pm.png)

```
The authorization server does not support this response type.
```
I'm using Doorkeeper grants assertion, https://github.com/doorkeeper-gem/doorkeeper-grants_assertion and my doorkeeper.rb file is the following one:

```ruby
Doorkeeper.configure do
  # Configuration
  orm :mongoid4
  default_scopes :public
  access_token_expires_in 2.hours
  client_credentials :from_basic, :from_params
  access_token_methods :from_bearer_authorization, :from_access_token_param, :from_bearer_param

  # Assertions
  resource_owner_from_assertion do
    User.find_or_create_with_github_token(params[:assertion])
  end

  # Returns the admin
  admin_authenticator do |routes|
    redirect_to(root_path) if (!current_user or !current_user.has_role?(:admin)) 
  end


  # Grant flow
  # # "authorization_code" => Authorization Code Grant Flow
  # "implicit"           => Implicit Grant Flow
  # "password"           => Resource Owner Password Credentials Grant Flow
  # "client_credentials" => Client Credentials Grant Flow
  #
  # If not specified, Doorkeeper enables authorization_code and
  # client_credentials.
  #
  # implicit and password grant flows have risks that you should understand
  # before enabling:
  #   http://tools.ietf.org/html/rfc6819#section-4.4.2
  #   http://tools.ietf.org/html/rfc6819#section-4.4.3
  #
  # grant_flows %w(authorization_code client_credentials)

  grant_flows %w(assertion)
end
```
Any ideas? Thanks!

BTW: I want to enable only the login using assertions, is it enough only with `grant_flows %w(assertion)` ?

**Comment by tute** [comment]
Hi @pepibumur. doorkeeper-grants_assertion [has no maintainer](https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/issues/7). I would be surprised if it works. I wonder if @christopherhein can share any insights on this.

Doorkeeper will only understand the four flows defined in that comment, and not assertions, unless Doorkeeper is extended. I'll close this issue as it doesn't belong in doorkeeper, you might reopen it in that repo.

Thanks for your input.

**Comment by tute** [comment]
BTW, it seems like some forks have fixed this issue (but didn't send back PRs): https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/network

**Comment by tute** [comment]
I just merged a commit that fixes it: https://github.com/doorkeeper-gem/doorkeeper-grants_assertion/commit/1b3acee3437fef80dd95038d40a1739aecdab0c0

**Comment by pepibumur** [comment]
Hello @tute , totally agree.
I've tried your last commit merge but still suffering the same problem. Do you know any way to handle that? How would you do it? I want to override the access_token generation and pass a Github token to authorize the user using its Github token. I saw the assertions concept and that was exactly what I was looking for. Thanks for your help.

**Comment by tute** [comment]
No idea exactly. Whatever you find, please post it in the wiki or a PR! :)

**Comment by StarWar** [comment]
How to issue token for a particular app in assertion flow?

Currently I'm using facebook token to issue access_token and it works without passing client_id and client_secret.
I want to issue token only if correct client_id and client_secret is provided.
