### ISSUE TITLE
Create a sample app for Doorkeeper Grape integration

### ISSUE THREAD

**Issue by sethherr** [doorkeeper-gem/doorkeeper#580]
As promised in https://github.com/doorkeeper-gem/doorkeeper/wiki/Grape-integration.

I'll make a sample app with doorkeeper, grape, winebouncer, grape-swagger and rails_swagger-ui and link to it in the wiki page before the end of the weekend.

**Comment by tute** [comment]
I will close this issue, as it's not an issue with doorkeeper itself. Thank you very much!

**Comment by sethherr** [comment]
It's up and added to the wiki too https://github.com/sethherr/grape-doorkeeper

**Comment by antek-drzewiecki** [comment]
Hi @sethherr, I will be referring to your sample application from wine_bouncer as well.
Note that we released a new authentication DSL `oauth2(*scopes)`, so you can remove the ugly `authorizations: { oauth2: [] },` hash! :+1:

**Comment by sethherr** [comment]
Hey @antek-drzewiecki, sorry I didn't see this till now. I updated the authentication hash to the new style, sethherr/grape-doorkeeper@6e8baa285c14e3c7376875f0f97a970571f4d32c
