### ISSUE TITLE
Doorkeeper::AccessToken.authenticate removed?

### ISSUE THREAD

**Issue by robguilfoyle** [doorkeeper-gem/doorkeeper#581]
I used to switch betweens sites by manually authenticating a resource's token with the below method:

    Doorkeeper::AccessToken.authenticate

Can you tell me where this method was extracted too?

**Comment by tute** [comment]
It is not. See also `Doorkeeper.authenticate` convenience method: https://github.com/doorkeeper-gem/doorkeeper/pull/405.
