### ISSUE TITLE
Custom resource owner grants for 2fa and social

### ISSUE THREAD

**Issue by maknz** [doorkeeper-gem/doorkeeper#585]
We have an app which can be authenticated with using username/password, optional 2 factor auth, or via Google as an identity provider. We want to implement OAuth2, but we'd need to modify the resource owner grant to take a 2 factor auth token, and implement a custom grant for the Google auth which instead of a username/password/token, takes an OAuth2 `code` and authenticates the user with Google.

I'm wondering how we could go about adding/modifying the resource owner grant for these use cases?

**Comment by tute** [comment]
Hi @maknz. This question doesn’t belong in this issue tracker, as this is not an issue with doorkeeper itself. Please consider posting it in https://stackoverflow.com/questions/tagged/doorkeeper. Closing this issue for now. Thanks!
