### ISSUE TITLE
rails helpers interface change between 2.1.1 and 2.1.2

### ISSUE THREAD

**Issue by ivan-kolmychek** [doorkeeper-gem/doorkeeper#587]
Looks like [this commit](https://github.com/doorkeeper-gem/doorkeeper/commit/db9c00f68c8d921b2f0c9997be0ab2c05d830ef0#diff-b5434f1575f11189eb3e29a738d0a87bL24) between 2.1.1 and 2.1.2 has broken the compatibility by removing `#valid_doorkeeper_token?` (and creating `#doorkeeper_token_is_invalid?` instead)

I couldn't find any notion on what is doorkeeper versioning model, but breaking changes in 2.1.x (x > 0) release definely goes against [semver](http://semver.org/), so, I think, it will be unexpected for alot of people.

Note, that these changes also are not in the changelog for 2.1.2 - were they intentional or just happened by accident?

Thanks.

**Comment by tute** [comment]
Hi @ivan-kolmychek, thanks for your input. I will now bring that method back to life at it seems useful.

For context, that file has been a bit of a mess for a long time, and only after that commit I started thinking of what should or should not be part of it's stable public interface. I'm also considering making the response method public too, see: https://github.com/doorkeeper-gem/doorkeeper/issues/563#issuecomment-76533278.

Thanks for reporting!

**Comment by ivan-kolmychek** [comment]
@tute thanks for the fix, but I'm back here with the same issue - the 2.1.1 version had scopes passed as an argument, so, the interface is still broken. =)

2.1.1
> def valid_doorkeeper_token?(*scopes)

2.1.3+
> def valid_doorkeeper_token?

**Comment by tute** [comment]
Thanks for reporting, @ivan-kolmychek. Do you think adding this to `NEWS` (and removing the arguments from your app) is an ok solution?

**Comment by ivan-kolmychek** [comment]
@tute thank you for response to such an old issue. I guess it's ok, especially if noone has reported it yet, which means we're the only one who relied on that, sorry to disturb you. 

We'll find the way around that on our own.
