### ISSUE TITLE
raising custom error based on different conditions in resource_owner_authenticator method in configure/initializer/doorkeepr.rb

### ISSUE THREAD

**Issue by elitmuscasts** [doorkeeper-gem/doorkeeper#590]
I want to customise error response based on different conditions.
for authentication, I have a few conditions where a user is not authenticated, for example,
not active user, user profile is incomplete etc etc.

I followed this, #315 it raises the error but can not rescue it 
```
Doorkeeper.configure do
  resource_owner_from_credentials do |routes|
    result = Session.authorize(params[:username], params[:password])
    # result be a hash like this { type: ok, user_id: 1111 } or { type: :password_invalid, msg: "password invalid."}
    if result[:type] == :ok
      User.find_by_id(result[:user_id]) 
    else
      raise Doorkeeper::Errors::OwnError
    end
  end
end
```

**Comment by elitmuscasts** [comment]
I want to customise error response based on different conditions.
for authentication, I have a few conditions where a user is not authenticated, for example,
not active user, user profile is incomplete etc etc.

I followed this, #315 it raises the error but can not rescue it 
```
Doorkeeper.configure do
  resource_owner_from_credentials do |routes|
    result = Session.authorize(params[:username], params[:password])
    # result be a hash like this { type: ok, user_id: 1111 } or { type: :password_invalid, msg: "password invalid."}
    if result[:type] == :ok
      User.find_by_id(result[:user_id]) 
    else
      raise Doorkeeper::Errors::OwnError
    end
  end
end
```

**Comment by tute** [comment]
Hi @elitmuscasts. This question doesn’t belong in this issue tracker, as this is not an issue with doorkeeper itself. Please consider posting it in https://stackoverflow.com/questions/tagged/doorkeeper. Closing this issue for now. Thanks!
