### ISSUE TITLE
A bug when issuing an access token with scopes?

### ISSUE THREAD

**Issue by calfzhou** [doorkeeper-gem/doorkeeper#593]
Using the latest master version of doorkeeper.

Backgrounds:

* `doorkeeper.configuration.default_scopes` is set to `public`.
* `doorkeeper.configuration.optional_scopes` is set to `x, y, z`.
* There is a registered application - app1, `app1.scopes` is set to `x, y`.

When app1 requesting an access token using client credential flow, the results are:

* if `params[:scope]` is not present, result token will have scopes `public`
* if `params[:scope]` is set to `public`, server will deny the request - because `public` is not in `app1.scopes`

This is very strange, since when i requesting `public` scope, it saids the scope is invalid. But when i'm not requesting any specific scope, it grants me a `public` scope.

In my opinion, when `params[:scope]` is not present, server should either deny the request or grant all scopes belonging to the client (in this case should be `x, y`), or grant it the default scope only if default scope belongs to the client.

**Comment by calfzhou** [comment]
with this PR, when `params[:scope]` is not present, server will grant it `default_scopes & app1.scopes` if `app1.scopes` is not blank.

**Comment by tute** [comment]
Closing in favor of PR.
