### ISSUE TITLE
bug: [refresh token flow] scope parameter should be `:scope`, not `:scopes`

### ISSUE THREAD

**Issue by calfzhou** [doorkeeper-gem/doorkeeper#594]
in [Doorkeeper::OAuth::RefreshTokenRequest](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib%2Fdoorkeeper%2Foauth%2Frefresh_token_request.rb#L21), it initializes `@original_scopes` with `parameters[:scopes]`, but according to rfc 6749 [Refreshing an Access Token](https://tools.ietf.org/html/rfc6749#section-6), the parameter name should be `scope`.

**Comment by tute** [comment]
Closing in favor of PR.
