### ISSUE TITLE
Support limiting application scopes per grant flow

### ISSUE THREAD

**Issue by calfzhou** [doorkeeper-gem/doorkeeper#597]
With current design, an application can be restricted within a set of scopes (#317), but still need restrictions on each grant flow.

For example an application is restricted with `public`, `profile.read` and `profile.write` scopes, and the oauth server enables both authorization code and client credentials flows. Since accessing `public` resource doesn't require an owner's grant, this scope can be used (by this application) in client credentials flow. But `profile.read` and `profile.write` must be authorized by profile's owner (using authorization code flow), server should deny the client if it requests using client credentials flow.

There should be two levels of restriction configurations, one is server-side, the other one is for every single application. Thus there could be `Doorkeeper.configuration.#{grant_type}_scopes` configurations (nil by default, means no limitation, and will fall back to `Doorkeeper.configuration.scopes`) as each grant flow's default scopes range. And for each application, there could be `application.#{grant_type}_scopes` fields (nil by default, means no specific limitation, and will fall back to `application.scopes`). The relation between these two set of scopes is exactly the same with current `server_scopes ` and `application.scopes`.

**Comment by calfzhou** [comment]
There could also be default scopes per grant flow, such as `Doorkeeper.configuration.#{grant_type}_default_scopes`.

**Comment by tute** [comment]
I don't want to build this into doorkeeper, seems complex implementation which makes it more prone to edge cases and bugs, and also complex for users, even when in need of simpler configurations.

I am interested though in allowing developers encode this in their apps. What APIs could we provide to give more granularity while authorizing? We have the `skip_authorization do |resource_owner, client|` configuration block, for example`. Naively we could make it fail is we find the scope and grant flows is not blessed. Also, we could add a more semantic `unauthorize_if` configuration block, where you could take care of such scenarios.

What do you think? Thanks for your input.

**Comment by calfzhou** [comment]
`skip_authorization` will not be invoked in client credentials flow. could we add a general callback which allows users deny any authorization or token request according to their business logic?

**Comment by tute** [comment]
It could be an option. Do you have some sample code? Doesn't need to be running, but a little spike on the idea.

**Comment by aiman86** [comment]
I had a very urgent and similar need to this feature request and built a quick-and-dirty extension: https://github.com/aiman86/doorkeeper_scopes_per_flow

Again - it's not the cleanest approach as it uses monkey patching and decorators to inject default scope and to validate that a flow is allowed to be given requested scopes. However, it should get the job done.

**Comment by tute** [comment]
@calfzhou what do you think of @aimannajjar's approach?

**Comment by calfzhou** [comment]
@aimannajjar's extension provides server-side per-flow config, which is just what i need. I think it's enough for most scenarios.

**Comment by tute** [comment]
I listed related projects in the wiki. Feel free to edit: https://github.com/doorkeeper-gem/doorkeeper/wiki#extension-projects. Thanks!

**Comment by aimannajjar** [comment]
Sounds good, thanks!
