### ISSUE TITLE
JWT Support

### ISSUE THREAD

**Issue by chriswarren** [doorkeeper-gem/doorkeeper#598]
Less an issue and more a question, I wanted to check on how you'd prefer JWT support be implemented, if at all.

I'm looking in to adding support for [JWT](http://jwt.io) support to Doorkeeper, and haven't found anyone discussing it. My questions are A) do you know of anyone already doing this and B) if not, would you want this to be part of Doorkeeper or an extension like the assertion granting?

I've started on a fork of doorkeeper to add it in, but can move it elsewhere if that's preferred.

**Comment by tute** [comment]
Why should it be related with doorkeeper? Is it related with OAuth 2? Would JWT share relevant pieces of code with doorkeeper?

**Comment by chriswarren** [comment]
Spec is at http://self-issued.info/docs/draft-ietf-oauth-jwt-bearer.html as well.

I'm looking at creating a flow like [Zendesks's SSO](https://support.zendesk.com/hc/en-us/articles/203663816-Setting-up-single-sign-on-with-JWT-JSON-Web-Token-).

**Comment by tute** [comment]
I see. It should be an extension, like the assertion grants feature. And it will need a maintainer, which probably is you! :)

**Comment by tute** [comment]
Closing for now, let me know if I can help you in any way. Thanks!
