### ISSUE TITLE
The redirect uri included is not valid.

### ISSUE THREAD

**Issue by wibicms** [doorkeeper-gem/doorkeeper#600]
I implement doorkepeer to authorize client application, but when it has been authorized successfully the doorkerper says "The redirect uri included is not valid".

I have tried to change redirect uri in applications table, but it not change anything.

Thanks for helping.

Wibi

**Comment by tute** [comment]
Hi @wibicms. This question doesn’t really belong in this issue tracker, as this is not an issue with doorkeeper itself. Please consider posting it in https://stackoverflow.com/questions/tagged/doorkeeper, where a wider audience can help you out. Closing this issue for now. Sorry I'm not able to help right now.
