### ISSUE TITLE
how to know when grant is created?

### ISSUE THREAD

**Issue by peterept** [doorkeeper-gem/doorkeeper#602]
I want to maintain a membership table for my users that have granted access to an application so they can access information related to the application.

How can I know when a grant has been created?

TIA

**Comment by tute** [comment]
Hi @peterept. This question doesn’t really belong in this issue tracker, as this is not an issue with doorkeeper itself. Please consider posting it in https://stackoverflow.com/questions/tagged/doorkeeper, where a wider audience can help you out. Closing this issue for now. Sorry I'm not able to help right now.

**Comment by peterept** [comment]
Thanks, fair enough - apologies.. I found a solution and posted it to Stackoverflow:

http://stackoverflow.com/questions/29092127/doorkeeper-how-to-know-when-a-grant-is-created/29113142#29113142

**Comment by tute** [comment]
Thanks for sharing the question and the solution! :+1:
