### ISSUE TITLE
Question about using scopes for different user roles

### ISSUE THREAD

**Issue by adampetrie** [doorkeeper-gem/doorkeeper#603]
Hi,

I have an app where a user resource can have multiple roles (admin, staff etc.) and I want to provide the ability for a logged in user to switch between these roles in a single session. When a user is in an admin role vs. a staff role, their permissions would change.

My question is whether or not scopes can be used to address this. At present we issue a doorkeeper token when a user logs in and we only ever let them be a single role. If I were to use scopes could I allow users to switch roles in a way that their token would know which role they were currently acting as?

Any insight is appreciated.

Thanks.

**Comment by tute** [comment]
Hi @adampetrie. This question doesn’t really belong in this issue tracker, as this is not an issue with doorkeeper itself. Please consider posting it in https://stackoverflow.com/questions/tagged/doorkeeper, where a wider audience can help you out. Closing this issue for now. Sorry I'm not able to help right now.
