### ISSUE TITLE
Customising views is not very clearly described

### ISSUE THREAD

**Issue by peterept** [doorkeeper-gem/doorkeeper#605]
This page:
https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-views

>rails generate doorkeeper:views
>
>This will copy all the views to app/views/doorkeeper

Is not clear what to do and if you need the layouts.

I played around with it and now I understand it (it is brilliant). If you have one of those views it will override the gem one. So you can safely delete any that you want to keep coming from the gem. And layouts are optional, and only needed if you want.

Can the page say:

"When a view is requested doorkeeper will first look in your app/views/doorkeeper folder, and if not found will fall back to the one included in the gem."

**Comment by tute** [comment]
That's a great improvement @peterept. Want to send a PR to the README, or update the wiki with your suggestions? Thanks!

**Comment by peterept** [comment]
I added this to the wiki page:

Doorkeeper looks first for its views in that subfolder, and if not found it will fall back to its default.

**Comment by tute** [comment]
That's perfect, thank you!
