### ISSUE TITLE
Potential New Doorkeeper Feature/Option - Allow client to dictate token expiration

### ISSUE THREAD

**Issue by jzw** [doorkeeper-gem/doorkeeper#607]
I've a question about a potential new feature that I'd like to see added to Doorkeeper. Note, I am not asking someone else to do it, I just want to get some feedback before I get started. First some background...

I have a "stand-alone Doorkeeper app" exclusively to provide/persist/validate tokens.  What I mean by stand-alone is our resources are spread out across several services.  The Doorkeeper app exists exclusively to provide/persist/validate tokens. The other services need to share information and they use tokens from Doorkeeper to authenticate (and authorize with scopes).

A common use case in this environment would be:

1. Service A needs Resource X on Service B.
2. Service A asks for and receives an AccessToken from Doorkeeper.
3. Service A hands Service B the token (this is handoff generally done via the browser) along with a request for Resource X.
4. Service B validates the token with Doorkeeper, and if it is valid it responds with resource X (back to the browser).

* I'm not sure if this is relevant but we use the [Client Credentials Flow](https://github.com/doorkeeper-gem/doorkeeper/wiki/Client-Credentials-flow) exclusively.

My particular issue is that sometimes we want a token to last a few seconds, and in other cases we may want the token to last minutes, hours, etc.  

A recent new feature (see #481 and #606) of Doorkeeper allows you to have application-specific expirations, however I would really like more control specifically for our scenario where all of these services are in-house, and we have a single Token provider (Doorkeeper). I'd *like* to be able to say "Give me a token that expires in N seconds".  

So, what I'd like to know is if I were to create a PR that implements this feature, would it be accepted?  I don't feel like this is an obscure use-case, and it seems like it could be useful to others.  

What I have in mind is a new boolean configuration option (something like `allow_client_to_provide_expires_in` which defaults to `false`), and when `true` then the `POST /oauth/token` API endpoint will accept an additional `expires_in` param.

**Comment by tute** [comment]
@jzw thanks for your notes.

I'm generally wary to do any custom extension to this OAuth implementation. The spec only defines `expires_in` in the context of responses, not requests, and before extending request steps I'd want to discuss with a set of people who dedicate themselves to security, something we don't yet have in this project.

Your use case does indeed sound reasonable, but I wouldn't merge such a PR as of now into doorkeeper. Prefer to stick to the spec (which in turn it doesn't take that many decisions anyway, but that's another topic!) as much as possible.

Thank you for your time.

**Comment by jzw** [comment]
@tute thanks for the feedback, and I understand your stance.
