### ISSUE TITLE
Dynamic expiration

### ISSUE THREAD

**Issue by jesuisbonbon** [doorkeeper-gem/doorkeeper#613]
I want to set dynamic expiration of the access_token, based on the user privilege 
How can i accomplish something like this ..

```
access_token_expires_in do |client|
    client.my_custom_field_which_contains_the_expiration_time.hours
end
```

**Comment by tute** [comment]
Exactly as you say! Add a migration adding the custom attribute to the `oauth_applications` table, and reference it in the code block. Please report in the wiki how it goes.
Thanks!

**Comment by jesuisbonbon** [comment]
are you sure, because the code below setting no expires_in values :(
```
  access_token_expires_in do |client|
    5.hours
  end
```

**Comment by tute** [comment]
If that's happening this is a bug, and should be reopened. How can I replicate it?

**Comment by jesuisbonbon** [comment]
in doorkeeper.rb 
```
  access_token_expires_in 5.hours
```
if i look in my rails log, a nice expires_in value
```
INSERT INTO "oauth_access_tokens" ("application_id", "resource_owner_id", "scopes", "expires_in", "token", "refresh_token", "created_at") VALUES ... ["expires_in", 18000] ...
```
and
```
  access_token_expires_in do |client|
    5.hours
  end
```
"expires_in" field is missing in the insert into statement
```
INSERT INTO "oauth_access_tokens" ("application_id", "resource_owner_id", "scopes", "token", "refresh_token", "created_at")
```

**Comment by tute** [comment]
You are right, you can use `custom_access_token_expires_in`, which takes a block.

It's surprising API, I would like `access_token_expires_in` to handle either case.

**Comment by jesuisbonbon** [comment]
Thanks! Working :)
