### ISSUE TITLE
Doorkeeper 2.1.5 Release

### ISSUE THREAD

**Issue by chriswarren** [doorkeeper-gem/doorkeeper#616]
Thanks for accepting my pull request. I've updated my gem to require Doorkeeper 2.1.5, which isn't out yet. Do you have any idea when you might build and push that up to RubyGems?

**Comment by tute** [comment]
It will be doorkeeper 2.2.0, as it's an enhancement of doorkeeper's API: https://github.com/doorkeeper-gem/doorkeeper/blob/master/NEWS.md#220---unreleased.

I release every three weeks on average, so if until ~mid April you can work with a commit version in the Gemfiles I'll do that, but if you need me to release earlier I could do it.

**Comment by chriswarren** [comment]
I can use the commit version until then. Thanks. Updated my readme accordingly.
