### ISSUE TITLE
the strange `custom_access_token_expires_in`

### ISSUE THREAD

**Issue by calfzhou** [doorkeeper-gem/doorkeeper#617]
doorkeeper v2.1.4

According to the generated doorkeeper config file, we could define a `custom_access_token_expires_in` to `Assign a custom TTL for implicit grants`, and the sample code shows
``` ruby
  # Assign a custom TTL for implicit grants.
  # custom_access_token_expires_in do |oauth_client|
  #   oauth_client.application.additional_settings.implicit_oauth_expiration
  # end
```

But i just tried it, feel very confusing about when and how this method is called.

I tried auth code, implicit, client credentials and refresh token flows, here is the result (assuming that the parameter is named `oauth_client`):

- authorization code flow:
  - will be called
  - parameter (`oauth_client`) is a `Doorkeeper::Application` instance
- implicit flow:
  - will be called
  - `oauth_client` is a `Doorkeeper::OAuth::PreAuthorization` instance
  - `oauth_client.client` is a `Doorkeeper::OAuth::Client` instance
  - `oauth_client.client.application` is a `Doorkeeper::Application` instance
- client credentials flow:
  - will be called
  - `oauth_client` is a `Doorkeeper::OAuth::Client` instance
  - `oauth_client.application` is a `Doorkeeper::Application` instance
- refresh flow:
  - will not be called

Really be confused by the logic :confused:

**Comment by tute** [comment]
Thanks for your time and report. We really need to flesh this out. If you can start a Pull Request I'll be happy to join so we make it better. Otherwise I'll work on this in a month.

**Comment by tute** [comment]
Thanks for your report. Addressing this issue in https://github.com/doorkeeper-gem/doorkeeper/pull/636 (also, closing it in favor of that PR).

Now parameter for `custom_access_token_expires_in` is either `Doorkeeper::OAuth::Client` or `Doorkeeper::Application`. `Doorkeeper::OAuth::Client` is a small wrapper around
`Doorkeeper::Application`, and can be treated as an `Application`.

Also, now we use `custom_access_token_expires_in` in `RefreshTokenRequest`.

Thanks again!
