### ISSUE TITLE
Admin Users

### ISSUE THREAD

**Issue by rkistner** [doorkeeper-gem/doorkeeper#618]
I have two types of users: "normal" users and admin users. In my doorkeeper application, it is easy to check whether an user is an admin, with something like `current_user.super_user?`. Is there a standard way to do the same from client applications?

I can add a custom API to do this (e.g. `/api/users/is-admin`), but this adds an additional API call. It would be convenient if the client application can just request e.g. an "admin" scope, but any user would be able to grant this. Is there a way to restrict a scope so it can only be granted by admin users?

**Comment by tute** [comment]
Hi @rkistner. You might want to take a look into JWT tokens, which just landed in master. I have solved this issue with a `/me` endpoint in the past, that defines the role for the user.

Consider asking this question in StackOverflow too, as the issue tracker is to discuss flaws or feature requests for doorkeeper. Also, a wider audience can help you out.

Thanks!

**Comment by rkistner** [comment]
Thanks @tute, that helps a lot. I'll go with a `/me` or similar endpoint now, and look at JWT at a later point.
