### ISSUE TITLE
Implementing `One-time Code Flow (Hybrid Authentication)` with Google and Facebook

### ISSUE THREAD

**Issue by movstox** [doorkeeper-gem/doorkeeper#619]
hi all,

This is just a question, sorry if I posted it into the wrong place.

Could you please help on what's the best way to integrate hybrid authentication scheme with doorkeeper?

What I have found so far is "Hybrid Authentication" at https://github.com/zquestz/omniauth-google-oauth2 and link on Google's site https://developers.google.com/+/web/signin/server-side-flow

If you could provide any sample applications, that would help a lot.

**Comment by tute** [comment]
Is there a standard for this? As of today, doorkeeper is supposed to comply with https://github.com/doorkeeper-gem/doorkeeper#ietf-standards. We are trying to build extensions as plugins to doorkeeper.

**Comment by movstox** [comment]
@tute I'm not sure if there's a standard for that, but it seems this way of client-side js auth is much more robust and advised to use by developers in the future.

If you think there's a good way to integrate this into doorkeeper, let me know. If I get it working, I'll just make my contribution.

**Comment by tute** [comment]
@movstox let me know if there's any concrete change that you think we should make in doorkeeper or in an extension library to it. Thanks!
