### ISSUE TITLE
Client Credentials Grant (without password or user interaction)

### ISSUE THREAD

**Issue by shankardevy** [doorkeeper-gem/doorkeeper#620]
Does doorkeeper support getting access token without user interaction?

> The client can request an access token using only its client  credentials 

(see http://tools.ietf.org/html/rfc6749#section-4.4)

I am working on an app where the oauth credentials do not belong to any real user. The oauth credentials are created for trusted client apps with different access permissions.

**Comment by tute** [comment]
Yes @shankardevy. See https://github.com/doorkeeper-gem/doorkeeper/wiki/Client-Credentials-flow. Also, there's relevant questions and answers in StackOverflow.

**Comment by shankardevy** [comment]
@tute thanks for the link.
