### ISSUE TITLE
How to Handle "Filter chain halted as :require_no_authentication"

### ISSUE THREAD

**Issue by wwvuillemot** [doorkeeper-gem/doorkeeper#625]
Hi,

I have an intermittent problem that seems specific to Safari (possible red herring).

* User goes to Site B
* User clicks on Sign In
* User redirected to Profile (Doorkeeper) site
* User signs in
* User redirected to Site B
* *some time later*
* User goes to Site B
* User clicks on Sign In
* User redirected to Profile site
* User redirected to root of Profile

In the logs, in these instances, I see that the filter chain is halted on ":require_no_authentication".  But by then the `redirect_uri` that was stored in session got cleared, and so DoorKeeper just redirects to the root.

This does not happen all the time.  I am suspecting I am doing something obviously stupid, just not obvious to me.  What is maddening (at least to me) is that the behavior is not consistent.  So some sort of race-condition, or otherwise bug in my session controller?

I appreciate I might just be asking what boils down to: `programmer is the bug`.  But any help is much appreciated.

~~~~
Apr 11 08:24:03 ABC-Profile app/web.2: Processing by Users::SessionsController#new as HTML  
Apr 11 08:24:03 ABC-Profile heroku/router: at=info method=GET path="/users/sign_in?return_to=%2Foauth%2Fauthorize%3Fclient_id%CLIENT_ID%26redirect_uri%3Dhttps%253A%252F%252Fwww.siteb.io%252Fauth%252FSTRATEGY%252Fcallback%26response_type%3Dcode%26state%CODESTATE" host=profile.armadillo.xyz request_id=REQUEST_ID fwd="1.2.3.4" dyno=web.2 connect=1ms service=10ms status=302 bytes=1196  
Apr 11 08:24:03 ABC-Profile app/web.2: Redirected to https://profile.abc.xyz/  
Apr 11 08:24:03 Armadillo-Profile app/web.2: Filter chain halted as :require_no_authentication rendered or redirected
~~~~

Below is the `sessions_controller` that uses Devise

~~~~ruby
class Users::SessionsController < Devise::SessionsController
  before_filter      :configure_sign_in_params, only: [:new, :create]

  # GET /resource/sign_in
  def new
    store_return_to
    super
  end

  # POST /resource/sign_in
  def create
    store_return_to
    super
    if current_user
      session[:user_id] = current_user.id
    end
  end

  # DELETE /resource/sign_out
  def destroy
    session[:user_id] = nil
    super
  end

  protected

  #   You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :return_to
  end

  def after_sign_in_path_for(resource_or_scope)
    return_to_url = session[:return_to]
    clear_stored_location
    if return_to_url
      return return_to_url
    else
      return super
    end
  end

  private

  def store_return_to
    session[:return_to]    = params[:return_to].to_s if params[:return_to]
  end

  def clear_stored_location
    session[:return_to]    = nil
  end

end
~~~~

**Comment by tute** [comment]
If we can't reproduce it, we can't fix it (http://yourbugreportneedsmore.info/). Is this still an issue for you? Can you provide a failing test? Thanks!

**Comment by tute** [comment]
Also, this issue seems more related with devise than with doorkeeper.

**Comment by wwvuillemot** [comment]
Again, I was thinking `require_no_authentication` was Doorkeeper filter, not devise.  If that is the case then I will close now.

Sorry!  And thank you for your time.
