### ISSUE TITLE
OAuth access grant callback?

### ISSUE THREAD

**Issue by leemartin** [doorkeeper-gem/doorkeeper#626]
First of all, this library fucking rocks. So, thanks for that.

I'm running an ID service with Doorkeeper which authenticates several mini applications which are part of a Suite I've built. I use campaign monitor to subscribe every newly created account to a mailing list I market to. I'd like to do some segmenting on this list related to **which** apps users are authenticating to. So my question is, is there a call to receive a callback from each oauth_access_grant so I can sniff the application_id and adjust my mailing list entry to reflect the fact that this user is using a certain app? Perhaps it's something I can adjust in the skip_authorization function?

Any help is much appreciated!

**Comment by tute** [comment]
Not sure how to build this off the top of my head. Did you ask also in StackOverflow, where a larger community might help you with this?
Thanks!

**Comment by tute** [comment]
I'll close this issue as it doesn't seem a bug/feature request in doorkeeper. If it is, feel free to reopen with more information.

StackOverflow might be a more fruitful place to ask. Thanks!
