### ISSUE TITLE
Allow Accept Header Versioning in Doorkeeper-generated routes

### ISSUE THREAD

**Issue by katpadi** [doorkeeper-gem/doorkeeper#634]
So I'm wondering where I can hook into the Doorkeeper-generated routes so I can validate version & vendor headers. Is there such a feature for this now? If not, this would be great :+1: :)

I am using Grape so this is what I want to put in there:

`version 'v1', strict: true, using: :header, vendor: 'katpadi'`

**Comment by tute** [comment]
I don't use Grape, so I'm not exactly sure what you need. If doorkeeper provided what you need, how would the syntax look like? Do you want to inject the headers, or read them?

You will probably find it useful to see the `doorkeeper_authorize!` method: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/grape/helpers.rb#L10-L19. You can override the parts of that class that make sense to you?

**Comment by tute** [comment]
ping @katpadi

**Comment by katpadi** [comment]
I was thinking of something like... Say a doorkeeper route is
"/oauth/token" (API endpoint)

How would I be able to say that I want it to strictly accept only v1? How
can I apply the default versioning of Doorkeeper?

**Comment by tute** [comment]
I don't know how to do that in Grape. I'll close this issue as it doesn't seem a bug/feature request in doorkeeper. If it is, feel free to reopen with more information.

StackOverflow might be a more fruitful place to ask!
