### ISSUE TITLE
Support JWT Bearer Authorization Flow

### ISSUE THREAD

**Issue by alfredw33** [doorkeeper-gem/doorkeeper#639]
I would like to have the ability for Doorkeeper to support the JWT Bearer Authorization Flow. I would like to implement something similar to how [Salesforce](https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_jwt_flow.htm) has done it but for Doorkeeper.

Currently I've already [forked](https://github.com/PatientOrderSets/doorkeeper) the project and I've added the code to support this new flow. I've been following the guidelines outlined by [IETF](https://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer-12).

Before I make a pull request I would like your help in getting all of the TravisCI tests to pass. I'm currently having problems with mongo mapper configuration issues for only certain builds but other then that all the tests pass. If somebody can help me with that it would be awesome. We'll continue with testing it locally in our application while we sort out this TravisCI problem.

 Looking forward to contribute back!

**Comment by tute** [comment]
It already works: https://github.com/doorkeeper-gem/doorkeeper#custom-access-token-generator.
Thanks!

**Comment by alfredw33** [comment]
Sorry to open it up again but unless I'm miss understanding what has been implemented Doorkeeper will generate a JWT token instead of a unique token for an access token.

What I'm proposing is that the token creation stays the same (i.e. using a a unique token) but instead of relying on regular authorization flow or user name and password for flow, Doorkeeper will take a JWT to authenticate a 3rd party on behalf of a user to produce an access token. As outlined in the IETF link I've sent, I don't think Doorkeeper can handle that type of flow. 

In reality it's very similar to the password flow but instead of taking a username and password it relies on the JWT to authenticate a 3rd party application on behalf of a user.

Currently the implementation we did only supports JWT using HMAC but we plan to support RSA soon.

Hope that clears up what we want to do but if you think this functionality has already been implemented or doesn't fit the vision of what Doorkeeper is about then I totally understand.

**Comment by tute** [comment]
Thanks for your input and work.

I'd rather not include that behavior in doorkeeper. How can we make it modular in a way that we can extend doorkeeper with this JWT behavior you add in your fork? Like we did for generating tokens (or JWT tokens, or whatever-tokens), how can we make doorkeeper aware of this kind of authentication?

I'd love to work towards that.

**Comment by alfredw33** [comment]
That sounds like a plan and I understand why this is a good way to go as it will allow for other people to  implement whatever flow they want.

I'll probably work on something soon but before that let me think about a way to get this done and run that by you before I start. I just need some time to think about it today. Some of my initial thoughts are to introduce some factory patterns/strategy pattern stuff.

**Comment by kiomac** [comment]
I've been working on a simple extension for Doorkeeper: [doorkeeper-jwt_assertion](https://github.com/kioru/doorkeeper-jwt_assertion)

I reused the `resource_owner_authenticator` configuration for authenticating the user once we have valid JWT claims available. Should I something like `resource_owner_from_jwt_claims` instead?

**Comment by tute** [comment]
I think `resource_owner_authenticator` is the right name for this. Why do you think having a more specific one could be better? The generic one could authenticate from jwt, devise or clearance, etc.

**Comment by tute** [comment]
BTW thanks for sharing your extension!

**Comment by kiomac** [comment]
First I was relying on the PasswordAccessTokenRequest, but now I built a specialized AssertionAccessTokenRequest in order to make the correct validations: 
 - validate_assertion (describing error responses in case of an JWT.decode error)
 - validate_client (based on the jwt issuer if it's configured to do so)
 - create_token (with no refresh_token)

This validations are the reason I want to build an specialized extension for Doorkeeper. Keeping the ietf-oauth-jwt-bearer consistent.

**Comment by tute** [comment]
This issue is fixed as of https://github.com/chriswarren/doorkeeper-jwt (also used as an example in the README: https://github.com/doorkeeper-gem/doorkeeper#custom-access-token-generator).
Thank you!

**Comment by DanielStevenLewis** [comment]
Hi there,

I'm writing to request that this ticket be reopened. My understanding of Doorkeeper::JWT is that it makes it such that JWTs are returned instead of Doorkeeper's standard access tokens. As per the guidelines Alfred linked to, the functionality that we're interested in is something different. We'd like the functionality for Doorkeeper to return access tokens (either standard access tokens or JWTs) in exchange for a JWT. In other words, when an application wants an access token, it must send Doorkeeper a JWT. (Note: for the sake of simplifying discussion, I'm assuming that refresh tokens are disabled). This flow confers better security.

Thanks,
Daniel

**Comment by DanielStevenLewis** [comment]
Tagging @tute @kiomac to bump my above post. I'm planning to create another (duplicate) GitHub issue if nobody responds in a few weeks.

Cheers,
Daniel

**Comment by nbulaj** [comment]
Hi @DanielStevenLewis . Thanks for the interest in this issue. You can propose a PR instead of new issue, I think it would be more helpful :)

**Comment by alfredw33** [comment]
It's been almost 4 years since I made my original post. Life got busy and I did not have the time to get the work done. 

what Tute was suggesting was to make it more modular and externally load this capability in. Is the expectation still to do that if I / someone makes a PR?

**Comment by DanielStevenLewis** [comment]
Hey guys,

@nbulaj Thanks for replying! I see where you're coming from, but I'd think that having an open issue/ticket would be the first step towards anyone putting up a PR, unless we need a whole new GitHub project for this feature. I for one prefer to reference tickets in my PRs. The community should also probably hash out the architecture before anyone starts coding anything; this discussion would be more appropriate in an open ticket. Such discussion would decrease the likelihood of someone wasting time developing code that'll end up getting declined.

Great question @alfredw33 ! Thanks for writing the original fork. @tute I don't understand why you wrote back then that you'd "rather not include that behavior in doorkeeper," and (noting that I haven't read through too much of the Doorkeeper code base or contributed to it before) I can't think of a reason why the behaviour shouldn't be included in Doorkeeper. It'd be great if you could let us know your reasoning. I'd like for the community to make sure that it's sound, and that it applies to a fulsome understanding of the feature request, as expressed in my first post. If anyone else can think of reasons for or against including the behaviour in Doorkeeper, please do let us know. If you (the reader) think this behaviour shouldn't be included in Doorkeeper, do you have any ideas as to how to make it modular?

**Comment by tute** [comment]
> It'd be great if you could let us know your reasoning

Some reasoning is in this blog post: https://robots.thoughtbot.com/splitting-an-open-source-project-in-two-with-git-submodules. The solution we got there might not work for this issue though.

doorkeeper as a framework is hard to move forward with such a tiny "team" of project owners (it used to be me while in thoughtbot, and it's @nbulaj now). doorkeeper as an extendable library, though, can work better with its scattered community, where subsets of people have particular use cases.

> Do you have any ideas as to how to make it modular?

See other gems for example implementations:

- https://github.com/doorkeeper-gem/doorkeeper-openid_connect
- https://github.com/doorkeeper-gem/doorkeeper-jwt
- https://github.com/doorkeeper-gem/doorkeeper-mongodb
- https://github.com/doorkeeper-gem/doorkeeper-grants_assertion

**Comment by tute** [comment]
It might be the case that doorkeeper should support it out-of-the-box due to better security by default. In that case, a PR will be needed indeed! 😊

**Comment by nbulaj** [comment]
Hi @DanielStevenLewis . You are free to open a new issue to discuss the feature you want.

I agree that it can be a Doorkeeper core implementation. I'm thinking about some refactoring to introduce plugin system that anyone can use to extend core functionality, but it's for future releases

**Comment by kiomac** [comment]
Hi @DanielStevenLewis. I can't agree more. We should keep an open discussion on the JWT Authorization Grant Flow. 

On the other hand, as for the [RFC 6749 - Section 1.3](https://tools.ietf.org/html/rfc6749#section-1.3) only four grant types are defined, which are well covered by the Doorkeeper gem. In my opinion a JWT Grant should be considered an extension, and therefore makes sense to build a gem. But as @nbulaj suggested, Doorkeeper needs a plugin system.

Building an external gem could offer extra functionalities that are not directly part of the Doorkeeper codebase, like a **signature key manager** (e.g. create and revoke RSA certificates), at least in the most basic form: a rails task. A minimal design for **multi-tent/client signature** validation. Even an **opt-in redis storage** module for the key manager.

**Comment by grzesiek** [comment]
This would be really cool feature :+1:
