### ISSUE TITLE
Docs for using application-specific scopes

### ISSUE THREAD

**Issue by katpadi** [doorkeeper-gem/doorkeeper#640]
Anything about this? I know there's a migration instruction but no further details. :(
I'm not sure as well, maybe it's just the wine_bouncer that's not working well with the app-specific scopes. thanks

**Comment by tute** [comment]
@katpadi we'll need more info to know exactly what issue you are having: http://yourbugreportneedsmore.info/.

cc @antek-drzewiecki

**Comment by katpadi** [comment]
Sorry! My bad... :-1: 

I don't want the API consumers to pass the scope. I want to determine it in my codes based on client id and set the scope OR just use the application-specific scopes feature that I read in the docs. But it just says about the migration file.

So, I have added the migration for oauth_applications table that adds the extra field 'scopes'. I want to know how I can enable it. Is there some sort of flag? Will it just automatically determine the scope? If it's the latter, it's not working for me. A blank scope just gets inserted in the oauth_access_tokens.

Thanks!

**Comment by tute** [comment]
https://github.com/doorkeeper-gem/doorkeeper/pull/469 implements application specific scopes. Those act as another filter of what scopes are allowed from clients (but doesn't pre-set scopes according to which application is being served).

Also, this open PR might be related with your issue: https://github.com/doorkeeper-gem/doorkeeper/pull/577.

**Comment by antek-drzewiecki** [comment]
@katpadi I doubt wine_bouncer has proper support for dynamic scopes. Since all endpoints are defined with what scopes they require.. If it is not something related to endpoints it should work fine. 

I could not find an example how to use application specific scopes. If there is some example I am gladly to assist you to find out if this is an wine_bouncer related issue as well.
