### ISSUE TITLE
Refresh token not having a TTL, is this a vulnerability?

### ISSUE THREAD

**Issue by dan-corneanu** [doorkeeper-gem/doorkeeper#643]
Hi,
I know that the specification says that *refresh tokens do not have a TTL*. I am just curios, isn't this presenting some security risks? What is actually the difference between a *refresh token* and an *access token*. If an access token can get compromised then so can the refresh token too. How is using a refresh token making things more secure?

Would a request to refresh a token require the client to present some extra credentials?

I've did a test using the *Resource Owner Credential* grant and was surprised to see that I can get a new token just by presenting the refresh token. Is this safe ?

```
curl -F grant_type=password -F username=dan.corneanu@xxxxxx.co.nz \
 -F password=xxxxxxx \
-X POST http://localhost:3000/oauth/token

  { 
    "access_token":"20cc6c995cbe5dae7c8c6a7e51f8d74a708a36b57511987f4a3614a73f5610dc",
    "token_type":"bearer",
    "expires_in":599,
    "refresh_token":"52589cf585b6a5bccbdabc751890e9835c96fef2e0a5af6f6c325747a98b03d3",
    "scope":"public"
    }

    curl -F grant_type=refresh_token \
 -H "Authorization: Bearer 20cc6c995cbe5dae7c8c6a7e51f8d74a708a36b57511987f4a3614a73f5610dc" \
 -X POST http://localhost:3000/oauth/token

    {
      "access_token":"0959af42209b9d216973f34b7fbe92243925188b986f60619fa148832685cc56",
      "token_type":"bearer",
      "expires_in":599,
      "refresh_token":"31b41fdf844f1b1bac9d7064314575cfcf9a4e3d92138ade62ea3103b2c1cd42",
      "scope":"investor"
    }
```

Can someone please shed some light on these issues?

**Comment by tute** [comment]
Will appreciate @diegode, @pose and @homakov's input here.

**Comment by homakov** [comment]
`How is using a refresh token making things more secure?`

It doesn't, it's a popular myth. refresh token is just key "id" and is ugly design of oauth. When access tokens expire you need to prove you have app secret with refreshing token request. 

It would be much better if oauth had app_secret_proof technique like in facebook by default.

**Comment by pose** [comment]
I agree with @homakov. Also, @jaredhanson might have something to add about this as well.

**Comment by dan-corneanu** [comment]
@homakov indeed, the specification states that 
> Because refresh tokens are typically long-lasting credentials used to
   request additional access tokens, the refresh token is bound to the
   client to which it was issued.  If the client type is confidential or
   the client was issued client credentials (or assigned other
   authentication requirements), the client MUST authenticate with the
   authorization server as described in Section 3.2.1.
> - section *6.  Refreshing an Access Token*

which makes sense if you have a client that can securely store a secrete (or provide other means to get the resource owner credentials). However, my client is a single page JavaScript application that is accessing an OAuth 2.0 protected API using the *Resource Owner Password Credentials Grant* 

What is my best option in this scenario:
1. use a longer TTL for the access token and drop the refresh token altogether
2. use a refresh token and every time when a refresh is required, prompt the user to provide the credentials again (annoying user experience)
3. securely store the client secrete in Java Script (is this possible? )

Any input is highly appreciated.

@tute since this is not a bug, can you mark it with a Question label or something similar? If this is not the right place to discuss it, please let me know (however, I am using doorkeeper to protect the APIs and thought that the people who have implemented it would be in the best position to give advice).

**Comment by bpieck** [comment]
No, you never will be able to store client secret securely in javascript. That's the reason, why oauth specifications always says: Only use implicit grant flow in this kind of applications!
https://tools.ietf.org/html/rfc6749#section-1.3.2

**Comment by dan-corneanu** [comment]
@bpieck I have decide to use the *Resource Owner Password Credentials* grant for the following reasons:
1. the Java Script application is developed, delivered, operated and owned by the same company that provides the API. It is considered a *highly privileged application* that will replace an existing old style, request/response web application UI
2. The *Implicit* grant flow does not issue a refresh token which means I'll have to use a rather long TTL for the access token
3. The *Implicit* grant flow exposes the access token in the redirect link. The user can bookmark that link or use the computer in a public space where someone can get a hand on it (it will be visible in the browser's navigation bar). Since the TTL is long, there might be a risk of someone else using this access token at a later stage. My client is very concerned about this issue.

Is there something else that I might have missed or something else to consider ?

**Comment by bpieck** [comment]
If you are using a secret in a javascript frontend, anyone else can just get tokens, whenever they want, too. So your client's concern should be the same for your approach, as for the implicit grant. They both enable the user to do stuff with their tokens from own apps. Worse: The long living token identifies them as theyself, since they needed to identify themself to get it. The open secrets enables them to do some nasty stuff, that identifies them as your javascript app and the user, whoever they lured to their own nasty page.

**Comment by tute** [comment]
Closing this issue as it's not a bug in doorkeeper. Please reopen if you think doorkeeper can do a better job in regards with this issue.
Thanks!
