### ISSUE TITLE
use_refresh_token customized

### ISSUE THREAD

**Issue by kiomac** [doorkeeper-gem/doorkeeper#646]
It should be possible to use or not use the refresh token accordingly.

Use case: In a service-to-service basis the client could use a JWT Assertion to request the access token. This token can have 1 hour TTL, with no refresh token. Meaning that he would need to use JWT assertion each time the token expires. At the same time, other clients using credentials may have a refresh token available.

Will it be ok to do something like `custom_access_token_expires_in` with a block call? Say, `custom_use_refresh_token`.

**Comment by tute** [comment]
I'm open to that. Different than the existing case, I wouldn't add the `custom_` prefix; I would check in code if the object responds to `#call` and if so call it, otherwise use it directly.

**Comment by thornbird** [comment]
@kiomac You raised this because you want to support concurrency of requesting refresh token?
E.g. multiple requests, with one same expired token, sent at the same time.

There will be case that server generated new access token already, but still, some requests are using old token?

Thanks!

**Comment by tute** [comment]
https://github.com/doorkeeper-gem/doorkeeper/pull/769 is related with this. I think there are no further actionable items in this issue, so I'll close it. We can reopen whenever needed. Thanks!

**Comment by thatsmydoing** [comment]
Hi, I'm interested in the feature originally proposed in this issue. Being able to customize whether or not to provide a refresh token given some conditions. I took a look at #769 and it wasn't entirely obvious to me how to use that for this case. Is it possible with the current doorkeeper?
