### ISSUE TITLE
Feature Request: Sequel ORM

### ISSUE THREAD

**Issue by xtagon** [doorkeeper-gem/doorkeeper#647]
Hi,

It seems Doorkeeper does not have an adapter for [Sequel](http://sequel.jeremyevans.net/) yet, but I would very much like to use Doorkeeper in a Rails app that uses Sequel, in which ActiveRecord is unavailable. Sequel supports most of the same functionality that ActiveRecord does, so I'm sure this is possible, but I'm not sure where to begin.

Would anyone be interested in providing a Sequel ORM adapter for Doorkeeper, or at least help to hold my hand while I fumble through making the adapter myself?

I took a look at the files in `lib/doorkeeper/orm/...` but being unfamiliar with Doorkeeper's source, I'm not clear on how it all works and ties together. Any pointers? I would really appreciate it.

:smile:

**Comment by tute** [comment]
I'm very much interested. There's a PR in https://github.com/doorkeeper-gem/doorkeeper/pull/281.

And there's a https://github.com/doorkeeper-gem/doorkeeper-orms project too, which I'd love to finish up integrating with doorkeeper.

@xtagon in an ideal world ORMs would work as plugins from their own repository, but I would merge a PR that incorporates sequel support into doorkeeper, provided it's reasonably encapsulated and it doesn't add significant complexity to existing files in the project.

Thanks for your input!

**Comment by xtagon** [comment]
@tute Ah, that one didn't come up in my issue search. Thank you! I'll take a look at what has been done and find ways to contribute to the effort.

**Comment by tute** [comment]
You might want to work on this after we make https://github.com/doorkeeper-gem/doorkeeper-orms/pull/2 work. :heart:

**Comment by xtagon** [comment]
That sounds like a good idea. Subscribed.

**Comment by tute** [comment]
PR merged! https://github.com/doorkeeper-gem/doorkeeper-mongodb is good basis for the next ORM extension to doorkeeper. :+1:

**Comment by xtagon** [comment]
Congrats, that's awesome. I'll play around with it when I get a chance.

**Comment by xtagon** [comment]
Didn't do anything interesting to it yet but you can keep a watch here: https://github.com/xtagon/doorkeeper-sequel

**Comment by nbulaj** [comment]
Take a look at the [doorkeeper-sequel](https://github.com/nbulaj/doorkeeper-sequel) extension on which I am currently working. It is not 100% tested yet, but I'm working on it. If someone wants to help - you are welcome.

**Comment by nbulaj** [comment]
Take a look at my [doorkeeper-sequel extension](https://github.com/nbulaj/doorkeeper-sequel). It is 100% compatible with Doorkeeper 4.0.0 and you can use it.

@tute you can add this to the Readme if you wish to let people know about the Doorkeeper Sequel ORM.
