### ISSUE TITLE
Doorkeeper overrides I18n.fallbacks

### ISSUE THREAD

**Issue by nvloff** [doorkeeper-gem/doorkeeper#649]
Doorkeeper 2.2.0 ( #627  ) broke the custom I18n.fallbacks we set in our app. We worked around that by having the fallbacks set in rails's `after_initialize`.

I don't think gems should change application's I18n fallbacks, it's just breaking things :)

**Comment by jasl** [comment]
The current way is working well on our app, but could you describe more details? and the codes. actually I don't know how to test this.

**Comment by tute** [comment]
We should append to the config, rather than set it.

**Comment by jasl** [comment]
you're right, but I thought the `app.config.i18n.fallbacks = [:en]` is only affect doorkeeper originally, let's me check the doc.

**Comment by tute** [comment]
Closing in favor of PR. Thank you both!
