### ISSUE TITLE
check_requirements! aborting the scope migration

### ISSUE THREAD

**Issue by repinel** [doorkeeper-gem/doorkeeper#653]
I have tested this with Rails 3.2. I upgraded Doorkeeper from `0.6.7` to `2.2.1` and I am not being able to run the migration that is suppose to create add the `scopes` column to `oauth_applications`. 

Since #628, `Doorkeeper::Orm::ActiveRecord.check_requirements!` was introduced and an error is raised when the ActiveRecord connection is available, the table exist and attribute `scopes` is found.

Should we consider changing the code to at least check if there are pending migrations? Any other ideas?

**Comment by tute** [comment]
I'm not opposed to a pending migrations task. Or a better error message that spits in standard output the needed migration: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/generators/doorkeeper/templates/add_scopes_to_oauth_applications.rb.

**Comment by repinel** [comment]
Checking the pending migrations could be a challenge to support multiples Rails versions. With Rails >= 4 this can be easily accomplished using the `ActiveRecord::Migrator.needs_migration?`, but previous versions require a little bit more code.

One simpler way might be to check the Rake tasks like `defined?(Rake) && Rake.application.top_level_tasks.include?(‘db:migrate’)`

I am inclined to favor the task checking. Any thoughts?

**Comment by tute** [comment]
Even simpler: do a `File.read` of `https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/generators/doorkeeper/templates/add_scopes_to_oauth_applications.rb`, and print it to standard output in https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/orm/active_record.rb#L27-L33. That's reliable across Rails, Ruby and OS versions! :)

**Comment by repinel** [comment]
Added the PR. Let me know if it's according to what you suggested so I can update the CHANGELOG.

**Comment by tute** [comment]
Great, thank you! Continuing conversation there.
