### ISSUE TITLE
strange revoke

### ISSUE THREAD

**Issue by bpieck** [doorkeeper-gem/doorkeeper#655]
I hope not to waste your time. Just recognized something a little strange.
When I understand revokation correctly (https://tools.ietf.org/html/rfc7009): 
We should access a request with client credentials as Authorization header (so Basic) and send token in body as parameter. The oauth server itself will verify, that the client identified correctly and client_id fits token's application.uuid.
But in doorkeeper it seems to be:
I set Authorization header Bearer with token and send token in body additionally - and it will just be accepted.

I just recognized that it seem not to make sense, to send this token twice.
When I tried to send client credentials via Authorization header it just did not revoke the token.

Do I misunderstand this - or is

**Comment by bpieck** [comment]
Just to show you, how I fixed that on my side:

````
    def revoke
      not_option_cors_headers
      revoke_token if server.credentials && token_param && token_match_credentials?
      render json: {}, status: 200
    end

    private

    def token_match_credentials?
      token.application && server.credentials.uid == token.application.uid && server.credentials.secret == token.application.secret
    end

    def revoke_token
      if token && doorkeeper_token.same_credential?(token)
        token.revoke
        true
      else
        false
      end
    end

    def token
      @token ||= AccessToken.by_token(token_param) || AccessToken.by_refresh_token(token_param)
    end

    def token_param
      @token_param ||= request.POST['token']
    end
````

**Comment by tute** [comment]
The spec (and our `TokensController`) don't expect both tokens to always be the same. A client application might be revoking a token while authorizing with another one.

Also, the credentials check in the model checks for resource owners, while your version does not.

That said, your code looks better than what is in current master. If you'd like to submit a PR with a refactor without changing behavior I will gratefully merge it.

Thank you!
