### ISSUE TITLE
Multiple urls validation errors exception

### ISSUE THREAD

**Issue by godsent** [doorkeeper-gem/doorkeeper#656]
Hi. When I tried to create \ edit an oauth application and submit more then one invalid url there is an exception "undefined method `join' for "<span class=\"help-block\">Must be an absolute uri.</span>":ActiveSupport::SafeBuffer".
It happens because of this line - https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/helpers/doorkeeper/dashboard_helper.rb#L8. I guess there should be just join, without reduce.

**Comment by tute** [comment]
Possibly, let's discuss over a PR and see the spec difference? Thanks for reporting!

**Comment by godsent** [comment]
PR is created - https://github.com/doorkeeper-gem/doorkeeper/pull/657

**Comment by tute** [comment]
Thanks! Closing in favor of PR.
