### ISSUE TITLE
implement rotateable secret

### ISSUE THREAD

**Issue by trungpham** [doorkeeper-gem/doorkeeper#659]
Right now if we change the application's secret, then all the existing api call will briefly be broken until all the active servers have been updated to use the new secret.

We should pull the secret column out of the applications table, and use has_many association, so we can have multiple active secret. This way, the application owner can explicitly delete the old secret after all the servers have been migrated to use the new secret.

**Comment by tute** [comment]
This feature is outside the scope of doorkeeper. Thanks!
