### ISSUE TITLE
Possible to create client without specifying redirect_uri?

### ISSUE THREAD

**Issue by bhritchie** [doorkeeper-gem/doorkeeper#660]
I'm trying to integrate a Rails app with Zapier using Doorkeeper. Zapier wants me to provide the client id, secret etc, but doesn't want to provide me with a redirect_uri - instead it seems that they want to pass this as part of the authorization call: https://zapier.com/developer/documentation/oauth-v2/

However the redirect_uri seems to be required for doorkeep to generate a set of client credentials in the first place.

Is there a way to satisfy both Doorkeeper and Zapier?

Thanks in advance.

**Comment by tute** [comment]
Quoting from the doc you link:

> 1. Redirecting the User to Your App
>
> We'll redirect the user to an authorize_url (provided by you), along with a query string which contains a redirect_uri (provided by us), scope (optional, provided by you) and client_id (provided by you).
>
> `302 <authorize_url>?client_id=<client_id>&scope=<scope>&redirect_uri=https://zapier.com/dashboard/auth/oauth/return/AppIDAPI/`

So their `redirect_uri` is `https://zapier.com/dashboard/auth/oauth/return/:AppIDAPI/`. Did you try that?

**Comment by bhritchie** [comment]
That didn't work, but I used it as a dummy and they gave me a redirect_uri afterwards. Since iit seems that I'm able to just change the redirect_uri parameter for an application without affecting the credentials, I guess I'm fine. Thanks, and sorry to trouble you!

**Comment by todddickerson** [comment]
@bhritchie did you end up just hard coding the redirect_uri or find a way to make it dynamic based on the passed in redirect_uri param?

**Comment by bhritchie** [comment]
@todddickerson I don't really remember anymore and I no longer have access to that codebase, but I think I just manually changed the redirect_uri in the doorkeeper config for Zapier once it was connected and had provided me a real uri.

**Comment by todddickerson** [comment]
@bhritchie - Thanks, looks like what we're going to do as well, if it changes we'll just add another oauth app
