### ISSUE TITLE
Reuse access tokens for the client_credentials grant type

### ISSUE THREAD

**Issue by gilbertquri** [doorkeeper-gem/doorkeeper#661]
Doorkeeper does not seem to reuse access tokens for the client_credentials grant type in any case. Is this intentional?

**Comment by tute** [comment]
This sounds like a bug, not intentional for sure.

**Comment by vovimayhem** [comment]
I read somewhere in this Issue Tracker and in the RFC specs that client credential tokens should not be allowed to refresh... let's validate if that's true first.

**Comment by tute** [comment]
> I think I read somewhere in this Issue Tracker and in the RFC specs that client credential tokens should not be allowed to refresh... I could be remembering it wrong, but let's validate if that's true first.

Please let us know where did you read this @vovimayhem, or the reasons behind that assertion that you remember. Thank you!

**Comment by vovimayhem** [comment]
@tute searched, but can't find it. :( I'll give it an eye in the RFC specs

**Comment by jimmykarily** [comment]
Guys any progress on this?

**Comment by jimmykarily** [comment]
@vovimayhem you probably refer to [this](https://tools.ietf.org/html/rfc6749#section-4.4.3). I don't think the original problem is a missing refresh token though. My problem is that when I request an access token for a client, even if a valid and not expired one exists, a new one is generated and returned. This is not a problem if the client can store the token and reuse it until it expires, but in my case the token is used from a short lived client (a docker container) and every time the container is launched the token generating process starts again resulting in many valid tokens for the same client. I can't find anything in the RFC that justifies this behavior. Still, I might missed it.

**Comment by jimmykarily** [comment]
I created a [Pull Request](https://github.com/jimmykarily/doorkeeper/pull/1) with what seems to fix the issue, at least on my project. I can change the base branch to the original gem's master if you prefer to keep the conversation on this repo (I just didn't want to create a PR until it's ready).

**Comment by tute** [comment]
> I created a Pull Request with what seems to fix the issue, at least on my project. I can change the base branch to the original gem's master if you prefer to keep the conversation on this repo (I just didn't want to create a PR until it's ready).

@jimmykarily that looks good to me, feel free to complete the tests and open up a PR here. Thank you!

**Comment by jimmykarily** [comment]
I will try to get it ready in the next couple of days. I remember having some trouble with the tests. I will ask for help if I get stuck.

**Comment by tute** [comment]
Closing in favor of PR: https://github.com/doorkeeper-gem/doorkeeper/pull/736. Thank you all!
