### ISSUE TITLE
Feature Request: Display Built-In Unauthorized 

### ISSUE THREAD

**Issue by edmondchui** [doorkeeper-gem/doorkeeper#664]
Per the wiki page [Customizing the response body when unauthorized](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-the-response-body-when-unauthorized), we can customize the respond body overwriting the method ```doorkeeper_unauthorized_render_options```.

However, it is currently impossible to display the three different reasons of unauthorized: ```revoked```, ```expired```, ```unknown``` which is accessible via the object ```OAuth::InvalidTokenResponse```.

It would be great if we can modify the definition of ```doorkeeper_unauthorized_render_options``` to passing the ```error``` object inside the method ```doorkeeper_render_error_with``` via the method ```doorkeeper_render_options``` to ```doorkeeper_unauthorized_render_options```:

```ruby
      def doorkeeper_render_error_with(error)
        options = doorkeeper_render_options(error) || {}
        if options.blank?
          head error.status
        else
          options[:status] = error.status
          options[:layout] = false if options[:layout].nil?
          render options
        end
      end
```

```ruby
      def doorkeeper_render_options(error)
        if doorkeeper_invalid_token_response?
          doorkeeper_unauthorized_render_options(error)
        else
          doorkeeper_forbidden_render_options(error)
        end
      end
```

**Comment by tute** [comment]
I'm not against this. How exactly would you use it? Would it still comply with the spec https://tools.ietf.org/html/rfc6749#section-5.2?

**Comment by edmondchui** [comment]
Yes, for the ```error_description``` field in that [section 5.2](https://tools.ietf.org/html/rfc6749#section-5.2) of the RFC.

**Comment by tute** [comment]
I feel positive about it but I'm not entirely sure. Would like to see sample code, and see if it's backwards compatible. If it looks all good we can merge a nice PR!

**Comment by edmondchui** [comment]
I actually copy and paste those modifications from my overwrite of the doorkeeper code. Sorry I don't have time to put up a crisp sample code for that.

If you have existing test suites we can simply run against them.

**Comment by tute** [comment]
It's really good timing. Because we didn't place any arguments on the template methods this would be a backwards incompatible change, but we are about to release version 3, so let's go ahead with a PR!

**Comment by tute** [comment]
Closing in favor of PR.
