### ISSUE TITLE
Allow specifying/limiting flows per application

### ISSUE THREAD

**Issue by lewislambert** [doorkeeper-gem/doorkeeper#672]
Hi,

Has anyone considered the ability to specify grant flows per application? The main driver behind this would be to allow anyone who creates an application to just use the `authorization_code` or `client_credentials` grant types but perhaps for a providers own native application or other trusted providers, allow the ability to use `password` grant flow.

I've not seen this mentioned in any other previous issues but I have seen this in some nodejs OAuth2 provider frameworks.

Just wondered what peoples thoughts were on this?

**Comment by tute** [comment]
> or other trusted providers

How do you verify it is your trusted app?

**Comment by lewislambert** [comment]
@tute I guess that would be out of scope for Doorkeeper and that would be for the OAuth service implementer to decide (in my case, me).

An example would be Twitter, so their native mobile app, users login with Username and Password, not redirected to their site in a browser to authorize. This is using the password grant, but naturally Twitter would not want anyone who creates a developer app to use this method.

It would be nice to limit the grant types per application.

**Comment by jasl** [comment]
agree.

**Comment by tute** [comment]
> I guess that would be out of scope for Doorkeeper and that would be for the OAuth service implementer to decide (in my case, me).

I'm still interested in your case too. How exactly would it work? It's hard for me to imagine now how is it possible to authenticate client applications in certain flows, and if it is not possible (or at least to many developers), then I fear such a feature would give a false feeling of security.

**Comment by lewislambert** [comment]
So let's say for example I have a central app which is the OAuth provider, all user accounts exist on this server and then I also have several other web-apps on different domains providing functionality but utilise the API from the OAuth server. As I own the additional apps, I know that I can be trusted to allow users to provide their username and password and use the password flow to exchange for an access token rather than use the authorisation code flow.

However, I don't want third parties to use the password flow as it would pose a security risk because they could possibly cache user credentials, whereas an access token could simple be provoked.

At the moment Doorkeeper provides functionality to specify allowable flows on a global level, so if I was to enable the password flow in order for my own apps to utilise, then other developers could do the same, which I wouldn't want.

Ideally there would be something like an additional database column in the applications table which holds which flows are allowed, then when processing the authorisation/access actions, the flow type requested could be checked against what is stored in the database.

This is basically how Twitter and Facebooks native mobile apps work, you enter your username and password direct using the password flow, but as a developer I would not be able to register an application and use the password flow because I am not considered a trusted/enterprise/partner developer.

This is kind of covered under section 2.1 of the OAuth 2 specification.

**Comment by tute** [comment]
I understand the feature request, but I believe the implementation is technically hard (if not entirely impossible). The problem is that this feature implies that there is a secure way to authenticate applications (this is _my_ application, and not a malicious one). See this answer for more context: https://stackoverflow.com/questions/6190381/how-to-keep-the-client-credentials-confidential-while-using-oauth2s-resource-o/6217429#6217429.

If we find the way to implement this, and we can prove it's secure against known attack vectors, I'm all in for this.

**Comment by lewislambert** [comment]
Okay I see your concern now. I think how the credentials themselves are kept secure is out of scope for Doorkeeper itself.

What I was think was something like Doorkeeper sets a configurable default set of grant types when someone registers and application, for example, client credentials and authorisation code  (the default in Doorkeeper now). This should not be customisable by users registering applications, but as an Administrator of the OAuth provider, you could specific additional flow types for specific applications. It would of course then be up to the owner of the OAuth server to determine which application can have which flows and why.

This way, Doorkeeper remains as secure as it is now but allows more flexibility to developers using Doorkeeper to protect their API's. In theory it should only require an additional column to store the allowed grants for the application and some additional logic in the controllers when an authorisation and access token request is made.

**Comment by jasl** [comment]
If you want a customize flow, implement as a simple API is the better and fastest way that you can focus on your business.

e.g. we have a flow that exchange the site's access_token by third parties' access token, so we implements like:
```
class AccessTokensController
  def exchange
    valid_third_party_token?(params[:provider], params[:access_token])
    user = User.find_or_create_by_3rd_party(params[:provider], params[:access_token])
    token = Doorkeeper::AccessToken.find_or_create_for(app,
                                                         user.id,
                                                         app.scopes,
                                                         Doorkeeper.configuration.access_token_expires_in,
                                                         Doorkeeper.configuration.refresh_token_enabled?)

      render json: {access_token: token.token}
  end
end
```

**Comment by lewislambert** [comment]
@jasl I'm not wanting a custom flow, it is just a case of more granual control of what grant types can be used by third-party developers.

**Comment by lewislambert** [comment]
I've not had chance to have a detailed look at the code but I suspect the changes would need to be made to `doorkeeper/lib/doorkeeper/request.rb`.

    def get_strategy(strategy, available)
      fail Errors::MissingRequestStrategy unless strategy.present?
      fail NameError unless available.include?(strategy.to_s)
      "Doorkeeper::Request::#{strategy.to_s.camelize}".constantize
    end

Simply checking strtegies against the application should suffice. It might take me a while to become familiar with the internal code, but I could probably figure it out and come up with a pull request, if people would find this useful? If not I can probably just override this method in my application.

I have however seen other OAuth2 provider frameworks provide this option in other languages, but I'm restricted to using Ruby for the current project I'm working on though.

**Comment by tute** [comment]
> This way, Doorkeeper remains as secure as it is now but allows more flexibility to developers using Doorkeeper to protect their API's. In theory it should only require an additional column to store the allowed grants for the application and some additional logic in the controllers when an authorisation and access token request is made.

This doesn't keep it secure, because there's no known way to identify clients. I don't want to add insecure options to the project. If someone really needs it, they should route around it, hopefully finding these discussions to make sure they are aware of the potential risks. Or if they know of secure ways to accomplish this, we should indeed integrate.

But the question continues to be unanswered: how exactly do you authenticate applications? If there is a good way, it should probably belong in doorkeeper (and the OAuth spec).

**Comment by lewislambert** [comment]
I think I need to explain this better and possibly with an example. The verification of the applications is not a programmatic verification but more a human verification. The point is, it should be possible to allow different grant types on a per application basis, how it is determined who can use what grant types should not be something that is determined by Doorkeeper, but the administrator of the OAuth provider.

I will try to provide an example of the coming days if you are happy to keep this issue open, or perhaps we can discuss this further directly at a later date?

**Comment by tute** [comment]
> The verification of the applications is not a programmatic verification but more a human verification.

This is incorrect? A human configuring anything in doorkeeper doesn't change the fact than an app has to be authenticated or not by doorkeeper. When any app asks to use an OAuth endpoint there's software deciding if it is allowed or not, and that software will be doorkeeper (or developer's extensions and monkey patches).

**Comment by lewislambert** [comment]
I think I must not be explaining very well. Yes there is an element whereby Doorkeeper would still authenticate a request. I meant the human factor would be the vetting to assign grant flow types to applications. Sorry if that was confusing.

Doorkeeper determining if an application can use a specific grant flow type, I'm not sure how you feel this poses any risk? It is not really much more complicated than validating scopes.

As an example, if I register an application and Doorkeeper is configured with the default grant flow types (authorisation code and client credentials) but I make a request and try to use the password type, it will fail because Doorkeeper knows that grant type is not enabled. So why can that process not be abstracted to be per application rather than globally set in the configuration?

**Comment by tute** [comment]
If there's two applications: one with flow A and other with flow B. Any application in the planet can use flows A and also B. There is no secure way to perform this comparison.

Please refer to Security Considerations section of the spec: https://tools.ietf.org/html/rfc6749#section-10.

Closing for now, but I will continue answering any questions and comments.

**Comment by lewislambert** [comment]
Happy for you to close down as it's obviously non-critical issue.

Well this what my concern was with the way Doorkeeper works at the moment, if I enable one flow, it is enabled for all.

What are the risks associated with having the allowable flows stored in the database with each application, then upon a request by a client for a specific flow, can this not be checked against what is stored in the database for that particular application?

**Comment by tute** [comment]
> Well this what my concern was with the way Doorkeeper works at the moment, if I enable one flow, it is enabled for all.

This is true regardless of how we implement it.

> Happy for you to close down as it's obviously non-critical issue.

It's not, thankfully. It would be if we implemented this.

> What are the risks associated with having the allowable flows stored in the database with each application, then upon a request by a client for a specific flow, can this not be checked against what is stored in the database for that particular application?

Did you read https://stackoverflow.com/questions/6190381/how-to-keep-the-client-credentials-confidential-while-using-oauth2s-resource-o/6217429#6217429, quoted in the third comment?

**Comment by tute** [comment]
> What are the risks associated with having the allowable flows stored in the database with each application, then upon a request by a client for a specific flow, can this not be checked against what is stored in the database for that particular application?

A more helpful answer is that the information you receive at the provider that identifies the client can't be trusted.

**Comment by lewislambert** [comment]
I'll take a look and do a little more research although this isn't about keeping client credentials secret, it's about validating them on the server. The client keeping their credentials is an entirely different story with its own risks.

**Comment by lewislambert** [comment]
Just as another note. A node equivalent of Doorkeeper which abstracts most of the logic to a model supports the ability to have variable grant types per application.

https://github.com/thomseddon/node-oauth2-server

This might give you some idea of my intentions.

**Comment by groe** [comment]
This would be useful.

I don't think app-specific configurable flows would give a false feeling of security (if there's a comment in the config or a hint in the application form with a warning about it).

App-specific flow whitelists would further *restrict* access, so overall they would improve security. Not by a huge factor, but still. For instance, imagine a scenario where a doorkeeper application had some internal apps that use the *Resource Owner Password Credentials Grant Flow*. Now they want to allow external developers access to their API with the *Authorization Code Grant Flow*. To be clear: The external developers can always use both flows. But it would be much harder to use the password flow (for instance  accidentally) if there's an app-specific whitelist and it does not include that flow.
