### ISSUE TITLE
Client Authorization only skipped when no client_id provided

### ISSUE THREAD

**Issue by Fryie** [doorkeeper-gem/doorkeeper#673]
In my API I disabled client authorization since it makes no sense for us (we're using a JS client, so the client credentials would be public knowledge anyway). 

This works well when no client_id is submitted, so we have no problems with our JS client, but the framework that our iOS app developer uses seems to require client_id and client_secret even for the password ("resource owner etc.", I always forget the exact name) flow. It appears that when such credentials are submitted, Doorkeeper always tries to authorize the client, even when this is disabled in the config.

**Comment by tute** [comment]
To your comment:

> It appears that when such credentials are submitted, Doorkeeper always tries to authorize the client, even when this is disabled in the config.

I quote from [section 4.3.2](http://tools.ietf.org/html/rfc6749#section-4.3.2) of the spec:

> The authorization server MUST: [...] authenticate the client if client authentication is included

---

> In my API I disabled client authorization since it makes no sense for us (we're using a JS client, so the client credentials would be public knowledge anyway).

How exactly did you disable them?

**Comment by Fryie** [comment]
Oh I see. Tbh, I did not read the full OAuth spec. If it really is part of the spec, then I understand that you want Doorkeeper to be compliant. Seems I'd have to take this issue to the provider of the iOS library.

> How exactly did you disable them?
The way it is described here: https://github.com/doorkeeper-gem/doorkeeper/wiki/Skipping-application-authorization

Maybe it would be helpful to include a note that this will not skip client authorization if client credentials are included.

**Comment by tute** [comment]
User authorization step is different from client authentication. Sadly I don't know of more digestible resources to learn the concepts in Omniauth than the spec. Closing, as this is not an issue with doorkeeper.
