### ISSUE TITLE
Have Multiple redirect_uri for same client app

### ISSUE THREAD

**Issue by gaurish** [doorkeeper-gem/doorkeeper#674]
We have a business use-case where same client ID & secret has should a whitelist of redirect_uri(multiple, more than one)

I have searched the docs & it doesn't seem currently its not possible to create multiple redirect_uri. each client can have just one url. 

So wondering, how easy it is to add support for multiple redirect_uri? is this something that's already been done?

**Comment by tute** [comment]
You can do this. In the admin interface for applications, near the textarea for URLs it says "Use one line per URI".
Best!

**Comment by gaurish** [comment]
:heart:  Thank you so much!
