### ISSUE TITLE
Grape helper should pass Doorkeeper headers to error

### ISSUE THREAD

**Issue by djordje** [doorkeeper-gem/doorkeeper#679]
Grape should expose `WWW-Authenticate` header from Doorkeeper.

https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/grape/helpers.rb#L29

Right now:

```rb
error!({ error: error.description }, status_code)
```

Should be:

```rb
error!({ error: error.description }, status_code, error.headers)
```

**Comment by tute** [comment]
Thanks for your report.

* Is this backwards compatible?
* Can you link to the relevant Grape documentation to understand why is this the way to go?
* Can you send a PR for this?

Thank you again!

**Comment by djordje** [comment]
> - Is this backwards compatible?

I've looked to `Grape::DSL::InsideRoute.error!` and method accept 3 params from beginning.

> - Can you link to the relevant Grape documentation to understand why is this the way to go?

From theirs README:

> When raising error!, pass additional headers as arguments.
>
> ```
> error! 'Unauthorized', 401, 'X-Error-Detail' => 'Invalid token.'
> ```

https://github.com/intridea/grape#headers:


> - Can you send a PR for this?

Of course

**Comment by tute** [comment]
Closing in favor of the PR. Please send over relevant information over to that commit message. :+1:
