### ISSUE TITLE
Confusion over `custom_access_token_expires_in` documentation

### ISSUE THREAD

**Issue by jpb** [doorkeeper-gem/doorkeeper#680]
The [generated initializer](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/generators/doorkeeper/templates/initializer.rb#L27-L30) states that `custom_access_token_expires_in` can be used to `Assign a custom TTL for implicit grants`. This does not seem to be the case, as this option is used for all grant types. Also, this lambda is [only evaluated once](https://github.com/doorkeeper-gem/doorkeeper/blob/8b59c77ca2324b747ab0570b47f6d14df62fbcc8/lib/doorkeeper/oauth/authorization/token.rb#L47) which, while it exposes the oauth client to be used to choose a TTL, does not aid towards the goal of setting a different TTL for implicit grants.

It seems like the documentation and actual behaviour are out of sync - which is correct?

Being able to set a low TTL for implicit grants would be valuable given their decreased security.

I am working with version 2.2.1.

**Comment by jpb** [comment]
After digging in more, I realized I was wrong about the `custom_access_token_expires_in` only being called once - this is called for each request.

I noticed the changes on #636 made the parameters to `custom_access_token_expires_in` consistent, but a `PreAuthorization` is never passed to it now. `PreAuthorization#request_type` would provide insight into wether or not the request is a implicit grant or not (if it equals `token`). I know that it is not ideal, but would the maintainers be open to adding a second argument to `custom_access_token_expires_in` that was the `PreAuthorization`, if available.

**Comment by tute** [comment]
The change wouldn't be backwards compatible. Also, it's not always there, what does it mean when it's not there?

Passing in always the `request_type` seems like a cleaner solution, and I would consider such a PR. It would be an additional hash argument, with the `request_type` for now.

**Comment by tute** [comment]
Closing for now, as this is not an issue in doorkeeper nor is it in our short term roadmap. Thank you for reporting!

**Comment by willsu** [comment]
@jpb were you able to find a workaround for setting custom TTLs on tokens issued via an implicit grant? Short of patching the `Doorkeeper::OAuth::Authorization::Token.custom_expiration` method, I can't think of any other reasonable solution. Also, thanks for creating some issue and adding some technical clarity to the problem.

**Comment by willsu** [comment]
FWIW: This is the temporary fix that I implemented to set customer TTLs on tokens acquired via implicit grants. It effectively rolls back the change made in #636 so that we have access to the `Doorkeeper::OAuth::PreAuthorization` instance in the `Doorkeeper::OAuth::Authorization::Token.custom_expiration`:

```
Doorkeeper version: 3.1.0
Rails version: 4.2.7.1
```

```RUBY
# file: config/initializers/doorkeeper_token_override.rb

class Doorkeeper::OAuth::Authorization::Token

  def self.access_token_expires_in(server, pre_auth)
    custom_expiration = server.custom_access_token_expires_in.call(pre_auth)
    if custom_expiration
      custom_expiration
    else
      server.access_token_expires_in
    end
  end

end

```

```RUBY
# file: config/initializers/doorkeeper.rb

  # Assign a custom TTL for implicit grants to 5 minutes.
  custom_access_token_expires_in do |oauth_client|
    if oauth_client.respond_to?(:response_type) && oauth_client.response_type.downcase == "token"
      600
    else
      7200
    end
  end
```

Maybe this will help someone else temporarily ¯\_(ツ)_/¯

@tute It would be great to get more formal doorkeeper configuration support for TTLs specific to tokens acquired via the Implicit Grant type. Thanks for all your hard work on this project! It has been a joy to use :+1:
