### ISSUE TITLE
Only kill refresh tokens until the new exchanged access token has been used

### ISSUE THREAD

**Issue by Neson** [doorkeeper-gem/doorkeeper#687]
For now, refresh token seems to become invalid immediately after they're used to grant an new access token. But clients, especially mobile apps, may lost their connection right after they send the token request, without receiving the response that contains the new access token! If such case happen, the client will lost all authentication credentials (both the access token and refresh token has become invalid) and have to request users to login again.

To resolve this bad user experience, maybe we can change the mechanism of withdrawing refresh tokens - instead of killing it right after its used, but to kill it after the new exchanged access token has been used. So the client may try to get the new access token with that refresh token as many times until they succeed. After the client has successfully get the new access token and use it to send an request to the server, we can then safely throw away the old refresh token for security.

Don't know if there are any plans on such (or similar) features? Or I can try to implement it and send a PR, if an setting to enable such functionality is acceptable :)

**Comment by tute** [comment]
This has been discussed before. I can't remember the issue or PR though. It is a nice to have. I'd like to have that context during this conversation, do you think you can find it?

**Comment by Neson** [comment]
Found #575 and #578 , catching on...

**Comment by tute** [comment]
@Neson if you'd like to take ownership of https://github.com/doorkeeper-gem/doorkeeper/pull/578, please go ahead.

**Comment by pmdeazeta** [comment]
Created this PR https://github.com/doorkeeper-gem/doorkeeper/pull/691 based on  https://github.com/doorkeeper-gem/doorkeeper/pull/578

**Comment by tute** [comment]
Thnk you! Closing in favor of PR.

**Comment by Neson** [comment]
:smile:
