### ISSUE TITLE
Custom Controllers

### ISSUE THREAD

**Issue by confact** [doorkeeper-gem/doorkeeper#695]
Is it anyway to customize the controllers? I want I way to migrate my old api-token to doorkeeper so I need to add a custom api-token to applications for a migration to oauth2 flow.

How can I do this without making some weird stuff?

**Comment by confact** [comment]
Found a way to override by looking randomly in wiki.

**Comment by f3ndot** [comment]
For those who are googling, the wiki page is **[Customizing routes](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-routes)**
