### ISSUE TITLE
Caching applications/access tokens

### ISSUE THREAD

**Issue by anthonator** [doorkeeper-gem/doorkeeper#696]
Is it possible to cache applications/access tokens with something like Redis?

**Comment by tute** [comment]
It's possible, and I don't plan to work on that. If you put together a PR
that works you may be able to create an extension to doorkeeper off of it,
like the mongo ORMs.

**Comment by anthonator** [comment]
Is the doorkeeper-mongo project a good example for this or is there some documentation for creating extensions I can look at?

**Comment by tute** [comment]
No docs yet. :/ doorkeeper-mongodb is the best extension I know as of now.

**Comment by tute** [comment]
Closing as this is not an issue with doorkeeper, happy to continue further discussion in this thread. Thanks!

**Comment by iRonin** [comment]
We're also interested in this however I find the codebase too tightly coupled with ActiveRecord pattern…
