### ISSUE TITLE
Null Refresh Token in Client Credential Flow

### ISSUE THREAD

**Issue by edmondchui** [doorkeeper-gem/doorkeeper#697]
I turn on refresh token by setting ```use_refresh_token``` in ```config/doorkeeper.rb```.

In the Resource Owner Password Credentials Grant flow I do get an access token with refresh token.

In the Client Credential Flow, however, I only get an access token with nil refresh token.

I look at the code and see the flowing line is causing this behavior:

https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/client_credentials/issuer.rb#L32

```ruby
        def create_token(client, scopes, creator)
          ttl = Authorization::Token.access_token_expires_in(@server, client)

          creator.call(
            client,
            scopes,
-->         use_refresh_token: false,
            expires_in: ttl
          )
        end
```

Is that intentional or a bug?

Thanks,
Edmond

**Comment by tute** [comment]
From section 4.4.3 for Client Credentials Grant (https://tools.ietf.org/html/rfc6749#section-4.4.3):

> A refresh token SHOULD NOT be included

I wish this was clearer in code. Thanks for your question.

**Comment by edmondchui** [comment]
Thanks for the explanation, @tute
