### ISSUE TITLE
Set Application Id to token in assertion grant flow

### ISSUE THREAD

**Issue by StarWar** [doorkeeper-gem/doorkeeper#698]
Currently I'm using following code to generate access_token from assertion using assertion grant flow

``` ruby
resource_owner_from_assertion do
    User.from_fb_access_token(params[:assertion]) if params[:assertion]
end
```

And this creates access_token without providing client_id and client_secret. I want to allow only valid applications to do so. With current solution anybody can access a new token with any fb access token.

It gives an access_token where application_id is nil, I want to set the application_id.

**Comment by tute** [comment]
Closing as duplicate of https://github.com/doorkeeper-gem/doorkeeper/issues/699.
