### ISSUE TITLE
OAuth 2.0 Token Introspection

### ISSUE THREAD

**Issue by willsu** [doorkeeper-gem/doorkeeper#700]
Greetings!

Thanks for the wonderful library. It has been a great help in setting up an OAuth2 Authorization Server.

I was wondering if you had any plans of supporting the 'OAuth 2.0 Token Introspection' Specification:
https://tools.ietf.org/html/draft-ietf-oauth-introspection-04

Is this support this functionality something on your radar?

Thanks a lot.

-- Will

**Comment by tute** [comment]
Hi @willsu. I am interested in making doorkeeper easy to extend. I welcome a plugin that extends doorkeeper, as https://github.com/doorkeeper-gem/doorkeeper-mongodb does. If whoever builds it needs any help or change in doorkeeper "main", I will be happy to accommodate that.
Thanks for your question!

**Comment by tute** [comment]
Closing this for now, as it's not an issue/feature that belongs in this repo. Again, happy to work with whoever starts the satellite project. Thanks!
