### ISSUE TITLE
`attr_accessible` deprecation exception

### ISSUE THREAD

**Issue by drn** [doorkeeper-gem/doorkeeper#701]
We updated to doorkeeper `2.2.2` from `2.2.1` and we're running into the following issue in our CI builds now:

```
`attr_accessible` is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add `protected_attributes` to your Gemfile to use old one.
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/activemodel-4.0.12/lib/active_model/deprecated_mass_assignment_security.rb:14:in `attr_accessible'
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/doorkeeper-2.2.2/lib/doorkeeper/models/access_grant_mixin.rb:16:in `block in <module:AccessGrantMixin>'
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/concern.rb:114:in `class_eval'
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.12/lib/active_support/concern.rb:114:in `append_features'
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/doorkeeper-2.2.2/lib/doorkeeper/orm/active_record/access_grant.rb:3:in `include'
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/doorkeeper-2.2.2/lib/doorkeeper/orm/active_record/access_grant.rb:3:in `<class:AccessGrant>'
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/doorkeeper-2.2.2/lib/doorkeeper/orm/active_record/access_grant.rb:2:in `<module:Doorkeeper>'
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/doorkeeper-2.2.2/lib/doorkeeper/orm/active_record/access_grant.rb:1:in `<top (required)>'
/home/ubuntu/thanx-core/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
...
```

I traced it back to this commit - https://github.com/doorkeeper-gem/doorkeeper/commit/c3d1a8318027b1ec5d8665511cf448b2ee45b73a

Any reason why this was added? Can it be reverted?

If it's helpful, I can dig into why `respond_to?(:attr_accessible)` is returning true in our project

**Comment by tute** [comment]
Argh, somewhere in merit gem there is a PR where it explains where is this condition returning true when not expected. I think Rails does define the method to be able to send an error message.
Are you in Rails 4.0?

**Comment by drn** [comment]
Thanks for checking this out. @tute - yup, the app that raised that exception is on Rails 4.0.12

**Comment by tute** [comment]
Rails 4.0 is EOL'd. As much as you don't upgrade Rails, I suggest not to upgrade doorkeeper for now.
Sorry for the change.

**Comment by drn** [comment]
Fun. It's on the docket to upgrade Rails anyways - we'll lock doorkeeper for now. Thanks for the info!
