### ISSUE TITLE
Index on "index_oauth_access_tokens_on_token" fails on Postgres

### ISSUE THREAD

**Issue by qnm** [doorkeeper-gem/doorkeeper#703]
Hi,

I have a recent installation of Doorkeeper, `2.2.1`, which we're running with Postgres 9.4.

I have 89 entries in the `oauth_access_tokens` table.

```
identity-production=> select count(*) from oauth_access_tokens;
 count
-------
    89
(1 row)
```

When a user creates an oauth token, the following error is being generated by Postgres:

```
ERROR: index row size [NUMBER] exceeds maximum [NUMBER] for index "index_oauth_access_tokens_on_token" HINT: Values larger than [NUMBER]/[NUMBER] of a buffer page cannot be indexed. Consider a function index of an MD5 hash of the value, or use full text indexing. 
```

My table is defined as:

```
identity-production=> \d oauth_access_tokens
                                         Table "public.oauth_access_tokens"
      Column       |            Type             |                            Modifiers
-------------------+-----------------------------+------------------------------------------------------------------
 id                | integer                     | not null default nextval('oauth_access_tokens_id_seq'::regclass)
 resource_owner_id | integer                     |
 application_id    | integer                     |
 token             | character varying           | not null
 refresh_token     | character varying           |
 expires_in        | integer                     |
 revoked_at        | timestamp without time zone |
 created_at        | timestamp without time zone | not null
 scopes            | character varying           |
Indexes:
    "oauth_access_tokens_pkey" PRIMARY KEY, btree (id)
    "index_oauth_access_tokens_on_refresh_token" UNIQUE, btree (refresh_token)
    "index_oauth_access_tokens_on_token" UNIQUE, btree (token)
    "index_oauth_access_tokens_on_resource_owner_id" btree (resource_owner_id)
```
The error seems to occur due to the btree index used on `token`, as [btree indexes can't handle data with more that 2713 bytes](http://dba.stackexchange.com/questions/25138/index-max-row-size-error).

I've "fixed" the problem (for some values of fixed) by removing the `index_oauth_access_tokens_on_refresh_token` index. For my use case, this is acceptable.

I'm unsure how to resolve this, beyond creating a specific migration for Postgres with a hashing function that avoids this limit.

Any help is appreciated.

**Comment by tute** [comment]
A PR modifying the indexes to be MD5 hash functions is welcome. Thanks for your report!

**Comment by qnm** [comment]
@tute I think this could be implemented as a Rake test, as the implementation is Postgres specific, and I wouldn't want to pollute the migration with pg-specific conditions.

Do you agree, or have you a better way to manage pg-specific migrations?

**Comment by tute** [comment]
You are right. I would add it to the relevant wiki pages or projects as docs. I assume you are using JWT tokens, and that is why they are bigger than allowed?

**Comment by qnm** [comment]
@tute Spot on - these are JWT tokens.I'll put something together early next week.

**Comment by qnm** [comment]
@tute I've dropped the doc here: https://github.com/doorkeeper-gem/doorkeeper/wiki/Postgres-Error:-index-row-size-%5BNUMBER%5D-exceeds-maximum-%5BNUMBER%5D-for-index-%22index_oauth_access_tokens_on_token%22

Is there a more suitable place for the info?

**Comment by tute** [comment]
That is great, I just updated the title. Thank you for documenting this! :heart:
