### ISSUE TITLE
Misleading example code

### ISSUE THREAD

**Issue by jscheid** [doorkeeper-gem/doorkeeper#705]
Hi,

On [this page](https://github.com/doorkeeper-gem/doorkeeper/wiki/using-resource-owner-password-credentials-flow) you offer the following example code:

```ruby
Doorkeeper.configure do
  resource_owner_from_credentials do |routes|
    u = User.find_for_database_authentication(:email => params[:username])
    u if u && u.valid_password?(params[:password])
  end
end
```

However this code will skip the Lockable strategy (if configured). I believe this code is better:

```ruby
u if u && u.valid_for_authentication? { u.valid_password?(params[:password]) }
```

Otherwise the following code is never executed: https://github.com/plataformatec/devise/blob/1a0192201b317d3f1bac88f5c5b4926d527b1b39/lib/devise/models/lockable.rb#L89-L111

**Comment by tute** [comment]
Thanks! Updated: https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Resource-Owner-Password-Credentials-flow.

**Comment by oney** [comment]
How to customize the failure error message?

**Comment by GeminPatel** [comment]
since the last comments, the code has changed. And I think lockable is broken again. Failed attempts reset has moved out to hook, https://github.com/plataformatec/devise/blob/715192a7709a4c02127afb067e66230061b82cf2/lib/devise/hooks/lockable.rb

The example does not suggest how to correctly do authenticate.

**Comment by rishabhsairawat** [comment]
@nbulaj [Using Resource Owner Password Credentials flow section in current_wiki](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Resource-Owner-Password-Credentials-flow) is outdated and resulting into bugs.

As mentioned by @GeminPatel, code for marking `failed_attempts = 0` has been moved to hook `Warden::Manager.after_set_user` So currently `failed_attempts` are not being reset to `0` for a valid authenticable user.

**Comment by nbulaj** [comment]
@rishabhsairawat @GeminPatel could you please fix the Wiki page with the correct approach?
