### ISSUE TITLE
100% rails independent?

### ISSUE THREAD

**Issue by rngtng** [doorkeeper-gem/doorkeeper#710]
I figured doorkeeper can be used with grape for authorization, but when it comes to administrate applications and to grant authorizations/tokens, it is unfortunately very much tight and dependent on rails.
I'd love to see this dependency to be removed, or a least having a clear separation, so I easily can choose my framework of choice. Are there any thoughts around that?

**Comment by tute** [comment]
I'll be happiest to go down that route. Would you like to submit a PR and we work together?

**Comment by rngtng** [comment]
nice! Sure I'm happy to do so. Let me find a setup to start with.. hopefully this wont be too ambitious :)

**Comment by rngtng** [comment]
here's the branch I'm working on. First goal was to get the specs running without having rails loaded. First approach is suuper hacky. now let's get the test green and make it nice.. :)

https://github.com/rngtng/doorkeeper/tree/be-rails-independent

**Comment by tute** [comment]
I like this work. Thanks for proposing and moving forward with it! Requiring the whole `rails` gem for doorkeeper seems like bloated.

**Comment by tute** [comment]
@rngtng are you able to move this PR forward? Thanks!

**Comment by nbulaj** [comment]
Hi @rngtng . Any progress there?

**Comment by rngtng** [comment]
@nbulaj no sorry. We actually moved away from ruby for oauth2. It’s a dead end. Looking into https://github.com/ory/hydra instead
