### ISSUE TITLE
MAC Tokens

### ISSUE THREAD

**Issue by tilo** [doorkeeper-gem/doorkeeper#713]
When will Doorkeeper support MAC Tokens?
It is listed as a "to do", but what is the ETA?
https://github.com/doorkeeper-gem/doorkeeper/wiki/Supported-Features

**Comment by tute** [comment]
Isn't that an old wiki page? :) Thanks for linking to it, I will remove that dusted roadmap!

About MAC tokens, would the custom token generator option help you? https://github.com/doorkeeper-gem/doorkeeper#custom-access-token-generator See how they use it for JWT: https://github.com/chriswarren/doorkeeper-jwt.

**Comment by tute** [comment]
I wouldn't add Mac tokens to doorkeeper's codebase, but I'd help building an extension. Thanks for your input!
