### ISSUE TITLE
Why not base on existing authentication frameworks like warden?

### ISSUE THREAD

**Issue by rngtng** [doorkeeper-gem/doorkeeper#714]
Hey. Just out of interest, what is/was the reason to not base on existing authentication frameworks like [warden](https://github.com/hassox/warden), especially as there's even an [oauth2 extension available](https://github.com/aceunreal/warden-oauth2)?

**Comment by tute** [comment]
There is no real reason. How do you think doorkeeper could leverage warden in its implementation?

**Comment by rngtng** [comment]
ok thanks. Well in regard of #710 I was looking on other solutions and what I liked with warden is its dependency just on rack and a nice clear interface for different auth strategies.. On the other hand, warden-oauth2 lacks a couple of authorization grants...
