### ISSUE TITLE
Anyone Can Edit Wiki

### ISSUE THREAD

**Issue by whatasunnyday** [doorkeeper-gem/doorkeeper#715]
I didn't think my wiki contributions would commit to doorkeeper. My apologies. 

Here are the changes I made:
https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples/_compare/86d2621c6fb07a4f7a530827e6d3e06384d0d465...1dd480d359f6521ec950f27353fe4963beaa392b

1.) Can someone okay my contributions?
2.) By default, anyone can edit a github wiki. Not sure if this was intentional. See https://help.github.com/articles/changing-access-permissions-for-wikis/ on how to fix it.

**Comment by tute** [comment]
Your contributions are in, thank you! https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples#failed-response-invalid-username-password-or-code

The configuration was good, there must have been a hiccup somewhere.
