### ISSUE TITLE
Custom response body when unauthorized

### ISSUE THREAD

**Issue by MathijsK93** [doorkeeper-gem/doorkeeper#720]
I want to provide an custom response body when the user is unauthorized, like DigitalOcean: https://api.digitalocean.com/v1. Doorkeeper has an example in the wiki at https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-the-response-body-when-unauthorized. By using the code from this example:
```ruby
  def doorkeeper_unauthorized_render_options
    {:json => {:error => "Not authorized"}}
  end
```

It gives me this error:
`wrong number of arguments (1 for 0)`
at line:
`def doorkeeper_unauthorized_render_options`

Anyone suggestions?

**Comment by tute** [comment]
The code was out of date, I updated it: https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-the-response-body-when-unauthorized/_compare/2bcdc1248600dc22e0aa6a840ee79f2d99839278...4fff5a88d484af2a56d20afc77fa4544ab61baed

`doorkeeper_unauthorized_render_options` accepts an `error` keyword argument.

Thanks for reporting!
