### ISSUE TITLE
doorkeeper devise sign_out @resource_owner return false

### ISSUE THREAD

**Issue by vishwasIref** [doorkeeper-gem/doorkeeper#721]
Hi ,
       I'm having a doorkeeper application acting as login service,I'm having one other client app using this login service to authenticate users.So when I logout from client app (Not login service) . I send a call to login service with access_token to sign_out resource owner from login service but its not working and sign_out method return false.
Here is my code 
```destroy_session``` get called when I logout from client app

```ruby

  before_action :doorkeeper_authorize!

  def destroy_session
    @current_user = find_current_user
    if @current_user
      sign_out @current_user
      # redirect_to root_url
    end
  end


  private

  def find_current_user
    resource_owner_id = doorkeeper_token.resource_owner_id
    user  = nil
    if !resource_owner_id.nil?
      user = User.find(resource_owner_id)
    end
    user
  end
```

**Comment by tute** [comment]
Probably there is no session? Is `@current_user` defined? After `destroy_session` runs, is a user still authenticated? It `current_user` for devise the same as `User.find(resource_owner_id)`?

**Comment by vishwasIref** [comment]
Since @current_user is not accessible in controller.Doorkeeper wont be having access to function in application controller as said in documentation.but yes user is logged in and current_user and resource_owner are same as logged in user.I had one more observation when i send a request to this method from my login service using the same access_token this WORKS . it successfully logged out the user from login service.Is this problem related to CORS.

**Comment by tute** [comment]
Is this still an issue for you?

Suggested refactor of your code (rewrote it to understand better what it's doing):

```ruby
def destroy_session
  if current_user
    sign_out current_user
    # redirect_to root_url
  end
end

private

def current_user
  @current_user ||= User.find_by_id(doorkeeper_token.resource_owner_id)
end
```

> when i send a request to this method from my login service using the same access_token this WORKS

This is how I'd expect it to function. What is the alternative?

**Comment by tute** [comment]
ping @vishwasIref!
