### ISSUE TITLE
Can't mass-assign protected attributes: scopes on new Rails 3.2 install

### ISSUE THREAD

**Issue by noctivityinc** [doorkeeper-gem/doorkeeper#723]
Just installed Doorkeeper and setup.  When I went to create an application received the following error:

    ActiveModel::MassAssignmentSecurity::Error in Doorkeeper::ApplicationsController#create
    Can't mass-assign protected attributes: scopes

and here are the params:

     {"utf8"=>"✓",
     "authenticity_token"=>"[FILTERED]",
     "doorkeeper_application"=>{"name"=>"Building API",
     "redirect_uri"=>"http://localhost:3001/auth/todo/callback",
     "scopes"=>""},
     "commit"=>"Submit"}

I checked the README and there is nothing about this being Rails 4.X only.  Thanks for the advise.

**Comment by tute** [comment]
This had been fixed in #704, but I didn't release the fix. I assume you are on v3, if you upgrade to 3.0.1 this should work fine. Thanks for your report!

**Comment by noctivityinc** [comment]
You are correct.   I spent all day trying to figure this out :)

3.0.1 fixes the problem.  Thank you.
