### ISSUE TITLE
Questions re: migration and foreign keys

### ISSUE THREAD

**Issue by shicholas** [doorkeeper-gem/doorkeeper#725]
I am interested in adding foreign keys to the standard doorkeeper migration.

Looking at the [migration file](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/generators/doorkeeper/templates/migration.rb) generated by Doorkeeper I have a few questions:

If I had a ``User`` table, whose ``username`` and ``password`` attributes correspond to creating an OAuth token, could I replace [this line](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/generators/doorkeeper/templates/migration.rb#L15) with something like:

```ruby
      t.integer  :user_id, foreign_key: true, null: false
```

Likewise, for an ``application``, can I replace [the following line](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/generators/doorkeeper/templates/migration.rb#L16) with

```ruby
      t.integer  :oauth_application_id, foreign_key: true, null: false
```

(and the similar two lines in ``oauth_access_tokens``)?

Any help would be much appreciated. Thank you for your hard work!

**Comment by tute** [comment]
I think that would be an improvement. Do you want to send a patch?

**Comment by shicholas** [comment]
sure, I'll send one shortly.

**Comment by tute** [comment]
Thanks! Closing in favor of PR.
