### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by jondavidchristopher** [doorkeeper-gem/doorkeeper#735]
Hi there. I would like to recommend that the documentation gets updated here:

https://github.com/doorkeeper-gem/doorkeeper/wiki/Enable-Refresh-Token-Credentials

to include the fact that you need to update "expires_at" also when doing a token refresh. I also had a strange issue where expires at was stored incorrectly and had to be wrapped in:

Time.at(token.expires_at)

when being saved and would throw an empty oauth error.

**Comment by tute** [comment]
Hi @jondavidchristopher! That is a wiki, please go ahead and perform the edit! Mention me in the message in case you want it reviewed. Do you know exactly how the change would look like? I don't fully understand your issue, so I could not fix it myself.

Thanks!
