### ISSUE TITLE
Issue when checking expiration date of grants

### ISSUE THREAD

**Issue by ablancag** [doorkeeper-gem/doorkeeper#738]
Hi there.

I found this issue when following a tutorial, as mentioned in my other issue.

In file `lib/doorkeeper/models/concerns/expirable.rb`, method `expired?` executes:

```ruby
expires_in && Time.now > expired_time
```

In my dev setup, I had to change the line to:

```ruby
expires_in && Time.now.utc > expired_time
```

so it would correctly validate. 

This was preventing me from getting to the URI validation and any other validation happening after this.

This was an issue because grant dates in the DB were in UTC and my Mac is running in timezone -06.00 (Mexico's CST). So when comparing dates, it wasn't comparing them correctly. I thought they would since they are supposed to be Date/Time objects and comparison would be done internally, accounting for time zones, but it seems it is not like that. 

Can you take a look at this? 

Regards,

**Comment by tute** [comment]
Thanks for your detailed bug report! There is a PR addressing this issue, and I copied there your bug for context: https://github.com/doorkeeper-gem/doorkeeper/pull/730#issuecomment-152788981. Will close this issue in favor of that thread. Thanks again for reporting!
