### ISSUE TITLE
Rails 5 ActionController::RoutingError (uninitialized constant ActionController::RackDelegation)

### ISSUE THREAD

**Issue by avdmatamoros** [doorkeeper-gem/doorkeeper#742]
I'm trying out rails 5 with doorkeeper and I encountered this issue:

    ActionController::RoutingError (uninitialized constant ActionController::RackDelegation):
    doorkeeper (3.0.1) app/controllers/doorkeeper/application_metal_controller.rb:4:in '<class:ApplicationMetalController>'
    doorkeeper (3.0.1) app/controllers/doorkeeper/application_metal_controller.rb:2:in '<module:Doorkeeper>'
    doorkeeper (3.0.1) app/controllers/doorkeeper/application_metal_controller.rb:1:in '<top (required)>'

It seems the RackDelegation module is being removed in rails 5 in this commit https://github.com/rails/rails/commit/d47438745e34d75e03347b54b604b71b7a92c3ac#diff-e7d3aaf1cb8ad2b300b3e1da6f318e50

**Comment by tute** [comment]
Thanks! Would be nice to get Travis running tests on Rails master as allowed failure, until we get version 5.

**Comment by tute** [comment]
Closing in favor of PR. Thanks!

**Comment by ebosantos** [comment]
I'm getting same error

`{
  "status": 404,
  "error": "Not Found",
  "exception": "#<ActionController::RoutingError: uninitialized constant ActionController::RackDelegation>",
  "traces": {
    "Application Trace": [],
    "Framework Trace": [
      {
        "id": 0,
        "trace": "doorkeeper (3.1.0) app/controllers/doorkeeper/application_metal_controller.rb:4:in `<class:ApplicationMetalController>'"
      },
      {
        "id": 1,
        "trace": "doorkeeper (3.1.0) app/controllers/doorkeeper/application_metal_controller.rb:2:in `<module:Doorkeeper>'"
      },
      {
        "id": 2,
        "trace": "doorkeeper (3.1.0) app/controllers/doorkeeper/application_metal_controller.rb:1:in `<top (required)>'"
      },
      {
        "id": 3,
        "trace": "activesupport (5.0.0.beta2) lib/active_support/dependencies/interlock.rb:12:in `block in loading'"
      },`

rails 5.0.0.beta2, doorkeeper 3.1.0. What do you suggest to do?

**Comment by jcgertig** [comment]
yes im also hitting this issue

**Comment by leomayleomay** [comment]
since this has been fixed in the master branch, i am wondering when the next version will be released, since I am using doorkeeper in one of my engines, I can not specify the `git` path to the edge.

**Comment by tute** [comment]
> since this has been fixed in the master branch, i am wondering when the next version will be released, since I am using doorkeeper in one of my engines, I can not specify the git path to the edge.

Just released an RC version:

* https://github.com/doorkeeper-gem/doorkeeper/releases/tag/v4.0.0.rc1
* https://rubygems.org/gems/doorkeeper

Enjoy!

**Comment by leomayleomay** [comment]
@tute thank you :)
