### ISSUE TITLE
Response with a custom error

### ISSUE THREAD

**Issue by ezilocchi** [doorkeeper-gem/doorkeeper#746]
Hi,

I'm working on a feature where I need to perform some custom logic as part of the user authentication process. As result of this extra logic I might need to stop the process and notify the user a situation (basically that the authentication has failed, but for a custom reason). In order to perform this I need to return an HTTP error and a message that need to be presented to the user.

The easiest way I found of saying to `Doorkeeper` that something went wrong during the authentication process, was raising a `Doorkeeper::Errors::DoorkeeperError` inside the `resource_owner_authenticator` block in the `config/initializers/doorkeeper.rb` file. The problem is that I can't specify the message I need to present to the user.

I looking into the code I found that doing this small change I was able to specify a message for my error

```
diff --git a/lib/doorkeeper/helpers/controller.rb b/lib/doorkeeper/helpers/controller.rb
index 71e33a2..ecdefd5 100644
--- a/lib/doorkeeper/helpers/controller.rb
+++ b/lib/doorkeeper/helpers/controller.rb
@@ -45,6 +45,8 @@ module Doorkeeper
                        :invalid_request
                      when Errors::InvalidGrantReuse
                        :invalid_grant
+                     else
+                       exception.message
                      end
```

`config/initializers/doorkeeper.rb`
```ruby
  resource_owner_from_credentials do |routes|
    raise Doorkeeper::Errors::DoorkeeperError.new('my_custom_message')
  end
```

`config/locales/doorkeeper.en.yml`
```yml
en.doorkeeper.errors.messages.my_custom_message: Some custom error message.
```

This is a hacky solution I know, but I would like to know if there is a better way or if it is worth to spend more time looking for a better one and then create a PR for it.

Thanks,
Emiliano.-

**Comment by tute** [comment]
I'm not against this. I think it's worth it to discuss in a PR, and we might merge either this solution or a better one if we find one.
Thanks!

**Comment by tute** [comment]
Thanks! Closing in favor of PR.
