### ISSUE TITLE
doorkeeper_unauthorized_render_options(error: nil) gives a syntax error

### ISSUE THREAD

**Issue by jiteshshetty** [doorkeeper-gem/doorkeeper#748]
When I am trying to use doorkeeper 3.0.0 + the bundle install works fine, but when I fire the rails server I get a syntax error:

```
/Users/XXXXXXX/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require': /Users/XXXXXXX/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/doorkeeper-3.0.1/lib/doorkeeper/rails/helpers.rb:14: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
      def doorkeeper_unauthorized_render_options(error: nil)
                                                       ^
/Users/XXXXXXXXX/.rvm/gems/ruby-1.9.3-p125@rails32x/gems/doorkeeper-3.0.1/lib/doorkeeper/rails/helpers.rb:17: syntax error, unexpected tLABEL, expecting ')'
      def doorkeeper_forbidden_render_options(error: nil)
```

I don't see this issue with doorkeeper 2.0.0, any help is much appreciated.

Regards,
Jitesh

**Comment by tute** [comment]
This should certainly be in the NEWS file, and I didn't add it. Ruby 1.9.3 support has been dropped, as [it reached its end-of-life almost two years ago](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) (and as a result it doesn't receive security patches any longer).

Will add this to the README. Thanks!

**Comment by msmukesh5** [comment]
You could try using some lower versions eg. gem 'doorkeeper', '~> 1.4.1' 
works well with ruby 1.9.3
