### ISSUE TITLE
resource_owner_from_credentials in v3.X doesnt work

### ISSUE THREAD

**Issue by noctivityinc** [doorkeeper-gem/doorkeeper#750]
I have the resource owner from credentials block set as follows:

    resource_owner_from_credentials do
      request.params[:account] = {:email => request.params[:username], :password => request.params[:password]}
      request.env["devise.allow_params_authentication"] = true
      account = request.env["warden"].authenticate!(:scope => :account)
      env['warden'].logout
      account
    end

and have also tried enabling the grant_flow and grant_types

    grant_flows %w(authorization_code client_credentials password)

and

    Doorkeeper.configuration.token_grant_types << "password"

But in version 3.0.1 of Doorkeerp the resource_owner_from_credentials block never appears to be called.  During the initial authorize routine, I get this;

    Started POST "/oauth/authorize" for 127.0.0.1 at 2015-11-19 13:43:15 -0500
    Processing by Doorkeeper::AuthorizationsController#create as JSON
      Parameters: {"grant_type"=>"password", "username"=>"jlippiner@gmail.com", "password"=>"testing", "scope"=>"public"}
    WARNING: Can't verify CSRF token authenticity
    Completed 401 Unauthorized in 6.7ms

**Comment by noctivityinc** [comment]
btw, here is my resource_owner_authenticator block

     resource_owner_authenticator do
       current_account || warden.authenticate!(:scope => :account)
     end

**Comment by tute** [comment]
`spec/requests/flows/password_spec.rb` should be covering that. Do you think this is a bug in doorkeeper or something going wrong with the configuration? How can I replicate this? Can you provide a sample app? Thank you!

**Comment by tute** [comment]
@noctivityinc, did you workaround this issue? Was it in your app's configuration or in doorkeeper's code? Thank you!

**Comment by noctivityinc** [comment]
I was able to get around it by changing some of the routes used by my iOS app.  I dont believe it was a doorkeeper issue.  Thanks.
