### ISSUE TITLE
Application resource just for registered users

### ISSUE THREAD

**Issue by yottanami** [doorkeeper-gem/doorkeeper#751]
How can I limit the application resource ( application scaffold ) for authenticated users?

**Comment by tute** [comment]
You can use `resource_owner_authenticator`. See:

* https://github.com/doorkeeper-gem/doorkeeper#authenticating
* https://github.com/doorkeeper-gem/doorkeeper/wiki/Authenticating-using-Clearance-or-DIY

Thanks!
