### ISSUE TITLE
Scope dialog skipped w/ Devise

### ISSUE THREAD

**Issue by fredkelly** [doorkeeper-gem/doorkeeper#757]
Probably well documented but I'm having difficulty configuring redirect URLs using Rails 4 + devise, this is my config:
```ruby
Doorkeeper.configure do
  # Change the ORM that doorkeeper will use (needs plugins)
  orm :active_record

  # This block will be called to check whether the resource owner is authenticated or not.
  resource_owner_authenticator do
    session[:user_return_to] = request.fullpath
    current_user || redirect_to(new_user_registration_path)
  end

  resource_owner_from_credentials do |routes|
    # TODO review this
    request.params[:user] = {:email => request.params[:username], :password => request.params[:password]}
    request.env['devise.allow_params_authentication'] = true
    request.env['warden'].authenticate!(:scope => :user)
  end

  # Issue access tokens with refresh token (disabled by default)
  use_refresh_token

  # snip...
end
```

I've got a standard Devise configuration. I'm finding users are redirected without being presented the "permissions dialog". I've tried overriding `after_sign_in_path_for(resource)` but I get some pretty weird behaviours. Is there a standard approach for setting up redirects when using doorkeeper + devise?

**Comment by pmackay** [comment]
I'm seeing the same problem, interested to know @fredkelly if you've found a solution or anyone else has suggestions?

**Comment by fredkelly** [comment]
Unfortunately I'm still looking for a good solution!

**Comment by tute** [comment]
The issue you describe seems very specific to your applications and their configuration. I suggest that you ask about it in http://stackoverflow.com/questions/tagged/doorkeeper, which will get attention
from more people than in this issue tracker.

For now, I will close this issue, and if you continue having problems and believe it's due to a bug in doorkeeper we will reopen. Thanks!
