### ISSUE TITLE
How does doorkeeper communicate redirect URI to Devise?

### ISSUE THREAD

**Issue by bsylvain** [doorkeeper-gem/doorkeeper#760]
In doorkeeper .rb the following config allow users to login before being redirected to the consumer app :

    resource_owner_authenticator do
      current_user || warden.authenticate!(:scope => :user)
    end

I want to have an alternate login screen for users coming from a consumer app, so i created a specific action.
To do so I used the following config :

    current_user || redirect_to(api_login_url)

Unfortunately, the user is not redirected to the consumer app but to the provider app root.

I tried to find in the code how warden.authenticate! works, but it's pretty opaque without explanations.

Is there a way to set the redirection URI to allow me to use an alternate login action?

**Comment by tute** [comment]
It seems very specific to your application rather than with doorkeeper itself. I'd suggest you ask about it in http://stackoverflow.com/questions/tagged/doorkeeper, which will get attention from more people than in this issue tracker. Thank you!

**Comment by tute** [comment]
Related issue: https://github.com/doorkeeper-gem/doorkeeper/issues/757
