### ISSUE TITLE
uninitialized constant Grape::API::Helpers 

### ISSUE THREAD

**Issue by ved54321** [doorkeeper-gem/doorkeeper#761]
I have used following gem in my rails 4 application,

```
doorkeeper (3.0.1)
grape (0.2.6)
```

I want to include doorkeeper authentication in my grape api,

following is my code which i did,

```ruby
require 'json_builder'
require 'doorkeeper/grape/helpers'
 module API
  module Fidelity
    class Fidelity < Grape::API
    helpers Doorkeeper::Grape::Helpers
       prefix  'api'
       default_format :json
       version 'fidelity'
       format :json
            before do
              doorkeeper_authorize!
           end
      end
```

I am getting `uninitialized constant Grape::API::Helpers` error with following log,

```
usr/local/rvm/gems/ruby-2.2.2@nusdigital/gems/doorkeeper-3.0.1/lib/doorkeeper/grape/helpers.rb:6:in `<module:Helpers>': uninitialized constant Grape::API::Helpers (NameError)
        from /usr/local/rvm/gems/ruby-2.2.2@nusdigital/gems/doorkeeper-3.0.1/lib/doorkeeper/grape/helpers.rb:5:in `<module:Grape>'
        from /usr/local/rvm/gems/ruby-2.2.2@nusdigital/gems/doorkeeper-3.0.1/lib/doorkeeper/grape/helpers.rb:4:in `<module:Doorkeeper>'
        from /usr/local/rvm/gems/ruby-2.2.2@nusdigital/gems/doorkeeper-3.0.1/lib/doorkeeper/grape/helpers.rb:3:in `<top (required)>'
```

Please help me on this.

**Comment by tute** [comment]
This is coming from https://github.com/doorkeeper-gem/doorkeeper/pull/567/files#diff-c2eb61b837013715de621d5245b8f366R6. @hobofan could it be because of Grape's version?

**Comment by hobofan** [comment]
I haven't used the gem in quite some time, but yes, it is very likely due to the grape version.
0.2.6 is 2 year olds now and IIIR the Helpers module was added around version 0.9.0.

**Comment by tute** [comment]
Thank you! @ved54321, it sounds like you'd need to upgrade Grape. When we find out what version is required, I'd like to get the documentation updated. Please let me know!

**Comment by ved54321** [comment]
ye sure @tute .I will try updating grape version and i will let you know .

**Comment by tute** [comment]
Thanks! Closing this issue for now, let me know if there is anything else we should fix in doorkeeper.

Related: https://github.com/doorkeeper-gem/doorkeeper/issues/766.
