### ISSUE TITLE
Regenerating secrete tokens

### ISSUE THREAD

**Issue by theycallmeswift** [doorkeeper-gem/doorkeeper#770]
I want to implement a way for users to regenerate their secret keys if they have been exposed.  Here's some pseudo code of what I'm thinking:

```ruby
def regenerate
  @application = Doorkeeper::Application.by_uid(params[:uid])
  @applicaton.secret = Doorkeeper::OAuth::Helpers::UniqueToken.generate

   if @application.save
      # blah
   else
      # blah
   end
end
```

Are there any issues around doing it this way?  Would there be interest in a pull request that added something like this to doorkeeper?

**Comment by christopherhein** [comment]
I like the idea would make implementing something like what Github has where you can easily refresh your application very easy.

Only thing I would do differently would be implementing a `.reset_secret` method on the `Doorkeeper::ApplicationMixin` module and then call `.generate` in there and call `.save` to clean up the controller a bit.

I'm not on Doorkeeper core, but I personally like the idea. :+1:

**Comment by theycallmeswift** [comment]
+1.  I think that's a much better way to implement it in Doorkeeper core.

**Comment by tute** [comment]
> I want to implement a way for users to regenerate their secret keys if they have been exposed.

Your code looks good.

If it were to make it into doorkeeper, it should probably belong in the admin interface, but then I'd worry that less competent developers would needlessly (or without understading the consequences) regenerate tokens, making their client apps fail.

I think this is simple enough (certainly the simplest of the tasks you have to do once keys have been compromised) to not deserve its implementation in doorkeeper.

Thank you!
