### ISSUE TITLE
Configuring activerecord

### ISSUE THREAD

**Issue by mateomurphy** [doorkeeper-gem/doorkeeper#781]
In the README it says:

> if you plan on using making User the resource owner, change the two lines in the migration file:
> 
> `t.integer    :resource_owner_id, null: false`
> to:
> `t.references :user, foreign_key: true, null: false`

However this doesn't seem to work, as the models appear to be hardcoded to search using the `resource_owner_id`. If there another configuration step to make this work, or is there an error in the documentation?

**Comment by maxmeyers** [comment]
In particular, [Doorkeeper::Application.authorized_for](https://github.com/doorkeeper-gem/doorkeeper/blob/4313541e4d806cd8e5cad20d4ca4444171c113d2/lib/doorkeeper/orm/active_record/application.rb#L20) references the `resource_owner_id` column.

**Comment by arcreative** [comment]
Having this issue as well... would be great if the key/column were configurable.

**Comment by tute** [comment]
Indeed this is a bug, thank you! A PR updating documentation, or making it work, will be appreciated and merged! Thanks again for reporting.

**Comment by jclem** [comment]
I've opened a PR that updates the README, as I also ran into this: https://github.com/doorkeeper-gem/doorkeeper/pull/829

**Comment by tute** [comment]
Thank you, @jclem!
