### ISSUE TITLE
`redirect_uri` is required, but is not required for following the client-credentials flow

### ISSUE THREAD

**Issue by inooid** [doorkeeper-gem/doorkeeper#782]
I recently tried to implement the doorkeeper gem, but I am trying to follow the client-credentials flow. I want to just register applications without binding them to a specific user and when trying to create a `Doorkeeper::Application`, I ran into a validation error that I cannot create a `Doorkeeper::Application` without providing a `redirect_uri`. While this is normal for [3-legged OAuth](http://oauthbible.com/#oauth-2-three-legged), this is not necessary for the [2-Legged OAuth](http://oauthbible.com/#oauth-2-two-legged).

To me it seems fairly normal to be able to disable that validation, because it's not always necessary. It now forces me to add a URI that I'll never need (as far as I know). Maybe I am missing some configuration, but I couldn't find it.

**Comment by tute** [comment]
If you know what you are doing, you can always seed in a dummy URL, or disable the validation modifying the code (monkey patching). But for being secure by default, I prefer it to be always on, and that behavior not to be configurable.

Thanks for your input!
