### ISSUE TITLE
New access_token is generated even if the old token is valid.

### ISSUE THREAD

**Issue by Nitin-Salunke** [doorkeeper-gem/doorkeeper#785]
When we authenticate a resource owner from credentials a new token is generated every time.
Instead we can just use the existing valid token until the token is expired.

**Comment by tute** [comment]
@Nitin-Salunke Is this behavior a bug, or does it go against the spec? Does it need to be changed? Thanks!

**Comment by Nitin-Salunke** [comment]
It is just a suggestion from me.
What is the need of creating a new token when your

**Comment by tute** [comment]
Thanks for your input. If it becomes problematic for any reason we'll address.
