### ISSUE TITLE
Incorrect information in readme about AR indexes?

### ISSUE THREAD

**Issue by chrismanderson** [doorkeeper-gem/doorkeeper#789]
In the readme, the section on [AR](https://github.com/doorkeeper-gem/doorkeeper/blob/master/README.md#active-record) says:

> if you plan on using making User the resource owner, change the two lines in the migration file

However, in the instructions directly following that, there is only one line that is changed, instead of two. Is there something missing from those instructions, or should it say change `one line` instead of `two lines`?

**Comment by tute** [comment]
It should say "change the line" indeed. Also, `making` should be removed. Thanks for reporting!

**Comment by tute** [comment]
Fixed, thank you!
