### ISSUE TITLE
use_refresh_token doesnt work

### ISSUE THREAD

**Issue by Showyilu** [doorkeeper-gem/doorkeeper#790]
I commented out `use_refresh_token` in `config/initializers/doorkeeper.rb`, and expected refresh_token to be generated. But it didn't generate. And I found out the problem might be 

````ruby
def use_refresh_token?
  !!@use_refresh_token
end
```

`@use_refresh_token` is `false` even though `use_refresh_token` is called. 

And by doing `!!Doorkeeper.configuration.refresh_token_enabled?` fixes the problem, since  `@config.instance_variable_set('@refresh_token_enabled', true)` is called in `lib/doorkeeper/config.rb`.

Did I miss anything or do anything wrong here?

**Comment by tute** [comment]
This is surprising. Other installations are making use of refresh tokens just fine. What version of doorkeeper are you using? If not latest, does it work if you upgrade? Thanks!

**Comment by Showyilu** [comment]
@tute Thanks for the reply. Im currently using doorkeeper-3.1.0. I think it is working fine. It was my mistake to try the implicit grant type.
