### ISSUE TITLE
Allow non-OAuth controllers to be disabled

### ISSUE THREAD

**Issue by mattgreen** [doorkeeper-gem/doorkeeper#81]
Devise has a helper method named `devise_for` which can be used in the routes DSL to configure which of Devise's controllers get added to the route set. This comes in handy when integrating with a project's existing functionality, or replacing the built-in controllers with your own.

It'd be awesome if Doorkeeper had a similar functionality. For example, on the project I'm working on, we use ActiveAdmin to create new applications, and a custom controller to handle the authorization of new apps to user accounts. Thus, the Doorkeeper-provided app admin, as well as the auth controller, are mapped, but not usable.

Is there any interest in this feature? If so, I'd be glad to implement it.

**Comment by spidie** [comment]
The skip functionality was just what I was looking for - can we get this added to the documentation? (I am happy to add this if that's ok).

**Comment by tute** [comment]
This is more of a Rails feature rather than doorkeeper's, bu I'd merge a PR
that shows this in a sentence or two in the README. Thanks!
