### ISSUE TITLE
Support for mounting it under a namespace?

### ISSUE THREAD

**Issue by mariogintili** [doorkeeper-gem/doorkeeper#814]
Hello peeps,

I'm developing an API, my app has no views. But I still wanted to leverage those from Doorkeeper - like `oauth/applications/new`. However I had mounted it under a namespace, `api`, i.e:

```ruby
  namespace :api do
    use_doorkeeper
    resources :users, only: [:index, :show, :create]
  end
```

After than I ran into a first exception, `Uninitialized constant Api::Doorkeeper`. So I went ahead, tried to be clever and added the following to the initializer `doorkeeper.rb`

```ruby
module Api
  Doorkeeper = ::Doorkeeper
end
```

Which worked! Up until I ran into the following:

<img width="1100" alt="screen shot 2016-04-10 at 08 51 00" src="https://cloud.githubusercontent.com/assets/3522106/14408776/676e7110-fef9-11e5-8890-e6a8615de58b.png">

Was wondering if namespace'd mounts where going to be supported soon? or should I just avoid at all costs?

**Comment by tute** [comment]
I wonder if the undocumented `:scope` routes option would help you on this: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/rails/routes.rb#L26.

Please let me know if it does, and if so, we'll add documentation. Thanks!

**Comment by mariogintili** [comment]
@tute hello, this seems to be working just fine now. Thanks, I will get back if any arises :)

**Comment by kyrofa** [comment]
@mariogintili I just ran into this. Using a scope just seems to nest the oauth routes further under the mount namespace. What solution did you actually end up using?

**Comment by kyrofa** [comment]
Oh sorry, you probably just moved it out of the namespace huh, @mariogintili. I should have read closer. I'm actually using doorkeeper in an engine that is mounted at a non-root route path, so that's not an option for me. Any ideas for how I should deal with that?
