### ISSUE TITLE
When creating application without scope it does not prevent access

### ISSUE THREAD

**Issue by edwardbako** [doorkeeper-gem/doorkeeper#820]
I'm using `optional_scopes :admin` in configuration. Then I've created new application. Scope field was left blank.
In one of my controllers I have `before_action -> { doorkeeper_authorize! :admin }`.
When I'm creating client without scope, it works properly. It denies access to resouce.
But I can provide scope 'admin', when creating client. And it works like client have access to scoped admin resources.
Question. How can we give a token to client with some scope if we didn't provide this scope on app creation? Isn't it something wrong? 
I think we should not give scoped access token if we not provide the scope on application creation.
Sorry for my English, hope thought is clear..)

**Comment by tute** [comment]
> How can we give a token to client with some scope if we didn't provide this scope on app creation?

Scopes are edited on app creation or updated, not during token request.

> I think we should not give scoped access token if we not provide the scope on application creation.

You can use `default_scope` for that. See: https://github.com/doorkeeper-gem/doorkeeper#access-token-scopes.

Thanks!
