### ISSUE TITLE
[v4.0.0.rc2] No route for new_oauth_application_path

### ISSUE THREAD

**Issue by sanchobouillant** [doorkeeper-gem/doorkeeper#821]
Hello,

I'm not a rails gutu ! :)

I test rails 5 (--api --edge). I wat to use Doorkeeper to handle my oauth server.

When i go to http://localhost:3000/oauth/applications i receive "undefined local variable or method `new_oauth_application_path'"

<img width="873" alt="routes" src="https://cloud.githubusercontent.com/assets/5731199/14682199/c36c3b36-0724-11e6-9f28-5b9afdbb4595.png">

I added in application.rb     
`config.middleware.use ActionDispatch::Flash
`
Routes.rb: 
```
Rails.application.routes.draw do
    use_doorkeeper
end
```

<img width="1258" alt="error" src="https://cloud.githubusercontent.com/assets/5731199/14682262/18c0df74-0725-11e6-88e3-1593a3b44741.png">

**Comment by tute** [comment]
I would expect that the `--api` mode for Rails interferes with the new HTML endpoint. Does this still happen if in `config/application.rb` you declare `config.api_only = false`?

**Comment by sanchobouillant** [comment]
It work with api_only = false

**Comment by tute** [comment]
doorkeeper admin interface is HTML, and needs features absent in Rails API mode.

**Comment by mmahalwy** [comment]
@tute any solution or work around for this whe doing api_only = true?

**Comment by tute** [comment]
You'd need to check what modules need to be included in the Doorkeeper controllers, and include them by hand only on that admin interface. Not sure which those are, I would try to debug that or ask in StackOverflow in case someone there has already done this.
