### ISSUE TITLE
Using without an ORM

### ISSUE THREAD

**Issue by colinramsay** [doorkeeper-gem/doorkeeper#822]
I'm looking to use Doorkeeper with SQL Server and tiny_tds, so we're not using an ORM. What's the approach in this situation? Is Doorkeeper dependent on using an ORM?

**Comment by tute** [comment]
It is now. You'd need to define an ActiveRecord like interface for doorkeeper to work.

**Comment by colinramsay** [comment]
Is there a spec for that? Is the guidance to just look at the mongodb version?

**Comment by tute** [comment]
There is no spec of what methods does doorkeeper use yet. It's a subset of http://api.rubyonrails.org/classes/ActiveRecord/Base.html.

**Comment by tute** [comment]
I'll close this as it's not something to be fixed in the project, but happy to continue further discussion.
