### ISSUE TITLE
Cannot use password grant_type on 4.0.0 RC3 using Rails 5 Beta3

### ISSUE THREAD

**Issue by saifis** [doorkeeper-gem/doorkeeper#824]
I followed the instructions to install, added 

`Doorkeeper.configuration.token_grant_types << "password"`

to the initializer, and when I try to send a grant_type=password to POST:/oauth/token
I get the 

```json
{
"error": "unsupported_grant_type",
"error_description": "The authorization grant type is not supported by the authorization server."
}
```

error, I have done the same thing on an older Rails4 app, which uses Doorkeeper 3.1.0 and it does not happen there.

tested out other types of grant types and they do not get rejected.

Please help.

**Comment by tute** [comment]
The syntax is `grant_flows ARRAY`: https://github.com/doorkeeper-gem/doorkeeper/blob/master/spec/dummy/config/initializers/doorkeeper.rb#L85

**Comment by tute** [comment]
Could that be the issue?

**Comment by saifis** [comment]
I've tried setting the array to password only, all of them , with and without the token_grant_types and still get the same error.

**Comment by tute** [comment]
The issue you describe seems specific to your application and configuration. I suggest that you ask about it in http://stackoverflow.com/questions/tagged/doorkeeper, where you will get attention
from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand the issue in order to help you.

Sorry I can't help you further right now. Thanks for reporting.

**Comment by saifis** [comment]
Thank you for the response, That was what I was afraid, of. I will start a new project and see if there are any changes.

**Comment by tute** [comment]
Thanks!

**Comment by saifis** [comment]
Tried this on the new Beta 4 of rails, created a new project, added doorkeeper, and sending grant_type=password gives me the invalid grant_type eroror

[doortest.zip](https://github.com/doorkeeper-gem/doorkeeper/files/242126/doortest.zip)

**Comment by tute** [comment]
The application you sent in a zip doesn't work because it's using doorkeeper v3.1, which doesn't work with Rails 5. Do you have another branch or app?

**Comment by Lyonsclay** [comment]
@saifis After updating the Gemfile in your app
 `gem doorkeeper', '~> 4.0.0.rc1'`

 and using this curl request;
`curl -v -H 'Content-Type: application/json' -H 'Accept: application/json' -X POST "http://localhost:3000/oauth/token" -d "{"grant_type": "password", "client_id": "fa927b2631bed16e3766318cc3db4910f003e9c9fc8a57eaaf2e9490a9436615", "client_secret": "b1d402d325ed2fb58ac9342ade12cdf1664716d9df4327f092fffbf5c08259b4", "token": "4b9d40942ba6d47c30c808253c18416085bd4b724ddebd741114ac7ce74690fd"}"
`
 I did not get the error you specified.

**Comment by tute** [comment]
Thank you for triaging this, @Lyonsclay. @saifis can you send reproduction steps?

**Comment by saifis** [comment]
After more looking, it seems a new rails app would work, I was missing the configuration needed within the initializaer, which confirms your diagnoses about something wrong on my end, sorry for the trouble. I will post what I did wrong when I figure it out..

**Comment by saifis** [comment]
I missed some of the new comments, sorry for the hassle.
