### ISSUE TITLE
Doorkeeper Unauthorised Render Options

### ISSUE THREAD

**Issue by kallahir** [doorkeeper-gem/doorkeeper#832]
I'm trying to use [this](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-the-response-body-when-unauthorized) to customize the output of my invalid token message, I need to add some additional informations to it, but unfortunately it's not working at all, the json that is being outputted is always the same and doesn't change.

Thanks!

**Comment by tute** [comment]
What version of Rails and doorkeeper are you using? Can you paste your controller code? Thanks!

**Comment by kallahir** [comment]
Doorkeeper version = 3.1.0
Rails version = 4.1.8

I'm using this Rails version because I'm deploying the application at Amazon and that is the version that they have there.

Best regards.

**Comment by tute** [comment]
Can you paste your controller code? Thanks!

**Comment by kallahir** [comment]
```
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def doorkeeper_unauthorized_render_options(error: nil)
    { json: { error: "CUSTOM ERROR!" } }
  end
end
```

**Comment by tute** [comment]
Probably the controller that hits Doorkeeper it not inheriting from `ApplicationController`. Can you try opening up the controller that receives that connection, or reopening the `Doorkeeper::ApplicationController` object?

**Comment by kallahir** [comment]
I didn't found anything like Doorkeeper::ApplicationController in any place of my code, I'm using grape to build a REST api is possible that is something related?

**Comment by tute** [comment]
> I'm using grape to build a REST api is possible that is something related?

It might be the case, Grape is not tested in CI and I don't have Grape projects

> I didn't found anything like Doorkeeper::ApplicationController in any place of my code

It's loaded by doorkeeper. Even thought it's not in your code, you can reopen it anywhere (oh, Ruby!) and do:

```ruby
class Doorkeeper::ApplicationController
  def doorkeeper_unauthorized_render_options(error: nil)
    { json: { error: "CUSTOM ERROR!" } }
  end
end
```

**Comment by kallahir** [comment]
I've tried many different approaches but I wasn't able to override the controller. =/
Do you have any insights that could help me?

**Comment by tute** [comment]
Can you share the code for your application?

**Comment by tute** [comment]
Or, can you paste the complete controller code where you define `before_action :doorkeeper_authorize!`?

**Comment by kallahir** [comment]
I was able to solve the problem that I was having, I don't know if this is the best way of doing it.
This is code the code that I had:

```
helpers Doorkeeper::Grape::Helpers
    helpers Devise::TestHelpers
    
    helpers do
      def failed(error_code)
        return { error: true,
                 error_code: error_code,
                 data: {} }
      end
      
      def success(data)
        return { error: false,   
                 error_code: "",
                 data: data }
      end
    end
    
    before do
      doorkeeper_authorize!
    end
    ...
```

I change to this and worked:

```
helpers Doorkeeper::Grape::Helpers
    helpers Devise::TestHelpers
    
    helpers do
      def failed(error_code)
        return { error: true,
                 error_code: error_code,
                 data: {} }
      end
      
      def success(data)
        return { error: false,   
                 error_code: "",
                 data: data }
      end
      
      def doorkeeper_render_error_with(error)
        status_code = case error.status
                      when :unauthorized
                        401
                      when :forbidden
                        403
                      end

        error!(failed("ERRO_0016"), status_code, error.headers)
      end
    end
    
    before do
      doorkeeper_authorize!
    end
    ...
```

All I had to do was override doorkeeper_render_error_with.

Finally.

**Comment by tute** [comment]
I'm glad you could work it out. Thanks for reporting the problem and sharing your solution.
