### ISSUE TITLE
Sprockets::Rails::Helper::AssetNotPrecompiled error with Sprockets 4

### ISSUE THREAD

**Issue by kramerc** [doorkeeper-gem/doorkeeper#834]
On Rails 5.0.0.rc1 and Sprockets 4.0.0.beta2, I receive the following error when accessing certain Doorkeeper routes such as `/oauth/applications`:
![2016-05-14_23-55-22](https://cloud.githubusercontent.com/assets/114056/15272507/e76c7460-1a2f-11e6-9fbb-c30eded1fedc.png)

I am able to fix this issue by adding the following to `app/assets/config/manifest.js`:
```js
//= link doorkeeper/application.css
//= link doorkeeper/admin/application.css
```

**Comment by tute** [comment]
Uhh thank you! This is a bug, would you be willing to send a patch to fix it? Thanks for reporting!

**Comment by kramerc** [comment]
I tried adding a `manifest.js` in the gem itself but it didn't resolve the problem. I'm not sure of any other way of fixing it with Sprockets 4 other than adding it my application's manifest. I can make a patch that adds these two lines in the application's manifest with the `doorkeeper:install` generator but I'm sure there's a better way.

**Comment by nbulaj** [comment]
For new versions of `Sprockets` we can add a precompile config in Doorkeeper Engine initializer. I can make a PR with fix for that issue.

**Comment by tute** [comment]
That's great. We'll need a regression (integration) spec as well.

Thank you all!

**Comment by nbulaj** [comment]
@tute you can check related commit.

What about the specs, I don't know how to test that behavior (with the assets config). Maybe somebody have thoughts on this?

**Comment by nbulaj** [comment]
@tute if you will try to use a new version of `Sprockets` with specs (update Gemfile with `gem 'sprockets', '4.0.0.beta2'`) and run the tests, then you will see 33 failures like:

>   33) Skip authorization form for previously authorized clients creates grant with new scope when scopes are greater
>         Failure/Error: <%= stylesheet_link_tag "doorkeeper/application" %>
>         
>         ActionView::Template::Error:
>           Asset `doorkeeper/application.css` was not declared to be precompiled in production.
>           Declare links to your assets in `assets/config/manifest.js`.
>           Examples:
>           `//= link ../javascripts/application.js`
>           `//= link_directory ../javascripts .js`
>           `//= link_directory ../stylesheets .css`
>           `//= link_tree ../javascripts .js`
>           `//= link_tree ../images`

My fix makes the tests green. I can add a spec to the `spec/controllers/applications_controller_spec.rb` to test against rendering errors if you think there is a need in this.

**Comment by tute** [comment]
> My fix makes the tests green. I can add a spec to the top of spec/controllers/applications_controller_spec.rb to test against rendering errors if you think there is a need in this.

That would be killer, yes please.

Do you think we need to add the gem upgrade in doorkeeper, or test against both versions, or instead include the fix regardless of sprockets version the user will run will be enough?

**Comment by nbulaj** [comment]
> Do you think we need to add the gem upgrade in doorkeeper, or test against both versions, or instead include the fix regardless of sprockets version the user will run will be enough?

Current `Rails` 5 version in master branch depends on `sprockets-rails` 3.0.4 which in turn depends on `sprockets` (>= 3.0.0). Precompilation issue is specific to the beta version of `sprockets` 4. I don't think that we need to upgrade the gem version in `doorkeeper` - it depends on what `rails` decide to include and developer needs.

What about test against both versions - it is quite possible, but is it necessary? [I added a special gemfile](https://github.com/nbulaj/doorkeeper-sequel/blob/master/gemfiles/sprockets-4.0.gemfile) with new `Rails` and `sprockets` for building with TravisCI, but I think it is redundant.

I think that checking sprockets version the user will run will be enough (as we do it for Rails and ActiveRecord: 4.2 or 5?).

**Comment by nbulaj** [comment]
> That would be killer, yes please.

As I said before, for non-beta release of `sprockets` (in other words for stable 4 version) current `doorkeeper` feature specs will throw an error anyway (with _ActionView::Template::Error_). And we will have to fix the error. Does it make sense to write a separate test to verify whether the view does not return an error?

It would be something like this:

```ruby
# spec/requests/applications/applications_request_spec.rb

feature 'Adding applications' do
  context 'in application form' do
    background do
      expect { visit '/oauth/applications/new' }.not_to raise_error
    end

   # ...
end
```

**Comment by nbulaj** [comment]
So what do you think about this, @tute ?

**Comment by tute** [comment]
@nbulaj we don't need the extra spec, I just verified hat you describe: with updated sprockrets this failures happen. Want to send a PR with your fix? Thank you!

**Comment by nbulaj** [comment]
> Want to send a PR with your fix?

Done.
