### ISSUE TITLE
NameError in Doorkeeper::Applications#new 

### ISSUE THREAD

**Issue by kumardev** [doorkeeper-gem/doorkeeper#837]
![error](https://cloud.githubusercontent.com/assets/3244310/15319208/5b735d6a-1c47-11e6-8d63-956a54c3493c.png)
Rails version - 4.1.4
Ruby version - 2.0.0

```
ActionView::Template::Error (undefined local variable or method `root_path' for #<#<Class:0xb10bc3c>:0xb10b570>):
    19:         <%= link_to t('doorkeeper.layouts.admin.nav.applications'), oauth_applications_path %>
    20:       <% end %>
    21:       <%= content_tag :li do %>
    22:         <%= link_to 'Home', root_path %>
    23:       <% end %>
    24:     </ul>
    25:   </div>
```

Any inputs on this would be very helpful .

**Comment by tute** [comment]
Do you have defined a root route in your `config/routes.rb` file? For example, `root to: 'home#index'`, or similar.

**Comment by kumardev** [comment]
@tute I defined the route for root and the issue got solved , thanks for pointing out .

**Comment by tute** [comment]
👍
