### ISSUE TITLE
Any way to use client_credentials flow in a controller instead of bearer grant?

### ISSUE THREAD

**Issue by cbetta** [doorkeeper-gem/doorkeeper#851]
I want to return something over API that does not belong to an authenticated user yet. Currently I first need to use the `client_credentials` grant on `/oauth/token` to get an `access_token` and then call the API. Is it possible to do this in 1 API call?

**Comment by tute** [comment]
You need to perform both calls: one to get the token, with which you can query the API. Thanks!

**Comment by cbetta** [comment]
@tute thanks for clarifying.
