### ISSUE TITLE
undefined local variable or method `root_path`

### ISSUE THREAD

**Issue by Morpheu5** [doorkeeper-gem/doorkeeper#854]
I'm getting the same as #821 when in `api_only` mode, and the following

    #<ActionView::Template::Error: undefined local variable or method `root_path' for #<#<Class:0x007fc9342dd340>:0x007fc9390285f0> Did you mean? font_path>

when I turn `api_only` to false. I generated the app with `--api` so initial conditions may be different from those of the OP in #821.

**Comment by tute** [comment]
Can you show your routes file, please?

**Comment by Morpheu5** [comment]
Sure, sorry.

```
Rails.application.routes.draw do
  use_doorkeeper
  resources :presets
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

**Comment by tute** [comment]
You need to define a `root` path. See http://guides.rubyonrails.org/routing.html#using-root.

**Comment by tute** [comment]
That's where the application goes when you visit `/`.

**Comment by Morpheu5** [comment]
Ah, yes… I keep tripping over the fact that I'm making an API and Doorkeeper has a web interface. It would be really nice if we could disable it. I'd like to keep my API minimal and develop a front-end to manage it, including managing Doorkeeper.

**Comment by tute** [comment]
> It would be really nice if we could disable it

I'm not against this feature. Thanks for reporting!

**Comment by realvjy** [comment]
My routes here

root 'static_pages#home'
get 'help', to: 'static_pages#help'
get 'about', to: 'static_pages#about'

Error
![image](https://cloud.githubusercontent.com/assets/7387461/23338553/28f00fbe-fc34-11e6-92bc-70754540ae2b.png)
