### ISSUE TITLE
4.0.0 on RubyGems?

### ISSUE THREAD

**Issue by connorshea** [doorkeeper-gem/doorkeeper#856]
Sorry if I missed an existing issue about this, I tried looking around but couldn't find anything. Since Rails 5 came out yesterday, is there any chance of a doorkeeper release compatible with it?

Thanks for all the work you do on the gem, it really is appreciated ❤️

**Comment by tute** [comment]
Thanks for your message! v4 betas and master are ready for Rails 5. Want to prepare a release, sending a PR with the code changes outlined in https://github.com/doorkeeper-gem/doorkeeper/blob/master/RELEASING.md? Thank you! 😃

**Comment by connorshea** [comment]
@tute sounds good to me! I'll mention you on it in a few minutes :)

**Comment by tute** [comment]
Yay, thank you! Closing in favor of PR. ❤️
