### ISSUE TITLE
Mongoid::Errors::DocumentNotFound in Doorkeeper::AuthorizationsController#new

### ISSUE THREAD

**Issue by whoteaches** [doorkeeper-gem/doorkeeper#862]
I upgraded doorkeeper today and I'm getting this mongoid error: Mongoid::Errors::DocumentNotFound in Doorkeeper::AuthorizationsController#new
I wasn't sure whether I should post this issue here or on https://github.com/doorkeeper-gem/doorkeeper-mongodb, but since this update was introduced in your main gem, I decided to post here.
Basically, it fails at creating an access_token, so there's no entry in the database and then it gives the not_found error.
Pls advise and thanks for a wonderful gem!

**Comment by tute** [comment]
This belongs in https://github.com/doorkeeper-gem/doorkeeper-mongodb, and that project has no active maintainer. Thank you, and sorry I'm not able to help you with this.

**Comment by pabloq** [comment]
hey @whoteaches  did you find any solution on this? I don't wanna use raise_not_found_error: false in mongoid config file...

**Comment by pabloq** [comment]
here is a fix: https://github.com/doorkeeper-gem/doorkeeper-mongodb/pull/19/files
