### ISSUE TITLE
How do I write tests with no token, or an invalid token?

### ISSUE THREAD

**Issue by Morpheu5** [doorkeeper-gem/doorkeeper#864]
With reference to [this](https://github.com/doorkeeper-gem/doorkeeper/wiki/Testing-protected-controllers), I'm wondering how I can test my controllers when requested without access token, or with a token for a user that is not authorised to make certain requests, or in certain ways.

**EDIT** A first workaround was to move the declarations inside each context, like

```ruby
    context 'when not logged in as a user' do
        let(:token) { double :acceptable? => false, :accessible? => true }
        before do
            allow(controller).to receive(:doorkeeper_token) { token }
        end

    	describe 'GET #index' do
            it 'responds with 401' do
    			get :index
    			expect(response).to have_http_status(401)
    		end
    	end
    end
    
    context 'when logged in as a user' do
        let(:token) { double :acceptable? => true }
        before do
            allow(controller).to receive(:doorkeeper_token) { token }
        end

    	describe 'GET #index' do
            it 'shows a list of all the users' do
    			get :index
    			expect(response).to have_http_status(200)
    			body = JSON.parse(response.body)
    			expect(body.count).to eq(4)
    		end
    	end
    end
```

Now, questions:

1. What is the meaning of `:accessible?`, and why does my controller receive it?
2. How would I go about simulating different authorisation levels, like user, editor, admin… considering that I'm relying on my own user model, and the only knowledge that Doorkeeper seems to have is regarding whether a user is an admin or not?

**Comment by tute** [comment]
> What is the meaning of `:accessible?`, and why does my controller receive it?

The definition of `accessible?` is `!expired? && !revoked?`, meaning: available current token.

> How would I go about simulating different authorisation levels, like user, editor, admin… considering that I'm relying on my own user model, and the only knowledge that Doorkeeper seems to have is regarding whether a user is an admin or not?

You can configure this with `resource_owner_authenticator`. Do you have something like `User.find(doorkeeper_token.resource_owner_id)` in your code? In that case, you can create a token with the foreign key to whichever user you want to test with.

Does this answer your questions?

**Comment by Morpheu5** [comment]
So far I had been stubbing like

    allow(controller).to receive(:doorkeeper_token) { nil }

to simulate being denied authentication, or

    let(:token) { double :acceptable? => true, :resource_owner_id => @users[1].id

to simulate a particular user. Is this equivalent to what you suggest? Or how is it different?

**Comment by tute** [comment]
That looks good to me, and it's how I would do it. Is there anything else you'd like to discuss for this one issue?

**Comment by Morpheu5** [comment]
No, happy to close it, thanks 👍
