### ISSUE TITLE
Mongoid issue- undefined method `refresh_token_revoked_on_use?' for Doorkeeper::AccessToken:Clas

### ISSUE THREAD

**Issue by shipdcare** [doorkeeper-gem/doorkeeper#866]
<img width="1096" alt="screen shot 2016-07-13 at 12 39 45 pm" src="https://cloud.githubusercontent.com/assets/12561390/16794683/ee011d62-48f6-11e6-8c28-c06af59aa9a7.png">

**Comment by tute** [comment]
Unfortunately https://github.com/doorkeeper-gem/doorkeeper-mongodb may be out of date, and has no maintainer.

**Comment by tute** [comment]
Closing in favor of https://github.com/doorkeeper-gem/doorkeeper-mongodb/issues/16.
