### ISSUE TITLE
Using doorkeeper in Rails 5 API mode

### ISSUE THREAD

**Issue by CaptainStiggz** [doorkeeper-gem/doorkeeper#869]
I'm getting an error trying to set up an application using the web interface with a Rails 5 API mode app. Is there a console command for generating a new application?

http://localhost/oauth/applications

```
ActionView::Template::Error (undefined local variable or method `new_oauth_application_path' for #<#<Class:0x007fcd2db2bea0>:0x007fcd2db0b498>):
    2:   <h1><%= t('.title') %></h1>
    3: </div>
    4: 
    5: <p><%= link_to t('.new'), new_oauth_application_path, class: 'btn btn-success' %></p>
    6: 
    7: <table class="table table-striped">
    8:   <thead>
```

**Comment by tute** [comment]
Doorkeeper views don't work on an `api_mode = true` app. See https://github.com/doorkeeper-gem/doorkeeper/issues/821#issuecomment-212562425. Thanks!

**Comment by CaptainStiggz** [comment]
@tute Thanks for getting back to me!

I created a simple rake task that lives in `lib/taks/doorkeeper.rake`. I'm pretty new to Rails, so I'm not sure if this is the best solution. I wasn't quite sure what the format for scopes should look like, so I omitted it. Are scopes stored in the database as such?

```
+-------------+
| scope       |
+-------------+
| user, admin |
| user        |
| public      |
+-------------+
```
```
include Doorkeeper

namespace :doorkeeper do
  desc 'Creates an OAuth2 client for Doorkeeper'
  task :create_client => :environment do
    
    #check the variables
    if ENV['NAME'].blank? or ENV['REDIRECT_URI'].blank?
      puts "Usage: rake doorkeeper:create_client NAME=name REDIRECT_URI=redirect_uri"
      exit
    end
    
    #create the application
    @application = Doorkeeper::Application.new({:name => ENV['NAME'], :redirect_uri => ENV['REDIRECT_URI']})
    if @application.save
      puts "Created Doorkeeper OAuth2 client with (name: "+@application.name+", redirect_uri: "+@application.redirect_uri+")" 
      puts "client_id: "+@application.uid
      puts "client_secret: "+@application.secret
    else
      puts @application.errors.full_messages
    end
  end
end
```

One other quick question/consideration. I was able to generate an access token using the password grant_type without supplying client credentials. For example, the following returns an access token:

`app.post '/oauth/token', params: {:username => "username", :password => "password"}`

If I wanted to restrict token grants so client_id and client_secret are mandatory, ie:

`app.post '/oauth/token', params: {:username => "username", :password => "password", :client_id => 'XXXX', :client_secret => 'XXXX' }`

Would I need to do so in a custom implementation of `resource_owner_for_credentials`?

**Comment by tute** [comment]
> If I wanted to restrict token grants so client_id and client_secret are mandatory [...]

The OAuth spec doesn't require client id when retrieving access token in password grant flow. Password grant flows have inherent security risks (https://tools.ietf.org/html/rfc6819#section-4.4.3), and should be used only if you know how they affect you.

---

The rake task you present has a few issues, which are better worked through in person. In NYC I attend workshop and project meetups (meetup.com), and if you are here that's a good spot where to meet and code. Do you have such resources where you live?

Thanks!
