### ISSUE TITLE
Ability to require valid client_secret when using refresh_token

### ISSUE THREAD

**Issue by avatarandrij** [doorkeeper-gem/doorkeeper#874]
I enabled refresh token, and it's working perfectly, except I  cant figure out how to require client_secret on refresh. 

Request

```
{
"grant_type":"refresh_token",
"refresh_token":"872049f90db52181bf038b8d1aee80076d913920a65bfd75b3fb7b0321754e0d"
}
```

works if refresh token is valid

but I need to force user use only requests like this:

```
{
"client_id":"821864185e6e1b201494e38f51d4d754ad39541b11cd512210c49f2db51affae",
"client_secret":"02e531d32fe251e58a5f632895bde09513dc5260c6da12c8816b7624cdb54e83",
"grant_type":"refresh_token",
"refresh_token":"872049f90db52181bf038b8d1aee80076d913920a65bfd75b3fb7b0321754e0d"
}
```

It's not possible without monkey patching now:
 file: doorkeeper/lib/doorkeeper/request/refresh_token.rb

```
      def validate_client
        !credentials || !!client
      end
```

invalid credentials is ignored, without ability to disable this

**Comment by tute** [comment]
This issue seems the contrary to https://github.com/doorkeeper-gem/doorkeeper/issues/739. What is the case? Do we require or not client authentication? Remember that this will depend on the type of grant being used. Thanks!

**Comment by nbulaj** [comment]
Take a look at RFC: https://tools.ietf.org/html/rfc6749#section-1.5

>    (G)  The client requests a new access token by authenticating with
>         the authorization server and presenting the refresh token.  The
>         client authentication requirements are based on the client type
>         and on the authorization server policies.

>    (H)  The authorization server authenticates the client and validates
>         the refresh token, and if valid, issues a new access token (and,
>         optionally, a new refresh token).
