### ISSUE TITLE
Allowing custom expiration time for access tokens per application

### ISSUE THREAD

**Issue by zmoti** [doorkeeper-gem/doorkeeper#876]
I am using implicit grant flow for my mobile application and I would like to configure the access tokens to never expire but only for the mobile application. Is it possible to configure this? 

Alternatively, is there a method I can specifically call to set the refresh token expiration to nil for a particular resource owner? I could use this to create an API endpoint which could check user's application ID and then update the `expires_in` column to be nil. 

I went through closed issues, but none of them really had a solution other than to set globally the access token expires in time to nil.

**Comment by tute** [comment]
> I am using implicit grant flow for my mobile application and I would like to configure the access tokens to never expire but only for the mobile application. Is it possible to configure this?

Implicit flows can't securely authenticate the client, so I wouldn't do so.
