### ISSUE TITLE
A more verbose 'Filter chain halted as :doorkeeper_authorize! rendered or redirected'

### ISSUE THREAD

**Issue by bsylvain** [doorkeeper-gem/doorkeeper#880]
I am upgrading Doorkeeper from 1.7 to 4.0.

The client hit /oauth/token with a 200 but get a 403 when hitting the API.

`Filter chain halted as :doorkeeper_authorize! rendered or redirected`

I keep getting this error that seems token related, but I am not sure if I need to update my client (that worked before migration) or if I missed some migration step. Is there a way to have a more verbose error message from doorkeeper_authorize ?

**Comment by bsylvain** [comment]
Ok so it seems that as soon as you declare scopes in doorkeeper.rb, you have to explicitely authorize scopes in doorkeeper_authorize.

**Comment by nbulaj** [comment]
So what the status of the issue, @bsylvain ? Did you solve the problem?

**Comment by tute** [comment]
So he says. Thank you both! :)
