### ISSUE TITLE
[meta] Add doorkeeper-openid_connect to the organization

### ISSUE THREAD

**Issue by toupeira** [doorkeeper-gem/doorkeeper#883]
I'm planning to make some updates to the `doorkeeper-openid_connect` gem and was [recommended to fork it](https://github.com/playon/doorkeeper-openid_connect/issues/17), so now I'm wondering if you would be willing to fork it straight to the `doorkeeper-gem` organization and give me push access to the repository?

Also a transfer (rather than a fork) would be cleaner, if you prefer that I'll ask them about it.

**Comment by tute** [comment]
Please do ask for the transfer, and I'll grant you access. Thanks!

**Comment by toupeira** [comment]
Ok @stephendyer should add you to the repository soon so you can initiate the transfer. Let me know if I can be of any assistance!

**Comment by tute** [comment]
Added you both!

**Comment by toupeira** [comment]
@tute thanks! Looks like the repository is still missing at https://github.com/orgs/doorkeeper-gem/teams/doorkeeper-openid_connect/repositories though :)

**Comment by tute** [comment]
Added! Thank you.

**Comment by toupeira** [comment]
@tute thanks, I'm able to push now. Can you also give me admin access to the repository? Some tools like Travis CI require it for setting up webhooks.

**Comment by tute** [comment]
Done.
