### ISSUE TITLE
Refresh Token Allows Replay Attacks

### ISSUE THREAD

**Issue by jimjeffers** [doorkeeper-gem/doorkeeper#886]
Hey there,

Not sure if this is per the spec, a bug, or a mistake on my part. But essentially I'm able to constantly refresh my access token with the same refresh token. I was under the impression once you used a refresh token it could not be used again. Here's my current setup:

rails (5.0.0.1) (api only app)
doorkeeper (4.2.0)

```
Doorkeeper.configure do

  orm :active_record

  resource_owner_authenticator do
    current_user || redirect_to(login_url)
  end

  resource_owner_from_credentials do
    user = User.find_for_database_authentication(email: params[:username])
    user if user && user.valid_password?(params[:password])
  end

  access_token_expires_in 10.minutes

  use_refresh_token

  default_scopes  :public
  optional_scopes :write, :update

  force_ssl_in_redirect_uri !Rails.env.development?

  grant_flows %w(password)

end
```

So here's what happens:

[grant_type: password]
http://127.0.0.1:3000/oauth/token

```
{
    "access_token": "28e68da90f162c9f8d6193cff29f658fca33516e731f4212a3437a1a55203415",
    "token_type": "bearer",
    "expires_in": 600,
    "refresh_token": "495240b7eb119031da381ecdefea3a77af172067b123b3757da1b30decbff7f3",
    "scope": "public",
    "created_at": 1474651785
}
```

[grant_type: refresh_token]
[495240b7eb119031da381ecdefea3a77af172067b123b3757da1b30decbff7f3]
http://127.0.0.1:3000/oauth/token

```
{
    "access_token": "663707f47f89db676b9b6602a7db22ae53c7ea4dbb1ee3d442ecc99b976e7853",
    "token_type": "bearer",
    "expires_in": 600,
    "refresh_token": "b8a6d75ce84e97795ef79f04fcee2286fcd52ffdaa1a3a1f7f4bebf74cee1f6f",
    "scope": "public",
    "created_at": 1474651904
}
```

Sending again:
[grant_type: refresh_token]
[495240b7eb119031da381ecdefea3a77af172067b123b3757da1b30decbff7f3]
http://127.0.0.1:3000/oauth/token

```
{
    "access_token": "fd854a6120dee9ae92086418a27bff2034b86ff0b630104d5570f16aa0cc7a84",
    "token_type": "bearer",
    "expires_in": 600,
    "refresh_token": "a5409273fc958bb2363a1212d0bff9430b5a17b2bad16867141f7ed9d5d1df46",
    "scope": "public",
    "created_at": 1474651960
}
```

In the console:

```
2.3.0 :003 > Doorkeeper::AccessToken.where(previous_refresh_token: "495240b7eb119031da381ecdefea3a77af172067b123b3757da1b30decbff7f3").count

 => 2
```

Should that be possible? I thought this could only happen once but I can repeat as much as I'd like. Thanks for any help!

**Comment by nbulaj** [comment]
https://tools.ietf.org/html/rfc6749#section-6

>   The authorization server MAY issue a new refresh token, in which case
>    the client MUST discard the old refresh token and replace it with the
>    new refresh token.  The authorization server MAY revoke the old
>    refresh token after issuing a new refresh token to the client.  If a
>    new refresh token is issued, the refresh token scope MUST be
>    identical to that of the refresh token included by the client in the
>    request.

**Comment by tute** [comment]
This is related with https://github.com/doorkeeper-gem/doorkeeper/issues/884. I believe doorkepeer now does follow the spec, and the attack is allowed by it.

That's a low bar though, and if you can suggest a backwards-compatible, safer default I'm all for it. We can continue discussing here or in a PR.

Thank you very much for your input.
