### ISSUE TITLE
401 Unauthorized -- Invalid grant when requesting refresh token.

### ISSUE THREAD

**Issue by eebasadre** [doorkeeper-gem/doorkeeper#887]
I'm having a trouble in requesting a refresh token, it keep returning an Unauthorized 401 error. I don't know if I'm lacking a parameters that I passed when I did a request.

I added the doorkeeper configuration for refresh token.

`use_refresh_token`

Here's the request details:

`{{root_url}}/oauth/token`

    {"refresh_token"=>"034a74c085219fb8297fd8ef9b59f080918f"
     "format"=>:json,
     "controller"=>"/oauth/tokens",
     "action"=>"create",
     "grant_type"=>"refresh_token",
     "client_id"=>"<client_id>",
     "client_secret"=> "<client_secret>"}

Error descriptions:

    {:error=>:invalid_grant,
     :error_description=>
      "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}

Btw, all of my api request authentication is not failing just this refresh token. I wonder what I'm missing in the request parameters.

**Comment by Sarmadpikessoft** [comment]
@eebasadre why you close the issue. i didn't see any solution here.

**Comment by wqsaali** [comment]
@eebasadre why did you close the issue. if there is not solution available?

**Comment by ideaoforder** [comment]
I'm actually having this same issue. How did you end up solving this @eebasadre?

**Comment by kevinetore** [comment]
@ideaoforder Did you fix this? I'm having the exact same issue.

**Comment by jeremypele** [comment]
Any update on this @ideaoforder @eebasadre ?

**Comment by prcongithub** [comment]
I am also facing the same issue.

**Comment by nbulaj** [comment]
Do you enabled required grant type in Doorkeeper initializer?

**Comment by reinvanimschoot** [comment]
Is there anyone who has a solution to this?
