### ISSUE TITLE
Destroying an OAuth Application can lead to a large number of SQL queries

### ISSUE THREAD

**Issue by davefp** [doorkeeper-gem/doorkeeper#888]
Rails 4.2.7.1
Doorkeeper 4.2.0

When an OAuth Application is destroyed e.g. `Doorkeeper::Application.first.destroy` all associated Access Tokens are also destroyed.

However, this is done using `dependent: :destroy` as seen here in the application mixin: https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/models/application_mixin.rb#L11

The problem is that ActiveRecord loads all the dependent tokens and destroys them one-by-one. For a long-running application, this can run into the thousands.

My personal experience with this was that a web request to destroy an application was bumping into our 10 second timeout thanks to all the DB calls.

I'm aware that there has been discussion about deleting tokens previously, and that my issue is more of a QoL problem than a hard 'bug', but it was certainly unexpected.

My gut feeling is that it's safe to simply do a `dependent: delete_all` on the tokens instead, which would make a single SQL query rather than one per token.

**Comment by tute** [comment]
> My gut feeling is that it's safe to simply do a dependent: delete_all on the tokens instead, which would make a single SQL query rather than one per token.

I agree. Would you please submit a PR addressing this? Thanks!
