### ISSUE TITLE
Interacting as an OAuth client with Doorkeeper ERROR

### ISSUE THREAD

**Issue by Blackening999** [doorkeeper-gem/doorkeeper#890]
While following this guide: https://github.com/doorkeeper-gem/doorkeeper/wiki/Interacting-as-an-OAuth-client-with-Doorkeeper#requesting-the-grant

I've stuck on "Requesting the Grant" step. With error report provided below:
http://prntscr.com/cokabc

I'm clicking "Authorize" from the recently created application.

What I'm doing wrong?
I'm pretty sure the "current_resource_owner" can be nullable... but it is not.

please, advise

**Comment by Blackening999** [comment]
I think the issue is because the AuthorizationController what is being invoked instead of TokenController. It isn't possible to have current_user at the stage of authorizing tokens

It's super urgent.

**Comment by nbulaj** [comment]
Hi @Blackening999. Don't even understand why you are trying to prompt the user to grant the access and have not authenticated user? Who will get that grant in that case? `AuthorizationsController` requires authenticated User.

**Comment by tute** [comment]
The issue you describe seems very specific to your code. I suggest that you ask about it in https://stackoverflow.com/questions/tagged/doorkeeper, which will get attention from more people than in this issue tracker.

Also, I recommend you follow the steps outlined in http://yourbugreportneedsmore.info/, so that people can better replicate or understand your issue in order to help you.

Sorry we don't have the time now to help you with this question, and thanks!

**Comment by Blackening999** [comment]
Hey @tute and @nbulaj 
Thanks for feedback!

It was long age and I already solved the issue by re-writing a lot of code. Doorkeeper by default is unable to work without sessions. I have a token based authentication so I don't have any "current_user" saved on back-end, which Doorkeeper relies the most during OAuth authorization process. I haven't got a time to reveal a solution, in short: it simply authenticate user by ownership to a specific OAuth application, so the only authorized user will be able to authenticate this way (by client id and secret in HTTP headers), and then I was able to cut in the chain when Doorkeeper is able to keep the rest process (but honestly I'd better write my own implementation from ground-up rather than using that library, no offense it's just too old).

If you still think my case is rare or very code-specific - try the very simple task. Integrate with Zapier using OAuth standard (Facebook following it as for example) without supporting sessions on back-end.

Best Regards

**Comment by tute** [comment]
Thank you for your feedback @Blackening999.

To understand better this problem, even though your token-based authentication, why do you need it not keeping sessions? Shouldn't that be transparent to the client?

And if you are the client (with Zapier for example) why do you need doorkeeper, which sets up the provider?

Thank you for your time discussing this.

**Comment by Blackening999** [comment]
@tute 

First of all because session are dinosaurs, and the real reason is that we're using always a back-end as API :) I haven't used sessions from the past 2 years, it's only JWT.
And yes, token-based authentication is more transparent and more performant, tokens being updated each 15 minutes.

For what we need Doorkeeper while integrating with Zapier - we need to authenticate and define user who creates integration(Zap) between 3rd party and our product. I think it's obvious.
So the OAuth strategy with refreshing token looks most appropriate in this matter.
Do you know other reliable and secure ways?

**Comment by tute** [comment]
I think using doorkeeper for token-based authentication is killing a mosquito with a cannon. OAuth is an absurdly configurable authorization framework, with many insecure options, that can mimic a simple token-based authentication solution.

Would Rails' `authenticate_or_request_with_http_token` with logic for refreshing the tokens (an extra class you'd write) suffice for your case?

**Comment by Blackening999** [comment]
the main problem is we don't want our customers run to a Zapier and enter new token once current one expires + we want to keep integrations diversified. Using OAuth applications from our end guarantees granularity per each user-integration pair and allows Zapier to refresh a token once current one expires.

Sure, I thought about authenticate_or_request_with_http_token , but it looks way less secure and it isn't allowing us to define a strict ownership per user
