### ISSUE TITLE
When generating Access Token immediately after generating the Authorization Code, the Authorization Code is not found in the "oauth_access_grants" table - MySQL Cluster (Percona XtraDB Cluster)

### ISSUE THREAD

**Issue by t-anjan** [doorkeeper-gem/doorkeeper#894]
My DB setup is using a cluster of 3 nodes running "Percona XtraDB Cluster" (PXC). This is "almost" synchronous replication. Reason for the "almost" explained below.

When I am using Doorkeeper for authorization (auth_code flow), the auth code gets generated (`/oauth/authorize`) and redirects back to the callback action. Then, omniauth-oauth2 gem makes another call to doorkeeper (`/oauth/token`) to get the access token. This latter call is made within a second or so of the `/oauth/authorize` call.

This is processed by `Doorkeeper::TokensController#create` which receives the auth code as one of the params. There, it checks if the auth code exists in the `oauth_access_grants` table. 

Normally, this works properly, of course. But when I am using a multi-node cluster of databases, if the first call (`/oauth/authorize`) accesses `DB Node A` to insert the auth code, and if the second call (`/oauth/token`) accesses `DB Node B` to check for the auth code, in some cases, this check comes back false. So, the whole login procedure fails.

PXC has a config setting to avoid this: https://www.percona.com/doc/percona-xtradb-cluster/5.6/wsrep-system-index.html#wsrep_sync_wait
### variable wsrep_causal_reads

> In some cases, master may apply event faster than a slave, which can cause master and slave to become out of sync for a brief moment. When this variable is set to ON, slave will wait until that event is applied before doing any other queries. **Enabling this variable will also result in larger latencies.**
### variable wsrep_sync_wait

> This variable is used to control causality checks on some SQL statements, such as SELECT, BEGIN/END, SHOW STATUS, but not on some autocommit SQL statements UPDATE and INSERT. Causality check is determined by bitmask:
> 
> ```
>     1 Indicates check on READ statements, including SELECT, SHOW, BEGIN/START TRANSACTION.
>     2 Indicates check on UPDATE and DELETE statements.
>     4 Indicates check on INSERT and REPLACE statements
> ```
> 
> This variable replaced the wsrep_causal_reads variable. Setting wsrep_sync_wait to 1 is the equivalent of setting wsrep_causal_reads to ON.

Setting `wsrep_sync_wait` to 1 in `my.cnf` fixes this issue for me, but it takes effect for my whole application, slowing down ALL queries.

`wsrep_sync_wait` is a session variable. So, we should be able to do the following:

```
SET SESSION wsrep_sync_wait = 1;
SELECT * FROM example WHERE field = “value”;
SET SESSION wsrep_sync_wait = 0;
```

The application runs the first SET command to enable wsrep_sync_wait. In the next command, the application sends the SELECT query. The node initiates a causality check, blocking incoming queries while it catches up with the cluster. When the node finishes applying the new transactions, it executes the SELECT query, returning the results to the application. The application, having finished the critical read, disables wsrep_sync_wait, returning the node to normal operation.

So, I need to run the SET command in the `AccessGrantMixin`'s `by_token` method, before and after the `find_by`.

I understand that this would be a very specific patch, specific to users of PXC. So, any suggestions would be welcome.

**Comment by tute** [comment]
Hi @t-anjan, thanks for your report.

Is monkey patching `Doorkeeper::AccessGrant#by_token(token)` an option for you? If not, what extension mechanism would be useful for your case?

Thanks!

**Comment by t-anjan** [comment]
Monkey patching is definitely an option if this cannot be handled in the gem. Are there any other options?

I was thinking of changing the `by_token` method to something like this:

```
      def by_token(token)
        is_mysql = connection.adapter_name.downcase.starts_with?('mysql')
        cluster_size = 1

        if is_mysql
          res = connection.execute("SHOW GLOBAL STATUS LIKE 'wsrep_cluster_size';")
          cluster_size = res.try(:to_h).try(:fetch, 'wsrep_cluster_size', 1).try(:to_i) || 1
        end
        
        connection.execute("SET SESSION wsrep_sync_wait=1;") if cluster_size > 1
        find_by(token: token.to_s)
        connection.execute("SET SESSION wsrep_sync_wait=0;") if cluster_size > 1
      end
```

**Comment by tute** [comment]
What about using a Strategy Pattern to be able to plug in the different strategies?
https://dockyard.com/blog/2013/07/25/design-patterns-strategy-pattern

**Comment by tute** [comment]
Closing this issue for now, as it's very specific to your app. I'd discuss a Strategy Pattern in a PR. Thank you!
