### ISSUE TITLE
show possible scopes in UI

### ISSUE THREAD

**Issue by grosser** [doorkeeper-gem/doorkeeper#896]
I want to show our users which scopes are allowed ...

```Ruby
Doorkeeper.configure do
  scopes ['default', 'projects', 'products', 'users']
end
```

This should then be shown in the UI via `doorkeeper.applications.help.scopes` and ideally be enforced via validations ... does that sound like something you'd merge ? ... I can try to make a PR ...

**Comment by tute** [comment]
That makes sense to me, somewhere in the layout or index action. I'm interested in seeing your PR!

**Comment by grosser** [comment]
looks like this already exists ... it's called `optional_scopes` ... not really sure what they are used for, but I'd simply add a validation on ApplicationMixing to validate that all scopes are in `scopes` (default + optional) ... does that sound about right ?

This would be opt-in behind a new `validate_application_scopes` flat ...

**Comment by grosser** [comment]
once I add optional scopes I get a big fat `The requested scope is invalid, unknown, or malformed.` ... not very helpful ... should say what scope I tried to use ...

**Comment by tute** [comment]
I thought you meant the admin interface, sorry about my misunderstanding.

The error message follows the spec as of https://tools.ietf.org/html/rfc6749#section-4.1.2.1.

I don't think we need to do any change in how doorkeeper handles scopes, so I'll close this issue, but I'm happy to continue further discussion around this and if you pinpoint improvements that we should make, we work through them.

Thanks!

**Comment by aharpervc** [comment]
I also had a similar question and found this existing issue.

> The error message follows the spec as of https://tools.ietf.org/html/rfc6749#section-4.1.2.1.

I see that is the case, and that current error description is the text from the spec explaining what `invalid_scope` means. However, the spec for `error_description` only says:

> OPTIONAL.  Human-readable ASCII [[USASCII](https://www.rfc-editor.org/rfc/rfc6749#ref-USASCII)] text providing
         additional information, used to assist the client developer in
         understanding the error that occurred.
         Values for the "error_description" parameter MUST NOT include
         characters outside the set %x20-21 / %x23-5B / %x5D-7E.

I don't interpret this as meaning the _only_ compliant values for this field are the explanatory text for the `error` code field. Instead, the spec recommends filling in _additional_ information, _besides_ the `error` field.

> not very helpful ... should say what scope I tried to use ...

I agree, and I think including the requested invalid scope(s) in the error description would solve this, and seems compatible with the spec.

Thoughts?
