### ISSUE TITLE
accessing authorization url using oauth2 gem.

### ISSUE THREAD

**Issue by yottanami** [doorkeeper-gem/doorkeeper#905]
I just checked this document:
https://github.com/doorkeeper-gem/doorkeeper/wiki/Testing-your-provider-with-OAuth2-gem

There is mentioned that for accessing authorization code I have to open the authorization url in browser.
The problem is I have to do this after each deployment or change on server manually.
Is there anyway to access it using code without opening the browser?

**Comment by tute** [comment]
> Is there anyway to access it using code without opening the browser?

Not that I know of. The user has to manually authorize access. I don't see why you'd need to do it on each deploy though.

I suggest that you ask about it in https://stackoverflow.com/questions/tagged/paperclip, which will get attention from more people than in this issue tracker.

Thanks!
