### ISSUE TITLE
i really don't understand the *invalid redirect url* problem

### ISSUE THREAD

**Issue by krtschmr** [doorkeeper-gem/doorkeeper#912]
`http://localhost:3000/oauth/authorize?client_id=54519be2a7ceb7d6d445a7d64c53f33b7b97ec66ea54e3ab4b595f8fd08ea442&redirect_uri=http://forum.cattle.com/upload/index.php?google-auth&state=4bddb12a0edb993e195b2031f63308a72c50a091&scope=public&response_type=code`

why is that constantly giving me an invalid redirect url?
i try to connect a WBB forum but constantly i get the redirection exception.

obviously i have 100% exactly the same URI as redirect_path in my application

`Callback urls:

http://forum.cattle.com/upload/index.php?google-auth
`

what am i missing?

**Comment by tute** [comment]
(This is somewhat related with https://github.com/doorkeeper-gem/doorkeeper/issues/716).

Do you have `force_ssl_in_redirect_uri` enabled? In that case, you'll need to use HTTPS.

**Comment by krtschmr** [comment]
`# force_ssl_in_redirect_uri !Rails.env.development?`

i run it in development mode.

**Comment by tute** [comment]
Current master (doorkeeper 4.2), and with that configuration set to false, accepts your URL. What version of doorkeeper are you using?

**Comment by krtschmr** [comment]
bundle shows
`  * doorkeeper (4.2.0)`

unfortunately with `http://www.google.com` it's working.

**Comment by krtschmr** [comment]
these 2 URLS

![image](https://cloud.githubusercontent.com/assets/13366714/21222863/b1e9beea-c2f6-11e6-92fe-42c2e5df0c20.png)


```


Started GET "/oauth/authorize?client_id=54519be2a7ceb7d6d445a7d64c53f33b7b97ec66ea54e3ab4b595f8fd08ea442&redirect_uri=http%3A%2F%2Fforum.cattle.com%2Fupload%2Findex.php%3Fgoogle-auth&response_type=code&scope=" for 10.0.2.2 at 2016-12-15 18:46:02 +0700
Processing by Doorkeeper::AuthorizationsController#new as HTML
  Parameters: {"client_id"=>"54519be2a7ceb7d6d445a7d64c53f33b7b97ec66ea54e3ab4b595f8fd08ea442", "redirect_uri"=>"http://forum.cattle.com/upload/index.php?google-auth", "response_type"=>"code", "scope"=>""}
  User Load (0.4ms)  SELECT  `users`.* FROM `users` ORDER BY `users`.`id` ASC LIMIT 1
  Doorkeeper::Application Load (0.3ms)  SELECT  `oauth_applications`.* FROM `oauth_applications` WHERE `oauth_applications`.`uid` = '54519be2a7ceb7d6d445a7d64c53f33b7b97ec66ea54e3ab4b595f8fd08ea442' LIMIT 1
  Rendering /home/tim/.rvm/gems/ruby-2.3.0/gems/doorkeeper-4.2.0/app/views/doorkeeper/authorizations/error.html.erb within layouts/doorkeeper/application
  Rendered /home/tim/.rvm/gems/ruby-2.3.0/gems/doorkeeper-4.2.0/app/views/doorkeeper/authorizations/error.html.erb within layouts/doorkeeper/application (0.5ms)
Completed 200 OK in 9ms (Views: 6.2ms | ActiveRecord: 0.7ms)


cache: [GET /oauth/authorize?client_id=54519be2a7ceb7d6d445a7d64c53f33b7b97ec66ea54e3ab4b595f8fd08ea442&redirect_uri=http%3A%2F%2Fforum.cattle.com%2Fupload%2Findex.php%3Fgoogle-auth&response_type=code&scope=] miss
Started GET "/oauth/authorize?client_id=54519be2a7ceb7d6d445a7d64c53f33b7b97ec66ea54e3ab4b595f8fd08ea442&redirect_uri=http%3A%2F%2Fwww.google.de&response_type=code&scope=" for 10.0.2.2 at 2016-12-15 18:46:03 +0700
Processing by Doorkeeper::AuthorizationsController#new as HTML
  Parameters: {"client_id"=>"54519be2a7ceb7d6d445a7d64c53f33b7b97ec66ea54e3ab4b595f8fd08ea442", "redirect_uri"=>"http://www.google.de", "response_type"=>"code", "scope"=>""}
  User Load (0.3ms)  SELECT  `users`.* FROM `users` ORDER BY `users`.`id` ASC LIMIT 1
  Doorkeeper::Application Load (0.3ms)  SELECT  `oauth_applications`.* FROM `oauth_applications` WHERE `oauth_applications`.`uid` = '54519be2a7ceb7d6d445a7d64c53f33b7b97ec66ea54e3ab4b595f8fd08ea442' LIMIT 1
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` ORDER BY `users`.`id` ASC LIMIT 1  [["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` ORDER BY `users`.`id` ASC LIMIT 1  [["LIMIT", 1]]
  Doorkeeper::AccessToken Load (0.3ms)  SELECT  `oauth_access_tokens`.* FROM `oauth_access_tokens` WHERE `oauth_access_tokens`.`application_id` = 1 AND `oauth_access_tokens`.`resource_owner_id` = 1 AND `oauth_access_tokens`.`revoked_at` IS NULL ORDER BY created_at desc LIMIT 1
  Rendering /home/tim/.rvm/gems/ruby-2.3.0/gems/doorkeeper-4.2.0/app/views/doorkeeper/authorizations/new.html.erb within layouts/doorkeeper/application
  Rendered /home/tim/.rvm/gems/ruby-2.3.0/gems/doorkeeper-4.2.0/app/views/doorkeeper/authorizations/new.html.erb within layouts/doorkeeper/application (5.8ms)
Completed 200 OK in 19ms (Views: 12.3ms | ActiveRecord: 1.0ms)

```

**Comment by tute** [comment]
There must be something with the query parameter. Do you need it?

Can you paste the contents of the `Gemfile.lock` file please?

**Comment by krtschmr** [comment]
doorkeeper.rb now added
`  native_redirect_uri "http://forum.cattle.com/index.php?google-auth"`

still not working. 
good hint with the query parameter. indeed it is needed, this is how WBB (burningboard) is working. obviously i can try to hack it out, but i would rather patch the URL Validator instead of hacking in a PHP forum.

**Comment by tute** [comment]
Define the URL with no query parameter, which will be ignored in the check, and that's ok. Yay! 🎉  :)

**Comment by krtschmr** [comment]
well, it's nice to find out the *bug*, but we maybe should consider fixing it somehow for a better experience while developing. maybe we need those parameters even in a production environment.

**Comment by tute** [comment]
Agreed. There is an open issue tracking how to improve the developer experience around this error: https://github.com/doorkeeper-gem/doorkeeper/issues/716.

In my computer the query parameter doesn't affect the check, so there is a Ruby version mismatch I believe. We could add a regression spec to test against different versions to see when does it behave differently.

**Comment by krtschmr** [comment]
`ruby 2.3.0`
