### ISSUE TITLE
Loading ActiveRecord (models) in intializer leads to settings conflicts with Rails

### ISSUE THREAD

**Issue by hidde-jan** [doorkeeper-gem/doorkeeper#913]
See this issue: https://github.com/rails/rails/issues/23589

Using doorkeeper will cause ActiveRecord to be loaded before Rails' own `new_framework_defaults.rb`. It seems that it's not 'safe' to load AR models in an initializer and that such things should be deferred until later using `ActiveSupport.on_load(:active_record)`.

**Comment by nbulaj** [comment]
Thanks @hidde-jan , fixed!
