### ISSUE TITLE
Token Info Routes Issue

### ISSUE THREAD

**Issue by yoda** [doorkeeper-gem/doorkeeper#916]
If one has configured the redirect_uri as being urn:ietf:wg:oauth:2.0:oob and then is also trying to add custom functionality to the token_info controller the route for the token_info controller fails.

```
use_doorkeeper do
     skip_controllers :applications, :authorized_applications
     controllers token_info: 'custom_token_info'
end
``` 

https://github.com/doorkeeper-gem/doorkeeper/blob/c846335ad75f2f9c7108e577cb84eaf8ab66b86f/app/controllers/doorkeeper/authorizations_controller.rb#L9

If we follow from this point on because the redirect_uri is native it exectutes
https://github.com/doorkeeper-gem/doorkeeper/blob/c846335ad75f2f9c7108e577cb84eaf8ab66b86f/lib/doorkeeper/oauth/code_response.rb#L21

which results in this being returned as the redirect_url call parameters and due to the route remap it cannot find these routes.
https://github.com/doorkeeper-gem/doorkeeper/blob/c846335ad75f2f9c7108e577cb84eaf8ab66b86f/lib/doorkeeper/oauth/authorization/token.rb#L30

```
ActionController::UrlGenerationError - No route matches {:access_token=>"...", :action=>"show", :controller=>"doorkeeper/token_info"}:
```

Should the function native_redirect be adaptive based on the configuration provided in the routes?

**Comment by faizalzakaria** [comment]
@yoda , i encountered the same problem. Wondering if someone taking care of this?

**Comment by nbulaj** [comment]
Hi @faizalzakaria  @yoda . Can you check `fix_token_info_routes` branch from the Git ?

**Comment by nbulaj** [comment]
Now in master. Let me know if it doesn't work
