### ISSUE TITLE
Allowing custom expiration time for access tokens according to grant type

### ISSUE THREAD

**Issue by pointcom** [doorkeeper-gem/doorkeeper#918]
I'm using many different `grant_types` : `password`, `client_credentials` and `authorization_code`.
I wanted to know if there's an easy way to set a custom expiration time based on the OAuth workflow used by the client.
For example, I would like to put `2 days` for both `password` and `authorization_code` and `1 month` for `client_credentials`.

Let me know if that makes sense. 
If that feature doesn't exist yet, I'll be glad to make a PR to add it.

**Comment by nbulaj** [comment]
Hi @pointcom. Currently it is impossible. To implement this functionality, Doorkeeper config option for token TTL must be changed to support not on;y integers, but also blocks. And that blocks must receive grant type from somewhere during Access Token creation...

Would you like to submit a PR ?

**Comment by nbulaj** [comment]
Merged in 62fd33b232ddfc868ca70d6bbce9ceb68e8b754e
