### ISSUE TITLE
Add Cookie to Response?

### ISSUE THREAD

**Issue by cickes** [doorkeeper-gem/doorkeeper#919]
We can customize Token response easily via:
https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-Token-Response

However, what is the recommended location to add a cookie to a response on a successfully authenticated user?  We want to add something like:  
`response.set_cookie "name", "Joe"`

**Comment by nbulaj** [comment]
Hi @cickes . Curently it is impossible (i.e no special option or method), maybe only if you will patch Doorkeeper response object. You can try to implement it yourself with some `proc` option in doorkeeper config for token response and send a PR.
