### ISSUE TITLE
Maintenance Tasks

### ISSUE THREAD

**Issue by maclover7** [doorkeeper-gem/doorkeeper#926]
Below is a list of maintenance tasks for Doorkeeper. Feel free to claim one, or else I'll likely end up completing it.

- [x] Add tests for `BaseRequest` (formerly `RequestConcern`)
- [x] Turn `URIBuilder` into a class
- [x] Create hierarchy for `Response` objects
- [ ] Add `Doorkeeper.framework('rails')?` method, add lots of `defined?(Rails)` checks, etc.
- [x] Deprecate unused `Doorkeeper` class methods
- [ ] Replace usage of `spec_helper_integration` with `spec_helper` where appropriate
- [ ] Try and reuse some objects in tests
- [x]  Add more tests where appropriate!!
- [x] Add test coverage tracking (#937)
- [ ] Add tests for `Doorkeeper::Errors::DoorkeeperError#type` (and subclasses!) --> ref #940

**Comment by zach-taylor** [comment]
To help find out where more tests are needed, would it be helpful to setup test coverage tracking? I can take a stab at it if you want.

**Comment by maclover7** [comment]
@zach-taylor sure, would be happy to review a PR to setup test coverage tracking.

**Comment by maxtedford** [comment]
@maclover7, I see there are still a few unfinished maintenance items on your list. Are you still interested in some help knocking these out?

**Comment by nbulaj** [comment]
@maxtedford feel free to send a PR
