### ISSUE TITLE
Why are query params not considered during match for valid Redirect URI?

### ISSUE THREAD

**Issue by agoodno** [doorkeeper-gem/doorkeeper#934]
I was getting the error message "The redirect uri included is not valid." while attempting to obtain an access token as part of the Implicit Grant flow. Looking through the source, I found that the problem was that the Redirect URI provided by Amazon's Alexa Skill to do the account linking was in the format:

`https://pitangui.amazon.com/spa/skill/account-linking-status.html?vendorId=<vendorId>`

The code in Doorkeeper strips off the query parameter `vendorId` before deciding if the redirect_uri provided in the request matches one of the URI's that the Doorkeeper application supports. I'm sure there is a reason this was done but I couldn't find it in the documentation.

My simple solution was to not strip the query parameters during the match. My branch with this change is here: [Query Params Remain During Match](https://github.com/doorkeeper-gem/doorkeeper/compare/master...agoodno:query-params-remain-for-uri-match?expand=1). This change might be too naive if it will cause other problems that I'm not aware of. An alternate solution would be to parse the "valid" parameters in the URI that is registered in the application and only remove extra query parameters that come in the request that don't match those "valid" parameters.

In the end, I'm just looking for Doorkeeper to support Redirect URI's that Amazon Alexa provides.

**Comment by dmitrytrager** [comment]
On the other hand, there is a [validation](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/authorization_code_request.rb#L47) that does not discard query.

But at this step when redirect_uri comes from params it contains code (for auth code strategy at least). And redirect_uri from grant doesn't. So looks like lack of query stripping in this case.

Probably, separate bug. Thoughts?

**Comment by agoodno** [comment]
It been a few months for me and I wasn't all that familiar with the Doorkeeper code to start with. My branch is working for me currently. I'll defer to you on this one.

**Comment by dmitrytrager** [comment]
Ok, I've switched to using fork too. Will create separate issue. Thanks.

**Comment by dmitrytrager** [comment]
Ok, I've switched to using fork too. Will create separate issue. Thanks.

**Comment by agoodno** [comment]
Thanks!
