### ISSUE TITLE
Protect resource

### ISSUE THREAD

**Issue by thiagoneves** [doorkeeper-gem/doorkeeper#946]
Hey guys, how is the best way to protect some resources only for cliente_credentials grant flow?

**Comment by nbulaj** [comment]
Hi @thiagoneves. What do you mean by _some resources_: controllers, models, etc? 

You can enable only `client_credentials` grant flow and you application will be able to work only with this strategy.

**Comment by nbulaj** [comment]
Closing due the lack of activity.

**Comment by nbulaj** [comment]
cv
