### ISSUE TITLE
Drop query on redirect_uri validation

### ISSUE THREAD

**Issue by dmitrytrager** [doorkeeper-gem/doorkeeper#949]
Many times in code `redirect_uri` is compared without query within validations. However, when we [authorize code request](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/oauth/authorization_code_request.rb#L47) it's compared with grant redirect_uri with query params.

Meanwhile, client sends request here with code attached as a query parameter. That's why this comparison is failed. Is this a real issue? If yes, should I prepare PR with fixes?

**Comment by sull** [comment]
is this related to this error?

> The redirect uri included is not valid.

**Comment by dmitrytrager** [comment]
Yes, you can get this kind of message.

**Comment by nbulaj** [comment]
Merged in df6ddc9 . Report if you have any problems with this
