### ISSUE TITLE
Problems with Mongoid 6

### ISSUE THREAD

**Issue by zeitnot** [doorkeeper-gem/doorkeeper#952]
I am using [this](https://github.com/michaeltrimm/doorkeeper-mongodb) fork to use doorkeeper with mongoid. But I have a problem. Since `ActiveRecord` is not used while using Mongoid the associations are required. For instance, I mean in [here](https://github.com/doorkeeper-gem/doorkeeper/blob/master/lib/doorkeeper/models/access_token_mixin.rb#L17) it is backward compatible thanks to ActiveRecord's existence. While using Mongoid how can we make it backward compatible?

**Comment by nbulaj** [comment]
Hi @zeitnot . doorkeeper model mixins must be uniq for all the ORM extensions, that is the current problem of this gems (they use AR mixin for their own models :\ )

**Comment by nbulaj** [comment]
It's the common problem with #971, it requires `doorkeeper-mongodb` core refactoring. Can you please address this issue to  `doorkeeper-mongodb` tracker? Thanks!
