### ISSUE TITLE
Sign up automatically after registration

### ISSUE THREAD

**Issue by OndrejPontes** [doorkeeper-gem/doorkeeper#955]
I have read a lot of tutorials and discussions about a doorkeeper and many people try to solve how to sign up automatically after registration, but nobody mentioned how to do that. 

Is something like that possible to configure in doorkeeper and if so, how to do it ?

**Comment by moger777** [comment]
@OndrejPontes I'd assume it's the same as normal login, in that you re-direct to same oauth endpoint:

```ruby
  # in config/doorkeeper
  resource_owner_authenticator do
    user = # the_code_that_finds_user, varies from app to app, warden.user works if you do devise
    if user
      user
    else
      redirect_to(login_or_register_path(after_login_path: request.full_path)
    end
  end

  # in login controller
  def login
    user = the_code_to_login_user # varies from app to app

    if user
      login(user)
      if params[:after_login_path] # this you need to make sure to pass from links to initial redirect path
        redirect_to(params[:after_login_path]
      end
    else
      # handle bad username and password
    end
  end

  # in register user controller
  def create
    user = User.new(permitted_user_params)
    if user.save
      login(user)
      if params[:after_login_path] # this you need to make sure to pass from links to initial redirect path
        redirect_to(params[:after_login_path]
      end
    else
      # handle invalid user
    end
```
Obviously above example could use some refactoring but general gist is you try to pass the original url to place you authenticate user (wether through login or though registration) and then redirect back at end.

**Comment by nbulaj** [comment]
Hi @OndrejPontes. Does @moger777 solution solves your problem?

**Comment by nbulaj** [comment]
Ok, so currently I'm closing this issue (because there is no bug), but remind myself to add a new Wiki page :)

**Comment by OndrejPontes** [comment]
:D

Dňa 2.2.2018 20:56 používateľ "Nikita Bulai" <notifications@github.com>
napísal:

Ok, so currently I'm closing this issue (because there is no bug), but
remind myself to add a new Wiki page :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/doorkeeper-gem/doorkeeper/issues/955#issuecomment-362690008>,
or mute the thread
