### ISSUE TITLE
AccessToken.matching_token_for returns wrong values

### ISSUE THREAD

**Issue by swilgosz** [doorkeeper-gem/doorkeeper#957]
I noticed, that in some cases the `Doorkeeper::AccessToken.matching_token_for` returns a token even if it should return nil

*Steps to reproduce.*

1. Get user: `owner = ResourceOwnerClass.find(:resource_owner_id)`
2. Create `app` with scope: `app = Doorkeeper::Application.create(name: "test-app", redirect_uri: "urn:ietf:wg:oauth:2.0:oob", scopes: "sample:scope")`
3. Create a user access token the same scope:  `token = Doorkeeper::AccessToken.create(application_id: app.id, scopes: "sample:scope", resource_owner_id: owner.id)`
4. `Doorkeeper::AccessToken.matching_token_for(app, u.id, "")` returns token , but should return `nil`

**Comment by swilgosz** [comment]
I'm still working on the fix and adding some more tests coverage

**Comment by nbulaj** [comment]
Hi @swilgosz , take a look at the last comments in #907 - you can refactor this PR to fix blank scopes.
