### ISSUE TITLE
Routing Error - uninitialized constant ActionController::RackDelegation

### ISSUE THREAD

**Issue by spchetan11** [doorkeeper-gem/doorkeeper#960]
I'm trying to implement doorkeeper in my rails 5 app along with Devise and Grape.

When I'm trying to setup a login access token using `http://localhost:3000/oauth/token` im getting the title error. 

Route File.

`Rails.application.routes.draw do
 use_doorkeeper resources :orders
 devise_for :users,
 only: :registrations,
 controllers: {
 registrations: "users/registrations"
}
end
`

GemFile.
`
gem 'devise', 
github: 'plataformatec/devise', branch: 'master'gem 'rails', '~> 5.0.2'
gem 'doorkeeper'
gem "doorkeeper-grants_assertion", github: "Inittec/doorkeeper-grants_assertion", branch: "master"
`
What am I doing wrong? The routes are present too.

Sorry about the formatting. Not able to figure out how to format the code.

**Comment by spchetan11** [comment]
NVM. Fixed it by specifying doorkeeper gem version in the gem file. `gem 'doorkeeper', '~> 4.2.5'`

**Comment by maclover7** [comment]
Closing since issue was resolved.
