### ISSUE TITLE
Adding additional information to a token

### ISSUE THREAD

**Issue by ekampp** [doorkeeper-gem/doorkeeper#961]
Hi there. 

I have been looking to add additional information to a token. Specifically I want to log some additional URL params present when authorising the token.

In that pursuit, I have found that the `Doorkeeper::AuthorizationsController#new` is responsible for creating the token, and redirecting to the client app. It also have access to said URL params.

So, my question is: What's the best way to parse the additional params into the token from `Doorkeeper::AuthorizationsController#new`? 

Thanks in advance.

**Comment by maclover7** [comment]
@ekampp Can you please provide more information about what you are trying to do? "Adding more information to the token" is a little vague. I _think_ overriding the action and calling `super` may work for you.

**Comment by nbulaj** [comment]
Hi @ekampp. Any news here?

**Comment by ekampp** [comment]
Hi @nbulaj I turned to another solution to fix my problem. So this can be closed from my perspective.
