### ISSUE TITLE
Proof Key for Code Exchange (PKCE)

### ISSUE THREAD

**Issue by chrisblatchley** [doorkeeper-gem/doorkeeper#975]
Opening a discussion about implementing [PKCE](https://tools.ietf.org/html/rfc7636)

I have to implement it anyway, so I figured I'd start upstream and see if there's any specific thoughts from doorkeeper maintainers.

**Comment by rsharrott** [comment]
@chrisblatchley Do you have a fork where you are working on this? I'd be willing to do some work on it as well.

**Comment by chrisblatchley** [comment]
@rsharrott https://github.com/chrisblatchley/doorkeeper/tree/pkce-updates. i can add you as a contributor

**Comment by rsharrott** [comment]
Please do! I reviewed your commit: https://github.com/chrisblatchley/doorkeeper/commit/60e8502725b30807645905b6c941f114bc229f78. Looks like you are pretty far along.
 
I was thinking that since plain is not suggested, I could add a config to allow it if needed, but default to off.

**Comment by chrisblatchley** [comment]
@rsharrott the main issues i'm curious about is making sure this feature can be upgraded to safely from existing doorkeeper installs, and then making sure the design is appropriate for doorkeeper maintainers' preferences.

**Comment by cickes** [comment]
Nice work on this.  

I see branch: https://github.com/chrisblatchley/doorkeeper/tree/pkce-updates
with open PR https://github.com/chrisblatchley/doorkeeper/pull/1 with a `moneytree` branch also with open PR https://github.com/moneytree/doorkeeper/pull/17

Is this still in progress of development?  How can I help?

**Comment by rsharrott** [comment]
@cickes I updated our PR to have the full implementation for review. Please let me know what I need to do to get in ready for adding to the mainline.

**Comment by nbulaj** [comment]
Merged in 4b42e9d9fd06bf34308e3184e298f34aa9ac1d10
