### ISSUE TITLE
Token are always persisted in database (JWT)

### ISSUE THREAD

**Issue by mdebo** [doorkeeper-gem/doorkeeper#983]
Hi
Thank you for your usefull work!
I'm using Dookeeper and JWT. So i use your gem combine with doorkeeper-jwt.
As I use JWT, I don't want to persist token in database. In fact, JWT gives the advantage of not needing to check the token in a db every time since you can just use cryptography to verify that the token is legitimate. I dont want to lose this benefit...
So, there is an option to tell doorkeeper to not store token in database? I can't find it in the wiki..
Thank you in advance

**Comment by nbulaj** [comment]
Hi @mdebo. Currently, that is impossible as far as I know. Every token is saved to the database. It is required to change some core architecture of the doorkeeper gem to implement such a functionality. You are very welcome with the PR if you want.

**Comment by nbulaj** [comment]
As it requires to change core Doorkeeper methods, feel free to send a PR @mdebo . Maybe it can be solved with some "NULL-orm" that will ignore DB and store / find only some structs based on decoded JWT.

**Comment by pandwoter** [comment]
Hi @nbulaj, would it be ok if I instead will try to provide a PR with this feature? As we want to have it in the doorkeeper codebase rather than maintaining fork...
