### ISSUE TITLE
What's the right way to set up doorkeeper with i18n?

### ISSUE THREAD

**Issue by jfly** [doorkeeper-gem/doorkeeper#994]
We have this issue (https://github.com/thewca/worldcubeassociation.org/issues/1939) in our project where doorkeeper's responses are not respecting the user's locale.

To support I18n, we added we've added a `set_locale` method  in our ` ApplicationController` to set `I18n.locale` whenever a request comes in (as per the directions on http://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests). However, [`Doorkeeper::TokensController`](https://github.com/doorkeeper-gem/doorkeeper/blob/master/app/controllers/doorkeeper/tokens_controller.rb) doesn't inherit from our `ApplicationController`, it inherits from `Doorkeeper::ApplicationMetalController`, which inherits from `ActionController::Metal`. This means our `set_locale` hook in our `ApplicationController` never gets a chance to run.

I was curious how this works in devise, and it turns out that they wrote their controllers in a way such that they inherit from your application controller (see `Devise.parent_controller.constantize` in https://github.com/plataformatec/devise/blob/3323197d68ed726f80f90361ce92151df782210a/app/controllers/devise_controller.rb#L2).

What's the right way to get doorkeeper to follow the same locale selection rules as the rest of our application?

**Comment by nbulaj** [comment]
Hi @jfly . How do you know what locale to use in case of API? I saw [your example](https://github.com/thewca/worldcubeassociation.org/issues/1939#issue-258366981) and as far as I see it will use default locale.

Btw, currently you can use only some workaround, for example patch `Doorkeeper::ApplicationMetalController` somewhere in initializer. The proper way is to make this controller configurable, as it is done for the Devise gem, so everybody will have an ability to customize the controller. @maclover7 what do you think?

**Comment by jfly** [comment]
Haha, that's an excellent question. When I filed this issue, I wasn't thinking about the fact that the user is not logged in yet. I guess the best we can do here is at least always return the error message in English. In order to accomplish that, I guess we should patch `Doorkeeper::ApplicationMetalController` as you suggest?

**Comment by nbulaj** [comment]
@jfly anyway, you have an error info in the JSON response (I mean "_invalid_grant_" type), so can't you use it to show your localized error? I don't know tech specs of your project, but I think it is not a problem both for backend or frontend app.

Btw yes, you can try to patch `Doorkeeper::ApplicationMetalController` if you know how to handle locales at that level :)

**Comment by nbulaj** [comment]
@jfly closing this issue. If it is still a problem - let me know.

**Comment by jfly** [comment]
Nah, this is not a big deal, thanks!
