### ISSUE TITLE
Expiration Time Base On Grant Type

### ISSUE THREAD

**Issue by GeminPatel** [doorkeeper-gem/doorkeeper#996]
**Feature:** To provide different expiration to tokens based on different grant type.

**Why?:** We may want different expiration time for client_credentials, password, and implicit. Password tokens may have 1 hr of expiry while Client Credential token may have 1 day of expiry.

Do you guys think this is possible/feasible feature to implement?

_PS: We may also keep these expiry times per client in a json column in the DB._

**Comment by kapilmittal** [comment]
+1 for this feature.
I also need to provide short lived user tokens and relatively long lived client tokens in my oauth app. 

Would you guys be interested in a PR for the same?

**Comment by nbulaj** [comment]
Hi @kapilmittal . Feel free to send a PR with this feature. I think it must be a configurable lambda that must be used optionally (if set) for all strategies

**Comment by nbulaj** [comment]
Merged in  55439ee
